wyeworks/nucore-open

Gemfile, Gemfile.lock
TECH TASK: Update gems for ed25519 SSH keys support
Merely having a `~/.ssh/id_ed25519` key on my computer causes Capistrano to raise this error:
```
NotImplementedError: unsupported key type `ssh-ed25519'
net-ssh requires the following gems for ed25519 support:
* ed25519 (>= 1.2, < 2.0)
* bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/565 for more information
Gem::LoadError : "ed25519 is not part of the bundle. Add it to your Gemfile."
```
This PR adds the gems per the instructions, so that Capistrano can use ed25519 keys, or fall back gracefully to RSA keys. Without doing this, I have to move `~/.ssh/id_ed25519` out of `~/.ssh`, call `ssh-add -K` (to unregister the key), and then do SSH operations via Capistrano.
=> TECH TASK: Update gems for ed25519 SSH keys support

app/services/user_finder.rb, app/views/search/_results_table.html.haml, spec/services/user_finder_spec.rb, vendor/engines/secure_rooms/app/views/search/_extra_columns.html.haml, vendor/engines/secure_rooms/app/views/search/_extra_headers.html.haml, vendor/engines/secure_rooms/config/locales/en.yml, vendor/engines/secure_rooms/lib/secure_rooms/engine.rb, vendor/engines/secure_rooms/spec/services/user_finder_spec.rb
Allows searching users by card number when secure rooms are used
To make it obvious why a particular user matched, I added `Card Number` as a column to the results table when the secure rooms engine is required.
=> [#143728] Allow searching users by card number

app/controllers/facilities_controller.rb, app/helpers/a_z_helper.rb, spec/helpers/a_z_helper_spec.rb
Fix issue where facilities beginning with lowercase letters were shifted to the end of the list.
Dartmouth has a lab called "bioMT" which was hard to find because it was pulled down to the bottom. 
This also fixes an issue with the A-Z list where it treats "b" and "B" as separate letters.
=> [#144525] Alphabetize homepage case insensitively

Gemfile, Gemfile.lock, config/initializers/uglifier_restriction.rb
https://github.com/mishoo/UglifyJS2/issues/3245 documents
a bug which occurs when using compression.
There does not appear to be any way to disable this particular path through the uglifier.
=> Revert Uglifier to 4.1.18, due to bug in Uglify 3.4.9.

doc/user_roles.md
Add documentation describing user roles and permissions
This is based on what we've done for Dartmouth and UIC in the past. I've added a little more detail including the account-specific roles.
Based on https://github.com/tablexi/nucore-uic/blob/develop/doc/user_roles.md and https://github.com/tablexi/nucore-dartmouth/blob/develop/doc/user_roles.md (restricted repositories)
There'll probably be some merge conflicts when we try to bring it down to the individual schools. Theirs have been somewhat crafted to be specific to their use case (DC wasn't using the billing admin role at the time we originally wrote it).
=> Document User Roles

app/assets/javascripts/timeline.js
Fix Daily View Navigation Skipping in Firefox
In Firefox and Chrome, `$(window).scrollTop()` returns different pixel values when the page is scrolled down to the exact same instrument. This difference of 1.5 pixels was enough to trip up the calculation to think that a hidden element was visible, which was causing the wrong element id to be appended when switching dates. By using the date navigation header’s height in the calculation, we get a more robust value which takes into accound the element that is being covered, and this works everywhere.
=> [#144715] Fix Daily View Navigation Skipping in Firefox

app/controllers/account_users_controller.rb, app/controllers/facility_account_users_controller.rb, app/models/account.rb, app/models/account_user.rb, app/services/account_role_grantor.rb, app/views/account_users/new.html.haml, app/views/facility_account_users/new.html.haml, config/locales/en.models.yml, config/locales/models/en.account.yml, config/locales/views/admin/en.facility_account_users.yml, config/locales/views/en.account_users.yml, spec/controller_spec_helper.rb, spec/controllers/facility_account_users_controller_spec.rb, spec/controllers/global_search_controller_spec.rb, spec/factories/users.rb, spec/models/account_spec.rb, spec/models/account_user_spec.rb, spec/models/chart_string_reassignment_form_spec.rb, spec/rails_helper.rb
Allow changes to account membership even if the chartstring becomes invalid.
Before:
The major issue was that `NufsAccount` runs the `ValidatorFactory`'s validations on `update`. The way this was being done before was triggering those validations, and if the validator raised a validation error, we couldn't add another user to the payment source.
This sidesteps that issue by doing the work from the `AccountUser` model and doing an ownership check on the `Account` just to make sure.
I also tried to standardize `AccountUser` creation so it's always going through the `grant` method. That accounts for a chunk of noise in the specs.
=> [#136546] Allow account membership changes after expiration

.gitignore, doc/HOWTO_oracle.md
TECH TASK: Use oracle/ in local directory for Oracle DB data
Instead of suggesting a directory in `$HOME`, we can just use a directory in the same place as the checkout.
=> Use oracle/ in local directory for Oracle DB data

app/services/whitespace_normalizer.rb, app/support/example_statement_pdf.rb, app/support/statement_pdf.rb, spec/services/whitespace_normalizer_spec.rb
Fix tab characters display on statement PDFs.
This started happening when we switched to using a TTF for the statements. Tab characters were displaying funkily. This should also handle if non-breaking spaces and its ilk get pasted in.
=> [#144294] Normalize whitespace in statement PDFs

vendor/engines/ldap_authentication/lib/ldap_authentication/user_entry.rb, vendor/engines/ldap_authentication/spec/ldap_authentication/user_entry_spec.rb
Tech task: Retry, up to three times, LDAP queries that time out.
This should help with the LDAP deactivation job getting occasional timeouts which
was causing the entire job to fail. It'll still end up crashing if there's a serious issue with LDAP, but hopefully, this will handle most of the cases.
=> [#140549] Retry LDAP queries up to 3 times

app/models/external_service/url_service.rb, spec/models/external_service/url_service_spec.rb
Handle external survey links that already contain a question mark.
If a survey link has a question mark in it, we would append additional query params with our own `?`. This came up in the context of PerfectForms. Qualtrics and Surveyor don't have `?` in their URLs, so it wasn't a problem before.
`http://www.survey.com/surveys/edit?id=123` would end up as `http://www.survey.com/surveys/edit?id=123?order_id=123-456&...`. This corrects it so we only end up with a single question mark.
=> Handle survey urls that already have a question mark in them

config/initializers/lograge.rb, vendor/engines/secure_rooms/app/services/secure_rooms/access_handlers/occupancy_handler.rb, vendor/engines/secure_rooms/app/services/secure_rooms/access_handlers/order_handler.rb, vendor/engines/secure_rooms/app/services/secure_rooms/access_manager.rb
Add debugging statements to secure_rooms engine
Some occupancies of secure rooms are not updating the related order detail records when a user exits the room. However, looking at these occupancies and order details does not reveal why this happens — calling the code that the controller would call, processes these order details correctly. This PR is to add some tracing calls to see what in the processing chain may be getting skipped.
=> [#144074] Add debugging statements to secure_rooms engine

app/models/external_service/url_service.rb, spec/models/external_service/url_service_spec.rb
Reverts tablexi/nucore-open#1771 because it seems to be causing https://rollbar.com/TableXI/nucore-nu/items/341/ and https://rollbar.com/TableXI/nucore-nu/items/342/
=> Revert "Handle survey urls that already have a question mark in them"

app/assets/stylesheets/nucore.scss, app/controllers/price_policies_controller.rb, app/models/price_policy.rb, app/services/price_policy_updater.rb, app/views/price_policies/_common_fields.html.haml, app/views/price_policies/_price_policy_fields.html.haml, app/views/price_policies/index.html.haml, app/views/time_based_price_policies/_price_policy_fields.html.haml, config/locales/views/admin/en.price_policies.yml, config/settings.yml, db/migrate/20181119211456_add_note_to_price_policies.rb, db/schema.rb, lib/settings_helper.rb, spec/factories/price_policies.rb, spec/features/admin/instrument_price_policies_controller_spec.rb, spec/features/admin/item_price_policies_controller_spec.rb, spec/features/admin/timed_service_price_policies_controller_spec.rb, spec/models/item_price_policy_spec.rb, spec/models/price_policy_spec.rb, spec/models/product_spec.rb, spec/models/service_price_policy_spec.rb, spec/price_policies_controller_shared_examples.rb, vendor/engines/secure_rooms/app/views/secure_room_price_policies/_price_policy_fields.html.haml, vendor/engines/secure_rooms/spec/factories/secure_rooms_price_policies.rb, vendor/engines/secure_rooms/spec/features/create_a_secure_room_spec.rb
Add a note field to price policies and optionally make it required.
Dartmouth wants to make it required. NU is fine adding the field, but does not want to require it being filled out.
=> [#144530] Allow requiring a note when creating price policies

config/initializers/sanitized_allowed.rb
Restore ability to allow links in product and facility descriptions to open in a new window.
Users have the ability to set a `target` on their links in the facility and product descriptions through the editor to allow opening a link in a new window. We added some sanitization to `Facility#description` in #1703 which strips out that attribute. This lets it through sanitization.
=> [#145520] Restore ability to have links open in new window

app/assets/stylesheets/nucore.scss, app/controllers/concerns/new_inprocess_controller.rb, app/controllers/facility_orders_controller.rb, app/controllers/facility_reservations_controller.rb, app/views/facility_orders/index.html.haml, app/views/facility_reservations/index.html.haml, vendor/engines/secure_rooms/app/controllers/secure_rooms/facility_occupancies_controller.rb, vendor/engines/secure_rooms/app/views/secure_rooms/facility_occupancies/index.html.haml
Make "Ordered For" column sortable on New/In Process orders page. Make the ordering of columns on the New/In process orders and reservations pages more consistent with each other.
Per NU, sorting on last, first made the most sense so we made this consistent across the columns.
=> [#141856] Make "Ordered For" column sortable on New/In Process orders page

app/models/external_service/url_service.rb, spec/models/external_service/url_service_spec.rb
Handle external survey links that already contain a question mark.
If a survey link has a question mark in it, we would append additional query params with our own `?`. This came up in the context of PerfectForms. Qualtrics and Surveyor don't have `?` in their URLs, so it wasn't a problem before.
`http://www.survey.com/surveys/edit?id=123` would end up as `http://www.survey.com/surveys/edit?id=123?order_id=123-456&...`. This corrects it so we only end up with a single question mark.
This was originally done in #1771 and reverted in #1780 because some of the URLs on NU prod contained leading whitespace which caused `URI(url)` to raise a `ActionView::Template::Error: bad URI(is not URI?)` error.
=> Handle External Service URLs that already contain a question mark

README.md
Updates the README to show the correct ruby version (2.4.1) which matches the `.ruby-version` file.
When I was following the setup guide, the `bundle install` step failed due to having installed ruby `2.2` instead of `2.4.1`
=> update README to specify ruby 2.4.1 to match the .ruby-version file

app/assets/stylesheets/nucore.scss
Restyle buttons with the UCONN design. Buttons colored based on use/manage mode.
Simply adding a 15% alpha layer
=> Use-Manage Buttons

app/assets/stylesheets/application.scss
Fix double search icon appearing in dropdowns that include searches.
Before and after:
We used this same fix on another project. Reference: https://github.com/tsechingho/chosen-rails/issues/103
=> [#141977] Prevent double icon in dropdown searches

.circleci/config.yml
Tech task: Ensure we are running all specs on CI.
This ended up being fine on open, but we're not running specs in Dartmouth which are more than one level nested. So we're running `vendor/engines/dc_chartstrings/spec/models/facility_spec.rb`, but not `vendor/engines/dc_chartstrings/spec/models/dc_chartstrings/general_ledger_account_spec.rb`. I'm also going to try this out on NU.
=> Add globstar option when running specs on CircleCI

app/models/order_detail.rb, spec/controllers/order_management/order_details_controller_spec.rb, spec/models/reports/export_raw_spec.rb
Require that the price change reason for an order be at least 10 characters. This validation only applies when an order is being manually adjusted from its calculated cost.
I debated if it was worth the effort of moving the specs over to the model, but they were already in the controller spec and the model spec is already almost 2000 lines long.
Also, by moving the `feature_setting` tag, I was able to drop the time that file takes to run from about 2:40 to 1:30 (flipping the feature settings is slow because we also end up reloading the routes).
UIC is the only school with this feature disabled, so we might be able to remove the feature flag at some point in the future.
=> [#145115] Add minimum price change reason length for order details

spec/features/placing_an_order_on_behalf_of_spec.rb
Tech Task: Support finding labels that have been upcased via CSS in specs.
UCONN is applying a `text-transform` to `label`s. Capybara uses exact matches, so in JS mode where the styles get applied, it can't find them. This switches to using regexes to allow case insensitivity. See #1787.
=> Allow JS capybara finders to find upcased labels

bin/merge_describer
Tech task: Use `master` as default base for merge_describer
Now that we're switching our downstreams to use `master` as the default branch and getting rid of `develop`, this changes the default base for our merge describer utility.
=> Use master as default base for merge_describer

app/models/order_detail.rb, app/models/reports/export_raw.rb, spec/factories/orders.rb, spec/models/reports/export_raw_spec.rb, vendor/engines/split_accounts/app/services/split_accounts/order_detail_splitter.rb, vendor/engines/split_accounts/spec/models/reports/export_raw_spec.rb
Adds the following fields to export raw: 
* Calculated Cost
* Calculated Subsidy
* Calculated Total
* Difference Cost
* Difference Subsidy
* Difference Total
The difference fields are the difference between the actual assigned price and the price as it would have been if it were automatically priced. This is to tell when a price was manually adjusted.
DC already had the "calculated" columns, so this pulls them up into the main app and adds the difference columns.
Extracted from https://github.com/tablexi/nucore-dartmouth/pull/245
=> [#144674] Add calculated cost fields to export raw

config/settings.yml, lib/settings_helper.rb, spec/helpers/settings_helper_spec.rb, spec/rails_helper.rb
Tech task: Remove `_on` suffix from all settings names.
This is into https://github.com/tablexi/nucore-open/pull/1804/files
It will also be slightly tedious to clean up the merge conflicts when this goes downstream.
=> Remove `_on` suffix from settings

config/settings.yml, lib/settings_helper.rb, spec/controllers/facilities_controller_spec.rb, spec/controllers/facility_accounts_controller_spec.rb, spec/controllers/facility_facility_accounts_controller_spec.rb, spec/controllers/search_controller_spec.rb, spec/controllers/training_requests_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/helpers/settings_helper_spec.rb, spec/lib/status_change_notifications_spec.rb, spec/models/budgeted_chart_string_spec.rb, spec/models/journal_spec.rb, spec/models/order_detail_spec.rb, spec/models/price_policy_spec.rb, spec/rails_helper.rb
Tech task: Fix tests that don't properly clean up `Settings` after themselves. This also makes it explicit which tests need to reload their routes, which should speed up overall suite speed.
The critical ones that caused https://github.com/tablexi/nucore-dartmouth/pull/244 to fail are related to the fiscal year. Using `allow(Settings.financial).to receive(: fiscal_year_begins)` makes it so rspec will un-stub it after the test is over so changes don't bleed across specs.
I could be convinced the `reload_routes` option isn't worth it.
=> Fixes for settings not being reset properly in tests

app/models/order_detail.rb, app/models/reports/export_raw.rb, spec/models/reports/export_raw_spec.rb
Fix bundle column in export raw to properly show the bundle name if the order was purchased as part of a bundle. The column was previously called "Bundled Product".
Currently, if you place an order with a bundle and then go to find those line items on the export raw report the "Bundled Products" column is always blank. I'm guessing that at one point (way back to even before my time) that a bundle was a single line item with multiple products. That appears to be what it's trying to report on. For a long time now, when you add a bundle, each product of the bundle is a separate line item with a `bundle_id` tying back to the product.
=> [#144522] Fix bundle column on export raw

app/views/shared/_header.html.haml, app/views/shared/_support.html.haml, config/locales/en.yml, config/settings.yml
Allow configuring a support email for top-level link
Shows a Support link in the top-level navigation if a support email has been configured. This way, we can configure per-school support emails, and this link is only displayed if such an email is configured.
=> [#137479] Allow configuring a support email for top-level link

app/views/shared/_header.html.haml, app/views/shared/_support.html.haml
Fix Support link when signed out, and make visible on mobile
=> [#137479] Fix Support link when signed out, and make visible on mobile

app/assets/stylesheets/responsive.scss
Ensure mobile menu appears above other content on page
=> [#141855] Ensure mobile menu appears above other content on page

spec/controllers/product_users_controller_spec.rb
Tech task: Fix sporadic test failure
The users in the controller are sorted by last name, first name. The user factory
assigns last names of integers (e.g. "8", "9", "10"), so if it happens to hit where
it goes from 9 to 10, the ordering may not be what the test was expecting. We don't
really care about the ordering in this spec, so we can ignore it.
See https://circleci.com/gh/tablexi/nucore-open/7099
=> Tech task: Fix sporadic test failure

app/models/instrument_price_policy_calculations.rb, vendor/engines/split_accounts/app/services/split_accounts/attribute_splitter.rb, vendor/engines/split_accounts/spec/services/order_detail_splitter_spec.rb
Fix errors on Create Journal and report when there is a canceled with cost reservation on a split account.
This is a side effect of the new calculated cost fields in #1810. All of the other cost calculations return an integer or BigDecimal, but cancelation fee was returning a Float, which can't be converted to a BigDecimal w/o a precision (`can't omit precision for a Float`).
=> [#146242] Fix for split accounts when cancelled with a fee

app/models/instrument_price_policy_calculations.rb, spec/models/reports/export_raw_spec.rb, vendor/engines/split_accounts/spec/models/reports/export_raw_spec.rb
Fix `calculated_cost` errors for orders that are missing reservations due to a previous bug.
There was a bug introduced in the Rails 5.0 upgrade that caused some reservations on split accounts to get deleted. We managed to recover most of the data from backups, but there are still some orders out there that were not recovered. This will prevent exceptions when reports and other views include those orders.
On split accounts, the calculated cost will show up as `$0.00`, but it should still be clear there's a problem since the reservation and actual times will be gone.
See https://github.com/tablexi/nucore-open/pull/949
=> Fix calculated_cost when missing reservation

app/models/reports/export_raw.rb, vendor/engines/split_accounts/app/services/split_accounts/order_detail_list_transformer.rb, vendor/engines/split_accounts/app/services/split_accounts/order_detail_splitter.rb, vendor/engines/split_accounts/spec/services/order_detail_splitter_spec.rb
Only calculate `calculated_cost`/`subsidy` when splitting an order detail if we are in the context of export raw.
There are a few other places like the the Journals#new (where we partition into valid/invalid accounts) that split order details. In these scenarios, the calculated_cost isn't used, so we don't need to copy it. This should add a performance improvement as well as avoiding errors like #1826.
Those columns were added in #1810.
=> Only split calculated_cost when doing export raw

app/views/instruments/schedule.html.haml, app/views/journal_cutoff_dates/edit.html.haml, app/views/price_groups/_accounts.html.haml, app/views/price_groups/_users.html.haml
Fix confirmation popups that used to exist.
The pages affected:
- Journal Cutoff Dates #edit
- Instruments #Schedule
- Price Groups #show > Accounts
- Price Groups #show > Users
This likely was broken during the rails 4 upgrade, a long time ago. Adds data:{} wrappers around the confirm actions
=> [#146388] Fix confirmation popups that used to exist

app/assets/stylesheets/nucore.scss, app/support/price_displayment.rb, app/views/facilities/disputed_orders.html.haml, app/views/facilities/movable_transactions.html.haml, app/views/facilities/transactions.html.haml, app/views/facility_notifications/in_review.html.haml, app/views/facility_notifications/index.html.haml, app/views/facility_statements/new.html.haml, app/views/shared/transactions/_table.html.haml, app/views/shared/transactions/_table_inside.html.haml, app/views/transactions/index.html.haml, config/locales/en.yml, spec/features/admin/review_period_spec.rb
Add total cost on unpaginated lists of transactions
I am not a fan of the way I keep track of how many columns this table has, so that I can position the `Total` correctly. I’m open to suggestions on how to make this better!
=> [#137738] Total cost on pages

app/models/account.rb, vendor/engines/c2po/app/models/credit_card_account.rb, vendor/engines/c2po/app/models/purchase_order_account.rb
Tech task: clean up Account to Facility relationship
A baby step towards making the relationship many to many. Turns out `Account#facilities` doesn't appear to be used anywhere.
=> Tech task: Clean up Account -> Facility relationship

app/assets/javascripts/app/bundle_products.js, app/inputs/order_detail_quantity_input.rb, app/inputs/quantity_input.rb, app/models/bundle.rb, app/models/bundle_product.rb, app/presenters/quantity_presenter.rb, app/support/price_displayment.rb, app/views/bundle_products/edit.html.haml, app/views/bundle_products/index.html.haml, app/views/bundle_products/new.html.haml, app/views/orders/_cart_row.html.haml
Fix display of quantities for Timed Services when inside of a bundle.
* In a cart
* In the admin of a bundle including the list of bundled products and the new and edit forms
The add product to bundle form will now switch between regular quantity and time-based based on what option has been selected from the dropdown.
=> [#144524] Fix display of timed service quantities in bundle

app/models/account.rb, app/models/account_config.rb, app/services/account_builder.rb, app/views/shared/_statements_table.html.haml, spec/models/account_config_spec.rb, spec/models/nufs_account_spec.rb, vendor/engines/c2po/spec/models/credit_card_account_spec.rb, vendor/engines/c2po/spec/models/purchase_order_account_spec.rb
Tech task: Rename Account `single_facility?` and `cross_facility?` methods to better describe their new behavior.
Extends from #1829
=> Account facility rename single cross methods

app/controllers/facility_orders_controller.rb, app/forms/add_to_order_form.rb, app/helpers/accounts_helper.rb, app/models/account.rb, app/models/order.rb, app/views/facility_facility_accounts/index.html.haml, app/views/facility_orders/_merge_order_form.html.haml, config/locales/en.yml, config/locales/forms/en.add_to_order_form.yml, spec/app_support/order_row_importer_spec.rb, spec/controllers/facility_orders_controller_spec.rb, spec/features/admin/adding_to_an_order_spec.rb
Allow facility staff to choose an account from a dropdown when adding to an existing order.
When the "cart" payment source is valid:
When the "cart" payment source is expired or suspended:
Previously, new orders always got added to the order's (aka "cart") account. This is problematic when the account has since been suspended or expired.
This should avoid that issue as well as provide a convenience to the facility staff. 
It will default to the cart account unless it is no longer valid, and only includes valid accounts.
Includes #1837. Clean diff: https://github.com/tablexi/nucore-open/compare/add_to_order_refactor...add_account_to_add_to_order_144300?expand=1
=> [#144300] Add account select to Add to Order form

app/assets/stylesheets/nucore.scss, app/controllers/account_facility_joins_controller.rb, app/forms/account_facility_joins_form.rb, app/models/account.rb, app/services/account_builder.rb, app/views/account_facility_joins/edit.html.haml, app/views/accounts/index.html.haml, app/views/admin/shared/_tabnav_payment_method.html.haml, config/locales/en.controllers.yml, config/locales/en.models.yml, config/locales/en.yml, config/locales/views/en.accounts.yml, config/routes.rb, config/settings.yml, spec/features/admin/account_facility_joins_controller_spec.rb
Add an interface for global admins to manage which facilities an account is valid for. This applies to non-global accounts (e.g. Credit Cards and POs).
I considered using checkboxes, but this seemed better for when there are lots of facilities.
We will probably want to disable this for NU for a little while until they can get BI to update their queries.
=> [#144419] Interface for managing an Account's facilities

app/controllers/instruments_controller.rb, app/views/instruments/instrument_status.html.haml, config/routes.rb, spec/controllers/instruments_controller_spec.rb
TECH TASK: Remove unused and unusable InstrumentsController#instrument_status
I was scratching my head with the `InstrumentStatus` records while working on `#139335`, and this action is unused and unusable (because there is no local variable or method called `instrument`, it always raises `ActiveRecord::RecordNotFound`, which results in a 404).
=> Remove unused and unusable InstrumentsController#instrument_status

app/models/price_policy.rb, spec/models/price_policy_spec.rb
Only require note for newly-created Price Policies
I did this work in `nucore-dartmouth` to expedite getting a hotfix released, so this PR just pulls up the code into `nucore-open` so that there’s not a conflict on the next regular release.
=> [#147636] Only require note for newly-created Price Policies

spec/factories/price_policies.rb, spec/models/reports/export_raw_spec.rb, spec/support/helper_methods.rb
Tech task: Add spec for timed services in export raw
We found an issue in Dartmouth with one of their custom columns and discovered there wasn't a base spec for timed services in the export raw.
=> Add spec for timed services in export raw

spec/models/reports/export_raw_spec.rb
Tech task: Fix spec for export raw price calculation.
Optional.
Cherry-picked from https://github.com/tablexi/nucore-dartmouth/pull/253
This will trigger pricing w/o changing the account. The account change was causing price group issues in Dartmouth. I'm pretty sure this change will also fix a spec in UIC.
=> Tech task: Fix spec for export raw price calculation.

spec/controllers/instruments_controller_spec.rb, spec/controllers/reservations_controller_spec.rb, spec/features/admin/account_facility_joins_controller_spec.rb, spec/features/admin/managing_training_requests_spec.rb, spec/features/admin/managing_user_spec.rb, spec/features/admin/product_notifications_controller_spec.rb, spec/features/admin/suspending_a_user_spec.rb, spec/features/my_files_spec.rb, spec/features/passwords_spec.rb, spec/models/product_for_cart_spec.rb, spec/services/results_file_notifier_spec.rb, vendor/engines/bulk_email/spec/features/bulk_emailer_searching_spec.rb
Tech task: Fix specs that are dependent on feature flagged routes.
Optional.
These all pass with the default `nucore-open` settings, but were failing in UIC where some of the flags are disabled.
See https://github.com/tablexi/nucore-uic/pull/223 for status
=> Tech task: Fix feature-flag dependent specs

app/controllers/relays_activations_controller.rb, app/helpers/products_helper.rb, app/views/admin/products/index.html.haml, config/locales/en.yml, config/locales/views/en.relays_activations.yml, config/routes.rb, spec/controllers/relays_activations_controller_spec.rb
Tool for turning all relays for a core on or off, at once
Since these actions call activate/deactivate on all relays regardless of their current status, I am not creating InstrumentStatus records on the instruments to signify that there was a change (because perhaps there was not one). This should be okay, because https://github.com/tablexi/nucore-open/blob/master/app/controllers/instruments_controller.rb#L72-L77 reconciles a relay’s actual status by creating (or skipping) an InstrumentStatus record on view.
=> [#139335] Tool for turning all relays for a core on or off, at once

db/migrate/20190104011154_change_account_facility_relationship_144419.rb
Use INSERT INTO that works on Oracle in migration
As-is, the migration fails in Oracle because [when a column is marked as not null, it must be specified in the `INSERT INTO` clause](https://asktom.oracle.com/pls/apex/asktom.search?tag=cannot-insert-null-values-to-a-column-defined-not-null-with-default-constraint). Therefore, we use the next value of the sequence for `account_facility_joins.id` to insert the correct value, and we leave the migration as-is for other databases.
=> [#144419] Use INSERT INTO that works on Oracle in migration

vendor/engines/c2po/app/models/purchase_order_account.rb, vendor/engines/c2po/config/locales/en.yml, vendor/engines/c2po/spec/models/purchase_order_account_spec.rb
Improve PO description if it's part of more than one facility. If it's part of more than one facility, it will now include "Shared (X Facilities)" as part of the description rather than the original facility it was created under.
This should support Dartmouth's "Resources" naming override, so they should see "Shared (X Resources)"
=> [#144419] Improve PO description if it's part of more than one facility

app/assets/stylesheets/nucore.scss, app/views/facility_orders/_merge_order_form.html.haml
Move the payment source dropdown to be next to the order status on the add to order form.
Per the client "Payment Source modification won't be super common, so we don't need this to be as prominent as the status selector."
=> [#144300] Rearrange payment source dropdown on add to order

app/assets/stylesheets/nucore.scss
Fix red text in `select` dropdowns in Firefox, specifically in the add product to bundle form.
Before:
This would have been happening on any `required` dropdown (that's not `js--chosen`) when the blank `option` was selected. This only seems to happen in Firefox. There is still a red border while the `select` is focused, but that is similar to other inputs (e.g. type a letter into a `number` field and it gets a red border _and_ the text is red).
=> [#144524] Fix red select text in Firefox

app/views/shared/_accounts_table.html.haml, config/locales/en.yml
Fix display of multi-facility accounts in the Manage Facilities > Users > User > Payment Sources tab.
I thought I had done this already, but it might have gotten lost in one of my branches. I'm surprised this doesn't error on #1863. I may try to add a spec over there to catch this.
This could get unwieldy if they start adding too many facilities, but I think we can address it if it becomes a problem. I was thinking maybe truncating after a certain number, so "Facility 1, Facility 2, Facility 3, and X more..." or something like that.
=> Show all facilities for account in user listing

app/controllers/product_notifications_controller.rb, app/models/instrument.rb, app/models/instrument_issue.rb, app/views/product_notifications/edit.html.haml, app/views/product_notifications/show.html.haml, config/locales/en.models.yml, config/locales/views/admin/en.product_notifications.yml, db/migrate/20190220001838_add_issue_report_recipients_to_product.rb, db/schema.rb, spec/models/instrument_issue_spec.rb, spec/models/instrument_spec.rb
Add the ability for a facility to specify a list of email recipients for each instrument's "Report an Issue" feature. If no list is specified, it will continue with the current behavior of notifying the facility directors, admins, and product's training request recipients.
=> [#147749] Add product-specific recipients for "Report an Issue"

spec/controllers/facility_accounts_controller_spec.rb, vendor/engines/c2po/spec/controllers/facility_accounts_controller_spec.rb
Only execute multi_facility test if the c2po engine is enabled
The c2po engine adds the ability to accept credit cards and purchase orders. When this engine is not turned on (like the case is with UIC), the test modified in this PR can’t run because the code it tests is not loaded. Hence, this PR adds a guard for executing the test only when the engine is turned on.
=> Only execute multi_facility test if the c2po engine is enabled

app/models/product.rb, db/migrate/20190227031006_fix_product_defaults.rb, db/schema.rb
Tech task: Use database defaults instead of activerecord callbacks for setting boolean fields on Product.
Encountered as I was working on #144828 and looking to add a new field. It seemed weird to be inconsistent.
=> [#144828] Use database for setting product boolean defaults

app/models/instrument.rb
Mark "Reservation Interval" as a required field when creating or editing an instrument.
It is required by virtue of the inclusion validation, but because it didn't have the presence validation, it didn't get the `*` to mark it as required.
This was just something I noticed as I was setting up a new instrument for testing on another story.
=> Make "Reservation Interval" appear as required on instrument edit form

app/controllers/user_suspension_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/users/show.html.haml, config/locales/en.models.yml, config/locales/views/admin/en.user_suspension.yml, config/locales/views/admin/en.users.yml, config/routes.rb, db/migrate/20190301022930_add_suspension_note_to_user.rb, db/schema.rb, spec/features/admin/suspending_a_user_spec.rb
Add the ability for global admins to add a note when suspending a user.
I decided not to add a new page (`user_suspension/new`) just because it seemed like an extra click. It might have made the user show view a little complex, though. I didn't spend much time on the interface, so feel free to give it additional love.
I also left the field optional. I suspect that you would run into problems if we added a validation on there (since all existing suspended users would not have a note).
I also went back and forth between `suspended_note` and `suspension_note`. I eventually just settled on `suspension_note`: I thought it read better on the form.
=> [#141852] Allow admins to add note when suspending a user

.github/CODEOWNERS
Remove Jason from CODEOWNERS
No reason to fill up @jhanggi’s GitHub inbox with review requests for every PR while he is out adventuring 😄
=> Remove Jason from CODEOWNERS

Gemfile, Gemfile.lock
Use published version of shoulda-matchers gem
With version 4.0.1 being published, the linked-to issue that required us to use a GitHub-backed version of the gem has been fixed, so this PR gets us back to using a published version of the gem.
=> Use published version of shoulda-matchers gem

app/assets/stylesheets/nucore.scss, app/controllers/instruments_controller.rb, app/controllers/products_common_controller.rb, app/helpers/products_helper.rb, app/models/instrument_for_cart.rb, app/models/product_for_cart.rb, app/views/admin/products/_meta_fields.html.haml, app/views/admin/products/_product_fields.html.haml, app/views/products_common/manage.html.haml, app/views/products_common/show.html.haml, config/locales/en.models.yml, config/locales/models/en.instrument_for_cart.yml, config/locales/models/en.product_for_cart.yml, config/locales/views/admin/en.products.yml, db/migrate/20190227032150_add_product_specific_training_request_toggle.rb, db/schema.rb, spec/controllers/instruments_controller_spec.rb, spec/factories/products.rb, spec/features/training_requests_spec.rb, spec/models/instrument_for_cart_spec.rb
Adds the ability to toggle the training requests feature per product.
One of the things I've done here is bring the instrument show and product show behavior closer together. Before, if there was an error such as missing schedule rules, or user not having accounts that can be used for the product, for instruments it would redirect back to the facility homepage and display an error, while for items and services it would show the product description with the error message. NU gave us the thumbs up for this change of behavior.
There's also some improvements to the admin interface to still do. The client would like a dropdown, which I agree would probably be a more efficient and intuitive interface, but it probably warrants a form object, which makes that page more complicated. Thoughts on …
=> [#144828] Toggle training requests per product

app/views/admin/products/_product_fields.html.haml
Fix toggle for restricting access for non-instrument products
When a non-instrument product is edited, the checkbox toggle should reflect the product’s type so that the element it is supposed to toggle can be found on the page. Currently, it is hardcoded to `.instrument_allows_training_requests` and when a service (for example) is being edited, the field’s class ends up being `.service_allows_training_request`, so the toggle does nothing.
=> [#144828] Fix toggle for restricting access for non-instrument products

app/views/admin/products/_product_fields.html.haml
Use timed_service rather than timed service in UI toggle to target correct element
Fixes #1897 for timed services as well (for these, `human` returned `timed service` instead of `timed_service`)
=> [#144828] Use timed_service rather than timed service in UI toggle to target correct element

spec/models/reservation_spec.rb, spec/rails_helper.rb
Stop setting unused ivars in spec/rails_helper.rb
I noticed that we’re unnecessarily setting instance variables in this file, for records that we just need to ensure exist in the database. To avoid encouraging or enabling referencing this shared state, this PR removes the ivar assignments and just leaves the record creation in place.
=> Stop setting unused ivars in spec/rails_helper.rb

app/models/schedule.rb, db/migrate/20190328133218_add_missing_indexes_for_timeline_pages.rb, db/schema.rb
[#148570] Add missing indexes to make timeline pages faster
Some of the queries on the timeline pages (which we do fewer of after #1912, but we still do them) result in very expensive query plans due to the lack of suitable indexes that they can use, given the heavy filtering we do on these pages (based on types of reservations, their dates, whether the products are archived, etc.)
=> [#148570] Add missing indexes to make timeline pages faster

spec/features/training_requests_spec.rb
Make spec/features/training_requests_spec work across schools
Currently, the spec breaks for Dartmouth since they use the word “Resource” instead of “Facility”, and the spec is hard-coded to expect the latter.
=> Make spec/features/training_requests_spec work across schools

app/controllers/user_accounts_controller.rb, spec/controllers/user_accounts_controller_spec.rb
Fix permissions so Facility Directors can manage a User’s Accounts
In #1917 I accidentally removed the ability for facility directors to see a user’s accounts (and now manage them), because the underlying resource being authorized changed as I moved the action away from `UsersController` and towards a resource-based one (not realizing the existing permissions in place). This PR fixes that.
=> [#144321] Fix permissions so Facility Directors can manage a User’s Accounts

spec/controllers/instruments_controller_spec.rb
Fix InstrumentsController spec so it works across schools
With #1881, this spec starts failing in Dartmouth, who don’t use training requests, because the error message is different since that validation fails first. This PR modifies the spec to check that a flash message is set, rather than checking the exact test, so that this works everywhere.
=> Fix InstrumentsController spec so it works across schools

app/controllers/facilities_controller.rb, app/controllers/product_accessories_controller.rb, app/helpers/products_helper.rb, app/models/facility.rb, app/models/product.rb, app/support/order_row_importer.rb, app/views/facilities/_product.html.haml, app/views/facilities/_product_list.html.haml, app/views/facilities/_recently_used_products.html.haml, app/views/facilities/index.html.haml, app/views/facilities/show.html.haml, config/locales/views/en.facilities.yml, lib/tasks/price_policies.rake, vendor/engines/bulk_email/app/controllers/bulk_email/bulk_email_controller.rb, vendor/engines/secure_rooms/app/controllers/secure_rooms/facility_occupancies_controller.rb, vendor/engines/secure_rooms/app/models/secure_rooms/facility_extension.rb
Improve performance of FacilitiesController#show page
This PR removes N+1 database queries for displaying instruments (per Skylight, we spend about 55% of the response time in the database), and rearranges the partials and attempts to optimize them so we have fewer object allocations (another performance hotspot per Skylight).
=> [#148491] Improve performance of FacilitiesController#show page

app/assets/stylesheets/app/tables.scss
Fix width of Remove? column for editing accounts for a User
=> [#144321] Fix width of Remove? column for editing accounts for a User

app/views/admin/shared/_tabnav_price_group.html.haml, app/views/price_groups/index.html.haml, config/settings.yml, lib/ability.rb, spec/controllers/price_groups_controller_spec.rb, spec/features/admin/price_group_management_spec.rb
Prevent facility directors from creating, editing or deleting price groups.
Adds `facility_directors_can_manage_price_groups` feature flag
=> [#148443] Prevent facility directors from creating, editing or deleting price groups

app/assets/stylesheets/app/tables.scss, app/controllers/user_accounts_controller.rb, app/views/user_accounts/edit.html.haml, config/locales/en.yml
Prevent removing owners from accounts, and add select all to form for editing a user’s accounts
=> [#144321] Prevent removing owners from accounts, and add select all to form for editing a user’s accounts

app/assets/stylesheets/app/tables.scss, app/views/user_accounts/show.html.haml
Only show Edit Payment Sources button for a user from global Users nav
As [agreed here by Dartmouth](https://pm.tablexi.com/issues/144321#note-15), and [detailed here](https://pm.tablexi.com/issues/147871#note-17) by Northwestern, the Edit Payment Sources button for a user should only be visible from the global Users navigation, which is restricted to a subset of users that should be able to edit a User’s accounts globally (rather than within a facility only).
Additionally, I snuck in a width change for the Remove? column so it’s got a bit more breathing room.
=> [#144321] Only show Edit Payment Sources button for a user from global Users nav

db/migrate/20190416205054_add_index_to_instrument_statuses.rb, db/schema.rb
Add missing index on instrument_statuses
As identified by NUIT and Skylight, one of the most frequent requests to NUcore for NU is querying:
```
SELECT * FROM (SELECT  "INSTRUMENT_STATUSES".* FROM "INSTRUMENT_STATUSES" WHERE "INSTRUMENT_STATUSES"."INSTRUMENT_ID" = :a1 ORDER BY created_at DESC ) WHERE ROWNUM <= :a2
```
The query currently does a full table scan because there is no index to satisfy it, and this PR fixes that. Because currently NUcore is experiencing massive performance problems and you’re offline at a full-day meeting, @rolfrussell, I am merging this so I can create the index for NU immediately.
=> [#148934] Add missing index on instrument_statuses

app/views/price_policies/index.html.haml, lib/ability.rb, spec/lib/ability_spec.rb, spec/price_policies_controller_shared_examples.rb
The original PR prevented facility directors from changing price groups.  This PR expands that to price policies.  This is based on feedback from Kayla.
With `facility_directors_can_manage_price_groups: true`
With `facility_directors_can_manage_price_groups: false`
=> [#148443 ] Prevent facility directors from changing price policies  (part deux)

spec/price_policies_controller_shared_examples.rb
Default facility_directors_can_manage_price_groups to true in relevant specs so dartmouth build succeeds
=> [#148443 ] Prevent facility directors from changing price policies (part trois) 

spec/features/admin/instrument_price_policies_controller_spec.rb, spec/features/admin/item_price_policies_controller_spec.rb, spec/features/admin/timed_service_price_policies_controller_spec.rb
Force feature specs to have 'facility_directors_can_manage_price_groups: true' so dartmouth tests pass
=> [#148443 ] Prevent facility directors from changing price policies (part quatre) 

vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/submission.js.coffee, vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/submissions_controller.rb, vendor/engines/sanger_sequencing/app/models/sanger_sequencing/ability.rb, vendor/engines/sanger_sequencing/app/models/sanger_sequencing/sample.rb, vendor/engines/sanger_sequencing/app/models/sanger_sequencing/submission.rb, vendor/engines/sanger_sequencing/app/views/sanger_sequencing/submissions/_form.html.haml, vendor/engines/sanger_sequencing/config/routes.rb, vendor/engines/sanger_sequencing/spec/factories/samples.rb, vendor/engines/sanger_sequencing/spec/models/sanger_sequencing/sample_spec.rb, vendor/engines/sanger_sequencing/spec/models/sanger_sequencing/submission_spec.rb, vendor/engines/sanger_sequencing/spec/presenters/sanger_sequencing/well_plate_presenter_spec.rb
Restore defaulting in sanger sequencing form and allow overriding in ACGT
The tight coupling between a sanger sequencing form and the ACGT form (despite them being very different) made #1947 change the prefilling behavior in ACGT (which NU does not want) and altered the prefiling behavior for sanger sequencing in a way that is different from what Dartmouth currently uses.
This PR restores the behavior in Sanger sequencing and allows us to override only the prefilling aspect of the form for ACGT, which is the combination that will work for NU and Dartmouth both.
Unfortunately, I had to restore some of the “create invalid samples and then make them valid” behavior, because for sanger sequencing forms, we default the customer sample id form field to a 4-digit-padded version of the record’s …
=> [#148949] Restore defaulting in sanger sequencing form and allow overriding in ACGT

app/controllers/facilities_controller.rb, app/models/facility.rb, app/views/facilities/_product_list.html.haml, app/views/facilities/show.html.haml
Improve performance of FacilitiesController#show (Part 2)
```
(0.4ms)  SELECT COUNT(*) FROM `products` WHERE `products`.`type` IN ('Service') AND `products`.`facility_id` = 1 AND `products`.`is_archived` = 0 AND `products`.`is_hidden` = 0
Service Load (0.3ms)  SELECT  `products`.* FROM `products` WHERE `products`.`type` IN ('Service') AND `products`.`facility_id` = 1 AND `products`.`is_archived` = 0 AND `products`.`is_hidden` = 0 ORDER BY lower(products.name) LIMIT 1
Service Load (0.3ms)  SELECT `products`.* FROM `products` WHERE `products`.`type` IN ('Service') AND `products`.`facility_id` = 1 AND `products`.`is_archived` = 0 AND `products`.`is_hidden` = 0 ORDER BY lower(products.name)
Rendered collection of facilities/_product.html.haml [2 times] (2.3ms)
Rendered …
```
=> [#148491] Improve performance of FacilitiesController#show (Part 2)

vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/submission.js.coffee
If there’s no sanger sequencing form, do nothing in the JS
If there’s no sanger sequencing form (like in the ACGT engine, where we use the same view but with different contents), do nothing here. @rolfrussell, I’m going to merge this to get a staging release out today, but if you have any comments let me know!
=> [#148949] If there’s no sanger sequencing form, do nothing in the JS

Gemfile
Move capistrano-related gems to :development group
`deployment` is not a group that we use, and per [Capistrano’s own documentation](https://github.com/capistrano/capistrano#install-the-capistrano-gem), this gem should be in `group :development`. This PR makes it so, simplifying the structure of our `Gemfile`.
=> Move capistrano-related gems to :development group

Gemfile, Gemfile.lock
Remove stale version lock for rollbar gem
The current version is 2.19.4, so this PR remove the now-stale version lock, allowing dependabot to include `rollbar` in its update checks.
=> Remove stale version lock for rollbar gem

lib/ability.rb, spec/lib/ability_spec.rb
Refactor the ability.rb class into role based methods to make it easier to manage.  Specifically this is being done in preparation for introducing a facility_billing_administrator role.
This refactoring leaves the logic of ability.rb intact but some differences:  
* It attempts to group abilities by role and not have them bleed into one another.  (It doesn't succeed 100%).
* It attempts to make it more likely that users with multiple roles will end up with the right set of abilities.  For example by reducing the number of `cannot` ability revocations.
* Originally `ability_extender.extend(user, resource)` was not reached for account_manager & billing_administrator.  In this version it is reached.  It wasn't clear to me why it shouldn't be reached.
Note that users with the `administrator` …
=> Refactor ability.rb class

spec/controllers/price_groups_controller_spec.rb, spec/lib/ability_spec.rb
because of the `facility_directors_can_manage_price_groups` feature
@vandrijevik I'm going to merge this because you are out tomorrow and it is just spec fixes.  I'd like to get the refactoring out to Dartmouth stage today if possible so they can test.
=> Refactor ability class - some tests broke in Dartmouth build

Gemfile, Gemfile.lock
Update mysql2 gem to 0.5.2
I believe this is a part of why deployments to TXI’s staging environment (which uses MySQL) are currently failing, due to https://github.com/brianmario/mysql2/issues/938 (and recompiling the native extensions against a newer version of the MySQL client libraries).
=> Update mysql2 gem to 0.5.2

app/views/facility_accounts/show.html.haml, config/settings.yml, vendor/engines/c2po/app/views/facility_accounts/account_fields/_credit_card_account.html.haml, vendor/engines/c2po/app/views/facility_accounts/account_fields/_purchase_order_account.html.haml, vendor/engines/c2po/config/locales/en.yml
Support account reference field in c2po engine
The c2po engine adds support for purchase orders and credit cards, and it is used by both NU and Dartmouth. This PR adds support for Dartmouth’s account reference field to this engine, and keeps the setting turned off in master (so the field is visible only for Dartmouth).
=> [#148865] Support account reference field in c2po engine

vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/submissions_controller.rb
Prefill rows in Sanger Sequencing for the desired quantity, not always 5
The number of rows we prefill on the sanger form should match the quantity that the user enters here:
Previously, we always pre-filled 5 samples, and even though the button to add samples worked as expected, users that would enter 17 (or whatever number they wanted) in the quantity field were confused as to why there are only 5 samples precreated.
=> [#149769] Prefill rows in Sanger Sequencing for the desired quantity, not always 5

app/services/account_builder.rb
Allow reference param in AccountBuilder
In the “move things around” shuffle while working on `#148865`, I forgot to include this commit, which actually allows the form to be saved with a reference field.
=> [#148865] Allow reference param in AccountBuilder

app/views/facility_reservations/_instrument.html.haml, app/views/reservations/_instrument.html.haml, spec/controllers/facility_reservations_controller_spec.rb
Only show relay toggles on today’s facility timeline
These toggles always reflect the current status (and they are quite slow to populate), so we will only show them on today’s page going forward.
=> [#149820] Only show relay toggles on today’s facility timeline

Gemfile, Gemfile.lock
Remove thin server from development and test
NUcore is deployed using unicorn, which is a vastly different server from thin. This PR removes thin, because there is no good reason to have it for development and test only.
=> Remove thin server from development and test

app/models/admin_reservation.rb, app/models/offline_reservation.rb, app/models/reservation.rb, db/migrate/20190610112539_add_billable_minutes_to_reservations.rb, db/schema.rb, spec/models/admin_reservation_spec.rb, spec/models/offline_reservation_spec.rb, spec/models/reservation_spec.rb
Add billable minutes to reservations and automatically set them
Adds the column and code for automatically calculating and setting it.
=> [#142338] Add billable minutes to reservations and automatically set them

app/models/order_detail.rb, app/models/reservation.rb, spec/models/order_detail_spec.rb
Update a Reservation’s billable_minutes after each save on an Order Detail
Sometimes, details that affect a reservation’s billable minutes are saved on the order detail and not on the reservation itself (such as assigning a price policy for problem orders). To ensure that `billable_minutes` get set even in these cases, we need to update the column on Reservation after the OrderDetail is saved, which is what this PR does.
=> [#142338] Update a Reservation’s billable_minutes after each save on an Order Detail

app/controllers/application_controller.rb, app/controllers/facility_order_details_controller.rb, app/models/concerns/users/roles.rb, app/models/user_role.rb, config/settings.yml, db/migrate/20190227032150_add_product_specific_training_request_toggle.rb, db/migrate/20190301022930_add_suspension_note_to_user.rb, db/migrate/20190328133218_add_missing_indexes_for_timeline_pages.rb, db/migrate/20190409205259_rename_billing_administrator_role.rb, doc/user_roles.md, lib/ability.rb, lib/tasks/demo_seed.rake, spec/controllers/facility_accounts_controller_spec.rb, spec/controllers/facility_journals_controller_spec.rb, spec/controllers/facility_statements_controller_spec.rb, spec/controllers/global_search_controller_spec.rb, spec/factories/users.rb, spec/helpers/application_helper_spec.rb, spec/lib/ability_spec.rb, spec/models/user_role_spec.rb, spec/models/user_spec.rb, spec/presenters/user_presenter_spec.rb, vendor/engines/bulk_email/spec/controllers/bulk_email/bulk_email_controller_spec.rb, vendor/engines/bulk_email/spec/models/bulk_email/ability_extension_spec.rb, vendor/engines/projects/app/models/projects/ability_extension.rb, vendor/engines/projects/spec/models/projects/ability_extension_spec.rb, vendor/engines/secure_rooms/app/models/secure_rooms/ability_extension.rb, vendor/engines/secure_rooms/app/models/secure_rooms/card_number_ability.rb, vendor/engines/secure_rooms/spec/models/ability_spec.rb, vendor/engines/secure_rooms/spec/models/secure_rooms/card_number_ability_spec.rb
Create a Facility Billing Administrator role similar to the Billing Administrator role but limited to specific facilities.
Optional.
Two feature flags have been renamed.   Make sure they merge correctly:
-   `billing_administrator`  -->  `global_billing_administrator`
-   `billing_administrator_users_tab`  -->  `global_billing_administrator_users_tab`
https://pm.tablexi.com/issues/144845
This PR renames the role `Billing Administrator` to `Global Billing Administrator`.
Kayla specified the following permissions:
- Has access to and may manage billing to:
- View and manage orders, including disputed orders
- Reassign the accounts associated with orders
- Create and manage journals * May create new users and assign user roles
- May add, edit, and suspend accounts
- May view, but not change, …
=> [#144845] Facility Billing Administrator role

app/models/reports/export_raw.rb, vendor/engines/split_accounts/app/services/split_accounts/order_detail_splitter.rb, vendor/engines/split_accounts/spec/services/order_detail_splitter_spec.rb
Handle billable minutes for split accounts
Splits the billable minutes for a reservation, shown in the raw export, the same way that the reserved and actual minutes are split.
=> [#142338] Handle billable minutes for split accounts

app/assets/javascripts/app/manage_orders.coffee, app/assets/javascripts/price_policy.js.coffee
Use change event for IE support, where input doesn’t fire on <select> elements
RaDar users (Kayla, in particular) use IE, which doesn’t fire `input` events on `<select>` elements, so we have to use `change` instead.
=> [#148102] Use change event for IE support, where input doesn’t fire on <select> elements

app/models/reservation.rb, spec/models/reservation_spec.rb
If canceled_at is set on an OrderDetail, don’t set billable_minutes
As reported by Aaron from NU, there’s a certain class of orders that need to have a state of Complete, but have been canceled (and so they have a canceled_at timestamp). For these orders, we should not set `billable_minutes` on the corresponding reservations, and this PR does exactly that.
=> [#142338] If canceled_at is set on an OrderDetail, don’t set billable_minutes

app/models/reservation.rb, lib/tasks/backfill_billable_minutes.rake
Backfill task for setting billable_minutes on past reservations
=> [#142338] Backfill task for setting billable_minutes on past reservations

app/controllers/order_detail_stored_files_controller.rb, app/models/external_service/survey_response.rb, app/models/order_detail.rb, spec/models/external_service/survey_response_spec.rb
Remove alias for OrderDetail#merge! and use standard #save!
ActiveRecord’s `save!` has standard, well-defined semantics. `Hash#merge!` also has standard, well-defined semantics. Aliasing `OrderDetail#merge!` just to mean `OrderDetail#save!` is confusing and we should not do it — it is pure cognitive overhead.
=> [#148527] Remove alias for OrderDetail#merge! and use standard #save!

app/models/external_service/external_service_receiver.rb, spec/models/external_service/external_service_receiver_spec.rb
Remove unnecessary metaprogramming from ExternalServiceReceiver
`#show_url` and `#edit_url` are the only non-ActiveRecord methods called on objects of this class, so let’s just define them and use regular Ruby semantics, instead of jumping through hoops and `method_missing` magic unnecessarily.
=> [#148527] Remove unnecessary metaprogramming from ExternalServiceReceiver

app/presenters/order_detail_presenter.rb, spec/presenters/order_detail_presenter_spec.rb
Remove unused OrderDetailPresenter#survey_url
This method is not used anywhere. Let’s remove it, so it doesn’t confuse anyone else when they’re working with external surveys!
=> [#148527] Remove unused OrderDetailPresenter#survey_url

config/deploy.rb, config/deploy/staging.rb
Reformat and alphabetize Capistrano deployment config
This format is meant to make it trivial to only add the things that are different for each school at the end, making conflicts easier to resolve, and reading these files more straightforward. I will do the same in nucore-nu and nucore-dartmouth for their staging and production deployments.
=> Reformat and alphabetize Capistrano deployment config

app/controllers/products_common_controller.rb, app/mailers/notifier.rb, app/models/order_detail.rb, app/models/order_status.rb, app/services/order_details/param_updater.rb, app/views/admin/products/_product_fields.html.haml, app/views/notifier/order_detail_status_changed.html.erb, app/views/notifier/order_detail_status_changed.text.erb, app/views/products_common/manage.html.haml, config/locales/en.models.yml, db/migrate/20190815101750_add_email_purchasers_on_order_status_changes_to_products.rb, db/schema.rb, spec/controllers/facility_journals_controller_spec.rb, spec/models/order_detail_spec.rb
Allow emailing purchasers on order status changes
The copy of the email is likely to change (pending feedback from NU), for which I will issue a separate pull request (and parametrize it into settings per our usual pattern).
=> [#146050] Allow emailing purchasers on order status changes

app/views/log_events/index.html.haml
Fix reference to LogEventSearcher, it is not in LogEvent
=> [#150534] Fix reference to LogEventSearcher, it is not in LogEvent

app/services/order_detail_batch_updater.rb
Send order status emails from OrderDetailBatchUpdater also
A follow-up to #2044, this PR makes mass updates made from the Orders tab also trigger the “order status changed” emails, that we are currently only sending when the status is changed for an individual order from its lightbox.
=> [#146050] Send order status emails from OrderDetailBatchUpdater also

lib/ability.rb, spec/controllers/facility_orders_controller_spec.rb, spec/lib/ability_spec.rb, vendor/engines/secure_rooms/app/models/secure_rooms/ability_extension.rb, vendor/engines/secure_rooms/spec/models/ability_spec.rb
Facility senior staff have the ability to see problem queues for Orders, Reservations, and Occupancies.
=> [#143406] facility senior staff can see problem queues

.github/CODEOWNERS
Tech Task: Add jhanggi back into CODEOWNERS
This hopefully will work with on user per row. I think this should make future diffs cleaner.
=> Add jhanggi back into codeowners

vendor/engines/sanger_sequencing/app/models/sanger_sequencing/sample.rb, vendor/engines/sanger_sequencing/app/models/sanger_sequencing/submission.rb
Tech Task: Add `inverse_of` to SangerSequencing Submission/Sample relationship. This ensures that some validations we add in NU will run properly.
I thought that this was something that Rails was supposed to have taken care of automatically, but in this case it did not, so we need to explicitly add it.
Extracted from https://github.com/tablexi/nucore-nu/pull/518
=> [#149698] Add inverse_of to sanger submission/sample relationship

app/controllers/facility_statements_controller.rb, app/views/facility_statements/index.html.haml, config/locales/forms/en.statement_search_form.yml, spec/features/admin/facility_statements_spec.rb
Fix statement searching CSV export and adjust the form layout to be more consistent with transaction search.
Based on client feedback to #2067 
> * Move the "Statement History" header to the space above left-hand navigation box
> * Move the "Status" drop down to the top right corner of the filtering selection area (to the right of the "Payment Sources" selection box)
> * Relabel the Date Range fields to "Start Date" and "End Date" to be consistent with other date filters
Rollbar error of the CSV export: https://rollbar.com/TableXI/nucore-nu/items/471/
```
NameError: undefined local variable or method `search_params' for #<FacilityStatementsController:0x000000000d0d2c00> (Most recent call first)
File /home/nucore/nucore-staging.northwestern.edu/releases/20190909125311/app/controllers/facili …
```
=> [#149187] Statement filtering feedback

README.md
Update readme about an issue if you run `rake db:setup` when setting up your local dev environment. I don't really know why this is the case--I think it has something to do with the engine loading. But it does work if you run the `db:create` and `db:schema:load` as separate commands.
=> Update readme about known issue of running db:setup

app/controllers/formio/submissions_controller.rb, app/models/external_service/external_service_receiver.rb, app/models/external_service/url_service.rb, app/views/formio/submissions/edit.html.haml, app/views/formio/submissions/new.html.haml, app/views/formio/submissions/show.html.haml, app/views/layouts/formio.html.haml, config/routes.rb, spec/models/external_service/url_service_spec.rb
Add support for Form.IO order forms
Form.IO’s forms have a prominently featured “Embed URL”. For each form, I wanted this to be the URL that the users can copy and enter into NUcore. However, the integration is done via JavaScript (instead of us redirecting to a different domain and then back to NUcore), and we’re serving up a NUcore page with JS that embeds the Form.IO form.
In order to make this all work, I’ve extended the existing classes to check whether the order form’s URL is a Form.IO one, and we do some special behavior. This is a short-term solution, because NU will be looking to replace Qualtrics and Surveyor forms with Form.IO-backed ones, at which point we can clean up all of this code and simplify it.
I’m still working on tests for the new controller, but I wanted to get this …
=> [#148527] Add support for Form.IO order forms

app/models/external_service/url_service.rb, spec/models/external_service/url_service_spec.rb
Gracefully handle space characters in the location of UrlService
Some URLs for Order Forms contain ` \t` characters at the beginning of their URLs, and #2089 caused the check on `location` to blow up when being parsed with URI (see errors at https://rollbar.com/TableXI/nucore-nu/items/489/). This PR fixes that by stripping out the characters, and adding a test to ensure that these URLs are handled gracefully.
=> [#148527] Gracefully handle space characters in the location of UrlService

.circleci/config.yml
Add workflows: key to Circle CI config
Without this, Circle CI is complaining that no workflows are configured, so pages like https://circleci.com/gh/tablexi/workflows/nucore-open/tree/master are empty, and the new UI blows up completely (on URLs like https://app.circleci.com/jobs/github/tablexi/nucore-open/7887)
=> Add workflows: key to Circle CI config

config/eye.yml.erb.template
Fix issues with default `eye.yml.erb template.
I believe the only thing keeping the file itself (rather than the template) from being checked in is keys/secrets in the notifications (email, ses, datadog).
=> Fixes to eye template

Gemfile, Gemfile.lock, config/initializers/health_check.rb, config/routes.rb
Adds a health check endpoint at `/healthz`.
We're adding this for UMass, but I believe we had been thinking of this for NU as well so their load balancers are hitting something a little more lightweight than the homepage.
=> Add health_check gem

config/settings.yml, vendor/engines/saml_authentication/lib/saml_authentication/devise_configurator.rb, vendor/engines/saml_authentication/lib/saml_authentication/saml_attributes.rb, vendor/engines/saml_authentication/lib/saml_authentication/user_locator.rb, vendor/engines/saml_authentication/lib/saml_authentication/user_updater.rb, vendor/engines/saml_authentication/spec/controllers/saml_authentication/sessions_controller_spec.rb
Allow SAML configuration to specify attributes that should not be updated upon login.
This is a refactor in UMass extracted from https://github.com/tablexi/nucore-umass/pull/10
This will allow some cleanup in Dartmouth as well.
=> Easy attribute update skipping in SAML

vendor/engines/saml_authentication/spec/controllers/saml_authentication/sessions_controller_spec.rb
Fix a spec that was failing when the single logout target is explicitly set via settings.
=> Fix SAML logout spec

app/controllers/users_controller.rb, app/forms/user_form.rb, app/views/search/_create_new_user.html.haml, config/settings.yml, lib/engine_manager.rb, vendor/engines/c2po/lib/c2po.rb
Adds support for some changes made in UMass around user creation. Also extracts some code from the C2PO engine into a helper for allowing the engine's views to take precedence over the main app's code.
I also renamed one of the settings so it's more in line with what it actually means: we are using netids in Dartmouth and UMass, however, the lookup feature (which NU has for looking up in their LDAP directory) does not exist.
Extracted from https://github.com/tablexi/nucore-umass/pull/18
=> Changes from UMass to support new user changes

app/services/users/convert_external_to_internal_user.rb, app/services/users/convert_internal_to_external_user.rb, lib/tasks/users.rake, spec/services/users/convert_external_to_internal_user_spec.rb, spec/services/users/convert_internal_to_external_user_spec.rb, vendor/engines/ldap_authentication/lib/ldap_authentication/user_lookup.rb, vendor/engines/ldap_authentication/lib/ldap_authentication/users_controller_extension.rb
Add rake tasks for converting a user between external and internal.
```bash
bundle exec rake users:convert:internal_to_external[netid123]
bundle exec rake users:convert:internal_to_external[netid123,true]
bundle exec rake users:convert:external_to_internal[email@example.org,netid123]
bundle exec rake users:convert:external_to_internal[email@example.org,netid123,true]
```
=> [#148121] Rake tasks for converting user between internal and external

config/application.rb, config/settings.yml
I'm assuming that by changing `application.rb` here, we only need to add the changes to the `settings.yml` file downstream in order for these changes to take effect. Let me know if I'm mistaken.
=> Move timezone configuration to settings

vendor/engines/saml_authentication/lib/saml_authentication/devise_configurator.rb
Fix SAML certificate path.
See #2113. That updated one spot, but not another.
=> Fix SAML certificate path

config/application.rb, vendor/engines/sanger_sequencing/app/presenters/sanger_sequencing/receipt_submission_presenter.rb, vendor/engines/sanger_sequencing/app/views/sanger_sequencing/purchase_notifier/_samples_table.html.haml, vendor/engines/sanger_sequencing/spec/mailers/previews/purchase_notifier_preview.rb, vendor/engines/sanger_sequencing/spec/mailers/purchase_notifier_spec.rb
Fix rare error when sending receipts for orders containing Sanger Sequencing submissions which have already been fulfilled and have results files uploaded.
`ActionView::Template::Error: undefined method `facility_sample_result_path'` because the path helper is not available in the mailer, but there was a partial that was being shared between regular web views and the email.
This should normally not be an issue since the receipt is usually sent immediately on purchase, so logically it hasn't been fulfilled and no results files have been uploaded. However, on the facility admin's order view, there is a "Send Receipt" button which re-triggers the email, so there is a possibility of this error being triggered in the future.
It also happened when delayed_job had crashed for a couple days and …
=> [#152015] Fix error on receipts containing sanger results files

app/forms/add_to_order_form.rb, app/models/order_detail.rb, app/models/order_detail_observer.rb, spec/factories/orders.rb, spec/features/admin/adding_to_an_order_spec.rb
Set ordered_at to "now" or match fulfilled at when adding onto an existing order.
This continues from #2116.
When ordering on behalf: Orders take on whatever date/time you put it under the "More options". If left blank, or unexpanded, it defaults to setting ordered_at to "now". This behavior should be unchanged.
When adding to an order:
"New" orders - get "now" as the ordered_at. If it's a reservation/service with order form, the order will receive the ordered_at of when the details gets fully added to the order (once you've resolved any issues like uploading the order form).
"Complete" - if you set a fulfilled at, both fulfilled_at and ordered_at will take on that time (the logic we've used is 12:00 noon Chicago time of the date you put in)
If you don't set a fulfilled date, both …
=> [#147850] Set ordered_at when adding to an order

app/support/accessories/accessorizer.rb, spec/models/order_details/accessorized_order_detail_spec.rb
Set `ordered_at` when adding an accessory to a reservation to match the original order's `ordered_at`.
Using the original order's `ordered_at` is what the client decided over using the timestamp of when the accessory is actually added.
=> [#147850] Set ordered_at for accessories

app/assets/stylesheets/app/homepage.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/bootstrap-accessibility.scss, app/assets/stylesheets/nucore.scss, app/assets/stylesheets/responsive.scss, app/helpers/date_helper.rb, app/views/facilities/_facilities_list.html.haml, app/views/facilities/_product.html.haml, app/views/facilities/_recently_used_facilities.html.haml, app/views/facilities/_recently_used_products.html.haml, app/views/layouts/application.html.haml, app/views/orders/_cart_row.html.haml, app/views/reservations/new.html.haml, app/views/shared/_header.html.haml, app/views/shared/nav/_nav_links.html.haml, config/locales/views/en.facilities.yml
Adds several tweaks to make nucore slightly more accessible. To identify the issues we have within nucore I used a browser extention called Axe. To find the most suitable contrast ratios for our colors I used a contrast tool found here: https://webaim.org/resources/contrastchecker/.
Outside of the changes introduced here there were a number of additional warnings that I either was not able to fix, or did not find it necessary to fix.
1. "IDs of active elements must be unique" - I was unable to fix this due to how we adjust the navbar based on screen size. Within the code, we dynamically assign IDs depending on the link type, which means we generate the same ID for the same link within the dropdown nav and the static nav on larger screens. I tinkered with it for a while, but was unable to …
=> [#169636849] Accessibility tweaks

app/views/layouts/formio.html.haml, app/views/layouts/plain.html.haml, app/views/layouts/two_column.html.haml, app/views/layouts/two_column_head.html.haml, app/views/shared/_nav.html.haml
Improve accessibility
* Fixes the label to the searchbar when user is not logged in
* Adds `lang` attribute to `html` tag on other layouts (we have more than just `application`)
* Adds `role="main"` attribute to other layouts
=> More accessibility tweaks

vendor/engines/split_accounts/spec/controllers/facility_accounts_controller_spec.rb
Tech task: update spec to handle forks of NUcore which use custom account types.
This will fix a broken test in https://github.com/tablexi/nucore-umass/pull/31
This change already exists in Dartmouth, but was never pulled up to open
=> Update spec to handle forks with different account types

app/views/facility_orders/_merge_order.html.haml
Fix error that happens when a timed service is included with a bundle containing
a reservation or a service containing an order form.
Looks like this was an edge case we just missed along the way. These partials are shared with the cart rows and it looks like that one is turning `TimedService` into `timed_service` while this was turning it to `timedservice`.
https://rollbar.com/tablexi/nucore-nu/items/472/
```
ActionView::MissingTemplate:
Missing partial orders/_timedservice_desc with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :prawn, :haml]}
```
=> [#152079] Fix error on merge orders containing timed services

config/ldap.yml.template, docker-compose.yaml, vendor/engines/ldap_authentication/README.md, vendor/engines/ldap_authentication/spec/fixtures/chico.user.ldif
Update instructions for running a dev LDAP server within `docker-compose`.
I did this as I was working on #2108 converting external to internal users. I initially left it in the `docker-compose.yml` file commented out, but I figured it won't be used enough it's not worth giving it such a prominent spot.
=> Add instructions for running LDAP in docker-compose

app/views/facility_facility_accounts/_facility_account_fields.html.haml, app/views/facility_facility_accounts/edit.html.haml, app/views/facility_facility_accounts/new.html.haml, db/migrate/20191219162724_increase_revenue_account_field_length.rb, db/schema.rb
Tech task: allow longer revenue accounts
NU has five-digit revenue accounts, but UMass has 6 digits. There is no real reason to restrict the length of this field down so hard in the database.
=> Allow longer revenue accounts

app/models/instrument_price_policy_calculations.rb, spec/models/instrument_price_policy_calculations_spec.rb
Prevent error when calculating on non-purchasable instrument price policies.
Pulled up from https://github.com/tablexi/nucore-dartmouth/pull/287
If an instrument price policy is not `can_purchase`, it is possible for the `usage_rate` to be `nil` (`presence` is required if `can_purchase` is `true`). This triggers a hard error in the calculations. This is not usually a problem, however Dartmouth has an additional field in their export raw for "Internal Cost". This is the price of an order detail if it had been purchased under the internal price group. Some products are not set up with internal pricing, so those lines was erroring during the export.
Item/Services already have this same logic built in.
=> [#150353] Prevent error when calculating on non-purchasable price policies

app/models/order_detail_observer.rb, spec/models/order_detail_spec.rb
Fix an issue where a timed service as part of a bundle cannot be added to an existing order. It was getting stuck as if there were an issue like a missing order form.
What was happening before:
We fixed a hard error in #2128, but this was still having a problem while validating the order.
=> [#152079] Fix adding timed service bundle

app/services/research_safety_always_certified_adapter.rb, app/services/research_safety_certification_lookup.rb, app/validators/order_research_safety_certification_validator.rb, app/views/product_research_safety_certification_requirements/index.html.haml, spec/features/admin/user_research_safety_certifications_controller_spec.rb, spec/features/research_safety/placing_a_reservation_spec.rb, spec/support/research_safety_test_helpers.rb, spec/validators/order_research_safety_certification_validator_spec.rb, vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/requires_research_safety_certifications_rule.rb, vendor/engines/secure_rooms/spec/services/secure_rooms/check_access/research_safety_spec.rb
Tech task: refactor parts of research safety to make it better for UMass.
The big thing this does is allow the forks to do their own internal caching of API calls. UMass will be doing a single call per user which returns a list of all of the active certifications. With this change, it uses the same object for multiple `certified?` checks so the HTTP response can be memoized.
I refactored this in conjunction with https://github.com/tablexi/nucore-umass/commit/fa658ac6cfc784f2a2d4be1298393ea6a1d52122 (which is not ready due to us still needing some additional data from them).
It also sets up a default that assumes a user is always certified. We'll need to swap this out in NU and UMass.
=> Research safety refactors for UMass

spec/models/stored_file_spec.rb
Tech task: remove spec that restricts what locations we can put uploaded files in.
This spec makes it very difficult to use a different pattern for the storage location. Now
we can change the setting to be whatever we want and it won't break specs.
In UMass we're storing them in `public/uploads`.
=> Remove constricting spec

app/models/product.rb, db/migrate/20200106194222_remove_limit_from_product_expense_account.rb, db/schema.rb, spec/models/product_spec.rb
Tech task: allow longer expense account values on Products.
Similar to #2136, UMass has six digit revenue accounts rather that NU's five (DC has 4 digit).
=> Allow longer expense accounts for products

Gemfile.lock, app/helpers/translation_helper.rb, app/models/account.rb, config/locales/en.models.yml, config/locales/models/en.account.yml
Tech task: Bump I18n gem to 1.7.1.
This change in I18n https://github.com/ruby-i18n/i18n/pull/503 breaks our lookup for one/many when there is also a nested hash.
`Account.model_name.human` was returning the hash `{:one=>"Payment Source", :other=>"Payment Sources", :owner=>"Owner", :statuses=>{:active=>"Active", :suspended=>"Suspended"}}`.
Cleaning this up seemed simpler than trying to dig in to I18n.
=> Upgrade I18n to 1.7.1

app/views/shared/_order_details_table.html.haml
Fix formatting of "Order Date" column on "My Orders" pages on both "Pending" and "All" tabs.
Before
After
=> Fix forrmatting of Order Date on "My Orders"

app/services/order_details/param_updater.rb, app/views/order_management/order_details/_form.html.haml, app/views/order_management/order_details/_reconcile_note.html.haml, spec/features/admin/manage_order_detail_spec.rb
Disable reconciliation note field on order detail modal as it is not editable. Also fix bug where filling in the reconciliation note field would not persist to the database.
=> [#140480] Disable reconciliation note field on order detail modal

README.md, config/environments/development.rb, docker-compose.yaml
Add delayed_job to our docker setup for development. This also adds `mailcatcher` so you can view emails.
In docker, `letter_opener`/`launchy` (which opens emails in the browser as soon as they get sent) won't work since they're inside a container and can't talk to the host machine.
=> Add delayed_job to docker setup

app/models/product.rb, app/services/journal_row_builder.rb, app/views/admin/products/_account_fields.html.haml, app/views/admin/shared/_sidenav_admin.html.haml, app/views/products_common/manage.html.haml, config/routes.rb, config/settings.yml, lib/settings_helper.rb, spec/controllers/facility_facility_accounts_controller_spec.rb, spec/services/journal_row_builder_spec.rb
Tech task: remove `recharge_accounts` feature flag.
UIC is the only one who used this feature flag.
=> Tech task: Remove recharge account feature flag

app/views/facility_facility_accounts/edit.html.haml, app/views/facility_facility_accounts/new.html.haml, spec/features/admin/recharge_accounts_spec.rb, spec/models/account_spec.rb
Fix recharge account editing. Clicking "Save" would take the user to a 404 page.
Editing a recharge account was broken and we didn't have a good spec around it. It's possible it was broken in #2136 by changing `form_for` to `simple_form_for`.
The spec is a little funky in how it fills out the form, but it needs to be in order for NU and Dartmouth to pass since they use different sets of fields.
=> Fix recharge account editing

Gemfile, app/models/product.rb
Tech task: Fix for oracle when upgrading to Rails 5.2
=> Rails 5.2 - Fix for Oracle: cannot where(type: Class). Must be strings.

Gemfile, Gemfile.lock, README.md, config/database.yml.mysql.template
Adds the [parallel_tests](https://github.com/grosser/parallel_tests) gem to speed up running tests locally. Usage is optional, but it can reduce the amount of time your test suite takes to run dramatically. Personally, `rspec spec` will take about 21 minutes to finish; `rake parallel:spec` reduces that to 4 minutes.
Caveat: if you're expecting a lot of errors, the output can be a little annoying to parse through. These sorts of things can be tweaked with additions to an optional `.rspec_parallel` file.
See the updated README for instructions on how to run.
=> Add parallel_tests gem

spec/features/admin/all_transactions_search_spec.rb, spec/features/admin/manage_order_detail_spec.rb
Tech task: Clean up specs.
Gets rid of a leftover debugging command as well as a couple capybara deprecations where it wants the selector to be a string rather than an integer.
=> Cleanup specs

doc/HOWTO_oracle.md
Tech task: update import script for importing Oracle database dumps.
This was originally written for an older version of Oracle. We need to change the user it's being mapped to as well as the tablespace.
=> Update import script in Oracle readme

Gemfile, Gemfile.lock
Tech task: Lock down FactoryBot to 4.X.
It's unclear why the upgrade is breaking it, but certain associations aren't
being persisted.
See https://github.com/tablexi/nucore-open/pull/1865 and the CircleCI build.
=> Lock down FactoryBot to < 5

config/locales/en.models.yml
"Manage Journals" got reverted to "Manage Journal". Add the "s" back on.
Looks like it was broken by https://github.com/tablexi/nucore-open/pull/2152 because we didn't have a journal translation/pluralization in the locales. It was using `model.human_name.pluralize` before; now it's using `model.human_name(count: :many)`.
=> Fix "Manage Journal" and add "s" on billing side bar

spec/features/admin/recharge_accounts_spec.rb, spec/services/reports/account_search_csv_spec.rb
Tech task: Fix specs that break downstream in the schools.
I've run these changes in all three schools, but I'm only issuing the PR here for now.
The second commit is my first attempt at fixing the recharge feature spec. It's particularly nasty, though. It needs to account for making sure Dartmouth doesn't make an API call, create the `api_speed_type` for UMass (which we only do on `create`, and handle a case where NU is setting the components of a chart string lazily so trying to change an attribute of a destroyed model triggers an error.
I ended up deciding it's much cleaner to conditionally run the spec based on if we're in `open` or a school that hasn't built custom validation yet.
=> Fix downstream specs

app/controllers/problem_reservations_controller.rb, app/services/problem_reservation_resolver.rb, spec/factories/products.rb, spec/features/fixing_a_problem_reservation_spec.rb, spec/services/problem_reservation_resolver_spec.rb
Ensure price policy is assigned when a user is resolving their own problem reservation. This also updates the "Fulfilled At" field to match the actual end time.
=> [#146482] Ensure price policy is assigned when resolving a problem

vendor/engines/dataprobe/lib/dataprobe/ipio.rb, vendor/engines/dataprobe/spec/lib/dataprobe/ipio_spec.rb
Use network timeouts when communicating with Dataprobe relays.
Currently, when a Dataprobe relay is not reachable via the network, the `TCPSocket.new` call hangs indefinitely, until that request’s Unicorn process is ultimately killed [for timing out](https://github.com/tablexi/nucore-nu/blob/master/config/unicorn/production.rb#L21). This PR switches to using non-blocking IO which emulates blocking IO, but with timeouts for connecting, writing, and reading of 5 seconds each. This way, a nonreachable Dataprobe relay doesn’t take down the entire application by rendering unicorns unusable until they are killed.
For a discussion of networking approaches in ruby, and why it is best to use these options on the system calls (and to never use `Timeout`), these may be helpful:
- …
=> [#151494] Use network timeouts to communice with Dataprobe relays

README.md
Clean up formatting of commands in README.
The commands weren't being formatted as code when parsed by Github's markdown parser. I noticed this because of some merge conflicts when bringing this downstream (we have some other school-specific info in the same spot of the file--easy enough to keep both).
=> Clean up formatting in readme

app/views/facility_accounts/index.html.haml, app/views/facility_accounts/search_results.html.haml
Fix location of search button on account search.
The button was being pulled to the right. Introduced in #2155
=> [#139340] Fix location of search button on account search

app/controllers/instruments_controller.rb, app/models/concerns/products/relay_support.rb, app/models/instrument_status.rb, app/models/power_relay.rb, app/models/relay.rb, app/services/instrument_status_fetcher.rb, config/initializers/power_relay_logger.rb, spec/controllers/instruments_controller_spec.rb, spec/services/instrument_status_fetcher_spec.rb
Improves the performance of relay status fetching from the reservation timeline view.
* Only query a relay once based on IP/port/outlet
* Avoid unnecessary database lookups and inserts
* Do not return non-physical relays as they do not display on the timeline view.
It also adds some logging to the network queries.
I'm not 100% we need the `InstrumentStatus`es stored in the database. I suspect there was an intention of using it as a kind of cache, but it's not really used anywhere. I feel like the entire model/database table could be removed, but I think that's beyond the scope of this PR. Values are still inserted when switching an instrument on and off.
Another improvement that would be possible is to only query by IP/port so if a relay has two outlets we only query it once.
=> [#148320] Improve performance of relay statuses

vendor/engines/secure_rooms/app/controllers/secure_rooms/occupancies_controller.rb, vendor/engines/secure_rooms/app/views/secure_rooms/occupancies/index.html.haml, vendor/engines/secure_rooms/app/views/secure_rooms/shared/_secure_rooms_dashboard.html.haml
Improve performance of public occupancies dashboard.
Skylight was highlighting this view as a painful page, partly because it is hit so often (every five seconds).
There were a couple things to improve:
* We were preloading **all** occupancies for the room. I think we thought we were preloading only the queried occupancies, but it turns out we were getting all of them. This dropped the render time from ~4-5 seconds to < 1 second
* Adding the `Accept` header in the ajax request dropped it from that 1 second to ~100ms. I believe this is because Rails didn't know how to respond so it searched through the templates to find something.
* Get rid of an N+1 and cut down the number of queries done on the view. This didn't make a significant improvement in the performance, but I do think it's a …
=> [#152761] Improve performance of occupancies dashboard

app/controllers/facility_orders_controller.rb, app/forms/add_to_order_form.rb, app/models/reports/export_raw.rb, app/models/reservation.rb, app/services/order_detail_update_param_hash_extractor.rb, app/services/order_details/param_updater.rb, app/services/reservation_creator.rb, app/views/facility_orders/_merge_order_form.html.haml, app/views/order_management/order_details/_form.html.haml, app/views/orders/_cart_row.html.haml, app/views/reservations/new.html.haml, config/locales/en.models.yml, config/locales/forms/en.add_to_order_form.yml, db/migrate/20200130153146_add_reference_id_to_order_details.rb, db/schema.rb, spec/controllers/facility_orders_controller_spec.rb, spec/controllers/order_management/order_details_controller_spec.rb, spec/features/placing_an_order_on_behalf_of_spec.rb, spec/features/purchasing_a_reservation_on_behalf_of_spec.rb
Adds a field to `OrderDetail` and updates relevant forms.
This still needs a little work. Some of the context lost on me has likely left holes in areas that require updating.
=> [#149740] Add reference_id to OrderDetail

app/views/layouts/formio.html.haml
Tech task: use haml syntax for Form.io layout and add a viewhook.
Pulled up from https://github.com/tablexi/nucore-nu/pull/560 This will allow us to make sure the Form.io pages include a favicon
=> Make formio layout more haml and add viewhook

app/models/instrument_status.rb, app/services/instrument_status_fetcher.rb, spec/services/instrument_status_fetcher_spec.rb
Fix issue where second relay on a shared schedule would be left in a spinning state on the timeline view.
Before, in the response we would get two entries but they'd be sharing the same `instrument_id`. This was causing the second relay to be left in a spinning state. This now makes sure that if there are two relays on different instruments, we return different `instrument_id`s.
=> [#148320] Fix caching issue with shared relays

app/support/order_row_importer.rb, spec/models/order_import_csv_spec.rb
Fixes for adding to an existing order in bulk upload.
Fixes to #2167.
> If the Payment Source varies for order details that are being added to an order, the Payment Source displayed in NUcore will only reflect the first Payment Source that is designated in the upload file. Behavior should be that the Payment Source matches the upload (assuming the Payment Source is valid, and the Purchaser is on it).
What was happening is for adding-on lines, it was taking the original order's account. It was still validating that user has permission to use the chart string specified in the upload; it just wasn't persisting it.
> If a Bulk Upload contains some rows with an Order number and other rows without an Order number, all orders will still be added to the Order. Behavior should be that lines …
=> [#151885] Fixes for add to order on bulk upload

app/models/order_detail.rb, spec/models/order_detail_spec.rb
Fix movable orders page when filtering by "Ordered at" and there's an unpurchased order in the cart.
We were not filtering out unpurchased orders from the `all_movable` scope. This only manifests itself in the "ordered" filter because fulfilled (the default filter) and journaled are always purchased.
```
facilities movable_transactions (ActionView::Template::Error) "undefined method `owner_user' for nil:NilClass"
```
=> [#152855] Properly filter unpurchased orders from movable

app/views/shared/transactions/_table_inside.html.haml, spec/system/admin/moving_transactions_spec.rb
Fix for movable transaction when order is missing costs.
This would usually be a problem order, or could also be a canceled order.
There are two errors `NoMethodError: undefined method '+' for nil:NilClass` and `TypeError: nil can't be coerced into BigDecimal`. They're both manifestations of the same thing, just depends on the order: `nil + something` or `something + nil`.
=> [#152849] Fix movable transaction when order is missing costs

app/support/order_row_importer.rb, spec/models/order_import_csv_spec.rb
Tech task: Fixes for add for add to order on bulk upload for NU-specific.
The original PR #2220 had a spec that was failing on NU because of its chartstring validation. Oracle also does not do case-insensitive WHERE, so the mis-cased email address was not being found in the database.
=> [#151885] Fixes for oracle on adding to bulk upload

.github/CODEOWNERS
Tech task: Update codeowners to use github teams.
Hopefully this will help us out from needing to change this file too much in the future.
=> Update codeowners to use github teams

app/forms/add_to_order_form.rb, app/models/order_status.rb, spec/forms/add_to_order_form_spec.rb
After adding to an existing order, use the most recent order's status and fulfillment date as the default in the next form.
We had a good amount of back and forth and decided this should do the trick.
- Sort the order details by creation time (i.e. ID)
- Look at the first order detail's ordered_at (this would be one of the orders in the original cart)
- Starting from the most recent, find most recent line item that does not match the original ordered date
- Use that for the defaults
- If there are no orders that don't match the original, fall back to "New"
=> [#149739] Maintain status/completion date after add to order

docker-setup.sh
Fix issue preventing the docker set up to compose the project
Replace `--no-clobber` for `-n` to avoid `cp: illegal option` error, when copying the secrete and database .yml templates
=> Change docker-setup

config/environments/production.rb
Tech task: Allow ES6 syntax in JS.
This error came up on open stage: `Uglifier::Error: Unexpected token: keyword (const). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true)`
=> Use Uglifier with harmony in order to allow ES6 syntax.

db/migrate/20200215061232_add_display_order_to_product_display_group_products.rb, db/migrate/20200224215210_fix_product_display_group_index_name.rb, db/schema.rb
Tech task: shorten index name for product display groups position field because it is too long for Oracle.
Oracle has a limit of 30 characters. I had given it an explicit name because Mysql also has some restrictions around index names.
I added this as a separate migration so that if the previous migration (which I have now changed) has already run, it'll clean up the name there.
=> Tech task: Shorten index name because oracle

spec/services/account_membership_cloner_spec.rb
Tech task: Fix account membership cloner spec when running under Oracle.
Mysql does a case-insensitive search, while Oracle is sensitive.
=> Fix account cloner spec when running under oracle

app/controllers/order_management/order_details_controller.rb, config/locales/en.controllers.yml, config/locales/views/admin/en.order_management.yml, spec/controllers/order_management/order_details_controller_spec.rb
Fix error when modifying an order detail with auto-scaled accessories.
To replicate:
- Create an instrument with an auto-scaled accessory
- Complete a reservation and add the auto-scaled accessory
- Visit the order detail popup
- Change the actual times
- Submit and you should get this error
=> [#152924] Prevent error when updating order with auto-scaled accessories

app/views/layouts/formio.html.haml
Fix print styles on Formio embeds.
When I changed from using raw html to more rails/haml-y syntax in #2212, I switched to using `stylesheet_link_tag`. According to the [docs](https://apidock.com/rails/ActionView/Helpers/AssetTagHelper/stylesheet_link_tag), "For historical reasons, the ‘media’ attribute will always be present and defaults to “screen”, so you must explicitly set it to “all” for the stylesheet(s) to apply to all media types.".
So, because it was now `media="screen"`, the styles were not being applied to print.
=> [#152933] Fix print styles on Formio embeds

app/services/journals/journal_format.rb, spec/services/journals/journal_format_spec.rb
Bug fix: The XLS spreadsheet was not being created for journals. The bug has not made it to any of the staging environments.
After the refactoring in #2206, we needed to make the format lookup symbol/string agnostic
=> Fix XLS journal spreadsheet rendering

app/controllers/facilities_controller.rb, app/models/product_display_group.rb, spec/controllers/facilities_controller_spec.rb, spec/models/product_display_group_spec.rb
Fix ordering of product groups on facility homepage.
I have no idea how I missed adding the `sorted` scope in the original PR.
=> [#38893] Fix ordering of product groups on facility homepage

app/controllers/facility_accounts_controller.rb, app/models/account.rb, app/views/facility_accounts/_account_table.html.haml, config/locales/views/en.facility_accounts.yml, spec/factories/accounts.rb, spec/factories/nufs_accounts.rb, vendor/engines/c2po/spec/controllers/facility_accounts_controller_spec.rb
Fixes a hard error on global "Users > Payment Sources". (`/facilities/all/accounts`).
This was broken by the removal of the `accountsfacility_id` column in #1863. We didn't have a test around that view, which would have caught it. This changes the behavior slightly: before we were only showing global accounts before. But when you searched that restriction when away. Now on the page, it'll include credit card and POs. I also added a facility column that will appear in the cross-facility context.
=> [#151928] Fix hard error on cross-facility Payment Sources

app/models/product.rb
Tech task: Fix circular dependency issue happening in Dartmouth.
I switched these over to `cattr_accessor` because I find the syntax a lot more readable. This came in from the product grouping in #2215. 
I'm not quite sure exactly why, but enabling the SecureRooms engine prevents this error from happening. I know that it appends to the `Product.types` array, but why it doesn't cause the circular dependency, I don't really understand.
That's why this was fine in open and NU since they both have the engine enabled while Dartmouth does not.
=> Fix circular dependency issue

spec/factories/users.rb, spec/services/order_row_importer_spec.rb, spec/system/admin/clones_account_memberships_spec.rb, vendor/engines/secure_rooms/spec/controllers/secure_rooms_api/events_controller_spec.rb
Tech task: Fix spurious test failure.
```
Failure/Error: click_link "Clone Payment Source Memberships"
Capybara::Ambiguous:
Ambiguous match, found 2 elements matching visible link "Clone Payment Source Memberships"
./vendor/bundle/ruby/2.5.0/gems/capybara-3.31.0/lib/capybara/node/finders.rb:300:in `block in synced_resolve'
./vendor/bundle/ruby/2.5.0/gems/capybara-3.31.0/lib/capybara/node/base.rb:83:in `synchronize'
./vendor/bundle/ruby/2.5.0/gems/capybara-3.31.0/lib/capybara/node/finders.rb:291:in `synced_resolve'
./vendor/bundle/ruby/2.5.0/gems/capybara-3.31.0/lib/capybara/node/finders.rb:52:in `find'
./vendor/bundle/ruby/2.5.0/gems/capybara-3.31.0/lib/capybara/node/actions.rb:42:in `click_link'
./vendor/bundle/ruby/2.5.0/gems/capybara-3.31.0/lib/capybara/session.rb:759:in `block (2 …
```
=> Tech task: Fix spurious spec failure

app/forms/add_to_order_form.rb, spec/factories/order_details.rb, spec/forms/add_to_order_form_spec.rb
Fix "Add to Order" issue where the defaults may be coming from the wrong order detail.
See #2207 for the original implementation
In Oracle, it's possible that the IDs of the rows in `order_details` (or really in any table) may not be assigned in the order of the sequence. This is due to the way that Oracle caches values in a sequence: it preallocates them into a cache, but different nodes get their own cache. So you can end up with an `ORDER_BY id` being different than `ORDER BY created_at`.
In the future, we should consider how to ensure proper ordering (see the references), but that is out of scope of the current ticket.
A couple references:
https://asktom.oracle.com/pls/apex/f?p=100:11:::NO::P11_QUESTION_ID:9539374000346423410 …
=> [#149739] Fix sorting when deciding most recent order

app/presenters/product_presenter.rb, app/views/facilities/_product.html.haml, app/views/global_search/_products.html.haml, app/views/product_display_groups/_form.html.haml, app/views/product_display_groups/index.html.haml, config/locales/en.yml, spec/presenters/product_presenter_spec.rb
Display "Inactive" next to product names in the product group management pages.
Per the client:
> This would be helpful in terms of organizing currently Active products versus Inactive products when viewing, creating, and editing Display Groups.
I also moved "Hidden" in here to allow some sharing of code with the homepage (and getting rid of the hard-coded string in the view).
=> [#38893] Add inactive tag to product names in groups

app/controllers/clone_account_memberships_controller.rb, app/controllers/log_events_controller.rb, app/controllers/search_controller.rb, app/models/log_event.rb, app/services/log_event_searcher.rb, app/services/user_finder.rb, spec/factories.rb, spec/factories/log_events.rb, spec/models/log_event_spec.rb, spec/services/log_event_searcher_spec.rb, spec/services/user_finder_spec.rb, vendor/engines/secure_rooms/spec/services/user_finder_spec.rb
Fix error when querying the audit log and the response comes back with more than 1000 accounts. Also, orders events reverse chronologically.
The way we were handling the queries before would fail if our query matched more than 1000 things. This often happened if they were querying for a partial chart string (e.g. a department). It would trigger Oracle's `OCIError: ORA-01795: maximum number of expressions in a list is 1000`.
For a good time, I recommend the ridiculousness of what I was attempting by looking at an interim query in the "much simpler query" commit.
=> [#152892] Fix error in audit log query

spec/support/matchers/case_insensitive_content.rb, spec/system/placing_an_order_on_behalf_of_spec.rb
Add case-insensitive RSpec matcher and change a test to use it.
There is a test failing in the nucore-uconn fork due to case sensitivity in the `have_content` matcher. We have added a `text-transform: uppercase` that is causing the test `it "can backdate an order"` to fail in `spec/system/placing_an_order_on_behalf_of_spec.rb` on this line:
```
expect(page).to have_content("Ordered Date\n#{I18n.l(2.days.ago.to_date, format: :usa)}")
```
The test output is:
```
Failures:
1) Placing an item order can backdate an order
Failure/Error: expect(page).to have_content("Ordered Date\n#{I18n.l(2.days.ago.to_date, format: :usa)}")
expected to find text "Ordered Date\n09/09/2020" in "You are ordering for User Last3 (username3)\nExit\nCIDER\nMy Orders » Order Receipt\nOrder Receipt\nWarning: you are on …
```
=> Add case insensitive rspec matcher

Gemfile, app/models/full_text_search/model.rb, app/models/full_text_search/oracle_searcher.rb, db/migrate/20200213005326_add_full_text_index_for_oracle.rb, spec/models/full_text_search/oracle_searcher_spec.rb
Adds on to #2209 to support Oracle
This is blocked on PRs into the oracle adapter. Right now, the schema dumper fails if there is a fulltext index and a regular index. It also does not dump the `sync: "ON COMMIT"`, which we would need in order to ensure the index is being updated properly.
=> [#140079] Improve product search for Oracle

app/controllers/account_suspend_actions.rb, app/services/log_event_searcher.rb, config/locales/views/admin/en.log_events.yml, spec/controllers/accounts_controller_spec.rb
Log the following event: Who/when some suspends/un-suspends a payment source
=> [#152869] Log payment source suspension

app/controllers/log_events_controller.rb
Tech task: preload event log associations.
This is a very minor performance enhancement. It doesn't help with any associations beyond the loggable (e.g. statement->facility or AccountUser->Account), but it helps with the initial associations.
=> [#152869] Preload associations in log event view

app/forms/add_to_order_form.rb, app/models/instrument.rb, app/models/product.rb, app/models/service.rb, spec/models/product_spec.rb, spec/system/admin/adding_to_an_order_spec.rb
Fix issue where order details added to an existing order could be missing `ordered_at`.
When adding to an existing order, if there was something to make it invalid for purchase the `ordered_at` field was not being set.
The simplest way to reproduce:
* Set up a new item or service
* Do not add any pricing
* Add the new product to an existing order. 
* It doesn't matter if you set the status to new or complete, it ends up missing the ordered_at. Fulfilled date does get set if you set it to complete.
Another way (very unlikely to actually happen in practice):
* Load the order page
* Open another tab and archive a product
* Go back to the first tab and add the archived product to the existing order. 
* No ordered_at 
We exclude archived products from the dropdown so in practice this shouldn't …
=> [#153141] Fix orders missing ordered at

app/models/budgeted_chart_string.rb, app/models/instrument.rb, app/models/price_policy.rb, app/models/product.rb, spec/lib/nucore/database/date_helper_spec.rb, spec/models/full_text_search/mysql_searcher_spec.rb, spec/models/full_text_search/oracle_searcher_spec.rb, vendor/engines/sanger_sequencing/spec/controllers/sanger_sequencing/submissions_controller_spec.rb, vendor/engines/secure_rooms/spec/controllers/facility_orders_controller_spec.rb
Tech task: Fix sporadic test failure.
The mysql/oracle full text searcher spec was not cleaning up after itself properly. When I wrote those tests I didn't realize that `PriceGroupProduct`s were being created in an `after_create` hook on the product so there were a couple of those that were being left in the database after the spec ran.
I was able to consistently reproduce the failures with
```
bundle exec rspec  spec/models/full_text_search/mysql_searcher_spec.rb spec/controllers/price_group_products_controller_spec.rb --order defined
```
```
Failure/Error: expect(PriceGroupProduct.count).to eq(PriceGroup.count)
expected: 3
got: 7
(compared using ==)
./spec/controllers/price_group_products_controller_spec.rb:47:in `block (3 levels) in <top (required)>' …
```
=> Fix sporadic test failure

app/models/statement.rb, app/services/log_event_searcher.rb
Fix Oracle error on statement search of LogEvents.
The default scope on statements was messing up oracle. Didn't seem to be an issue on mysql.
=> [#152892] Fix oracle query for event logs

config/deploy.rb
Tech task: Update version lock in capistrano deploy. This was preventing automated deployment of open to the TXI stage and likely would have caused deployment failures downstream.
See: https://circleci.com/gh/tablexi/nucore-open/8725
=> Tech task: Update version lock in capistrano deploy

lib/tasks/demo_seed.rake
Tech task: Fix for demo seeds broken by moving from single facility accounts to multi-facility accounts. 
Likely broken since we merged in #1841.
=> Fix demo:seed after multi-facility accounts

app/models/journal_row.rb, vendor/engines/split_accounts/app/services/split_accounts/order_detail_splitter.rb, vendor/engines/split_accounts/spec/services/order_detail_splitter_spec.rb
Fixes an error when creating a journal containing a split account.
The error is: `Mysql2::Error: Duplicate entry '148655' for key 'PRIMARY'`
This came up at Dartmouth. I was able to reproduce it in open, but struggled to generate a test case that failed. It seemed to be happening when the purchaser of the order detail was a member of all of the subaccounts (this may be coincidental).
What is happening is for split accounts, when you create a journal we generate virtual order details containing the split data (which account, cost, etc). We then generate a journal row for each of these virtual order details. In some cases, when we are saving the journal row to the database, Rails is also trying to auto-save the virtual order detail. Since the virtual order detail has the same ID as the …
=> [#153460] Fix error on journal creation with split account

spec/controllers/offline_reservations_controller_spec.rb, spec/services/auto_expire_reservation_spec.rb
Fix error involving metadata in WHERE clause in tests. 
In Oracle, we can't put a CLOB in the WHERE clause. Because Large objects (LOBs) are not supported in comparison conditions.
=> Fix Oracle error test involving metadata

app/controllers/problem_reservations_controller.rb, app/services/log_event_searcher.rb, app/services/problem_reservation_resolver.rb, config/locales/views/admin/en.log_events.yml, spec/services/problem_reservation_resolver_spec.rb
Log the following event: Who/when someone resolves an order in the problem queue
We are only logging when a user resolves the problem, and we are not logging or tracking when a facility resolves the problem
=> [#152869] Log resolve order problem queue

README.md
Tech task: Fix link in README to Form.io tips and tricks doc.
At some point we should convert this to markdown, but that's for another time.
=> Fix README link to form.io tips and tricks

app/views/log_events/index.html.haml, config/locales/views/admin/en.log_events.yml
Fix issues with dropdown for event type in the log event index
Error Reported: Dropdown contain "Order added to problem queue %{cause}"
=> Fix issue in Log event index dropdown

app/models/concerns/products/relay_support.rb, app/models/product_display_group.rb, spec/app_support/auto_logout_spec.rb, spec/app_support/end_reservation_only_spec.rb, spec/app_support/reservation_instrument_switcher_spec.rb, spec/models/instrument_spec.rb, spec/models/product_display_group_spec.rb
Fix situation where when creating a new product group containing an instrument with a relay the instrument was getting set to "Reservation Only"
This seems to be happening only when creating a new product group. Adding to an existing group does not trigger the bug.
I'm actually a little surprised this hasn't bitten us before in some other case like bundles.
What's happening is that the validations on `Product`/`Instrument` are being triggered as part of the `ProductDisplayGroup`'s validation. I can't explain why it's only being triggered in this single case. But because we're triggering the validations, there's some code in there that should only be triggered during product edit that deletes and rebuilds the relay. However, since we're only running the validations and not the save, the …
=> [#153552] Fix issue where relays were getting deleted

spec/controllers/users_controller_spec.rb
Fix spec failure happening in other schools when checking for the name of the internal price group #2294 
Northwestern's base rate is "Northwestern Base Rate", but Dartmouth's is "Dartmouth Base Rate".
=> [#152869] Fix failing spec for other schools

app/controllers/instruments_controller.rb, app/controllers/reservations_controller.rb, app/controllers/single_reservations_controller.rb, app/models/order_detail.rb, app/models/reservation.rb, app/services/move_to_problem_queue.rb, app/services/next_available_reservation_finder.rb, app/services/reservation_creator.rb, app/services/reservation_window.rb, app/support/reservations/validations.rb, app/views/reservations/_js_variables.html.haml, app/views/reservations/new.html.haml, config/routes.rb, spec/controllers/instruments_controller_spec.rb, spec/controllers/reservations_controller_spec.rb, spec/models/order_detail_spec.rb
Prevent abandoned carts created when clicking an instrument name. This should also help prevent order/detail IDs from growing too fast.
Before, if you click an instrument, a new order and order detail are created. Users are often doing this to check the schedule for the instrument. If the user closes the tab comes back to the instrument, yet another order detail is created. We were deleting the cart if the user clicks "Cancel", but the order and order detail IDs were still eaten up.
Now, for normal single-reservation purchases, we go to a parallel controller where we do not create the order/detail prior to the user filling out the form. I did need to rework some of the code to avoid persisting and then rolling back the order/detail. Without these changes, the abandoned carts would not be …
=> [#152604] Prevent abandoned reservation carts

app/models/full_text_search/oracle_searcher.rb, spec/models/full_text_search/oracle_searcher_spec.rb
Fixes an issue where Oracle would error when parsing reserved words like "and", "or", or "about" when doing a search for products.
See https://docs.oracle.com/cd/B10501_01/text.920/a96518/cqspcl.htm#20741 for a list of the reserved words.
See https://github.com/tablexi/nucore-nu/pull/573 (private) for verification this passes CI.
=> [#153781] Handle special characters and reserved words in oracle search

.github/CODEOWNERS
Tech task: remove GS/NUcore maintenance group from codeowners so it's just our internal team now.
@giladshanan you should now be part of the tablexi/nucore group so you should get tagged automatically on any new PRs once this is merged.
=> Tech task: remove GS/NUcore maintenance group from codeowners

app/assets/javascripts/app/reports.coffee, app/views/reports/report.html.haml
Fixes the export raw link that was somewhat broken in #2317. 
Because the controller changed to use a different parameter, whatever you put in the dialog prompt was getting ignored and it was always falling back to the current user's email address.
I considered trying to refactor it use all the newer shared code in `export_csv_report.coffee`, but this code is doing a lot of extra stuff like munging query parameters and it seemed like more effort than it was worth. I did do some renaming so it uses our more modern `js--` class prefix rather than IDs.
=> [#153049] Fix export raw link

app/controllers/single_reservations_controller.rb, app/views/reservations/new.html.haml, spec/system/admin/adding_to_an_order_spec.rb, spec/system/purchasing_a_reservation_on_behalf_of_spec.rb, spec/system/purchasing_a_reservation_spec.rb
Fixes the "Cancel" button behavior on new reservation page.
This does modify behavior a little bit, but the behavior before felt unexpected.
There are a couple ways to get to this page:
* Clicking on an instrument from the facility homepage. This is the new order-less reservation flow from #2292. 
* Before: The cancel button was missing
* After: The cancel button will return you the facility homepage.
* The reservation was in the cart because it was a bundle.
* Before: The cancel button brought you back to the facility homepage, but left everything in your cart
* After: The cancel button brings you back to your cart
* The reservation was in a cart because it was added with the order form
* Before: The order detail was removed from your cart (this seemed wrong) and brought you to the …
=> [#152604] Fix cancel button behavior on new reservation page

app/views/users/index.html.haml, app/views/users/show.html.haml, lib/ability_helper.rb
[Additional Order For Button](https://pm.tablexi.com/issues/148167)
It looks to me like it is possible to have a case where user cannot `:edit`, but they can `:switch_to`.  This is my attempt to handle both of those cases while also adding the new button inline with other buttons if they exist.
=> [#148167] Add order for button

vendor/engines/c2po/app/services/purchase_order_account_builder.rb, vendor/engines/c2po/app/views/facility_accounts/account_fields/_purchase_order_account.html.haml, vendor/engines/c2po/app/views/facility_accounts/purchase_order_account/_show.html.haml
TECH TASK:  
Add hooks for adding additional form fields for POs.  Used by Dartmouth to capture federal funding info.  Extracted from https://github.com/tablexi/nucore-dartmouth/pull/302
https://pm.tablexi.com/issues/153933
=> [#153933] Add hooks for extending POs

app/services/reservation_window.rb, spec/controllers/reservations_controller_spec.rb, spec/system/admin/price_group_management_spec.rb
While [updating specs](https://github.com/tablexi/nucore-dartmouth/pull/303) for Dartmouth that use a `user_based_price_groups: false` context, discovered a small error in the logic for reservation max windows.  This shouldn't impact NU or other contexts that use the `user_based_price_groups` feature.
=> [#152604] Check the price_groups from order_detail when setting max reservation window

app/models/full_text_search/oracle_searcher.rb, spec/models/full_text_search/oracle_searcher_spec.rb
Fixes a hard error in product searching in oracle when the query contains only curly braces. 
We were handling the empty string case before, but once we started removing the braces, it would pass the empty string check, but then become empty. Oracle doesn't like those kinds of queries.
I'll have a PR in NU with this same code in NU to validate the specs against oracle.
=> [#153781] Fixes for oracle full text search

app/controllers/facilities_controller.rb, app/views/facilities/_facility_fields.html.haml, app/views/facilities/manage.html.haml, config/locales/en.models.yml, config/settings.yml, db/migrate/20200702212036_add_payment_url_to_facilities.rb, db/schema.rb
Adds a 'Payment URL' field for facilities. This field is feature flagged and disabled by default.
In support of https://github.com/tablexi/nucore-umass/pull/48 and https://pm.tablexi.com/issues/153971
Edit:
Show:
=> [#153971] Add payment_url field to facilities

app/controllers/formio/submissions_controller.rb, app/models/order_detail.rb, spec/models/order_detail_spec.rb, vendor/engines/sanger_sequencing/README.md, vendor/engines/split_accounts/spec/services/order_detail_splitter_spec.rb
Includes the merge_with_order_id in the order number when adding to an order with form.io or IMSERC forms.
Also used when adding to an order with ACGT/Sanger forms, but that flow isn't allowed with current permissions.
I tested ACGT forms by adjusting [permissions](https://github.com/tablexi/nucore-open/blob/master/vendor/engines/sanger_sequencing/app/models/sanger_sequencing/ability.rb#L12), removing the `user: user` scoping.  With this change, it is possible to add ACGT forms to an existing order, but the user is redirected to an invalid route afterwards (`/orders/:id`).  Leaving this alone for now, assuming that this flow isn't needed.
=> [#153177] Fix incorrect order numbers when adding forms to an existing order

app/models/log_event.rb, app/models/price_group_member.rb, app/models/product_user.rb, app/views/log_events/index.html.haml
Includes the facility name for event logs where possible.  Also includes the price group name for soft deleted price groups.
=> [#153876] Event log improvements

app/services/next_available_reservation_finder.rb, spec/services/next_available_reservation_finder_spec.rb
Fix hard error when a next reservation cannot be found.
Easy way to reproduce: create a series of schedule rules that does not include the current day (e.g. Wednesday). Try to create a new reservation.
Caused by a bad copy/paste in #2292.
=> [#154053] Fix error in next reservation finder

Gemfile, Gemfile.lock
Tech task: Remove `ruby-erd` dependency.
[ruby-erd](https://github.com/voormedia/rails-erd) is used to generate model diagrams (entity relationship diagrams). It can be useful from time to time, but it doesn't provide enough value regularly to keep in the app. When it would be useful
we can always temporarily add it back in--or manually install the gem.
=> Tech task: Remove `ruby-erd` dependency

app/controllers/facility_accounts_controller.rb, spec/factories/accounts.rb, spec/services/account_builder_spec.rb, spec/system/admin/managing_payment_sources_spec.rb
Fixes an issue in UMass where when editing an account's (speed type in their case) description, the field does not get updated.
This does not seem to be an issue at other schools, but the test here should confirm that.
Dartmouth build: https://app.circleci.com/pipelines/github/tablexi/nucore-dartmouth/23/workflows/d7b389e3-6366-444e-b60a-468270d7dcc1/jobs/1468/steps
UMass build: https://app.circleci.com/pipelines/github/tablexi/nucore-umass/285/workflows/28b86eec-5e70-4b66-875e-e470822515d5/jobs/293/steps
NU build: https://app.circleci.com/pipelines/github/tablexi/nucore-nu/466/workflows/5241863f-92ff-43a3-bc84-7edb015ebeb3/jobs/2593/steps
=> [#154004] Fix issue updating an account's description

app/models/price_group.rb, db/migrate/20150204174650_add_admin_editable_to_price_group.rb, lib/tasks/cleanup.rake
UMass doesn't have a cancer center Price Group.  The seed file will just skip creating a cancer center PriceGroup if no `cancer_center` key is found in `settings.yml`.  I added a rake task that makes it easier to destroy an existing global PriceGroup if needed.  The rake task will fail if the PriceGroup has any associated `order_details`.
=> [#153972] Add the option to remove the cancer center PriceGroup

app/models/relay.rb, db/migrate/20200723191759_remove_limit_from_relays_ip.rb, db/schema.rb, spec/models/relay_spec.rb
Removes the max length restriction from the `ip` column.
=> [#153973] Allow full domain names for relays

app/controllers/concerns/price_group_members_controller.rb, app/models/account_price_group_member.rb, app/models/price_group_member.rb, app/models/user_price_group_member.rb, config/locales/views/admin/en.log_events.yml, lib/tasks/cleanup.rake, spec/models/price_group_spec.rb
I think this has actually been broken since https://github.com/tablexi/nucore-open/pull/2302.
Run `rake cleanup:log_events:metadata` after merging
=> [#153876] Fix error when viewing logs for account price groups

app/helpers/translation_helper.rb, app/mailers/account_search_result_mailer.rb, app/mailers/application_mailer.rb, app/mailers/cancellation_mailer.rb, app/mailers/csv_report_mailer.rb, app/mailers/instrument_issue_mailer.rb, app/mailers/notifier.rb, app/mailers/offline_cancellation_mailer.rb, app/mailers/order_assignment_mailer.rb, app/mailers/order_detail_dispute_mailer.rb, app/mailers/problem_order_mailer.rb, app/mailers/purchase_notifier.rb, app/mailers/results_file_notifier_mailer.rb, app/mailers/training_request_mailer.rb, app/mailers/upcoming_offline_reservation_mailer.rb, app/views/notifier/new_user.html.haml, app/views/notifier/new_user.text.erb, app/views/order_detail_dispute_mailer/dispute_resolved.text.erb, config/locales/en.notifier.yml, spec/factories/users.rb, spec/mailers/previews/notifier_preview.rb, vendor/engines/bulk_email/app/mailers/bulk_email/mailer.rb
Tech task: Refactor new user welcome email
I wanted to do this as part of the updating of the welcome email for UMass. There was a lot of duplication that we don't need between the text version and the html version. This will require a little bit of cleanup in the other schools but it should be straightforward, plus I improved the mailer preview so there's separate previews for internal vs external users.
One last thing I did was renamed `BaseMailer` to `ApplicationMailer`, which is the standard name for the mailer superclass for Rails (we originally created these classes before Rails had a standard superclass).
=> [#154126] Refactor welcome email

app/models/journal_cutoff_date.rb, app/services/admin_reservation_expirer.rb, app/support/auto_canceler.rb, app/support/journals/closer.rb, db/migrate/20100528203109_order_details_add_and_remove_fields.rb, db/migrate/20100708221022_remove_statement_id_from_order_details.rb, db/migrate/20110729173029_change_vestal_versions.rb, db/migrate/20120502223446_alter_journal_rows_remove_nu.rb, db/migrate/20120510172358_add_bi_table.rb, db/migrate/20120801223135_journal_rows_allow_null_account.rb, db/migrate/20160415231343_clean_duplicate_reservations.rb, db/migrate/20170112204251_increase_delayed_jobs_handler_capacity.rb, db/migrate/20180907190857_fix_oracle_timestamps.rb, db/migrate/20190104011154_change_account_facility_relationship_144419.rb, db/migrate/20191114122118_move_ordered_at_to_order_detail.rb, db/migrate/20200213005326_add_full_text_index_for_oracle.rb, lib/nucore/database.rb, spec/mailers/previews/cancelation_mailer_preview.rb, spec/mailers/previews/instrument_issue_mailer_preview.rb, spec/mailers/previews/notifier_preview.rb, spec/mailers/previews/order_detail_dispute_mailer_preview.rb, spec/mailers/previews/problem_order_mailer_preview.rb, spec/mailers/previews/training_request_mailer_preview.rb, spec/support/matchers/sql_matchers.rb, vendor/engines/sanger_sequencing/db/migrate/20160519030413_create_sanger_sequencing_submissions.rb, vendor/engines/sanger_sequencing/spec/mailers/previews/purchase_notifier_preview.rb
Tech task: update capitalization of `Nucore` module name so it's consistent throughout the codebase.
It needs to be `Nucore` so that Rails's autoloader loads it properly from `nucore` directory/files.
=> Tech task: Clean up capitalization of Nucore module

app/views/shared/_google.html.erb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/settings.yml
Tech task: Move google analytics key out of per-environment constant into Settings.
NU is the only one that uses this as far as I know. My plan is to open a new PR in nucore-nu that adds the key to `config/settings/production.yml` so that it's prepped for when this comes in.
=> Tech task: Move google analytics key out of constant into settings

CHANGELOG.md
Tech task: Fix changelog PR numbers so they're actual links.
I expected Github to auto-link them, but I guess that's only PRs and issues.
=> Tech task: Fix changelog links to point to the PR

Gemfile, Gemfile.lock
Tech task add `after_commit_everywhere` which is apparently now a non-explicit AASM dependency.
Fixes this message I'm seeing after https://github.com/tablexi/nucore-open/pull/2366
```
[DEPRECATION] :after_commit AASM callback is not safe in terms of race conditions and redundant calls.
Please add `gem 'after_commit_everywhere', '~> 0.1', '>= 0.1.5'` to your Gemfile in order to fix that.
```
=> Tech task: Add AASM dependency

config/locales/views/admin/en.log_events.yml
The filters work against `PriceGroupMember`, which could be `UserPriceGroupMember` or `AccountPriceGroupMember`, so the options need to be inclusive instead of doing interpolation.
=> [#153876] Fix dropdown options for price group members

app/controllers/application_controller.rb
Tech task: Refactor 404/403 handling for non-HTML pages. 
The changed code deals with 404 not founds and 403 unauthorized for things like PDFs (statements) and ICS calendar invites to have them display as an HTML error page. For example, if you mess with the ID of a statement, then you should see a 404 page, even if the extension is `.pdf`. Without this handling, we would get template not found errors.
The code as it was broke in Rails 6. This change will work in both Rails 5.2 and 6.0.
=> Tech task: Refactor 404/403 handling for non-HTML pages

Gemfile, Gemfile.lock
Tech task: Lock ckeditor to < 5 because the new version has breaking changes.
It's not quite clear to me what we would need to do in order to upgrade, so it seemed better to just lock it down for now. https://github.com/galetahub/ckeditor/compare/v4.3.0...v5.0.0
Original dependabot PR https://github.com/tablexi/nucore-open/pull/1914
=> Tech task: Lock ckeditor to < 5

Gemfile.lock
Bump devise_ldap_authenticatable to 0.8.7
Looks like we don't get dependabot updates to nested dependencies (this is required through the engine).
=> Bump devise_ldap_authenticatable to 0.8.7

Gemfile, Gemfile.lock
Tech task: switch to newer prawn-rails library.
The older [prawn_rails](https://github.com/Whoops/prawn-rails) hasn't been updated since 2012. I'm amazed it still continued to work. It will no longer work in Rails 6.
The newer [prawn-rails](https://github.com/cortiz/prawn-rails) library has the same API, but is actually maintained
=> Tech task: switch to newer prawn-rails library

app/support/auto_canceler.rb
Fix Oracle syntax error in AutoCanceler.
This was fixed in NU, but the fix never made it upstream.
Originally fixed as https://github.com/tablexi/nucore-nu/pull/407/commits/0234e93b4bbd3d195cf442ada85b8e6bf14b4648 as part of the Rails 5 upgrade. https://github.com/tablexi/nucore-nu/pull/407/files (note: this is a private repo)
=> Fix Oracle syntax error in autocanceler

vendor/engines/bulk_email/app/mailers/bulk_email/mailer.rb, vendor/engines/bulk_email/spec/mailers/bulk_email/mailer_spec.rb
Fix issue in bulk email when the facility has a comma in the name.
Dartmouth was having deliveries get blocked because they would see multiple "From" addresses in the email header. This was being caused because of how the comma was being interpreted. With this change, the from header will have quotes where necessary to probably escape everything.
This was from the facility "Electron Microscopy - Irradiation, Pre-clinical Imaging and Microscopy Resource".
```
From: <Electron.Microscopy.-.Irradiation@radar-app01.dartmouth.edu>,
Pre-clinical Imaging and Microscopy Resource
<Cancer.Center.Core.Operations@Dartmouth.edu>
```
=> [#154227] Properly handle commas in facility names when setting the "from" name in bulk email

app/models/product.rb
Tech task: Update `Product#account` validation so it works properly in tests when the feature is disabled.
Originally, this validation would never be added at all if the `expense_accounts` feature were disabled (like it is a UConn, and I'm guessing _was_ at UIC). Then, when we turned on the feature in the specs (see `spec/models/product_spec.rb:172`), the validation would not be run because it's not there. Now it will conditionally run based on the setting at runtime rather than compile/load time.
=> Update validation so it works properly with expense_accounts feature disabled

app/models/journal_row.rb, spec/models/journal_row_spec.rb
Tech task: use proc for journal row validation to better handle testing no matter what the expense_account feature flag is set to.
See also #2385
=> Tech task: Update journal row account validation to handle settings properly

spec/system/admin/review_period_spec.rb
There were warnings in the test logs:
```
The :exact option only has an effect on queries using the XPath#is method. Using it with the query "th" has no effect.
The :exact option only has an effect on queries using the XPath#is method. Using it with the query "td" has no effect.
```
... and in fact the `:exact` option had no effect.  For example, `expect(page).to have_selector("td", text: "$1.0", exact: true)` passes unexpectedly.  
This change restores expected behavior and resolves the log noise.
=> TECH TASK: Use exact_text option instead of exact

Gemfile, Gemfile.lock
The current versions of these gems aren't compiling on our servers.  We should look into using NodeJS instead of `mini_racer`.
=> TECH TASK: Rollback libv8 and mini_racer

app/views/facility_accounts/show.html.haml
There were hints showing up in the "show" view for Dartmouth.
At some point we may want to set hints to false globally for all `ReadonlyInput`s.
=> [#153933] Don't show hints in show view

Gemfile, Gemfile.lock, app/support/statement_pdf.rb
Tech task: update default paper size in PDFs to US Letter.
When we upgraded the Prawn gems in #2377, that changed the default paper size to A4. Fortunately, CI caught some errors in NU because one of the tables wasn't wide enough in the new paper size.
The documentation [suggests putting this configuration into an initializer](https://github.com/cortiz/prawn-rails#default-configuration), but this is the only place we make PDFs, this seems to be a more obvious spot a developer might see to change it if they're working on making a custom statement. (A4 is a very standard paper size outside the US).
=> Tech task: Update default PDF paper size to letter

app/controllers/instrument_schedule_positions_controller.rb, app/controllers/instruments_dashboard_controller.rb, app/models/facility.rb, app/models/reservation.rb, app/models/schedule.rb, app/views/admin/shared/_sidenav_product.html.haml, app/views/instrument_schedule_positions/edit.html.haml, app/views/instrument_schedule_positions/show.html.haml, app/views/instruments/_instrument_fields.html.haml, config/locales/views/admin/en.instrument_schedule_positions.yml, config/routes.rb, db/migrate/20200904185502_add_position_to_schedules.rb, db/schema.rb, lib/ability.rb, lib/nucore/database/sort_helper.rb, spec/lib/ability_spec.rb, spec/support/matchers/display_order_matchers.rb, spec/system/admin/instrument_schedule_positions_spec.rb
Allow admins to set the display order for instruments in the Instruments Dashboard and Daily timeline views.
Instruments are ordered by schedule, so instruments that share a schedule will appear together as a group, in alphabetical order.
=> [#153890] Custom display order for instruments

app/mailers/notifier.rb, app/models/order_detail.rb, config/locales/en.notifier.yml, spec/mailers/previews/notifier_preview.rb
Set the app name dynamically so that each school's emails will include the appropriate app name (CORUM, Radar. or NUCore).
=> [#154551] Use correct app name in mailers

config/settings.yml
This will make it easier to manage forwarded staging emails from the various schools.
=> TECH TASK: Use one common email address for staging emails

config/settings.yml, config/settings/stage.yml
In https://github.com/tablexi/nucore-open/pull/2414 the email address was set in `settings.yml` but we just want to make the change for staging, so it belongs in `stage.yml`.
=> Tech Task: Set email address in the correct place

app/models/product.rb, app/views/product_users/index.html.haml, app/views/schedule_rules/_schedule_rule_fields.html.haml, app/views/users/access_list.html.haml, spec/models/product_spec.rb, vendor/engines/bulk_email/app/services/bulk_email/recipient_searcher.rb, vendor/engines/bulk_email/spec/services/bulk_email/recipient_searcher_spec.rb
*Users on Training Request List*: exclude users who have requested training on inactive products or products that no longer have an access list
*Authorized Users*: exclude users who are authorized on inactive products or products that no longer have an access list
*Customers*: exclude customers who have only purchased products that are now inactive
*Account Owners*: exclude owners whose accounts have only been used to purchase that are now inactive
Also refactors the `RecipientSearcher` queries to make them more consistent and easier to understand.
=> [#154684] Update bulk email queries

app/models/concerns/downloadable_file.rb
This is a side effect of the switch from fog to the `aws-sdk-s3` gem.
=> Tech Task: Fix download links from S3

spec/rails_helper.rb
Tech task: Increase capybara/chrome browser size so screenshot on test failures are easier to read.
Before, especially on the front end, we were getting the responsive view.
Before
After
=> Tech task: Increase capybara browser size so screenshots are easier to read

app/controllers/orders_controller.rb, app/models/order.rb, spec/controllers/orders_controller_spec.rb, spec/system/placing_an_order_on_behalf_of_spec.rb
Fix an issue when ordering on behalf if you update the quantity field, the value of quantity nor note and reference id are not persisted.
To replicate:
* Add an item with a note to the cart
* Fill in the note and reference id fields
* Change the quantity field
* Click "Purchase"
* You will see the "Quantities have change. Please review" message, but the note, quantity, and reference fields all revert to their previous values.
* Clicking Update does the same thing
It always reverted to it's previous vlue:
Put in 3, click update -> reverts to 1
Put in 4, click update -> field shows 3
While I had no problem replicating this in the browser, I struggled to get a failing spec. I'm not sure what the difference in behavior is. I left in the specs, but they were still passing before the other …
=> [#154764] Fix issue where quantity was not being updated

app/models/time_range.rb, spec/models/offline_reservation_spec.rb, spec/models/time_range_spec.rb
Fix time range display when times are one month apart on the same day of month (e.g. 7/1 and 8/1).
They were being treated as if they were on the same day, so the range was appearing as `Fri, 07/01/2016 12:00 PM - 12:00 PM`.
I happened to notice the pending test, so I figured I'd take a quick look into this.
=> Fix time range display issue where times are the same day of the month

app/views/facilities/index.html.haml
A view hook is more than we need for the wording change we need to make in the UMass fork.
See https://github.com/tablexi/nucore-umass/pull/82
=> [#155076] Use html helper in place of the view hook for welcome helper text

app/support/statement_pdf.rb
Fix issue where statements were opening in browser rather than downloading.
The way to specify downloading in Prawn changed when we switched which gem we were using. See #2377
The similarity to issues we had with Paperclip/S3 is purely coincidental. See #2424
=> [#155168] Force download of statements rather than open in browser

CHANGELOG.md, config/ldap.yml.template, vendor/engines/ldap_authentication/lib/ldap_authentication.rb, vendor/engines/ldap_authentication/lib/ldap_authentication/user_entry.rb, vendor/engines/ldap_authentication/lib/tasks/ldap_authentication.rake
Using `username_attribute` is more accurate and desciptive.
Also, fix an instance of a scope that no longer exists (`authenticated_externally`).
=> Tech Task: Rename attribute field

vendor/engines/split_accounts/app/models/split_accounts/reports/export_raw_transformer.rb, vendor/engines/split_accounts/spec/models/reports/export_raw_spec.rb
Adds a Parent Account column to split account rows in the Export Raw CSV.
=> Add parent account to export raw reports

app/controllers/global_user_roles_controller.rb, app/models/reports/global_user_roles_report.rb, app/models/reports/log_events_report.rb, app/views/global_user_roles/edit.html.haml, app/views/global_user_roles/index.html.haml, config/locales/en.yml, spec/models/reports/global_user_roles_report_spec.rb
In support of https://github.com/tablexi/nucore-nu/pull/602
Add view hooks for additional user attributes on the Global User Roles page
Add an Export to CSV function on the Global User Roles page
=> [#153160] Add a CSV export for global user roles

app/services/order_row_importer.rb, app/views/order_imports/new.html.haml, config/locales/views/admin/en.order_imports.yml
- List optional fields and available product types
- Correctly describe default behavior (`fail_on_error` defaults to true)
- Download link doesn't require a right-click
- Move hint text closer to the relevant form elements
- Clarify logic for adding to existing orders vs creating new orders
Note: The file upload button text is "Browse" on Firefox, but "Choose File" is still accurate for Chrome
=> [#153119] Update and reorganize help text for Bulk Import

vendor/engines/split_accounts/app/models/split_accounts/reports/export_raw_transformer.rb
Move the new Parent Account column to the right-most position in the export raw report. NU uploads the report to their BI software so the column order matters.  At some point we should review column ordering as a whole.
=> [#154741] Move Parent Account column to the right

app/controllers/global_user_roles_controller.rb
I paginated the records but missed adding the `will_paginate(@users)` view helper, so when there are more than 50 records, there were no navigation arrows to get users to the next page. I'm not expecting this list to get much longer than 100 records, so skipping pagination for now.
=> [#155438] Sort global users alphabetically by last name, remove pagination

app/models/order_detail.rb, app/models/reports/account_transactions_report.rb, app/presenters/order_detail_notice_presenter.rb, config/locales/en.yml, spec/presenters/order_detail_notice_presenter_spec.rb
Adds a column to the transaction report CSV for order detail notices: Missing Actuals, Missing Price Policy, In Review, In Dispute, Open Journal, Can Reconcile, Ready for Statement, Ready for Journal, and Awaiting Payment.
=> [#155217] Add notices to transaction report

config/deploy.rb
Updates the deployment config to match the newly updated capistrano version.
=> Tech Task: Lock capistrano version at 3.15

app/views/facility_reservations/index.html.haml
Make it easier for admins to email users from the New/In Process tab of the Reservations page.
=> [#155220] Add mailto link to new/in process reservations page

app/views/facility_reservations/index.html.haml
Add a tooltip for the mailto link on the New/In Process reservations page.
=> [#155220] Add tooltip for mailto link

app/models/reservation.rb, app/services/order_details/param_updater.rb, db/migrate/20210126230013_add_object_changes_to_versions.rb, db/schema.rb, spec/models/order_detail_spec.rb, spec/models/reservation_spec.rb, spec/system/admin/manage_order_detail_spec.rb
When adding actual times to an order detail, it's possible for the reservation update to fail silently.  This results in the order detail being moved out of the problem queue even though the reservation record is still missing actual times.
Also:
- Adds paper_trail tracking to the Reservation model.  
- Adds an `object_changes` column to the Versions table to make working with paper trail easier
- Remove temporary code.
=> [#156326] Handle reservation save issues

app/assets/stylesheets/app/kiosk.scss, app/assets/stylesheets/application.scss, app/controllers/concerns/reservation_switch.rb, app/controllers/kiosk_accessories_controller.rb, app/controllers/kiosk_reservations_controller.rb, app/controllers/reservations_controller.rb, app/helpers/reservations_helper.rb, app/presenters/reservation_user_action_presenter.rb, app/services/users/auth_checker.rb, app/support/accessories/accessorizer.rb, app/views/facility_reservations/timeline.html.haml, app/views/kiosk_accessories/new.html.haml, app/views/kiosk_reservations/begin.html.haml, app/views/kiosk_reservations/index.html.haml, app/views/kiosk_reservations/stop.html.haml, config/locales/en.yml, config/locales/views/en.kiosk_accessories.yml, config/locales/views/en.kiosk_reservations.yml, config/routes.rb, config/settings.yml, lib/ability.rb, spec/presenters/reservation_user_action_presenter_spec.rb, spec/services/users/auth_checker_spec.rb, spec/system/admin/launch_kiosk_view_spec.rb, spec/system/kiosk_view_spec.rb, vendor/engines/ldap_authentication/README.md
In this PR:
In the next PR:
- Facilities should have the option to show or hide the Kiosk page and the link to get there.
=> [#152645] Kiosk View page

app/controllers/order_management/order_details_controller.rb, config/locales/views/admin/en.order_management.yml, vendor/engines/secure_rooms/app/models/secure_rooms/occupancy.rb, vendor/engines/secure_rooms/spec/factories/occupancy.rb, vendor/engines/secure_rooms/spec/models/secure_rooms/occupancy_spec.rb
Addresses a missing translation key caused by problem_description_key returning nil.
Also improves the flash displayed when a "missing actuals" reservation is edited successfully with no actual start date and no actual duration mins.
=> [#156326] Fix error messaging for 0 min actual duration

app/controllers/facility_notifications_controller.rb, app/controllers/kiosk_accessories_controller.rb, app/controllers/kiosk_reservations_controller.rb, app/support/reservation_instrument_switcher.rb, app/views/kiosk_reservations/_reservations_table.html.haml, app/views/kiosk_reservations/error.html.haml, app/views/kiosk_reservations/index.html.haml, config/locales/views/en.kiosk_accessories.yml, config/locales/views/en.kiosk_reservations.yml
Adds a 5 minute auto refresh and limits the list of reservations to those that are actionable.
Also a bit of clean up.
=> [#152645] Kiosk auto-refresh

app/services/users/auth_checker.rb, app/views/kiosk_accessories/new.html.haml, app/views/kiosk_reservations/begin.html.haml, app/views/kiosk_reservations/stop.html.haml, config/settings.yml
Adds a feature flag that allows users to take actions from the kiosk view without authenticating.
The intent is to allow gathering some user feedback while exploring further options for enabling the kiosk view feature with SSO.
=> [#155874] Add feature flag for using the kiosk without authenticating

app/controllers/concerns/sortable_billing_table.rb, app/controllers/facilities_controller.rb, app/controllers/facility_journals_controller.rb, app/controllers/facility_notifications_controller.rb, app/controllers/facility_statements_controller.rb, app/controllers/transactions_controller.rb, app/views/shared/transactions/_in_review.html.haml, app/views/shared/transactions/_sortable_table_headers.html.haml, app/views/shared/transactions/_table_headers.html.haml, app/views/shared/transactions/_table_inside.html.haml
Addresses column headers being misaligned (#156344).
Adds a new "Disputed at" column on the Disputed Orders page.
Adds sorting to the following columns:
* Order
* Order Detail
* Fulfilled Date
* Ordered For
* Payment Source
* Order Status
...and where appropriate:
* Disputed at (a new column on the Disputed Orders page)
* Review Closes
Sorting is only enabled on the following admin billing pages:
* All Transactions
* Move Transactions
* Disputed Orders
* Send Notifications
* Orders in Review
* Create Journal
* Create Statements
...and also:
* My Transactions
* My Transactions in Review (but not the Recently Reviewed table)
=> [#155218][#156344] Make columns in billing tables sortable

app/controllers/instrument_schedule_positions_controller.rb, app/models/facility.rb, app/models/schedule.rb, spec/system/admin/instrument_schedule_positions_spec.rb
On the [Manager Timeline](https://nucore-staging.northwestern.edu/facilities/all_prods/reservations/timeline) and [User Timeline](https://nucore-staging.northwestern.edu/facilities/all_prods/public_timeline) we sort first by instrument display order (`schedules.position`), then by instrument name.  
The [Instrument Dashboard](https://nucore-staging.northwestern.edu/facilities/all_prods/instruments/dashboard) was missing the sorting by name (see [here](https://github.com/tablexi/nucore-open/blob/master/app/controllers/instruments_dashboard_controller.rb#L29)), so instruments with no display order set were appearing un-sorted.
=> [#155889] Fix instrument display order on Instrument Dashboard

app/controllers/facility_journals_controller.rb, app/views/facilities/disputed_orders.html.haml, config/locales/en.yml
Adds a helpful message when there are no orders in dispute.
Removes column-based sorting from the invalid orders table.
=> [#155218] Sortable columns fixes

app/views/admin/shared/_sidenav_billing.html.haml
Adds a view hook to the bottom of the billing sidenav.
Can be used to add additional links for custom reconciliation workflows.
In support of https://github.com/tablexi/nucore-umass/pull/103
https://pm.tablexi.com/issues/155876
=> [#153934] Add view hook for custom reconciliation workflows

app/assets/javascripts/page_refresh.js, app/support/reservation_instrument_switcher.rb, app/views/reservations/list.html.haml
Adds additional logging for reservation switch failures, and an hourly refresh to the My Reservations page.
The refresh is intended to prevent a possible edge case:
* The user starts a reservation, and leaves the "My Reservations" tab open with an "End Reservation" link on it
*  The user doesn't end the reservation, and 12 hours later the reservation is moved to the problem queue
*  The user clicks the stale "End Reservation" link
*  The user will not see an error, and may think they have ended their reservation
=> [#156362] Add hourly refersh for My Reservations Page

docker-compose.yaml
Currently, there is not a context set for the mailcatcher build, so when running docker-compose is defaults to the production docker-file, which is not what's needed for a local environment setup.
=> TECH TASK: docker-compose config update

config/eye.yml.erb, config/secrets.yml.template, lib/daemons/auto_cancel.rb
The `ENV["HOSTNAME"]` is not set when the eye config gets loaded.  Instead, use the value of `run_auto_cancel` to control which instances run the auto_cancel process.
NOTE:  I've already set the value on the server.
=> [#156687] Manage auto_cancel process via secrets.yml

config/locales/en.notifier.yml, spec/mailers/notifier_spec.rb
Clean up the email wording be eliding the text "a/an", as it seems to be unnecessary
=> [151925] Remove 'a/an' from the email text.

vendor/engines/bulk_email/app/services/bulk_email/recipient_searcher.rb, vendor/engines/bulk_email/app/views/bulk_email/bulk_email/_fields.html.haml, vendor/engines/bulk_email/config/locales/en.yml, vendor/engines/bulk_email/spec/services/bulk_email/recipient_searcher_spec.rb
Updates the query scopes to include hidden products if they are active (not archived).
These products are in frequent use and purchasers of these products should be included in bulk emails.
=> [#156691] Include hidden active products in search results for bulk email

app/controllers/concerns/new_inprocess_controller.rb, app/controllers/concerns/order_details_csv_export.rb, app/mailers/account_transaction_report_mailer.rb, app/models/reports/account_transactions_report.rb, app/support/price_displayment.rb, app/views/facility_orders/index.html.haml, app/views/facility_reservations/index.html.haml, spec/models/reports/account_transaction_report_spec.rb
New/In Process orders haven't been fulfilled yet so:
- Use ordered_at instead of fulfilled_at dates.
- Costs here will mostly be estimated (or "Unassigned"), so cost headers should be clearly labeled with "Estimated".  In some cases the cost may be actual, but we are ok considering that a "very good estimate".
=> [#156428] CSV Export fixes

app/controllers/concerns/new_inprocess_controller.rb, spec/controllers/facility_orders_controller_spec.rb, spec/controllers/facility_reservations_controller_spec.rb
Fixes: ActiveJob::SerializationError (Unsupported argument type: Symbol)
=> [#156428] Use string instead of symbol

app/models/user.rb, config/initializers/devise.rb
After 29 days of inactivity, users will need to log in again.
=> [#155425] Sign out user after 29 days of inactivity

app/support/reservation_instrument_switcher.rb
The intent of this logging was to confirm whether there was an issue in the relay switch logic that would explain large numbers of problem reservations in one particular facility (at UMass).  The logging didn't reveal any bugs, so we don't need the noise.
=> Tech Task - Remove relay switch logging

app/controllers/facility_statements_controller.rb, app/models/statement.rb, app/services/statement_creator.rb, app/views/shared/_statements_table.html.haml, config/locales/en.yml, config/routes.rb, spec/system/admin/facility_statements_spec.rb
Adds a "Resend" link to each statement in the Statement History tab.
=> [#155203] Allow resending statement emails

Gemfile, Gemfile.lock, config/application.rb, spec/system/accessing_invalid_files_spec.rb
Introduce rack-utf8_sanitizer in order to prevent malicious/invalid query parameters.
This should prevent our exception-monitoring from having many results if/when an outside system scans.
=> Prevent invalid query parameters from causing exceptions

config/ldap.yml.template, vendor/engines/ldap_authentication/lib/ldap_authentication.rb
Allow setting optional encryption method in `ldap.yml`. Valid values: simple_tls or start_tls
=> Tech task: Allow setting encryption options

config/settings.yml, vendor/engines/saml_authentication/README.md
This makes the risk of not specifying an SSO binding clearer
=> Tech Task - Update saml settings documentation and README

app/controllers/users_controller.rb, app/helpers/date_helper.rb, app/models/user.rb, app/views/product_users/_table.html.haml, app/views/users/access_list.html.haml, spec/controllers/users_controller_spec.rb, spec/models/user_spec.rb, spec/system/admin/user_access_list_spec.rb
Added new "Date added" column to the User access list for Product and likewise on the Product access list for Users. This column reads from the existing `ProductUser.approved_at` field and indicates when a person was granted access to a restricted product.
User Access List:
Product Access List
=> [#144829] Display Date Added on product access lists

app/controllers/user_password_controller.rb, app/models/user.rb, config/locales/en.yml, spec/system/passwords_spec.rb
Addresses 2 issues with updating an existing user's password:
- If the password fails the complexity check, an exception is raised:  The change you wanted was rejected.
- After updating the password successfully, the user is logged out but remains on the password update page.
=> [#155473] Fix password update

app/controllers/facility_statements_controller.rb, app/forms/statement_search_form.rb, app/mailers/statement_search_result_mailer.rb, app/models/statement.rb, app/views/facility_statements/index.html.haml, app/views/global_search/_statements.html.haml, app/views/shared/_statements_table.html.haml, config/locales/en.models.yml, config/locales/en.yml, spec/system/admin/facility_statements_spec.rb
There is a column and filter on the Statement History page which is named "Sent To", but it is actually listing account admins.  This could potentially cause confusion, especially with the newly added feature allowing statements to be re-sent.
=> [#155203] Rename Sent To column

app/controllers/kiosk_reservations_controller.rb, app/helpers/reservations_helper.rb, app/models/admin_reservation.rb, app/models/offline_reservation.rb, app/models/reservation.rb, app/presenters/reservation_user_action_presenter.rb, app/support/reservations/relay_support.rb, app/views/kiosk_reservations/_reservations_table.html.haml, config/locales/views/en.kiosk_reservations.yml, spec/system/kiosk_view_spec.rb
The kiosk page doesn't behave when a switchable instrument is placed offline or on an admin hold.
Resolves `NoMethodError: undefined method 'full_name' for nil:NilClass`
=> [#157607] Handle admin and offline reservations in kiosk view

app/controllers/facility_facility_accounts_controller.rb, app/models/facility_account.rb, app/views/facility_facility_accounts/_facility_account_fields.html.haml, config/settings.yml
This adds a feature flag that makes it possible for global admins to self-correct if an error has been made.
In support of https://github.com/tablexi/nucore-dartmouth/pull/356.
=> [#157527] Add feature flag to allow global admins to edit revenue account 

config/initializers/devise.rb, config/settings.yml
Make Devise lock_strategy configurable via settings.yml
Currently, the locking behavior in Devise uses a hard-coded configuration, which does not allow for easy overriding in a school-specific fork. This PR moves the configuration to the `settings.yml` facility, so that we can selectively disable locking for a school. The method I am using for opting out of locking is based on [this line of code](https://github.com/heartcombo/devise/blob/v4.8.0/lib/devise/models/lockable.rb#L103), which should short-circuit the Lockable method and just call `super` without any of the locking functionality when the `lock_strategy` is not `:failed_attempts`. Per https://github.com/heartcombo/devise/blob/v4.8.0/lib/devise/models/lockable.rb#L19, `:none` is also a valid option for the lock strategy, so my …
=> [#157835] Make Devise lock_strategy configurable via settings.yml

app/controllers/product_user_imports_controller.rb, app/models/product_user.rb, app/models/product_user_import.rb, app/views/product_users/index.html.haml, app/views/shared/_flashes.html.haml, config/locales/en.controllers.yml, config/locales/views/admin/en.product_users.yml, config/routes.rb, db/migrate/20210706192338_create_product_user_imports.rb, db/schema.rb, spec/files/product_user_imports/existing_users.csv, spec/files/product_user_imports/user_not_found.csv, spec/models/product_user_import_spec.rb, spec/system/admin/import_product_users_spec.rb
The import process should only add new approved users when no errors occur.
Any error should prevent the import from adding new approved users.
Import includes one existing user and one new one:
All users already have access:
One username is not found:
=> [#142305] Add import for adding approved users

app/views/product_users/index.html.haml, spec/system/admin/access_list_tab_spec.rb, spec/system/admin/import_product_users_spec.rb
Use polymorphic routes for CSV export link.  
Addresses errors like:
```
ActionView::Template::Error: No route matches {:action=>"index", :controller=>"product_users", :facility_id=>"dartlab", :format=>:csv, :service_id=>"NonSterileSorterSetUp"}, missing required keys: [:instrument_id]
```
... which are caused when a user tries to access the "Access List" tab for a non-instrument product.
=> [#142305] Fix Access List tab

spec/rails_helper.rb, spec/system/kiosk_view_spec.rb
SEVERE errors will now explicitly cause a spec to fail
SEVERE and WARNING level errors will get sent to STDERR
=> Tech task - Improve system spec handling of JS errors

spec/models/journal_creation_reminder_spec.rb
These time based specs fail on the oracle-based NU repo.
=> Tech task- Make specs more flexible

app/controllers/facility_account_users_controller.rb, config/locales/views/admin/en.facility_account_users.yml, spec/controllers/facility_account_users_controller_spec.rb, spec/system/admin/managing_payment_sources_spec.rb
This PR adds error handling for attempts to replace an account owner with a user that is already an account member.
=> [#152051] Fail gracefully when replacing account owner with existing member

config/deploy.rb
If we don't remove this, Dependabot might accidentally upgrade capistrano,
and it won't fail until we try to do a deploy.
We have not found this lock entry to ever be useful in preventing capsitrano-config-inconsistency
=> Remove capistrano lock directive.

app/controllers/reservations_controller.rb, app/controllers/single_reservations_controller.rb, app/services/order_purchase_validator.rb, app/services/reservation_creator.rb, app/support/reservations/validations.rb, spec/controllers/reservations_controller_spec.rb, spec/system/holiday_reservation_access_spec.rb, spec/system/purchasing_a_reservation_on_behalf_of_spec.rb
Admins should be able to reserve on holidays when ordering for other users- even if the user doesn't have holiday access.
Also, reservations that fail validation have two error messages.  This removes the one at the top of the page that just says: "Validation failed: " with no further details.
An example of the problem:
Resolved:
=> [#142306] Allow admins to reserve on holidays when ordering on behalf of other users

spec/system/admin/facility_reservations_tooltip_spec.rb
The `nufs_account` factory is over-ridden by individual schools, and some of them have date validations.  
This spec doesn't need to care about that.
=> Tech task: Use a generic account instead of nufs_account

.github/CODEOWNERS
this should reduce the noise, and allow the code-owners to review dependabot
PRs on their schedule
=> prevent dependabot from auto-requesting code review from owners.

app/services/order_purchase_validator.rb, app/services/order_purchase_validator_error.rb
Otherwise, the specs might fail if they didn't require the containing-file
before using the error class.
This way, the auto-loader can find the error class when appropriate
=> [adhoc] Fix CI failure by separating error class.

app/views/facility_accounts_reconciliation/_table.html.haml
Updates the row scope for the table to be order detail instead of invoice number
=> [adhoc] update table row header

app/views/facility_accounts_reconciliation/_table.html.haml, config/locales/en.yml
The caption was "Credit Cards available to reconcile", but we are reconciling orders here (not payment sources).
=> [adhoc] Clarify table captions

app/assets/javascripts/form_io_submission.js, app/controllers/surveys_controller.rb, app/models/external_service/survey_response.rb, app/views/formio/submissions/edit.html.haml, app/views/formio/submissions/new.html.haml, app/views/layouts/formio.html.haml, config/routes.rb, doc/HOWTO_external_services.md, spec/models/external_service/survey_response_spec.rb, spec/support/contexts/external_service_context.rb
Use ajax POST calls to store data coming back from form.io instead of a GET/query string.
Also updates some documentation that still references the Surveyor application (which is no longer in use).
=> [#157154] Refactor Form.io survey data handling

app/views/problem_order_mailer/notify_user_with_resolution_option.html.haml, app/views/problem_order_mailer/notify_user_with_resolution_option.text.erb, config/locales/views/en.problem_order_mailer.yml
This PR updates the email for problem orders to have more clarity, and use styling to inform the actions that should be taken by the user.  Includes changes to both problem order mailers (some facilities allow users to resolve these orders on their own).
User resolvable:
Facility staff resolvable:
=> [#156659] Update text styling for problem order email

spec/system/admin/managing_payment_sources_spec.rb, vendor/engines/c2po/app/services/credit_card_account_builder.rb, vendor/engines/c2po/app/views/facility_accounts/account_fields/_credit_card_account.html.haml
Exposes cc month and year for editing by admin role users
=> [#145122] allow CC expiration date to be edited

vendor/engines/secure_rooms/app/models/secure_rooms/user_extension.rb, vendor/engines/secure_rooms/spec/models/user_spec.rb
Oracle doesn't consider an empty string when enforcing uniqueness, but MySQL does
https://decipherinfosys.wordpress.com/2007/11/30/multiple-null-values-in-a-unique-index-in-sql-serverdb2-luw/
This prevents saving empty strings to the database, since MySQL enforces uniqueness to non-NULL values.
=> [#158849] Fix card number and iclass indexes for mysql

config/ldap.yml.template, vendor/engines/ldap_authentication/README.md
We should use port 636 in development, this is what NU is using.
=> Tech task - Update template and readme to use port 636 instead of 389 for LDAP

Gemfile
Migration failed when merging in the rails 6.0 branch to NU.
Addresses:
```
bundle exec rake db:create db:schema:load
Created database '//localhost:1521/ORCLCDB.localdomain'
rake aborted!
ArgumentError: wrong number of arguments (given 4, expected 2)
/home/circleci/project/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/schema_definitions.rb:266:in `initialize'
```
Supports https://github.com/tablexi/nucore-nu/pull/760
=> [#158518] Use updated version of activerecord-oracle_enhanced-adapter

app/models/order_import.rb, app/services/order_row_importer.rb, config/locales/services/en.order_row_importer.yml, spec/services/order_row_importer_spec.rb
Use `skip_blanks` instead of `skip_lines`.
For some reason `skip_lines` is more brittle, and can cause the process to stall until the DelayedJob worker times out (4 hrs).
From the [Ruby CSV documentation](https://ruby-doc.org/stdlib-2.6.1/libdoc/csv/rdoc/CSV.html#method-c-new):
"When setting a true value, CSV will skip over any empty rows. Note that this setting will not skip rows that contain column separators, even if the rows contain no actual data."
=> [#158114] Improve error handling for order import

app/services/order_details/reconciler.rb, spec/services/order_details/reconciler_spec.rb, vendor/engines/c2po/spec/system/account_reconciliation_spec.rb
In [#142337] Implements bulk reconcile note (tablexi/nucore-open#2710) we introduced a regression that causes individually applied reconcile notes to not be saved to the db.
=> Fix reconcile note bug, add specs

app/controllers/facility_accounts_reconciliation_controller.rb, app/services/order_details/reconciler.rb, app/views/facility_accounts_reconciliation/_action_row.html.haml, spec/services/order_details/reconciler_spec.rb, vendor/engines/c2po/spec/system/account_reconciliation_spec.rb
This PR adds logic to account for the bulk note checkbox value when determining how to update order detail records.  
Also changes the bulk note checkbox checked value from `"0"` to `"1"`.  The value is not sent in params when unchecked.
Handles the following edge case:
- User checks the bulk note checkbox
- User enters a bulk note
- User unchecks the bulk note checkbox
- User reconciles transactions
In this case the bulk note will not be applied, which is the expected behavior.
=> [#159023] Only apply bulk reconcile note when the bulk note checkbox has been checked

app/assets/javascripts/bulk_note.js, spec/rails_helper.rb, spec/support/helper_methods.rb, vendor/engines/c2po/spec/system/account_reconciliation_spec.rb
Use the correct selector to hide/show bulk note input.
Also:
- Enable JS for system spec
- Address capybara deprecation message `WARN Selenium [DEPRECATION] Manager#logs is deprecated. Use Chrome::Driver#logs instead.`
- Add a `select_from_chosen` helper method
=> [#159023] Fix bulk note checkbox

app/models/concerns/products/relay_support.rb, app/views/layouts/application.html.haml
Only used for Dartmouth's login deprecation warning for non SSO users,
which is removed in https://github.com/tablexi/nucore-dartmouth/pull/379
=> [#158344] Remove global banner view hook

Gemfile, app/assets/javascripts/power_relay.js, config/initializers/oracle.rb
@jhanggi fixed some issues that were merged in to 6.1:
https://github.com/jhanggi/oracle-enhanced/pull/1
This is just adding those changes in as a patch.  This is only in use by NU:
https://github.com/tablexi/nucore-nu/pull/771
=> Add patch for oracle-enhanced adapter

app/controllers/application_controller.rb
Addresses ArgumentError: Invalid formats: nil
Silently ignored before rails 6.0
https://github.com/rails/rails/commit/0eb9e1e51a9df554e1cf7a42ec339ca6f0120a04#
Tested locally by patching `formats_with_html_fallback`:
```
def formats_with_html_fallback
[nil] + [:html]
end
```
... when clicking something I can't see while "acting as" another user:
```
rescue_from NUCore::NotPermittedWhileActingAs, with: :render_acting_error
def render_acting_error
render "/acting_error", status: 403, layout: "application", formats: formats_with_html_fallback
end
```
... the call to render raises `ArgumentError: Invalid formats: nil`.
=> [#159184] Don't pass nil as a possible mime type

app/assets/javascripts/app/manage_orders.js, app/assets/stylesheets/app/order_management.scss, app/helpers/accounts_helper.rb, app/models/account.rb, app/views/order_management/order_details/_form.html.haml, app/views/order_management/order_details/_split_costs.html.haml, vendor/engines/split_accounts/README.md
Addresses bounce back:
- split calculations were returning incorrect values
- Purchase order accounts included the facility in the link
Also I added a new column to show the split % and a link to the parent split account.
=> [#155286] Fix split calculations for order detail table

app/views/order_management/order_details/_form.html.haml
I recently made the costs partial wider without realizing it needed to be span5 for modal viewing.
Before (span6):
Fixed (span5):
=> [#155286] Adjust split cost table for view in modal

app/controllers/facility_order_details_controller.rb, spec/controllers/facility_order_details_controller_spec.rb
Addresses:
```
An ArgumentError occurred in facility_order_details#destroy:
wrong number of arguments (given 2, expected 0..1)
app/controllers/facility_order_details_controller.rb:42:in `rescue in destroy'
```
=> [#159074] Pass order_detail_id to translation helper

app/assets/stylesheets/app/order_management.scss, app/views/order_management/order_details/_costs.html.haml, app/views/order_management/order_details/_form.html.haml, app/views/order_management/order_details/_split_costs.html.haml
Narrow column on the left, wider column on the right
Update split cost table styling
=> [#159255] Rearrange order detail form inputs (#781)

app/models/order_detail.rb, app/presenters/order_detail_notice_presenter.rb, app/views/shared/_problem_order_details.html.haml, config/locales/en.yml, spec/models/order_detail_spec.rb
Prevents order details from getting reconciled when they are missing required form or survey results.
=> [#159074] Prevent completing order details that are missing a form or survey

app/views/layouts/formio.html.haml
As recommended by form.io support team
=> [#155215] Specify a stable version and use cdn.form.io

app/views/time_based_price_policies/_table.html.haml, db/migrate/20220209233321_adjust_price_policy_usage_rate_precision.rb, db/schema.rb, spec/models/instrument_price_policy_calculations_spec.rb, spec/services/price_policies/time_based_price_calculator_spec.rb
Change the hourly rate precision to 8 decimal places (from 4). Ensure that displayed price is truncated to 4 digits (not rounded).
=> [#158143] Change hourly rate precision

app/views/shared/_problem_order_details.html.haml
This link would 404 if pointed at the order detail when the order has not been merged
=> [#159074] Fix "Update" link for merge orders 

app/helpers/accounts_helper.rb, app/views/order_management/order_details/_form.html.haml, config/locales/en.yml
Reservation order details can have date and time inputs in some cases, and they need more space on the page.
=> [#159255] Give time data inputs more space

Capfile
Discovered this gap while debugging the issue with missing ckeditor icons.
This cleans up old assets while still keeping a few recent versions around to support rolling deploys and for ease of rolling back.
This should prevent an issue such as:
* `sprockets-rails` has a bug which breaks asset references
* capistrano runs `assets:precompile` against sym-linked `assets/` directory
* future deploys will reference the broken assets unless manually cleaned up
=> [#159611] Configure capistrano to clean up old assets on deploy

config/locales/en.models.yml, config/locales/en.yml
A few minor changes to terminology around Reservation costs.  Goal here is to make the connection between "Reservation Cost" and "Reservation Cost Window" more clear to the user.  This PR incorporates feedback to align the language with compliance requirements.
1. When setting pricing rules, the header "Reservation Cost" should remain "Reservation Cost"
2. When editing an instrument, the field "Cancelation Minimum (hours)" should be renamed to "Reservation Cost Window (hours)"
3. For the helper text when editing an instrument:
“The number of hours before a reservation begins that a user may cancel a reservation without invoking the Reservation Cost. When blank or set to 0, the Reservation Cost will not be charged.”
=> [#159906] Update reservation cost terminology

config/locales/en.yml, vendor/engines/saml_authentication/app/controllers/saml_authentication/sessions_controller.rb, vendor/engines/saml_authentication/spec/controllers/saml_authentication/sessions_controller_spec.rb
If updating from SAML data fails, we want to show the user a helpful message.
Coming from work on https://github.com/tablexi/nucore-umass/pull/337
=> [#155264] Handle validation errors when updating from SAML

config/environments/development.rb, config/environments/test.rb, vendor/engines/c2po/lib/c2po.rb
Because of the way classes and code were loaded, there was an issue with the c2po engine that caused the menu to load incorrectly, producing duplicate menu items. This was not noticed in development.
The `development` and `test` environments have been updated to better match `stage` and `production` and the issue with c2po has been corrected.
On stage
In development, now.
=> [#158844] Updates environment cache settings & c2po loading 

bin/latest_from_open
Not everyone has the `co` alias set for the `checkout` command
=> Tech task - Use checkout instead of co alias

.circleci/config.yml, Dockerfile, Gemfile, Gemfile.lock, README.md
Using node instead of mini_racer, as mini_racer is failing to compile on the TXI stage server.
=> [#159884] Remove mini_racer

app/controllers/account_price_group_members_controller.rb, config/locales/en.yml, spec/system/admin/price_group_management_spec.rb
The search box for adding a price group member to a facility only executes a search of accounts by account number, this is a bit difficult since the account number is not particularly memorable.
This PR updates the search to `AccountSearcher` to execute the search, allowing searches for account by account number, accounts receivable number, description, or owner's name, NetID, or username.
=> [#158778] improve payment source search

CHANGELOG.md, config/deploy.rb, config/eye.yml.erb, config/secrets.yml.template, doc/HOWTO_recurring_tasks.md, lib/daemons/recurring_tasks.rb
I've discovered 2 problems with the implementation for managing which servers run recurring tasks:
1) capistrano sets the ENV variable during deployment, but restarting the application manually with `eye-patch load config/eye.yml.erb` will not have the variable set, so recurring_tasks will not be reloaded
2) The recurring_tasks are running on both UMass production servers
Rather than debug the current approach, I'm using `.bashrc` to control the behavior.  
This is explicit, easy to reason about, and it works.
I've updated `.bashrc` on UMass and TXI servers
=> Tech task - Use .bashrc to determine which servers should run recurring_tasks

app/controllers/concerns/user_controller_flash_text.rb, app/controllers/users_controller.rb, app/helpers/users_helper.rb, app/views/users/_new_user.html.haml, app/views/users/index.html.haml, config/locales/views/admin/en.users.yml, spec/controllers/users_controller_spec.rb, spec/helpers/users_helper_spec.rb, spec/system/admin/managing_user_spec.rb
When a user is created, there are some helpful things the admin should be reminded of.
This puts information about price group and payment source in the flash message that appears after successful user creation.
=> [#157969] After User Creation Screen changes

app/support/orders/item_adder.rb, app/views/bundle_products/edit.html.haml, app/views/bundle_products/index.html.haml, app/views/bundle_products/new.html.haml, app/views/orders/_cart_row.html.haml, spec/system/placing_an_order_spec.rb
When TimedServices are part of a bundle, the time is preset, it's not possible for a user to adjust the amount of time they'd like.
This updates the behavior of bundled TimedServices so that the time can be adjusted by the user on checkout.
=> [#153891] TimedServices adjustment in product bundles

spec/system/admin/managing_user_spec.rb
Sometimes the db call executes before the user record is created by the system spec
=> Tech task -Remove db call

app/lib/staging_mail_interceptor.rb, config/eye.yml.erb, config/settings.yml, config/settings/stage.yml, spec/lib/staging_mail_interceptor_spec.rb, spec/models/product_spec.rb, spec/services/log_event_searcher_spec.rb, vendor/engines/bulk_email/bulk_email.gemspec, vendor/engines/c2po/c2po.gemspec, vendor/engines/dataprobe/dataprobe.gemspec, vendor/engines/fine_uploader/fine_uploader.gemspec, vendor/engines/fullcalendar/fullcalendar.gemspec, vendor/engines/ldap_authentication/ldap_authentication.gemspec, vendor/engines/projects/projects.gemspec, vendor/engines/saml_authentication/saml_authentication.gemspec, vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/admin/batches_controller.rb, vendor/engines/sanger_sequencing/sanger_sequencing.gemspec, vendor/engines/secure_rooms/secure_rooms.gemspec, vendor/engines/split_accounts/split_accounts.gemspec
- Use "allow_list" in place of "whitelist", a term which has a racist history
- Allow stage to send email to any address "@txidigital.com"
- Clean up references to "@tablexi.com"
=> Tech task - Add txi digital to allow list

app/assets/javascripts/app/bundle_products.js, app/views/bundle_products/new.html.haml, config/locales/en.yml
For Timed Services, the quantity field may be confusing for some users, since its meaning has recently changed.
This adds some informational hint text that dynamically appears when a Timed Service is being added to the bundle. It also makes it trivial to add hints for other product types.
=> [#153891] Adds dynamic hint logic to new bundle product view

app/forms/user_form.rb, app/helpers/users_helper.rb, app/models/user.rb, app/services/users/convert_external_to_internal_user.rb, app/services/users/convert_internal_to_external_user.rb, app/services/users/default_price_group_selector.rb, spec/models/user_spec.rb
We currently have 2 ways to determine if a user is internal or external - checking for a stored password or comparing username and email.  We'd like to be able to support SSO that uses email as username, and this allows that while also moving to a single way of checking user type.  
I've confirmed this change with all the schools.  Some schools will benefit from a little user record cleanup after this is released.
=> [#160400] Simplify logic for user type (internal/external)

config/application.rb
[ActiveRecord::Coders::YAMLColumn](https://github.com/rails/rails/blob/dc1242fd5a4d91e63846ab552a07e19ebf8716ac/activerecord/CHANGELOG.md) changed in 6.1.6.1, requiring `yaml_column_permitted_classes` to be set in the `application.rb` file
=> Rails 6.1.6.1 bump bug fix

app/assets/javascripts/app/orders_edit_date.js, app/controllers/orders_controller.rb, app/services/order_detail_update_param_hash_extractor.rb, app/views/orders/_edit_date.html.haml, app/views/orders/_form.html.haml, config/locales/en.yml, spec/controllers/orders_controller_spec.rb, spec/system/placing_an_order_on_behalf_of_spec.rb
This separates the order date from the completion date on the orders show page. The fulfilled at date is manually set.
=> [#157534] Change Order on Behalf of Screen

spec/system/admin/recharge_accounts_spec.rb
the have_field matcher doesn't handle nil/empty string value checking:
https://github.com/teamcapybara/capybara/pull/1169#issuecomment-44575123
=> Tech task - Fix recharge spec

config/locales/en.yml, vendor/engines/saml_authentication/lib/saml_authentication/saml_authenticatable_with_custom_error.rb, vendor/engines/saml_authentication/spec/controllers/saml_authentication/sessions_controller_spec.rb
To help clarify/confirm for the user and assist in debugging, it would be helpful to include the username and email that is returned from the SAML response when SSO fails.
Also logs a warning to rollbar with the complete user attributes.
=> [#160776] Include username and email when NETID login fails

app/controllers/orders_controller.rb, app/services/order_purchaser.rb, app/views/orders/_edit_date.html.haml, spec/system/placing_an_order_on_behalf_of_spec.rb
- After clicking "update", show the fulfilled date on the form
- Set the fulfilled date as expected
=> [#160846] Fix fulfilled_at date setting when ordering for

app/models/bundle_product.rb, spec/factories/bundle_products.rb, spec/models/bundle_product_spec.rb
It would be a good idea to check if we have any bundles that will be made invalid by this change:
```
Bundle.all.select do |b| 
b.bundle_products.any? do |bp| 
bp.product.type == "TimedService" && bp.quantity > 9
end
end.count
```
Previously, this `quantity` field was used to indicate quantity of minutes, now it is quantity of products.
=> [#160830] Limit quantity to 10 for times service products in bundles

app/views/account_price_group_members/new.html.haml, app/views/account_users/user_search.html.haml, app/views/clone_account_memberships/index.html.haml, app/views/facility_account_users/user_search.html.haml, app/views/facility_accounts/index.html.haml, app/views/facility_accounts/new_account_user_search.html.haml, app/views/facility_users/search.html.haml, app/views/global_user_roles/search.html.haml, app/views/order_imports/new.html.haml, app/views/product_users/index.html.haml, app/views/product_users/new.html.haml, app/views/user_price_group_members/new.html.haml, app/views/users/_search_form.html.haml, app/views/users/new.html.haml, config/locales/en.notifier.yml, config/locales/en.yml, config/locales/views/admin/en.clone_account_memberships.yml, config/locales/views/admin/en.order_imports.yml, config/locales/views/admin/en.product_users.yml, config/settings.yml
Not every school calls their online SSO account "NetID". This reorganizes the translation files so that "NetID" is easy to change to something else.
The order import template contains "Netid" and is a static file. So this also adds `order_import_template_name` to the `settngs.yml` file, in case a school would like to change to its own template with school specific language.
=> [#160767] Adds NetID as a term in the translation file

config/locales/en.yml, config/locales/views/admin/en.clone_account_memberships.yml
OSU will have "name or username" instead of "name, NetID, or username" in many places.
=> [#160466] Allow comma usage when setting SSO ID name

CHANGELOG.md, app/controllers/facility_facility_accounts_controller.rb, app/models/facility_account.rb, app/services/converters/double_entry_order_detail_to_journal_row_attributes.rb, app/services/converters/product_to_journal_row_attributes.rb, app/views/facility_facility_accounts/_facility_account_fields.html.haml, spec/services/converters/product_to_journal_row_attributes_spec.rb, vendor/engines/split_accounts/spec/services/journal_row_builder_spec.rb
I have confirmed this approach with UConn - the only other school besides OSU that currently has `expense_accounts: false`.
=> [#160840] Hide unused revenue_account inputs (#180)

spec/controllers/account_price_group_members_controller_spec.rb, vendor/engines/c2po/spec/controllers/account_price_group_members_controller_spec.rb
Since account number formats and validations may be different across schools, this uses account numbers from factories instead of hardcoding them. This prevents spec failures from invalid account formats.
Changes are from https://github.com/Oregon-State/nucore-osu/pull/125/commits/f4649c2b52d2fb8394756328727c66ec1112baf8
=> Account spec changes from OSU

app/assets/javascripts/app/manage_orders.js, app/views/order_management/order_details/_form.html.haml, config/locales/en.yml
To recalculate the price of an order detail, the payment source can be toggled, which is a fairly unnatural way to do that. This adds a "Recalculate pricing" button that recalculates the price.
=> [#159098] Adds "Recalculate pricing" button to order detail form

app/views/admin/shared/_tabnav_product.html.haml
This puts the tabs in a more intuitive order
=> [#160012] Reorder instrument/secure room tabs

vendor/engines/c2po/spec/controllers/account_price_group_members_controller_spec.rb
In UMass the search string used for this spec was too short to be valid, so the spec failed. This lengthens the search string to be valid.
=> Account price group members controller spec fix

config/locales/views/admin/en.transaction_search.yml
In `transaction_search`, the value of `journal_or_statement_date` was changed incorrectly. This changes it back.
=> Small translation fix.

db/migrate/20221010164640_adjust_relays_ethernet_port_number.rb, db/schema.rb, spec/system/admin/instrument_relay_tab_spec.rb
This changes the `ethernet_port_number` on Relays from an integer to a string
=> [#160949] change ethernet port to string

app/models/account.rb, app/models/account_config.rb, app/support/reconcilable_account.rb, config/environments/development.rb, spec/controllers/facility_accounts_reconciliation_controller_spec.rb, vendor/engines/c2po/app/models/credit_card_account.rb, vendor/engines/c2po/app/models/purchase_order_account.rb, vendor/engines/c2po/lib/c2po.rb
Cached classes requires a lot of server restarts when developing. This disables class caching.
It also adjusts some loading behavior of the `C2po` engine so the application works correctly with respect to the caching. The way `C2po` was setup to load, `AccountConfig`'s reconcilable accounts would disappear. This make the reconcilable account code a bit more clear.
=> Disables class caching in the development environment

app/models/account_config.rb, vendor/engines/c2po/lib/c2po.rb
This reverts commit dc521a2d754b5343afb7abccece54eae6ef013fc.
Account config collections have order dependencies.
We can handle uniqueness more easily with arrays (vs handling ordering with sets)
=> Tech task: Revert "Changing AccountConfig's data structures to sets (#3188)"

db/schema.rb
This was incorrectly changed in a PR (#3137) of unrelated changes. This changes the schema back
=> Changes `revenue_account` in schema back to integer

app/models/order_status.rb, spec/system/admin/manage_order_detail_spec.rb
Addresses https://rollbar.com/tablexi/nucore-nu/items/823/.
```
NameError: undefined local variable or method `current_facility' for #<Class:0x000000000adb9610>
```
introduced in [this](https://github.com/tablexi/nucore-open/pull/3156/files#diff-ef96217bf42a44cb4eba3a75f27db3dbe91e46dc9d9486b60a649f37fb2164b8R58) commit
=> Tech task: Fix typo in canceled_statuses_for_facility and add spec coverage

Dockerfile, Gemfile, Gemfile.lock, app/assets/stylesheets/app/facility.scss, app/models/concerns/downloadable_files/image.rb, app/views/facilities/_facilities_list.html.haml, app/views/facilities/_facility_fields.html.haml, app/views/facilities/manage.html.haml, config/locales/simple_form.en.yml
Users can attached image files of any size and dimension to a Facility, which can make the `facility_tile_list` grid layout in unexpected ways. This uses `ActiveStroage#variant` to make images the same size and dimension, it adds colored padding if the image is the wrong aspect ratio.
This depends on `libvips` to do the image processing. That or `ImageMagick` must be installed on the server for this to work.
=> [#160368] Add image processing to DownloadableFiles::Image

app/assets/stylesheets/app/tables.scss, app/views/shared/_order_detail_action_form.html.haml
At smaller viewport widths, the Status column of the order details table is too narrow. This sets a minimum width for that column
=> [#160958] Sets a minimum width of the status column on the order details table

config/secrets.yml.template, spec/services/scishield_api_adapter_spec.rb
For some reason, mocking the value for `scishield_endpoint` in the spec file is [flaky](https://app.circleci.com/pipelines/github/tablexi/nucore-open/3196/workflows/c4589d9f-581d-44a2-a858-4a04654bc7c1/jobs/11447/parallel-runs/2?filterBy=FAILED):
`Absolute URI missing hierarchical segment: 'http://?include=course_id&filter[status]=1&filter[user][condition][path]=user_id.mail&filter[user][condition][operator]=%3D&filter[user][condition][value]=research%40osu.edu'`
I tried debugging by SSHing into the active CI run, and the specs that sometimes fail in CI were passing.  They also pass when run locally.  And also sometimes they pass in CI as well.
Rather than dig further into the cause, I'd like to try reading the value from the secrets file for testing environment instead.
=> [#160883] Set scishield_endpoint in spec environment

app/mailers/results_file_notifier_mailer.rb, spec/mailers/previews/results_file_notifier_preview.rb
The reply-to email address for every file upload notification email was the same. The changes the reply-to email address to the product's contact address, or the facility's address, if they exist.
=> [#159346] Adds optional reply-to address to ResultsFileNotifierMailer

config/initializers/devise.rb, config/settings.yml
Some schools want a different unlock strategy and a different lock period. This adds those configurations to the settings file.
=> [#160506] Add unlock strategy and timing to settings file

app/models/order_status.rb, spec/models/order_status_spec.rb
Some schools have a custom root order status.  This change allows handling that with the newly refactored approach to order statuses (we don't use awesome nested set any more).
=> [#161123] Allow handling custom root order statuses

vendor/engines/split_accounts/app/models/split_accounts/split_account.rb
When looking at lists of accounts, it can sometimes be helpful to quickly identify which ones are split accounts.
This adds "(SPLIT)" in front of split accounts account numbers to make them easier to identify.
=> [#160914 ] Add label to split accounts

config/settings.yml, spec/models/account_spec.rb, vendor/engines/c2po/app/models/purchase_order_account.rb, vendor/engines/c2po/app/views/facility_accounts/account_fields/_affiliate.html.haml, vendor/engines/c2po/app/views/facility_accounts/account_fields/_purchase_order_account.html.haml, vendor/engines/c2po/config/locales/en.yml
Some changes from https://github.com/Oregon-State/nucore-osu/pull/225
This PR:
* Creates a feature flag to include `AffiliateAccount` in purchase order or not. This allows an affiliate account to be optional if false.
* Updates views to depend on `PurchaseOrderAccount`'s attribute names rather than field names in the translation file.
* Adjusts account_spec to properly work with name-spaced facility accounts
=> [#161053] PurchaseOrder & Account updates from OSU

app/lib/affiliate_account.rb, app/models/account.rb, config/settings.yml, doc/HOWTO_feature_flags.md, spec/support/shared_examples/affiliate_account_shared_examples.rb, vendor/engines/c2po/app/models/purchase_order_account.rb
When the change was pulled into OSU, spec failures occurred. This cherry picks the fixes for those failures.
It adjusts how the `po_require_affiliate_account` feature flag works. It removes the `affiliate_id` validation instead of removing the `AffiliateAccount` include. And it insures the validation test only runs for `PurchaseOrderAccount`
=> [#161053] Pulls in affiliate fixes from OSU

app/controllers/kiosk_reservations_controller.rb, spec/system/admin/launch_kiosk_view_spec.rb
Refreshing the kiosk was returning a 500 error. This corrects that by passing the correct variable to the view, and adds a couple of specs to test.
=> [#160950] Fixes the kiosk refresh

app/controllers/products_common_controller.rb, app/views/admin/products/_account_fields.html.haml, app/views/products_common/manage.html.haml
To enable an instrument to have an external revenue account in https://github.com/Oregon-State/nucore-osu/pull/233, some changes were made to the `Product` controller and views.
This ports over the changes that should be in Open.
=> [#161107] Ports some changes to the products controller & view from OSU

config/locales/en.notifier.yml
This changes the statement email subject to use `!Statement!` instead of "Statement", so that it will changed based on what `Statement` is set to in the translation file
=> [#161267] Changes statement email subject to use `!Statement!`

app/models/facility_account.rb, app/views/admin/products/_account_fields.html.haml, app/views/products_common/manage.html.haml, config/locales/en.yml
Adjusts label on views to make it easier to change the name on the account label. This is helpful to OSU, who can have 2 recharge accounts for each product
Refactors value of `facility_account` field
=> [#161107] Updates recharge accounts for products

app/views/shared/_header.html.haml
When ordering on behalf of a user, the header menu doesn't have a vertical divider after the username, making it run into the next column. This adds a vertical divider
=> [#159180] Add a vertical divider after username in header

lib/tasks/order_details.rake
This updates the rake task that adds a missing template to order details.
Now it will only add a file if the form is missing, a file is created instead of using the product's file. And it's now possible to pass multiple ids to the rake task.
=> [#161308] Updates rake task to add missing template to order detail

Dockerfile.github-actions, README.md
As we prepare to move away from CircleCI this will be helpful to have here in nucore-open.
I used [prograils' ruby image](https://github.com/prograils/docker-ruby-node-chrome-pack/blob/2.7.5/Dockerfile) as a base and added in ENV variables to control node version and bundler version.  This allows CI testing to run in an environment that matches production more closely.
=> Tech task - Add Dockerfile for Github Actions testing

app/lib/settings_helper.rb, app/models/concerns/active_storage_file.rb, app/models/concerns/downloadable_files/image.rb, app/models/stored_file.rb, config/settings.yml, doc/HOWTO_feature_flags.md, spec/spec_helper.rb, spec/system/facility_list_tile_spec.rb
This adds the `active_storage_for_images_only` feature flag to allow for the use of `ActiveStorage` just for `DownloadableFiles::Image`.
Since UMass would like to use images but is using Paperclip otherwise, this will allow them to add images via `ActiveStorage` so there's less to migrate over to `ActiveStorage` when the time comes.
=> [#161102] Adds `active_storage_for_images_only` feature flag

app/models/power_relay.rb, vendor/engines/dataprobe/lib/dataprobe/ipio.rb, vendor/engines/dataprobe/spec/lib/dataprobe/ipio_spec.rb
Compliments of @stevens101:
The TCP port field available on the product relay page is incorrectly hard-coded to 9100, which is the factory default port for this relay. This patch should be more useful, so that any valid user-defined integer will be used to report the status and to toggle the outlet for the product.
=> [#161290] Fix: implement dataprobe relay port configuration option

app/assets/stylesheets/nucore.scss, app/helpers/accounts_helper.rb, app/views/facility_accounts/show.html.haml, app/views/order_management/order_details/_form.html.haml
Some payment sources have long descriptions and the account number gets pushed out of view.
Also:
- Add a view hook for the top of the payment source detail page
- Clean up an old view helper method
=> [#155885] Adjust account dropdown width

app/views/layouts/formio.html.haml, doc/HOWTO_external_services.md
Allows upgrading the version of form.io assets by setting `FORMIO_VERSION` on the server, then doing a full eye-patch quit/load to pick up the version change. This allows for some testing to be done without a code change and deployment.
=> Tech task: Add ENV variable for formio version

app/models/concerns/downloadable_files/image.rb, config/application.rb
This sets `ActiveStorage`'s variant processor to vips.
Take care to verify this works correctly in OSU.
=> [#161102] Sets ActiveStorage's variant processor to vips

spec/system/admin/facility_statements_spec.rb
An upgrade to `aws-sdk-s3` caused this test to start failing randomly.
=> Tech task - Fix flaky spec

app/views/facilities/index.html.haml
This adjusts the home page such that the wlecome `.alert-info` paragraph is not rendered if the welcome text is blank.
=> [#160217] Make home page welcome message optional

app/assets/javascripts/form_io_submission.js
If a user clicks more than once before the request is resolved, we end up with duplicated submission IDs stored for the survey URL.
=> [#160761] Prevent double-clicks from breaking things

app/models/schedule_rule.rb
Looks like this is needed for the `schedule_rule:add_price_group_discounts` rake task to work
=> [#161362] Remove `ignored_columns` from `ScheduleRule`

app/controllers/formio/submissions_controller.rb
This removes the `to_date` conversion on the `OderDetails`'s `created_at`.
Converting this from a DateTime to a Date seems to result in form.io turning it back into a DateTime, probably at 12:00 AM UTC of the given date. Then converting it into to CST, resulting in the date being yesterday rather than today.
=> [#160761] formio order date issue

spec/models/order_import_csv_spec.rb, spec/models/order_import_spec.rb
Some order importer specs were missing the use of translations. This adds those in.
=> Fix: Adds translations to order import specs

spec/controllers/facility_accounts_reconciliation_controller_spec.rb, spec/controllers/facility_journals_controller_spec.rb, spec/controllers/facility_reservations_controller_spec.rb, spec/controllers/orders_controller_spec.rb, spec/controllers/reservations_controller_spec.rb, spec/forms/add_to_order_form_spec.rb, spec/forms/admin_reservation_form_spec.rb, spec/models/reservation_spec.rb, spec/services/order_row_importer_spec.rb, spec/services/transaction_search/date_range_searcher_spec.rb, spec/support/spec_date_helper.rb, spec/system/editing_a_reservation_spec.rb
Including `DateHelper` at the wrong spot in specs can cause hard to debug problems. This removes `DateHelper` includes and uses the newly created `SpecDateHelper` class instead.
=> TECH TASK: Remove `DateHelper` includes from specs

.github/dependabot.yml, .github/workflows/test-suite.yaml
Use ** filter to include PRs on namespaced branches like dependabot/gem-upgrade-branch
https://stackoverflow.com/questions/64635032/github-actions-run-on-push-to-all-branches
=> Tech task: Run CI testing for dependabot PRs

vendor/engines/ldap_authentication/lib/ldap_authentication.rb
Update `YAML.safe_load` to use keyword args
=> [#159818] Update LDAP authentication engine for ruby 3.1

Gemfile, Gemfile.lock
https://github.com/prawnpdf/prawn/issues/1195
https://github.com/prawnpdf/prawn/discussions/1210
Discovered while attempting a stage release:
```
SSHKit::Runner::ExecuteError: Exception while executing as nucore@tablexi-shared02.txihosting.com: rake exit status: 1
rake stdout: Nothing written
rake stderr: rake aborted!
LoadError: cannot load such file -- matrix
/home/nucore/nucore.stage.tablexi.com/shared/bundle/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/nucore/nucore.stage.tablexi.com/shared/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:332:in `block in require'
/home/nucore/nucore.stage.tablexi.com/shared/bundle/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/dependencies.rb:299: …
```
=> [#159818] Add matrix gem because prawn hasn't had a new release in 2 years

app/controllers/order_details_controller.rb, app/models/order_detail.rb, config/locales/en.controllers.yml, config/locales/en.yml, db/migrate/20230505222132_add_skip_missing_form_to_order_details.rb, db/schema.rb, spec/system/admin/manage_order_detail_spec.rb
This adds a boolean column to order details to allow admins to mark transactions where the missing order form - template file or form.io - can be safely skipped.
NU Stage has ~1.2m order detail records and should be a good testing place for the migration.
=> [#161733] Allow skipping form.io forms with missing form response

app/models/reports/order_import.rb, spec/models/reports/order_import_spec.rb
The parameters passed into `I18n.t` needed to be updated for Ruby 3.
=> [#161764] Fix order import for ruby upgrade

app/controllers/transactions_controller.rb, app/forms/transaction_search/search_form.rb, app/models/account.rb, app/models/order_detail.rb, app/services/transaction_search/account_type_searcher.rb, app/services/transaction_search/searcher.rb, app/views/facility_accounts/_account_table.html.haml, app/views/user_accounts/show.html.haml, config/locales/en.yml, config/locales/views/en.facility_accounts.yml, spec/services/transaction_search/searcher_spec.rb
This allows users to filter search by account type, and it displays account types in tables to make the type of the account easier to see.
=> [#160881] Search & display account types

app/controllers/instrument_relays_controller.rb, app/models/power_relay.rb, app/views/instrument_relays/_form.html.haml, app/views/instrument_relays/index.html.haml, config/locales/en.yml, config/locales/simple_form.en.yml, db/migrate/20230519154410_add_secondary_outlet_to_relays.rb, db/schema.rb, doc/coding_standards.md, spec/controllers/relays_activations_controller_spec.rb, spec/models/power_relay_spec.rb, spec/system/admin/instrument_relay_tab_spec.rb
Allows specifying a secondary outlet for relays.
If specified for Synaccess A and B relays, the secondary outlet will be switched along with the primary outlet.
Use case is something like 2 monitors for a single instrument.
=> [#161672] Add secondary outlet to relays

app/models/account_config.rb, app/services/transaction_search/account_type_searcher.rb, spec/models/account_config_spec.rb
The transaction type searcher was listing `account_types`, which could include some types that are disabled from being created.
This adds a method which list only the account types that can be created
=> [#160881] Fix account type searcher account list

app/validators/account_validator/account_number_format_error.rb
This corrects an error in `apply_to_model` which happened during the Ruby 3 upgrade, which adds more errors to the model than are necessary.
=> [#161763] Excess Chart String account validation errors

config/settings.yml, doc/coding_standards.md, spec/system/creating_a_journal_spec.rb
Different schools have different account types. This allows the account type used in `spec/system/creating_a_journal_spec.rb` to be specified in `config/settings.yml`
=> TECH TASK: Updates creating a journal spec to get account from Settings

app/mailers/notifier.rb, config/settings.yml, spec/mailers/notifier_spec.rb
This adds an optional BCC to the statement email which can be set in `settings.yml`
=> [#161283] Optional BCC on invoice emails

app/assets/javascripts/facility_journal.js, spec/system/creating_a_journal_spec.rb
This spec has been failing pretty frequently - I'm not sure why it ever passes actually.
Since the spec was not selecting any transactions to journal, the JS is comparing the Journal Date with `undefined`:
```
const checked = document.querySelectorAll("table.js--transactions-table tr td input[type='checkbox']:checked");
```
=> Fix: Add wait to flaky spec

.github/workflows/nucore-auto-deploy-staging.yml, spec/system/creating_a_journal_spec.rb
We are using the `tablexi/infrastructure` repo to add the public key for `txinucorega` to the `.ssh/authorized_users` file for nucore.
=> Tech task: Update CI user

app/models/account.rb, app/models/order_detail.rb, app/presenters/order_detail_notice_presenter.rb, app/views/order_management/order_details/_dispute.html.haml, config/locales/en.yml, spec/presenters/order_detail_notice_presenter_spec.rb, spec/system/resolving_a_disputed_order_spec.rb
This only allows global admins to resolve disputed transactions, if they are associated with an account type that only allows global admins to resolve disputes.
=> [#161811] Only global admins can resolve auto-disputed transactions

app/models/account.rb, app/services/notification_sender.rb
This pulls into Open some non-engine changes from UMass that are needed to enable auto-disputing transactions. This does not enable auto-disputing, but sets up some methods to override in the case auto-disputing is desired.
=> [#161811] Adds auto-dispute setup code from UMass

app/controllers/products_common_controller.rb, app/models/product.rb, app/views/admin/products/_product_fields.html.haml, app/views/products_common/manage.html.haml, config/locales/views/admin/en.products.yml, db/migrate/20230724224847_add_billing_mode_to_product.rb, db/schema.rb, spec/factories/products.rb, spec/system/managing_product_billing_mode_spec.rb
This adds a billing mode attribute to products that global admins can set only on creation. Users who are not global admins cannot set this attribute (it defaults to "Default").
=> [#161857] Add new dropdown for Billing Mode when creating new products

CHANGELOG.md, README.md, app/models/price_group.rb, db/seeds.rb, lib/tasks/demo_seed.rake, lib/tasks/pirce_groups.rake, lib/tasks/schedule_rules.rake, spec/rails_helper.rb
When a global price group is created, it needs to be added to all the schedule rules for it to appear on the UI for each product.
This created a rake tasks which does that.
=> [#161847] Rake tasks for adding new PriceGroups to ScheduleRules

app/views/order_management/order_details/_form.html.haml, spec/system/admin/manage_order_detail_spec.rb
This field is validated by JavaScript, this PR changes the date into the format the JavaScript expects, to remove the validation error message when changing the date.
See https://github.com/tablexi/nucore-open/pull/3588 for original screenshots
=> [#160013] Updates formatting of fulfilled_at in form

app/models/order_detail.rb, lib/tasks/demo_seed.rake, spec/models/order_detail_spec.rb, spec/system/admin/billing_mode_workflow_spec.rb
This implements the "Skip Review" billing mode, which will reconcile an order detail whenever it goes into the "complete" state, rather than going through the billing workflow. This is done for order details of products that are in the "Skip Review" billing mode.
=> [#161858] Skip Review billing mode

app/models/price_group.rb, app/views/price_groups/index.html.haml, config/locales/en.yml
This adds a "Global" column to the facility price group table, to indicate if a price group is global or local.
=> [ #161840] Adds Global column to price group table

app/models/concerns/downloadable_files/image.rb, config/locales/simple_form.en.yml
It was possible to upload an unprocessable image format (e.g. JFIJ) without getting any sort of error in the UI.
This adds `processable_image` to the validation, which will provide an error in the UI, and it lists the valid image formats
=> [#161905] Invalid image format uploads

app/controllers/orders_controller.rb, app/lib/nucore.rb, app/models/nonbillable_account.rb, app/models/order_detail.rb, app/models/product.rb, app/models/user.rb, app/support/orders/item_adder.rb, lib/tasks/demo_seed.rake, spec/system/admin/billing_mode_workflow_spec.rb, spec/system/cart_billing_mode_spec.rb
This creates a Nonbillable account type, which allows users to not use an account when purchases nonbillable products
=> [#161859] Create non-billable account type

app/assets/javascripts/facility_journal.js, spec/system/creating_a_journal_spec.rb
The "Select All" link does not have an event listener on it. So when transactions are selected using that link, the  Journal 90 day popup is not setup correctly.
This adds a listener to the "Select All" link
=> [#161924] Journal 90 day popup bug

app/models/account.rb, spec/system/cart_billing_mode_spec.rb
Dartmouth has `user_based_price_groups` disabled, which changes the behavior of the cart. So specs were added with that flag disabled
=> [#161859] Adds feature flagged specs for cart billing mode

app/models/nonbillable_account.rb, app/models/price_group.rb, app/models/price_policy.rb, app/models/product.rb, app/models/product_for_cart.rb, app/services/price_policy_builder.rb, app/views/price_policies/_table.html.haml, app/views/price_policies/index.html.haml, app/views/time_based_price_policies/_table.html.haml, config/locales/views/admin/en.price_policies.yml, spec/system/admin/billing_mode_workflow_spec.rb, spec/system/admin/creating_an_item_spec.rb, spec/system/admin/instrument_price_policies_controller_spec.rb
This automatically sets up $0 price policies for products that skip order review (Skip Review, and Nonbillable modes).
It may be necessary to call `create_nonbillable_price_policy` on `skip_order_review?` products that already exist
=> [#161917] Allow purchasing without price rules in nonbillable mode

app/controllers/facility_statements_controller.rb, app/forms/statement_search_form.rb, app/mailers/statement_search_result_mailer.rb, app/models/statement.rb, app/presenters/statement_presenter.rb, app/views/global_search/_statements.html.haml, app/views/shared/_statements_table.html.haml, config/locales/en.yml, config/routes.rb, db/migrate/20230907173215_add_cancelation_date_to_statements.rb, db/schema.rb, spec/models/statement_spec.rb, spec/system/admin/cancel_statement_spec.rb
This allows statements that do not have any associated reconciled order details to be canceled.
=> [#161771] Cancel statements

app/views/facility_statements/index.html.haml, app/views/shared/_statements_table.html.haml, app/views/statements/index.html.haml, spec/system/admin/cancel_statement_spec.rb
Account owners and business admins will get an error when trying to access the Statements tab of the My Payment Sources - Details page - for an account that has cancelable statements.
Bug introduced in https://github.com/tablexi/nucore-open/pull/3663
Rollbar:
https://app.rollbar.com/a/tablexi/fix/item/nucore-dartmouth/364/occurrence/365890715445#detail
=> [#161969] Fix My Payment Sources page

app/models/order_detail.rb, spec/services/auto_expire_reservation_spec.rb
Nonbillable and Skip Review transactions should go to the problem queue like everyone else.
Before this change, Nonbillable and Skip Review transactions would get marked "Complete" as part of being moved to the problem queue, and then go automatically to "Reconciled". The system does not expect the order detail to be reconciled, so it raises an error and rolls everything back:
`raise "Trying to move Order ##{@order_detail} to problem queue, but it's not a problem" unless @order_detail.problem?`
The code's definition of "problem" is more complex than it needs to be but it requires the the order detail to be in the "complete" state:
```
before_save :set_problem_order
def set_problem_order
self.problem = problem_description_key.present?
update_fulfilled_at_on_resolve if time_data.present? …
```
=> [#161966] Don't auto-reconcile problem orders

app/models/order_detail.rb, app/models/price_group.rb, app/models/product.rb, app/models/product_for_cart.rb, app/services/price_policy_builder.rb, app/services/reservation_window.rb, app/views/price_policies/_table.html.haml, lib/tasks/price_policies.rake, spec/factories/products.rb, spec/system/cart_billing_mode_spec.rb
- Addresses this Rollbar error: https://app.rollbar.com/a/oregonstate/fix/item/RELMS/38/occurrence/365621698022#detail
- Allows external users to reserve or purchase any Nonbillable product
- Requires a payment source selection for Skip Review products
- Updates the setup_global method
- Big improvement in improved spec coverage
This adds a new `after_create` callback on `Product`. Instead of creating a price policy for just the base price group, it creates one for all global price groups. For existing `skip_review_mode?` products to work correctly, they will need to have these price policies added manually:
`bundle exec rake 'price_policies:update_skip_review[commit]'`
=> Fix external user and nonbillable instrument bug

config/initializers/action_mailer_interceptors.rb
We need to explicitly load the class before using it.
This is only loaded on staging so it didn't fail until we attempted stage releases.
=> [#160235] Add require statement

app/models/reservation.rb, app/support/price_displayment.rb
Reservations for reconciled order details have their `billable_minutes` set to `nil`. OSU and UMass use this attribute in their statements, which means the purchased quantity is blank. Dartmouth and NU use `PriceDisplayment#wrapped_quanity` to display the quantity on the statement. This method relies on `actual_duration_mins` and `duration_mins` instead of `billable_minutes`
This PR makes `PriceDisplayment#wrapped_statement_quanity`, which uses a calculated value of, instead of the saved value for `billable_minutes`.
This method can be used by OSU and UMass to address the blank quantity on statements.
=> [#161863] Instrument quantity on reconciled statements

spec/system/creating_a_journal_spec.rb
These specs often fail in CI, let's see if a longer wait time helps.
=> [Tech Task] Increase wait time on flaky specs

Gemfile, Gemfile.lock
https://github.com/jquery-ui-rails/jquery-ui-rails/issues/146#issuecomment-1655225232
This gem does not appear to be actively maintained...
We should probably use something else
https://github.com/tablexi/nucore-open/security/dependabot/43
https://github.com/tablexi/nucore-open/security/dependabot/44
https://github.com/tablexi/nucore-open/security/dependabot/45
=> Security update for jquery-ui-rails gem

Dockerfile, Dockerfile.github-actions
In the build process on Github, there was a `sudo: not found` error. This PR removes `sudo` from the Dockerfiles
=> [#161941] Removes `sudo` from Dockerfiles

Gemfile, Gemfile.lock
jquery-ui-rails v7 caused an issue with the `datepicker` where some of the HTML is not rendered
jquery-ui-rails v7
jquery-ui-rails v6
=> Downgrade jquery UI rails

app/models/reservation.rb
`billable_duration_mins` needs to be called on `Reservation`, not just within the class
=> [#161863] Tech tasks: make Reservation#billable_duration_mins public 

app/controllers/products_common_controller.rb, app/models/concerns/products/schedule_rule_support.rb, app/models/instrument.rb, app/views/instruments/_instrument_fields.html.haml, app/views/instruments/_instrument_manage_fields.html.haml, config/locales/en.yml, db/migrate/20231011195736_add_pricing_mode_to_products.rb, db/schema.rb
Add pricing mode to instrument. It can either be Schedule Rule or Duration (defaults to the first one). For new/edit, user sees a radio button. Also, it's in the Details tab.
=> [#161991] [Shared dev] Duration based pricing - Select pricing mode

app/controllers/instrument_duration_rates_controller.rb, app/models/duration_rate.rb, app/models/instrument.rb, app/views/admin/shared/_tabnav_product.html.haml, app/views/instrument_duration_rates/edit.html.haml, config/locales/en.models.yml, config/locales/views/admin/en.instrument_duration_rates.yml, config/locales/views/admin/en.products.yml, config/routes.rb, db/migrate/20231012210150_create_duration_rates.rb, db/schema.rb, spec/factories/products.rb, spec/system/admin/instrument_duration_pricing_tab_spec.rb
For Instruments with Duration pricing mode there's a new Duration Pricing tab, where users can set their duration pricing rules. Rules are sorted by minimum duration.
=> [#161992] [Shared dev] Duration based pricing - (2) Set discounts

app/views/schedule_rules/_schedule_rule_fields.html.haml
Fixes price groups being duplicated when editing an instrument's schedule rules.
=> [#161895] Only show highlighted price groups if present

app/controllers/instrument_duration_rates_controller.rb, app/views/admin/shared/_tabnav_product.html.haml, app/views/instrument_duration_rates/edit.html.haml, app/views/schedule_rules/_schedule_rule_fields.html.haml, app/views/schedule_rules/index.html.haml, config/locales/views/admin/en.instrument_duration_rates.yml, spec/system/admin/instrument_duration_pricing_tab_spec.rb, spec/system/admin/instrument_scheduling_tab_spec.rb
Both Schedule Rule discounts and duration-based discounts cannot be set for the same instrument.
=> [#161993] Duration based pricing - (3) Create duration and schedule tabs

app/controllers/instrument_duration_rates_controller.rb
When product is not an instrument, navegation to duration pricing rules ended up in errors. Now it redirects user to facility products overview.
=> If product is not an instrument, redirect to products overview

.github/workflows/nucore-heroku-auto-deploy-staging.yml
Triggering on a push to the master branch means
we cannot check if the test were succesful or not.
This has been broken since we switched over to heroku.
https://github.com/tablexi/nucore-open/actions/workflows/nucore-heroku-auto-deploy-staging.yml
The deploys are being skipped because there is not any `github.event.workflow_run.conclusion` to check:
```
jobs:
deploy-staging-heroku:
if: ${{ github.event.workflow_run.conclusion == 'success' }}
```
=> [Tech task] Fix heroku deployments

app/models/price_group.rb, db/migrate/20231102000551_add_global_boolean_column_to_price_groups.rb, db/schema.rb, spec/factories/price_groups.rb, spec/models/price_group_spec.rb
This cleans up some long-standing technical cobwebs that were standing in the way of linking duration rates to price groups. 
Previously we required all price group records to have a facility ID, while also depending on a missing facility ID as a way of identifying global price groups.  This is clunky, and makes it impossible to update global price groups without skipping validations.  
With this change, price groups that are set up with `global: true` no longer require a facility ID.  This is a clearer, more standard approach, and it means the application no longer depends on invalid database records.  Plus, it paves the way for updating duration rates via price groups using `accepts_nested_attributes`.
=> [#162031] Refactor global price groups

app/controllers/price_policies_controller.rb, app/models/duration_rate.rb, app/models/instrument.rb, app/models/price_group.rb, app/models/price_policy.rb, app/models/rate_start.rb, app/services/price_policy_updater.rb, app/views/instrument_price_policies/_price_policy_fields.html.haml, app/views/time_based_price_policies/_stepped_billing_adjustment_row.html.haml, app/views/time_based_price_policies/_stepped_billing_amount_row.html.haml, app/views/time_based_price_policies/_stepped_billing_price_policy_fields.html.haml, db/migrate/20231031155216_create_rate_starts.rb, db/migrate/20231031160639_change_duration_rates.rb, db/schema.rb, spec/system/admin/instrument_price_policies_controller_spec.rb
Instruments with Duration pricing mode have new fields in the Pricing rules table. There Stepped billing rates can be set.
Adjustment input now has a `-` before it, so we're explicit about it being a discount.
Pending:
- Validate that Stepped billing rate <= base rate
- Validate that Stepped billing adjustment <= base rate
- Improve error messages
=> [#162031] [Shared dev] Duration based pricing - Move form inputs to Pricing tab

app/views/schedule_rules/_schedule_rule_fields.html.haml, spec/system/admin/instrument_scheduling_tab_spec.rb
Always show options for schedule groups, regardless of the pricing mode.
=> [#162084] Show Scheduling groups for duration instruments

app/models/account.rb, app/models/nufs_account.rb, app/services/order_row_importer.rb, config/settings.yml, spec/factories/accounts.rb, spec/models/order_import_csv_spec.rb, spec/services/order_row_importer_spec.rb
Currently when orders are imported, the account validation is checked against the current time, rather than the time the order was actually fulfilled.
This PR changes the validation to check against the time the order was fulfilled, rather than the current time.
These changes are ported in from https://github.com/UMass-CORUM/nucore-umass/pull/574
=> [#161345] Order import account validation

app/controllers/product_user_imports_controller.rb, config/locales/en.controllers.yml, spec/system/admin/import_product_users_spec.rb
When importing an access list, the flash messages can get too large, which can cause a server side error in the Nginx proxy. This PR reduces the size of the flash messages.
More than 30 failures
Less than 30 failures
=> [#162009] Improve access list import messages

app/controllers/schedule_rules_controller.rb, app/views/schedule_rules/_schedule_rule_fields.html.haml
Update the styling and ordering on the edit page to match the form when adding new discounts
=> [#162094] Display price group discounts properly when editing

app/models/nonbillable_account.rb
In https://github.com/tablexi/nucore-open/pull/3795, `Account#validate_against_product` adds a `fulfillment_time` parameter to what is passes into `account_open?`, making it necessary for each account subclass to add that parameter to its method signature.
This PR adds `fulfillment_time`  to `NonbillableAccount#account_open?`
=> [#161345] Fix: Nonbillable account open parameter

app/controllers/price_policies_controller.rb, app/models/duration_rate.rb, app/services/price_policies/time_based_price_calculator.rb, app/views/time_based_price_policies/_stepped_billing_price_policy_fields.html.haml, app/views/time_based_price_policies/_stepped_billing_table.html.haml, db/migrate/20231116194445_update_duration_rate_rate_and_subsidy_to_per_minute_values.rb, db/schema.rb, spec/factories/duration_rates.rb, spec/services/price_policies/time_based_price_calculator_spec.rb
Implements the calculation logic to apply the stepped billing rates set by admin users.
Includes a couple small changes as well:
- Store rate and subsidy as per-minute values for consistency with price policies
- A small visual fix for displaying the Initial Rate start as 0hrs in a read only input
=> [#161995] Stepped billing calculations

app/models/price_group.rb, lib/tasks/schedule_rules.rake
At least some existing schedule rules are missing price group discounts for some global price groups.
This rake task will check all schedule rules and add missing global price group discounts to them.
=> [#162094] FIX: rake task to add missing global price groups to schedule rules

app/services/research_safety_adapters/scishield_api_adapter.rb, app/services/research_safety_adapters/scishield_training_synchronizer.rb, config/settings.yml
The Scishield API may have a rate limit in some cases, which causes it to stop responding.
This PR updates `ResearchSafetyAdapters::ScishieldTrainingSynchronizer#synchronize` to make batched requests to the API. The size of the batches, and the sleep time between them can be set via environment variables `SCISHIELD_BATCH_SIZE` and `SCISHIELD_BATCH_SLEEP_TIME`
=> [#162000] Use batched requests to sync with the Scishield API

bin/merge_describer, bin/release_describer, doc/HOWTO_related_repos.md
Adds ruby script for collecting, merging, sorting and organizing merge describer output from a list of repos.
This is very useful for us at TXI, since we are supporting 4 instances of the application.
Also:
Dartmouth had a few git log entries with `*`s. This removes them so `echo` doesn't try to list every file in the working directory
Example:
```
bin/release_describer ~/Workspace v2023-11-08
Processing changes from nucore-open ...
Processing changes from nucore-nu ...
Processing changes from nucore-osu ...
Processing changes from nucore-umass ...
Processing changes from nucore-dartmouth ...
nucore-open
Shared Dev (0)
Open Highlights (12)
* Adds .png to email attachement (https://github.com/tablexi/nucore-open/pull/3800)
* [#161345](https://pm.tablexi.com/issues/161345) Handle expired …
```
=> Tech task: Release describer script

app/controllers/schedule_rules_controller.rb, lib/tasks/schedule_rules.rake
This adds better logging output for the dryrun script and fixes the ordering of price groups discounts.
=> [#162094] Price group ordering clean up

doc/product_pricing.md
Documentation for Stepped billing. Also includes already existing logic for pricing.
=> [#161996] Stepped billing Documentation

app/assets/javascripts/price_policy.js, app/models/duration_rate.rb, app/models/price_policy.rb, app/views/time_based_price_policies/_stepped_billing_price_policy_fields.html.haml, app/views/time_based_price_policies/_stepped_billing_table.html.haml, spec/system/admin/instrument_price_policies_controller_spec.rb
* Allow users to fill up to 4 steps for Stepped billing.
* Display per minute rate/subsidy for steps.
=> [#162138] Improvements stepped billing

spec/system/admin/billing_mode_workflow_spec.rb
A couple of billing mode workflow specs fail in CI but not locally. Adding `wait_for_ajax` seems to make them more reliable.
=> TECH TASK: fix flaky  billing mode specs

spec/system/admin/billing_mode_workflow_spec.rb
* Fix flaky test
Optional.
Removed the `wait_for_ajax` and added an expectation before navigating to the Transactions page. My idea is that we want to be sure change got saved before visiting the other page.
=> TECH TASK: Fix flaky test

app/assets/javascripts/_common.js, app/assets/stylesheets/app/user_product_access_list.scss, app/controllers/product_users_controller.rb, app/lib/facility_product_routing_concern.rb, app/views/product_users/_export_csv.html.haml, app/views/product_users/_table.html.haml, app/views/product_users/_users_results.html.haml, app/views/product_users/index.html.haml, app/views/product_users/search.html.haml, config/locales/views/admin/en.product_users.yml, spec/system/admin/access_list_tab_spec.rb
* Add search feature to product Access List tab.
* Change page size to 50 for results in Product Access List tab.
=> [#161789] Access List Enhancements

app/controllers/price_groups_controller.rb, spec/system/admin/price_group_management_spec.rb
* Make Price Groups Users tab Search case insensitive
Optional.
=> [#161915] Make Search case insensitive and add spec

bin/release_describer
Adds some interactive handling for stashing any unstaged code changes
Check out the default branch and pull recent changes
Grab the most recent release tag by default
=> Tech Task: Make release script more user friendly

app/services/order_row_importer.rb, public/templates/bulk_import_template.csv, vendor/engines/projects/app/models/concerns/projects/order_row_importer_extension.rb, vendor/engines/projects/config/locales/en.yml, vendor/engines/projects/lib/projects/engine.rb, vendor/engines/projects/spec/models/projects/order_row_importer_extension_spec.rb
This changes the Project ID column to Project Name in the bulk order import
=> [#161990] Change Project ID to Project Name in bulk order import

Dockerfile.github-actions
This updates the ChromeDriver URL in Dockerfile.github-actions
=> TECH TASK: Update the ChromeDriver URL in Dockerfile.github-actions

app/controllers/facility_orders_controller.rb, app/forms/add_to_order_form.rb, app/support/orders/item_adder.rb, app/views/facility_orders/_order_table.html.haml, app/views/facility_orders/_order_table_headers.html.haml, app/views/facility_orders/show.html.haml, config/locales/views/en.facility_orders.yml, spec/system/admin/adding_to_an_order_spec.rb, vendor/engines/projects/app/models/projects/order_detail_extension.rb, vendor/engines/projects/config/locales/en.yml, vendor/engines/projects/spec/controllers/order_management/order_details_controller_spec.rb, vendor/engines/projects/spec/models/projects/order_detail_extension_spec.rb
⚠️ **This PR relies on Projects module being enabled. We should check this won't fail in Production and cause errors for any school that doesn't have it enabled.**
* Create a new order when a product from a new facility is added to an existing order. If the order already exists, add to it.
- Fix failing spec - it's reasonable that it's failing but it's worth it to improve the spec instead of just making it pass
=> [#162194] Create a new order when adding cross-core products to an existing order

spec/system/quick_reservations_spec.rb
This adds the `user_based_price_groups` feature flag to `spec/system/quick_reservations_spec.rb`. Dartmouth doesn't have this flag enabled, but it's required for one of the specs to work correctly
=> [#160449] Add feature flag for quick reservation spec

app/assets/javascripts/app/merge_orders.js, app/controllers/products_controller.rb, app/forms/add_to_order_form.rb, app/views/facility_orders/_merge_order_form.html.haml, spec/system/admin/adding_to_an_order_spec.rb
* Only the products that are available for cross core ordering are in the list.
Optional.
=> [SHARED DEV] [#162194] Return products depending on original order facility

app/models/duration_rate.rb, spec/system/admin/instrument_price_policies_controller_spec.rb
* Update validation for Duration based pricing rules so subsidy can be zero.
Optional.
=> [Shared dev] [#162151] Allow subsidy to be zero in price rules

app/controllers/user_research_safety_certifications_controller.rb, app/services/research_safety_adapters/scishield_api_client.rb, app/services/reservation_creator.rb, app/views/user_research_safety_certifications/index.html.haml, config/locales/en.services.yml, spec/rails_helper.rb, spec/services/scishield_api_adapter_spec.rb, spec/system/research_safety/scishield/scishield_timeout_spec.rb
This adds handling for timeout errors for requests to the Scishield API. An error message is displayed to users, instead of the previous behavior, which was throwing a 500 error.
=> [#162205] Scishield updates

app/controllers/quick_reservations_controller.rb, app/models/concerns/products/scheduling_support.rb, app/views/quick_reservations/new.html.haml, spec/models/instrument_spec.rb, spec/system/quick_reservations_spec.rb
This fixes a some  bugs in the QR walk up controller.
Handles that case
* when the minimum reserve time is larger than any of the reserve intervals
* when a non-actionable reservation is redirected to
* when the instrument has no schedule rules
=> [#162190] QR walk up fixes

app/services/research_safety_adapters/scishield_api_client.rb, app/services/research_safety_adapters/scishield_training_synchronizer.rb, config/settings.yml, spec/services/research_safety_adapters/scishield_training_synchronizer_spec.rb
This adds a sleep of `batch_sleep_time` to each API request in `api_unavailable?`.
The sync for OSU is failing due to `api_unavailable?` returning `false` when API requests are generally possible. Adding the sleep time in `api_unavailable?` makes it more reliable.
=> [#162204] Add sleep time to SciShield availability check

.github/workflows/test-suite.yaml, app/models/order.rb, spec/support/helper_methods.rb, spec/support/select_from_chosen.rb, spec/system/admin/adding_to_an_order_spec.rb
A couple small changes to address unpredictable failures in `rspec ./spec/system/admin/adding_to_an_order_spec.rb:206`
This seems to still be failing in OSU and other repos, so we will skip for now and continue with our release.
We can keep debugging next sprint.
=> [Tech task] Spec clean up

spec/support/select_from_chosen.rb, spec/system/admin/adding_to_an_order_spec.rb
* Fix failing spec for adding to order
Optional.
=> Fix failing spec for adding to order

app/services/research_safety_adapters/scishield_api_client.rb, spec/services/scishield_api_client_spec.rb
The `scischield` settings are nested under the `research_safety_adapter` key in the `settings.yml` file
=> [#162204] Fix typo and add spec

app/controllers/quick_reservations_controller.rb, app/models/concerns/products/scheduling_support.rb, app/presenters/reservation_user_action_presenter.rb, app/support/reservations/moving_up.rb, app/views/quick_reservations/show.html.haml, spec/models/reservation_spec.rb, spec/presenters/reservation_user_action_presenter_spec.rb
This renames the `startable_now?` method to `movable_to_now?`, which is a name that more clearly communicates the question the method is answering.
It also adds a comment to the `quick_reservation_data` explaining why the time is set to 1 minute in the future
=> Tech task: reservation scheduling

db/migrate/20240410203410_update_cross_core_ordering_available_in_products.rb, db/schema.rb
* Default Cross-Core ordering visibility to off.
=> [#162250] Update default value for `cross_core_ordering_available` column

app/forms/add_to_order_form.rb, app/views/facility_orders/show.html.haml, spec/system/admin/adding_to_an_order_spec.rb
* Fix bug for duplicate order details.
Add a spec to add to facility order using Feature Flag.
New spec failed with old code as it found two "Make a reservation" buttons.
=> [#162225] Multi-Facility - Duplicates being created

app/assets/javascripts/app/facility_order_show.js, app/assets/javascripts/application.js, app/assets/stylesheets/app/accordion.scss, app/assets/stylesheets/application.scss, app/views/facility_orders/show.html.haml, config/locales/views/en.facility_orders.yml
- Put each cross-core order into a toggle/accordion element, which will be closed when the user first visits the page
- Add a Header that says “Cross Core Orders” to separate them from the “original” order
=> [#162262] Put each cross-core order into a toggle/accordion element

app/assets/javascripts/app/merge_orders.js, app/controllers/facility_accounts_controller.rb, app/forms/add_to_order_form.rb, app/lib/ability.rb, app/models/concerns/users/roles.rb, app/views/facility_orders/_merge_order_form.html.haml, config/routes.rb, spec/system/admin/adding_to_an_order_spec.rb
* When an admin places a cross-core order, update valid payment source list.
=> [#162263] Multi-Facility - 5c When an admin places a cross-core order, update valid payment source list

app/assets/stylesheets/app/order_management.scss, app/views/facility_orders/_merge_order.html.haml, app/views/facility_orders/_merge_order_missing_form_reminder.html.haml, config/locales/en.yml, spec/system/admin/adding_to_an_order_spec.rb
- Make the warning message red
- Make the warning message clearer
- Add the warning message to a modal that appears when page is loaded
=> [#162176] Make it harder to ignore missing forms

config/environments/production.rb, config/initializers/session_store.rb
Set same_site to :none so that we pass along the originating url when making the SAML request
The return_to path was already being included in the cookie, but this was not being sent to the IdP because the default is SameSite=Lax
For more info:
https://support.okta.com/help/s/article/FAQ-How-Chrome-80-Update-for-SameSite-by-default-Potentially-Impacts-Your-Okta-Environment?language=en_US "...the new default will be SameSite=Lax, and cookies that need to work cross-site must be explicitly labeled with a new SameSite=None attribute value. Additionally this will require HTTPS (not plaintext HTTP) because browsers will ignore the SameSite=None attribute unless it is accompanied by the Secure attribute."
=> [#162253] Fix redirect path after SSO login

app/controllers/reservations_controller.rb, spec/system/admin/adding_to_an_order_spec.rb
* Payment Sources list in Reservation form for Cross-Core orders to only include the ones available for the instrument's facility.
Optional.
=> [#162263] Fix Payment Sources list in Reservation form

app/controllers/instrument_relays_controller.rb, app/models/power_relay.rb, config/locales/en.yml, spec/system/admin/instrument_relay_tab_spec.rb
- Improve hint message
- Remove noisy rollbar logging
- I went ahead and added logic to automatically sync up the outlets as well since it seemed pretty straightforward
=> [#162193] Add clearer secondary outlet message

app/services/research_safety_adapters/scishield_training_synchronizer.rb, spec/system/research_safety/scishield/scishield_timeout_spec.rb
We're seeing frequent and inconsistent Net::OpenTimeout errors that are causing `api_unavailable?` to fail, preventing the sync task from running.
By making `api_unavailable?` more resilient, we have a better chance of keeping the backup layer more up to date.
We are in communication with SciShield customer service as well to see if they can help identify the root cause.
=> [#162275 Make the SciShield backup layer more resilient

app/assets/stylesheets/app/order_management.scss, app/assets/stylesheets/nucore.scss
Makes font size consistent with other text on the page
Makes background colors darker to maintain color contrast ratio
Before:
Now:
Also made the word "red" more red to bring the contrast ratio into compliance =:
=> [#162289] Update label styling

app/controllers/instrument_relays_controller.rb, spec/system/admin/instrument_relay_tab_spec.rb
Addresses:
```
A TypeError occurred in instrument_relays#update:
no implicit conversion of nil into Integer
app/models/power_relay.rb:48:in `activate_secondary_outlet'
```
=> [#162293] Only update secondary outlet when we have a secondary outlet to set

app/models/order_detail.rb, app/presenters/order_detail_presenter.rb, app/views/facility_orders/index.html.haml, vendor/engines/projects/app/services/projects/cross_core_facility_searcher.rb, vendor/engines/projects/app/views/projects/projects/cross_core_orders.html.haml, vendor/engines/projects/config/locales/en.yml, vendor/engines/projects/spec/system/cross_core_orders_spec.rb
* Show price group (estimated or final) in orders table.
=> [Shared dev] [#162175] Show price group in orders table

app/models/order_detail.rb, app/models/statement.rb, app/support/example_statement_pdf.rb, config/locales/services/en.statement_pdf.yml, spec/models/statement_spec.rb, spec/support/contexts/cross_core_context.rb, vendor/engines/projects/app/controllers/projects/projects_controller.rb, vendor/engines/projects/app/models/projects/project.rb, vendor/engines/projects/spec/system/cross_core_orders_spec.rb
Adds a message to cross-core statements which include cross-core transactions from other facilities.
If the user placed the order, then this message would just cause confusion:
Items on this statement may have been placed on your behalf by another core facility.
This will need to be applied to each school's statement format individually
=> [#162207] Add a message to all cross-core statements

app/models/order_detail.rb, app/models/reports/export_raw.rb, spec/models/reports/export_raw_spec.rb
New columns should help admin users assess how cross core orders are used
=> [#162303] Add cross core columns to export raw

app/controllers/reservations_controller.rb, app/presenters/reservation_user_action_presenter.rb, app/views/reservations/earliest_move_possible.html.haml, spec/system/admin/reservation_actions_spec.rb
* Redirect to correct order after "Move Up"
=> [Shared dev] [#162254] Redirect to correct order after "Move Up"

.github/workflows/nucore-heroku-auto-deploy-staging.yml
Reverts tablexi/nucore-open#4182
Since this got in master, deploys to Heroku are failing. Also, I couldn't find this version in the repo (tag or release) or marketplace.
=> Revert "Bump akhileshns/heroku-deploy from 3.13.15 to 4"

app/views/facility_orders/_order_table.html.haml, spec/system/admin/adding_to_an_order_spec.rb
* Fix bug where order results files were not visible
Bug was introduced as part of https://github.com/tablexi/nucore-open/pull/4344
=> [#162314] Fix bug where order results files were not visible

app/controllers/facility_orders_controller.rb, app/views/facility_orders/show.html.haml, spec/system/admin/adding_to_a_cross_core_order_spec.rb, spec/system/admin/projects_edit_spec.rb, spec/system/admin/projects_show_spec.rb, vendor/engines/projects/app/controllers/projects/projects_controller.rb, vendor/engines/projects/app/models/projects/ability_extension.rb, vendor/engines/projects/app/models/projects/project.rb, vendor/engines/projects/app/views/projects/projects/edit.html.haml, vendor/engines/projects/app/views/projects/projects/show.html.haml
* Add ability to edit cross core projects
=> [Shared dev] [#162202] Edit project

app/services/projects_search/cross_core_searcher.rb, app/views/shared/transactions/_table_inside.html.haml, spec/system/admin/projects_show_spec.rb
* Prevent dup projects in index and hide account columns
=> [#162202] Fix Projects tab 

app/views/facility_orders/_order_table_actions.html.haml
In an earlier ticket (#162254) we made a change to the redirect for the Reservation Actions, and mistakenly removed those action links for non-cross-core reservations.
=> Fix: Display reservation actions for all orders (not just cross core)

spec/system/admin/reservation_actions_spec.rb
* Tech task: fix flaky test
Spec failed multiple times and always the "Move" button seemed to not get clicked. Now we wait until AJAX request (the one that loads the modal) finishes before clicking the button
=> [Tech task] Fix flaky reservation actions spec

app/models/order_detail.rb, app/models/reports/account_transactions_report.rb, app/views/shared/transactions/_cross_core_icon.html.haml, app/views/shared/transactions/_table_inside.html.haml, config/locales/en.yml, spec/models/reports/account_transaction_report_spec.rb, spec/support/contexts/cross_core_context.rb, spec/system/admin/all_transactions_search_spec.rb
* Show an icon for Cross Core transactions under the order id.
* Should it be part of the "badges" in the last column?
=> [#162199] Cross Core transactions

app/models/order.rb, spec/models/order_spec.rb
* Clear cross core project when clearing cart
=> Fix: [#162350] Clear cross core project when clearing cart

app/models/external_services/survey_response.rb, doc/HOWTO_external_services.md
The IMSERC app (used by NU) is no longer in use
=> [#162271] Remove references to the IMSERC app (no longer in use)

app/views/facility_accounts_reconciliation/_action_row.html.haml, app/views/facility_accounts_reconciliation/_table.html.haml
=> [#161679] Fix Deposit number labels

app/models/reports/account_transactions_report.rb, app/presenters/order_detail_presenter.rb, spec/models/reports/account_transaction_report_spec.rb
* Fix ampersand (&) in product names for Transactions report
=> [#162336] Fix ampersand (&) in product names for Transactions report

app/views/quick_reservations/new.html.haml, config/locales/views/en.quick_reservations.yml, spec/system/quick_reservations_spec.rb
* Add note field to quick reservation
=> [#162296] Add note field to quick reservation

app/models/reservation.rb
* Decrease Facility reservations page load time
We could just check the `order_detail_id` and that should be faster than checking the `order` (which goes through the `order_detail`).
=> [#162383] Use order_detail instead of order

app/support/orders/item_adder.rb, spec/models/order_spec.rb
* Allow adding multiple services to order without requiring multiple forms
=> [#162375] Allow adding multiple services to order

app/assets/javascripts/app/order_table_refresh.js, app/controllers/facility_orders_controller.rb, app/controllers/order_management/order_details_controller.rb, app/helpers/bootstrap_helper.rb, app/lib/ability.rb, app/views/facility_orders/_order_table.html.haml, app/views/facility_orders/show.html.haml, app/views/order_management/order_details/files.html.haml, spec/rails_helper.rb, spec/system/admin/adding_to_a_cross_core_order_spec.rb
* Fix file upload for cross core orders
Tried to add specs [here](https://github.com/tablexi/nucore-open/blob/master/spec/system/admin/adding_to_a_cross_core_order_spec.rb#L20) but I run into the same problem as with [this one](https://github.com/tablexi/nucore-open/blob/master/spec/system/admin/adding_to_a_cross_core_order_spec.rb#L57) we ended up skipping.
=> [SHARED DEV] [#162345] Allow facility staff to upload file to order for cross core

app/controllers/orders_controller.rb, config/locales/en.controllers.yml
Refactor add_account_to_order to return redirect path or error message
The nested `return` was intended to stop processing after the redirect,
but instead was returning control to the caller, causing:
orders#choose_account (AbstractController::DoubleRenderError)
"Render and/or redirect were called multiple times..."
Introduced in https://github.com/tablexi/nucore-open/pull/3637
To recreate:
1. Add something to the cart
2. Click “Change Payment Source”
3. Open a new tab
4. Remove item from the cart
5. In the original tab, select a payment source and click “Continue”
Also, when you click “Change Payment Source”, you can click “Continue” without selecting a payment source.  Then you get a 404.
=> [#162406] Fix: bug when choosing an account

Gemfile.lock, app/assets/javascripts/app/hide_reconcile_fields.js, app/controllers/facility_accounts_reconciliation_controller.rb, app/controllers/facility_journals_controller.rb, app/forms/statement_search_form.rb, app/models/order_detail.rb, app/models/order_status.rb, app/models/statement.rb, app/services/order_details/reconciler.rb, app/views/facility_accounts_reconciliation/_action_row.html.haml, app/views/facility_accounts_reconciliation/_table.html.haml, app/views/facility_accounts_reconciliation/index.html.haml, config/locales/en.yml, db/seeds.rb, lib/tasks/demo_seed.rake, lib/tasks/order_status.rake, spec/rails_helper.rb, spec/services/order_details/reconciler_spec.rb, spec/system/admin/facility_statements_spec.rb, vendor/engines/c2po/spec/system/account_reconciliation_spec.rb
NOTE: run the rake task on heroku after deploying
* Admins can now mark as "Unrecoverable" statements that are unreconciled.
=> [#162311] New reconciliation status for "abandoned" orders

app/views/facility_orders/show.html.haml, config/locales/views/en.facility_orders.yml
In the order's show view accessed through the "Manage Facility" menu, there's a section with a "Cross-core header". This header doesn't describe the menu's function correctly. The menu allows adding cross-core products to an order but it also allows to add products from the same facility as well and many users use it this way.
Before:
After:
I suggest a less specific header: "Add Product to Selected Order"
Didn't opt for a dynamic header as the header is defined in the HTML view structure. I don't think moving the logic to the javascript code to change it dynamically when selecting a facility in the menu dropdown is worth the effort as it's just a header and the action button already provides this information dynamically to the user. Let me know what you guys think about this.
=> [#162402]Change cross-core orders header

Gemfile.lock, vendor/engines/saml_authentication/spec/controllers/saml_authentication/sessions_controller_spec.rb
- Bump rexml from 3.3.2 to 3.3.8
- Fix failing tests after upgrade on saml_authentication engine
SAML authentication tests were failing after the upgrade because the behaviour of `REXML::Document.new(value)` changed (from 3.3.2 to 3.3.3) when value is an invalid xml from returning an invalid document representation to raising an error.
SAML is a specification for exchanging authentication information between parties which uses xml with base64 for data exchange between servers.
The xml used in the failing tests was invalid because the ruby_saml library [url-encodes](https://github.com/SAML-Toolkits/ruby-saml/blob/148a4c2de713a98c58c28bbc7785c05698216a4d/lib/onelogin/ruby-saml/saml_message.rb#L112) the base64 encoded xml automtically but then does not url-decodes it when decoding the base64 …
=> [#162423] Tech Task: bump rexml and fix saml authentication tests

spec/system/admin/all_transactions_search_spec.rb, spec/system/admin/facility_orders_search_spec.rb, spec/system/admin/projects_show_spec.rb
Clean up capybara spec warnings by converting ids to strings when using them as selectors in matchers.
=> [#162433] Tech task: fix capybara warnings on selector types

spec/controllers/order_detail_stored_files_controller_spec.rb
- Add conditional expectation option on validation errors for StoredFile when active_storage is used
- I manually tested it with active_storage option on and off
=> Fix orde detail file blank validation spec

vendor/engines/bulk_email/spec/services/bulk_email/content_generator_spec.rb
* Recently we introduced a change that had single quotes instead of double ones. Updating it before I forget about it
=> Change single quotes to double

.github/dependabot.yml
This should cause all rails gems to be updated together in the same pr.
Allow only patch updates since larger updates should be done with manually.
=> [#162448] Tech task: Group rails gems on dependabot prs

app/assets/stylesheets/nucore.scss, app/helpers/price_policies_helper.rb, app/models/concerns/price_policies/usage.rb, app/models/instrument.rb, app/models/price_policy.rb, app/services/price_policy_updater.rb, app/views/instrument_price_policies/_price_policy_fields.html.haml, app/views/instrument_price_policies/_table.html.haml, app/views/time_based_price_policies/_adjustment_row.html.haml, app/views/time_based_price_policies/_amount_row.html.haml, app/views/time_based_price_policies/_price_policy_fields.html.haml, app/views/time_based_price_policies/_table.html.haml, config/locales/en.models.yml, config/locales/views/admin/en.price_policies.yml, db/migrate/20241022135335_add_price_policy_usage_rate_daily.rb, db/schema.rb, spec/factories/price_policies.rb, spec/models/instrument_price_policy_spec.rb, spec/system/admin/instrument_price_policies_controller_spec.rb, spec/system/admin/timed_service_price_policies_controller_spec.rb
Handle price policy for instruments with daily schedules.
- Added two columns to `price_policies` table to track the usage rate per day and the usage subsidy per day.
- Hide minimum cost and cancellation cost inputs for instruments in this schedule, this applies for view and edit price policies tables. See screenshot.
- Improve format here and there
- Align minus sign for subsidy input
- Added constants for Instrument pricing modes
Daily rate price policies view
Daily rate price policies edit
=> [#162409] [Shared dev] Daily rate price policies updates

app/controllers/price_groups_controller.rb, app/models/price_group.rb, app/models/price_policy.rb, app/services/price_policy_builder.rb, app/services/price_policy_updater.rb, app/views/price_groups/_price_group_fields.html.haml, app/views/price_groups/index.html.haml, app/views/price_policies/index.html.haml, config/locales/en.models.yml, config/locales/en.yml, db/migrate/20241014161738_add_is_hidden_to_price_groups.rb, db/schema.rb, spec/factories/price_groups.rb, spec/support/shared_examples/hidden_price_groups_shared_examples.rb, spec/system/admin/instrument_price_policies_controller_spec.rb, spec/system/admin/item_price_policies_controller_spec.rb
Added the ability to hide price groups in the admin menu. This option is only available for non-global price groups.
Once a price group is hidden, current price policies related to that group aren't visible or editable anymore. Old price policies remain visible. It also updates their can_parchase value to false
This is a draft PR, tests are on their way
=> [#161850]Add ability to hide Price Groups

spec/support/shared_examples/hidden_price_groups_shared_examples.rb
There is a flaky test failing related to hidden price groups; Some assertions are happening before loading the desired page it's not finding specific content on the page. I added some tests to make sure it loads the page correctly.
=> Fix: Price policies flaky spec

spec/system/admin/instrument_price_policies_controller_spec.rb
This is causing newest price policies tests to fail if the environment have that flag off.
=> [Fix] Enable director edit price policy flag on new price policies tests

db/migrate/20241014161738_add_is_hidden_to_price_groups.rb
Oracle prefers 0 and ` for booleans: https://stackoverflow.com/questions/19435160/how-to-update-a-boolean-field-in-oracle-table
=> Fix migration for Oracle

app/helpers/date_helper.rb, app/models/instrument.rb, app/models/reservation.rb, app/services/next_available_reservation_finder.rb, spec/factories/products.rb, spec/models/instrument_spec.rb, spec/services/next_available_reservation_finder_spec.rb
Make product's next available reservation logic to work for daily rate instruments.
> To be discussed
> What should be the reserve interval for daily rate instruments?
This does not include schedule rules changes required by daily rate instruments.
When loading the reservation page, the initial date should be an empty slot where the instrument can be reserved using the default duration.
=> [#162473][Daily Rate]: Find next available reservation time

app/services/price_policy_builder.rb, spec/services/price_policy_builder_spec.rb, spec/support/shared_examples/create_product_with_price_rule_shared_examples.rb, spec/support/shared_examples/create_service_with_price_rule_shared_examples.rb, spec/system/admin/creating_a_service_spec.rb, spec/system/admin/creating_an_item_spec.rb
There's a service that automatically creates price_policies with a usage_rate value of 0. This is not totally real as some price_policies aren't meant to have usage_rate at all which may result in future bugs.
Change the code to reflect reality, add tests, and refactor a little to reuse some code.
=> [#162393] Avoid creation of service and item price policies with usage_rate

app/assets/javascripts/app/checkbox_form.js, vendor/engines/c2po/spec/system/account_reconciliation_spec.rb
On the Credit Card Orders Reconciliation page the "Update order" button should only be available if an order is selected. 
The button wasn't behaving as expected because it was turning into active once the "Use bulk note" checkbox was checked despite no orders being selected.
Before:
After:
The check box form logic was looking for any checkbox in the submit button's parent component to be checked to activate the button. I exclude the bulk note checkbox from this check
=> [161578] Fix bulk note checkbox dynamic behavior

app/services/price_policies/time_based_price_calculator.rb
A small operator change in the time_based_price_calculator resulted in failing tests on some repos as it was skipping the calculation when the start date and the end date where the same.
=> Fix scanning-in-and-out-spec failing test

app/controllers/instruments_controller.rb, app/controllers/products_common_controller.rb, app/helpers/products_helper.rb, app/lib/ability.rb, app/views/instruments/_instrument_fields.html.haml, config/locales/en.controllers.yml, spec/controllers/instruments_controller_spec.rb, spec/system/admin/creating_an_instrument_spec.rb
Only allow global admins to create daily rate instruments and only show the option to them.
=> [#162480][Daily rate] Only allow global admins to create instruments

spec/system/purchasing_a_reservation_spec.rb
Fix test that changed due to merging this PR: https://github.com/wyeworks/nucore-open/pull/4782 not up to date with master.
The fixed test currently asserts the correct message. It use to fail due to other reason with a generic message which was fixed (by chance) in the aformentioned PR.
=> Fix daily reservation on unavailable day test

app/controllers/order_management/order_details_controller.rb, app/models/order_detail.rb, app/models/order_status.rb, spec/models/order_status_spec.rb, spec/system/admin/manage_order_detail_spec.rb
Ticket: [#162417 | Status in Order Detail page does not show Unrecoverable
](https://pm.tablexi.com/issues/162417?issue_count=45&issue_position=23&next_issue_id=162414&prev_issue_id=162472)
After changing the status of an order to Unrecoverable, then going back to the Order Detail page, the Order Status is displayed as "New".
Added the Unrecoverable status to the order details view dropdown and added permissions to set the status of completed orders to unrecoverable.
=> [#162417] Fix order details unrecoverable status flow

.github/workflows/test-suite.yaml, Dockerfile.github-actions, README.md
* Transition: use WyeWorks' Dockerhub instead of TXI's.
Removed usage of `DOCKER_HUB_ACCESS_TOKEN` as the images are public.
=> Tech task: [#162459] Use wyeworkshub image instead of nucoretxi

vendor/engines/c2po/spec/system/account_reconciliation_spec.rb
Reconcile credit card tests fail on the c2po engine if credit card is not reconcilable because the route is not generated.
The simplest solution is to skip those on setups where they are not used.
=> [#161265] Skip credit card reconcile test if not reconcilable

app/views/reservations/new.html.haml
Fix checkbox label clicking not toggling checkbox change because there was a hidden input under the same label, with the same name which I found to be useless
=> [Fix] Label click not toggling checkbox

app/support/reservations/validations.rb, config/locales/en.models.yml, spec/controllers/order_management/order_details_controller_spec.rb, spec/services/problem_reservation_resolver_spec.rb, spec/system/admin/manage_order_detail_spec.rb, spec/system/editing_a_reservation_spec.rb, spec/system/fixing_a_problem_reservation_spec.rb, vendor/engines/secure_rooms/config/locales/en.yml, vendor/engines/secure_rooms/spec/models/secure_rooms/occupancy_spec.rb
- Refactor reservation non positive duration error message to be used for daily and normal booking
- Make secure rooms error not to depend in main app locale
=> [#162525] Improve duration error message

app/assets/javascripts/app/calendar.js, app/presenters/calendar_events_presenter.rb, app/views/instruments/schedule.html.haml, app/views/reservations/_js_variables.html.haml
Add event calendar render logic to make it more clear when daily booking reservations start and end during a day.
These changes are only applied if daily booking is set for the instrument.
- Add calendar render event logic to keep event block offsets depending on proportion of the day occupied.
- Used the `eventAfterRender` hook instead of `eventRender` because the former includes segment information which is useful when an event spans over multiple calendar lines.
- Render events whose duration is less than a day as small blocks (like the admin hold in the screenshot)
- Show dates on event tooltips
=> [NUOPEN-5][Daily rate] Render calendar monthly events with offsets

app/controllers/instruments_controller.rb, config/locales/en.controllers.yml, spec/system/admin/editing_an_instrument_spec.rb
Add info message when an instrument's `start_time_disabled` is changed because schedule rules are affected.
=> [NUOPEN-6][Daily rate] Show message when changing start_time_disable

app/assets/stylesheets/calendar/fullcalendar.extensions.scss
The color of the admin hold blocks in the calendar was quite light. Made it a little bit darker.
Before:
After:
=> [NU-2] Change admin hold calendar color

spec/system/admin/projects_show_spec.rb
spec/system/admin/projects_show_spec.rb has some randomly failing tests as Capybara finds more than one link with an order detail ID. This pr specifies where to look for the link so that duplications aren't a problem.
=> Fix project show flaky spec

app/controllers/file_uploads_controller.rb, app/controllers/services_controller.rb, app/models/external_services/external_service.rb, app/views/services/_service_fields.html.haml, app/views/services/_service_manage_fields.html.haml, config/locales/en.controllers.yml, config/locales/en.models.yml, config/locales/en.yml, db/migrate/20250110132703_add_product_sanger_sequencing_enabled.rb, db/schema.rb, spec/controllers/services_controller_spec.rb, spec/system/admin/creating_a_service_spec.rb, spec/system/admin/editing_a_service_spec.rb
- Add `sanger_sequencing_enabled` to product
- Allow admins to switch that flag on for Services
- When the flag is switched on an ExternalService pointing to Sanger is created if it does not exists
=> [OSU-114] Setup sanger enabled service

vendor/engines/sanger_sequencing/app/models/sanger_sequencing/sanger_product.rb, vendor/engines/sanger_sequencing/app/models/sanger_sequencing/submission.rb, vendor/engines/sanger_sequencing/spec/models/sanger_sequencing/submission_spec.rb
The `SangerProduct` model does not exist for every sanger service, so for those the group will be nil which we should treat it as `default`.
This impacts which submissions are shown on the batch creation page.
=> [OSU-114] Handle nil and default as the same sanger group

vendor/engines/sanger_sequencing/lib/sanger_sequencing/engine.rb
Change which class include the module because it causes an error if there's other engine doing the same for Product. It's likely some loading issue related to STI. This solves OSU upstream merge failing specs.
=> [Fix] Include SangerProduct into Product

app/controllers/application_controller.rb, spec/requests/error_pages_spec.rb
Acting as error handling is raising template not found error.
=> [Fix] Acting as error handling

Gemfile, Gemfile.lock
After concurrent-ruby update to 1.3.5 the "logger" module is not required and rails is raising an error. https://github.com/rails/rails/pull/54264.
Since dependabot is updating `concurrent-ruby` along other libraries we should pin it until we upgrade rails to the version that fixes this issue (which is not 7.0.X).
=> [Chore] Pin concurrent-ruby < 1.3.5

config/initializers/rollbar.rb
These are handled by rollbar after we refactored error handling (they used to be catched before rollbar by application controller's rescue from)
=> [Chore] Ignore rollbar errors handled by rails

vendor/engines/sanger_sequencing/app/models/sanger_sequencing/batch.rb, vendor/engines/sanger_sequencing/app/models/sanger_sequencing/submission.rb, vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/shared/_sidenav.html.haml, vendor/engines/sanger_sequencing/spec/models/sanger_sequencing/batch_spec.rb, vendor/engines/sanger_sequencing/spec/models/sanger_sequencing/submission_spec.rb
- Use the same semantics as submissions group filtering, that is, nil or empty treated the same as default group
- In the Sanger navtab partial, render batch link for each group instead of hardcoding default and fragment groups links
=> [OSU-123] Fix batch group filtering

spec/support/select_from_chosen.rb, vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/vue_well_plate_editor_app.js, vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/well_plate_builder.js, vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/admin/batches_controller.rb, vendor/engines/sanger_sequencing/app/models/sanger_sequencing/batch_form.rb, vendor/engines/sanger_sequencing/app/models/sanger_sequencing/well_plate_configuration.rb, vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/batches/new.html.haml, vendor/engines/sanger_sequencing/config/locales/en.yml, vendor/engines/sanger_sequencing/spec/javascripts/sanger_sequencing/well_plate_builder_spec.js, vendor/engines/sanger_sequencing/spec/system/batches/creating_a_batch_spec.rb
- Allow to select reserved cells when creating a batch of Sanger submissions
- Decaffeinate and fix well plate builder javascript tests
-
=> [OSU-123] Sanger submission batch specify reserved cells

vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/submission.js
The acgt engine overrides the submission form and does not define the `corePrimers` variable
=> [Fix] Fix conflict with sanger sequencing and acgt

vendor/engines/sanger_sequencing/app/assets/stylesheets/sanger_sequencing/submissions.scss, vendor/engines/sanger_sequencing/app/views/sanger_sequencing/submissions/_form.html.haml
=> [OSU-116] Move primers help text to the top

app/presenters/quantity_presenter.rb, app/support/price_displayment.rb, app/support/reservations/date_support.rb, app/views/facility_orders/_order_table.html.haml, spec/system/admin/order_show_spec.rb
* Show duration in days for Daily Rate Instruments
=> [NUOPEN-215][Shared dev] Show duration in days for Daily Rate Instruments

app/models/time_range.rb, app/support/reservations/date_support.rb, app/views/order_management/order_details/_reservation.html.haml, spec/system/admin/order_show_spec.rb
* Show Actual duration days as days in Manage order modal
=> [NUOPEN- 221][Shared dev] Show Actual duration days as days in Manage order modal

spec/system/admin/instrument_relay_tab_spec.rb
Fix spec depending on relay of type Synaccess Rev A which can be disabled by a FF.
=> [Fix] Spec depending on synaccess rev a relay selection

app/helpers/application_helper.rb, app/models/concerns/products/scheduling_support.rb, app/models/instrument.rb, app/models/product.rb, app/models/product_display_group.rb, app/views/facilities/_product_display_group.html.haml
- Prevent N+1 by eager loading instruments' alerts and offline reservations on facility show. I had to move some associations from instrument to product
- Some code improvement on product display groups
=> [OSU-124] Improve facility show loading speed

app/controllers/order_imports_controller.rb, app/models/order_import.rb, app/views/admin/shared/_tabnav_order.html.haml, config/locales/views/admin/en.log_events.yml, spec/controllers/order_imports_controller_spec.rb, spec/models/order_import_spec.rb
- Add log event when an order import is created
- Fix order import form tab not being selected
=> [NU-57] Bulk orders import event log

spec/system/admin/projects_show_spec.rb
- Fix some `project_show_spec` flaky tests that use record ids to match page content
=> [NUOPEN-212] Project show flaky specs

spec/system/admin/projects_show_spec.rb
More flaky spec fixes.
Match full path on links instead of just the link text.
=> [NUOPEN-219][Tech task] Fix links matching on project show spec

.github/workflows/test-suite.yaml
- Add event on test workflow so we can run it for PRs created from forks.
Docs: https://docs.github.com/es/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target
=> [Chore] Run CI on PRs from forks

.github/workflows/test-suite.yaml
- Change test-suite workflow events because it was triggering two workflow runs for pushes to existing pull requests.
- Remove event `pull_request_target` because it runs in the context of the main branch, which seems to imply that nothing from the pull request branch gets tested
- In order to be able to run a single workflow for the repo collaborators and fork pull request I changed test-suite to only run for the `pull_request` event and for pushes to `master` so the staging deployment works.
=> [Fix] Change test-suite workflow trigger events

app/controllers/product_notifications_controller.rb, app/models/product.rb, app/services/order_purchaser.rb, app/views/product_notifications/edit.html.haml, app/views/product_notifications/show.html.haml, config/locales/en.models.yml, config/locales/views/admin/en.product_notifications.yml, db/migrate/20250326131059_change_product_order_notification_recipient.rb, db/schema.rb, spec/controllers/orders_controller_spec.rb, spec/models/product_spec.rb, spec/system/admin/product_notifications_controller_spec.rb
- Allow to specify a list of recipients on product order notification
- Rename `order_product_recipient` field to plural and extend its limit
=> [UMASS-133] Allow multiple recipients on product order notification

app/assets/stylesheets/app/statements.scss, app/assets/stylesheets/application.scss, app/controllers/facility_statements_controller.rb, app/models/statement.rb, app/presenters/statement_presenter.rb, app/views/facility_statements/index.html.haml, app/views/shared/_statements_table.html.haml, config/locales/en.models.yml, config/locales/en.yml, config/settings.yml, spec/presenters/statement_presenter_spec.rb, spec/system/admin/facility_statements_spec.rb, vendor/engines/c2po/spec/system/account_reconciliation_spec.rb
- Show reconciled_notes/unrecoverable_notes on statement table
> Note: it depends on changes from #5159 
- Render one log event per line and truncate long user names
=> [UMASS-167] Show reconciliation note

Gemfile, Gemfile.lock, config/environments/production.rb, config/initializers/uglifier_restriction.rb
- Uglifier, which is configured on staging and production, was failing to compress javascript code with ES6 syntax.
=> [FIX] Replace uglifier by terser

.rubocop_todo.yml, app/controllers/facility_account_users_controller.rb, app/controllers/order_management/order_details_controller.rb, app/helpers/account_price_group_members_helper.rb, app/mailers/problem_order_mailer.rb, app/models/concerns/downloadable_files/image.rb, app/models/order_status.rb, app/models/reports/account_transactions_report.rb, app/services/price_policy_builder.rb, app/support/orders/item_adder.rb, db/migrate/20200414202107_add_metadata_to_log_events.rb, db/migrate/20231116194445_update_duration_rate_rate_and_subsidy_to_per_minute_values.rb, spec/models/account_spec.rb, spec/models/instrument_issue_spec.rb, spec/models/reports/account_transaction_report_spec.rb, spec/models/statement_spec.rb, spec/services/log_event_searcher_spec.rb, spec/services/research_safety_adapters/scishield_training_synchronizer_spec.rb, spec/support/shared_examples/hidden_price_groups_shared_examples.rb, spec/system/admin/manage_order_detail_spec.rb, vendor/engines/sanger_sequencing/spec/presenters/sanger_sequencing/well_plate_presenter_spec.rb, vendor/engines/secure_rooms/app/controllers/secure_rooms/ethernet_ports_controller.rb, vendor/engines/secure_rooms/spec/system/edit_secure_room_ethernet_ports_spec.rb
> This is part of NUOPEN-58
- Enable cop to detect trailing whitespace
- Run rubocop autocorrect
=> [NUOPEN-58] Clear trailing whitespaces

app/controllers/facility_estimates_controller.rb, app/views/facility_estimates/index.html.haml, config/locales/en.models.yml, config/locales/en.yml, spec/factories/estimates.rb, spec/system/admin/viewing_estimates_spec.rb
Add a page that lists the user's estimates and shows the estimate details when clicking on one of them.
=> [NUOPEN-225] List and show estimates

app/models/statement.rb, app/views/shared/_statements_table.html.haml, spec/models/statement_spec.rb
- Remove `<ul/>` element bullet point from first note item
- Don't render empty notes when reconcile note field is ""
=> [UMASS-176][Fix] Remove style to first reconcile note

app/controllers/facility_accounts_reconciliation_controller.rb, app/controllers/order_management/order_details_controller.rb, app/helpers/order_details_helper.rb, app/lib/ability.rb, app/views/facility_accounts_reconciliation/_action_row.html.haml, config/locales/en.controllers.yml, spec/requests/order_management/order_details_spec.rb, spec/system/admin/manage_order_detail_spec.rb, vendor/engines/c2po/spec/system/account_reconciliation_spec.rb
- Use cancancan with custom action to authorize marking an order as unrecoverable
- Hide Unrecoverable option to non allowed users
=> [NOPEN-238] Update mark as unrecoverable permissions

app/views/shared/_statements_table.html.haml
When clicking expand on the statement history notes the page jumped to focus the target element.
Follow bootstrap example: https://getbootstrap.com/docs/4.0/components/collapse/#example
=> [UMASS-167] Fix page jump when expanding collapsed notes

spec/rails_helper.rb
- Increase IDs used by `FactoryBot.build_stubbed` so they don't overlap DB ids causing flaky specs like `spec/models/order_detail_spec:163` (https://github.com/wyeworks/nucore-open/actions/runs/14593368046/job/40933472282)
=> [Tech tasks][NUOPEN-223] Flaky specs: increase stub instance ids

spec/system/admin/instrument_schedule_positions_spec.rb
Wait for page to change before matching content. This fixes the flaky spec in `spec/syste/admin/instrument_schedule_positions_spec:47` (https://github.com/wyeworks/nucore-open/actions/runs/14593360285/job/40933450962)
=> [Tech Task][NUOPEN-223] Flaky spec: instrument schedule positions matching before page change

app/controllers/email_log_events_controller.rb, app/helpers/email_log_events_helper.rb, app/helpers/log_events_helper.rb, app/models/log_event.rb, app/models/reports/log_events_report.rb, app/services/log_event_searcher.rb, app/views/email_log_events/index.html.haml, app/views/log_events/_filter_form.html.haml, app/views/log_events/index.html.haml, config/locales/en.log_event_types.yml, config/locales/views/admin/en.log_events.yml, spec/services/log_event_searcher_spec.rb, spec/system/admin/email_log_events_spec.rb
- Add filters to email log by reusing the log events page form and search clases
- Move form to its own partial view
- Move events locales to its own file
=> [UMASS-142] Add filter to email log events

app/services/notification_sender.rb, spec/system/admin/review_period_spec.rb
On PR #5218 I changed how notifications where queued from using `.delay` to `ActionMailer::Base.deliver_later`. This broke the case when global billing admin user triggers this use case with the facility `Facility.cross_facility` which is always built on the fly and has no id, thus it cannot be serialized when queued.
=> [Fix] Notification sending for global billing

spec/system/admin/creating_an_estimate_spec.rb
Enable user price groups on estimate creation spec since they are required to calculate prices.
=> [Fix] User price groups on estimates specs

app/assets/javascripts/app/submit_on_change.js, app/controllers/users_controller.rb, app/views/users/access_list.html.haml, config/locales/en.yml, spec/system/admin/user_access_list_spec.rb
On the user product access list, add a checkbox to toggle hide inactive products.
Also added `(inactive)` label next to the name.
=> [UMASS-161] Toggle hide inactive products in user access list

app/models/estimate.rb, app/views/facility_estimates/show.html.haml, spec/system/admin/creating_an_estimate_spec.rb
* Add total price row in Estimate show
=> [NUOPEN-229] Add total price row in Estimate show

app/controllers/users_controller.rb, app/views/users/access_list.html.haml, config/locales/en.yml, spec/system/admin/user_access_list_spec.rb
On the user product access list, hide inactive products by default. Change "Hide inactive products" checkbox by "Show inactive Products".
=> [UMASS-161] Hide inactive products by default

app/presenters/order_detail_notice_presenter.rb, config/locales/en.yml, spec/presenters/order_detail_notice_presenter_spec.rb
Fix missing translation caused by order details with `problem_description_key` nil but `problem` attribute set to true.
=> [OSU-52] Fix translation missing condition

app/views/facility_estimates/_form.html.haml, spec/system/admin/editing_an_estimate_spec.rb
While opening the estimate edit view for an estimate with an existing user, the username field was shown as empty. With this change, it autofills the username on the form
=> [NUOPEN-235] Autocoplete username on estimates edit screen

app/controllers/facility_estimates_controller.rb, app/models/estimate.rb, app/models/estimate_detail.rb, app/views/facility_estimates/_estimate_detail.html.haml, spec/system/admin/duplicating_an_estimate_spec.rb, spec/system/admin/editing_an_estimate_spec.rb, spec/system/admin/recalculating_estimate_spec.rb
* Fix Estimate flow
* Make recalculation happen when clicking “Update”. ✅ 
* If “Recalculate” fails, redirect user to Edit page, so they can make the necessary changes. ✅ 
* If “Duplicate” fails, redirect user to New page, so they can see the errors and make any changes before saving. ✅
=> [NUOPEN-233] Fix Estimate flow

app/assets/javascripts/app/merge_orders.js, app/controllers/facility_orders_controller.rb, app/views/facility_orders/_merge_order_form.html.haml, spec/system/admin/adding_to_an_order_spec.rb
On manage order form, set default product to empty option instead of selecting the first one.
=> [NU-399] Default product blank on add to order

config/settings.yml, db/migrate/20250611145625_add_monetary_cap_to_accounts.rb, db/schema.rb, spec/system/admin/managing_payment_sources_spec.rb, vendor/engines/c2po/app/models/purchase_order_account.rb, vendor/engines/c2po/app/services/purchase_order_account_builder.rb, vendor/engines/c2po/app/views/c2po/facility_accounts/show/_additional_account_fields.html.haml, vendor/engines/c2po/app/views/facility_accounts/account_fields/_purchase_order_account.html.haml, vendor/engines/c2po/config/locales/en.yml, vendor/engines/c2po/spec/models/purchase_order_account_spec.rb
Add a monetary cap field to purchase orders
=> [NU-402] Add monetary cap field to P.O.s

app/services/price_policy_builder.rb, spec/services/price_policy_builder_spec.rb
Fixed automatic price policy creation for instruments with daily booking pricing mode when using "Skip Review" billing mode. The system now properly initializes daily-specific pricing fields to ensure correct pricing configuration for daily-based reservations.
When creating price policies for instruments configured with daily booking pricing mode through the "Skip Review" billing mode, the `PricePolicyBuilder` service was not properly handling the daily-specific pricing fields (`usage_rate_daily` and `usage_subsidy_daily`). This caused issues in the automatic price policy generation process.
- Updated `PricePolicyBuilder.create_price_policy_for` method to conditionally set pricing fields based on daily booking mode
- Updated `PricePolicyBuilder.new_price_policy` method for consistency …
=> [NU-408] Fix daily booking skip review instrument creation

app/controllers/concerns/sortable_billing_table.rb, app/services/transaction_search/date_range_searcher.rb, spec/system/admin/all_transactions_search_spec.rb
Sorting for transactions in statement/journal state is done in a model scope (as oposed to the other cases which are simple order clauses) so I exclude it from the sorting logic.
I also fixed Date range select options locale which was missing a nested translation which is only supported by the `text_helpers` gem.
=> [NUOPEN-261] Fix transactions statemented filter

app/assets/stylesheets/app/reports.scss, app/assets/stylesheets/nucore.scss, app/views/facility_accounts_reconciliation/_action_row.html.haml, app/views/facility_journals/index.html.haml, app/views/reports/report.html.haml, vendor/engines/secure_rooms/app/views/secure_rooms/ethernet_ports/edit.haml
Make some corrections needed after the bootstrap upgrade:
1- Fix reconcile purchase orders form:
before:
now:
2- Fix side menu padding:
before:
now:
3- Fix pending journals modal
before:
now:
4- Fix export reports links
before:
now:
5- Fix price policy form styling
before:
after:
=> Nuopen 266 fix styling issues

app/assets/javascripts/app/tab-counts.js
Fix numbers on tabs
before:
after:
=> [NUOPEN-266] Fix tab spinners

app/controllers/concerns/sortable_column_controller.rb, spec/system/admin/all_transactions_search_spec.rb
Oracle adapter uses `first_value()` SQL function when implementing `columns_for_distinct()` method, which is used by active record, in this case, when there's an order by clause and some conditions apply on the joined tables.
We were providing several order criteria as a string which made first_value to be called with multiple arguments thus giving an error.
The fix is to provide multiple order criteria as independent entries.
Reference:
- FIRST_VALUE(): https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/FIRST_VALUE.html
- Oracle adapter `columns_for_distinct()`: https://github.com/rsim/oracle-enhanced/blob/1ad893df4f3c083c8c6044e57f5b06c80cad2b28/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb#L652
=> [NU-409] Fix sortable column order in Oracle

Dockerfile
- Set back the default cmd to run puma server (after https://github.com/wyeworks/nucore-open/pull/5523)
- Set develop target cmd to bin/dev
- Use non interactive flag for yarn install
=> [Fix] Set dockerfile deploy cmd

app/presenters/order_detail_notice_presenter.rb, config/settings.yml, spec/presenters/order_detail_notice_presenter_spec.rb
There're are order notices that depend on the current time so this disables static notices until we find a workaround.
=> [NUOPEN-263] Compute notices on render

spec/requests/facility_billing_log_events_spec.rb
Use matching case string in spec to work in Oracle.
=> [UMASS-191] Use matching case in spec

app/assets/stylesheets/app/facility_accounts.scss, app/inputs/date_picker_input.rb
- Set account form max-width to form-control instead of inputs so it applies to select elements as well
- Use bootstrap input styles for date picker. This applies to all date pickers in the app
> These changes are needed for school specific changes
Before
After
When the account form has a select box it spans the full width of the page since the max width style was only applied to inputs.
The date picker is rendered for the account `expires_at` field and was not using bootstrap styles.
=> [OSU-173] Account styles fixes

app/controllers/facility_journals_controller.rb, app/services/order_details/reconciler.rb, app/views/facility_accounts_reconciliation/_table.html.haml, app/views/facility_journals/show.html.haml, config/locales/en.controllers.yml, config/routes.rb, spec/controllers/facility_accounts_reconciliation_controller_spec.rb, spec/controllers/facility_journals_controller_spec.rb, spec/services/order_details/reconciler_spec.rb, vendor/engines/c2po/spec/system/account_reconciliation_spec.rb
Add mass unreconciling functionality for journal transactions, allowing facility administrators to efficiently reverse reconciled payment transactions in bulk.
=> [NU-28] Mass journal transaction unreconcile

app/models/order_detail.rb, config/settings.yml, spec/models/order_detail_price_groups_spec.rb
Added configurable pricing flow feature that allows price groups to be determined by payment source (account owner) instead of purchaser when enabled.
This change introduces a new feature flag `pricing_flows_from_payment_source` that modifies how price groups are calculated for order details. When enabled, the system will use the account owner's price groups instead of the purchaser's price groups for pricing calculations.
=> [NU-26] Use account owner for pricing when feature flag is enabled

app/services/order_details/reconciler.rb, spec/controllers/facility_journals_controller_spec.rb
On the Manage journal page, when doing bulk reconciling/unreconciling errors weren’t being handled correctly
=> [NU-28] Fix error message when rollbaking reconcile and unreconcile all

app/controllers/facility_journals_controller.rb, app/models/order_detail.rb, app/models/order_detail/accessorized.rb, app/services/order_details/reconciler.rb, app/views/facility_journals/show.html.haml, config/locales/en.controllers.yml, spec/controllers/facility_journals_controller_spec.rb
Allow only global administrators to mass unreconcile journal orders, including accessory orders that were previously failing due to state transition conflicts. Only orders within the selected journal are affected - related orders outside the journal remain unchanged.
Previously, mass unreconciling would fail when journals contained parent orders with accessories. When a parent order was unreconciled, it would trigger an `after_save` callback that attempted to update child orders' status, causing invalid state transitions from 'reconciled' to 'complete' using the wrong event.
- Restricted mass unreconciling feature to global administrators only
- Added proper state machine transition `unreconcile` event to OrderDetail model
- Modified reconciler to use the state machine's `unreconcile!` …
=> [NU-28] Only global admin can mass unriconcile

app/models/account.rb, app/models/product.rb, spec/models/account_spec.rb, spec/models/order_detail_price_groups_spec.rb
When user_based_price_groups_exclude_purchaser FF is on and a payment source has a price group assigned, use that price group directly instead of comparing it with the owner's price groups.
[#NU-26 | Pricing flowing from payment source/payment source owner ](https://universe-of-universities.atlassian.net/browse/NU-26)
=> [NU-26] Use payment source price group when assigned

spec/services/auto_expire_reservation_spec.rb
* Use correct account for the non-billable reservation spec
[#NU-26](https://universe-of-universities.atlassian.net/browse/NU-26)
When user goes through the reservation flow, they can only select the NonBillable account, so it makes sense to set it in the spec.
=> [NU-26] Use correct account for the non-billable reservation spec
