wyeworks/nucore-open

- vendor/engines/c2po/config/locales/en.yml
- vendor/engines/c2po/lib/c2po/facility_accounts_controller_extension.rb
There's also some refactoring and reformatting that should make Rubocop and Code Climate a bit happier.
> [#92708] Trap badly-formatted PO expiration dates

- app/views/notifier/order_receipt.html.haml
- config/locales/en.yml
https://pm.tablexi.com/issues/89150
Add total line to emailed receipt.
> Add mailed receipt total line

- lib/validator/validator_factory.rb
- spec/controllers/facility_journals_controller_spec.rb
Yet another attempt to get CI passing.
JournalRow has some extra validations on NU, so we can't just replace with the ValidatorDefault.
> [#94276] Fix spec, which was broken on NU

- app/models/instrument_price_policy.rb
- app/views/price_policies/instrument/_minimum_calculation.html.haml
https://pm.tablexi.com/issues/94323
`instrument_price_policies#index (ActionView::Template::Error) "undefined method `*' for nil:NilClass"`
> [#94323] Fix minimum cost subsidy error

- app/views/shared/_problem_order_details.html.haml
https://pm.tablexi.com/issues/47799
> [#47799] Show customer which order is for

- app/controllers/instruments_controller.rb
https://pm.tablexi.com/issues/96159
> [#96159] Lock window default should be 0

- app/controllers/reservations_controller.rb
- app/helpers/reservations_helper.rb
- app/support/reservations/date_support.rb
- app/support/reservations/duration_change_validations.rb
- app/support/reservations/moving_up.rb
- app/support/reservations/validations.rb
- app/views/reservations/_reservation_fields.html.haml
- spec/app_support/reservations/duration_change_validations_spec.rb
- spec/factories/reservations.rb
- spec/models/reservation_date_support_spec.rb
- spec/models/reservation_spec.rb
https://pm.tablexi.com/issues/92231
Fixing the things Aaron found.
> [#92231] Add time to ongoing reservations fixes

- app/controllers/account_price_group_members_controller.rb
- app/controllers/concerns/price_group_members_controller.rb
- app/controllers/price_groups_controller.rb
- app/controllers/user_price_group_members_controller.rb
- app/views/admin/shared/_tabnav_price_group.html.haml
- lib/ability.rb
- spec/lib/ability_spec.rb
https://pm.tablexi.com/issues/50175
This includes the changes that Aaron and Todd asked for.
> [#50175] Make cancer center users visible for facility admins

- app/models/order_detail.rb
- app/models/order_status.rb
- app/support/products/scheduling_support.rb
- spec/app_support/reservation_instrument_switcher_spec.rb
https://pm.tablexi.com/issues/96992
> [#96992] Exclude reconciled orders when completing

- app/assets/javascripts/app/reservation_time_field_adjustor.js.coffee
This should address Aaron's feedback.
> [#94617] Changing start time was not adjusting duration/end time

- README.md
- doc/instrument_pricing.md
I wrote this up as something to send to UIC for clarification. Double check my calculations and make sure they match with how you think the model works.
> Instrument pricing documentation

- app/controllers/product_users_controller.rb
- app/models/product_user_creator.rb
- spec/models/product_user_creator_spec.rb
This is a regression from the Training Request list #298.
> [#99059] Soft error on duplicate ProductUser

- app/controllers/facility_notifications_controller.rb
- app/controllers/facility_orders_controller.rb
- app/controllers/facility_statements_controller.rb
- app/controllers/orders_controller.rb
- app/controllers/users_controller.rb
- app/models/order_import.rb
- app/models/reports/order_import.rb
- config/environments/test.rb
- lib/status_change_notifications.rb
- spec/controllers/facility_orders_controller_spec.rb
This should ideally help address some timeouts that are happening with large order lists for Send Notifications.
I will not be surprised if there are some test failures from checking that emails were indeed sent.
> [#102917] Use delayed job for email sending

- app/views/admin/shared/_sidenav_product.html.haml
- config/routes.rb
> [#103870] Use feature flag for training request in product sidebar

- app/helpers/facilities_helper.rb
- app/views/facilities/show.html.haml
- config/routes.rb
- config/settings.yml
- spec/controllers/facilities_controller_spec.rb
UIC does not want this feature enabled as they have concerns with
hidden instruments on shared schedules.
The test will fail in UIC until #329 is merged.
> [#103850] Feature flag for public daily view

- app/views/admin/shared/_tabnav_order.html.haml
- app/views/admin/shared/_tabnav_reservation.html.haml
UIC does not have a review period, so there is no way to dispute, so there's no need for the tab.
> [#121201] Hide Dispute tab if there is no review period

- Gemfile
- Gemfile.lock
- config/application.rb
- config/schedule.rb
- config/schedule_custom.rb
I feel like it would be good to have some documentation about the cron jobs, or even better, how to make sure you have everything running you need in production. I feel like that may be job for the next implementation.
> [#102970] Add Whenever to manage cronjobs

- lib/ability.rb
- spec/lib/ability_spec.rb
Related to refactor of abilities in #359 and #362.
> [#121327] Facility Admin/Directors were unable to delete admin reservations

- app/controllers/facilities_controller.rb
- app/models/user.rb
- db/migrate/20150930213606_add_active_facilities_index.rb
- db/schema.rb
- spec/factories/facilities.rb
- spec/factories/orders.rb
- spec/models/user_spec.rb
* Return facilities list to alphabetical order
* Use acting_user as source for most recent facilities
* Order recent facilities by name
* Ensure orders are searched by ordered_at for use in recent facilities
* Add index for the homepage ordering
> [#94618] Homepage fixes

- config/environments/production.rb
To be followed by cleanup to NU & UIC’s stage and prod environment
files.
> Clean up environments/production.rb

- lib/tasks/demo_seed.rake
Two commits, first one is some rubocop autocorrects including single->double quotes and 1.9 hash syntax. Second commit is the actual change.
> Create Billing Admin in demo seed

- lib/tasks/db.rake
This cleans out a bunch of other stuff that gets created along the ways
(especially from production data exports).
The best way to clean out the database is to drop and recreate the
user, but that requires SYS permissions.
> Even more severe oracle cleaning

- Gemfile
- Gemfile.lock
- app/controllers/facilities_controller.rb
- app/models/facility.rb
- spec/controllers/facilities_controller_spec.rb
- vendor/engines/c2po/lib/c2po.rb
- vendor/engines/c2po/spec/controllers/facilities_controller_spec.rb
I’m going to need to protect a couple columns on Facility for the
credit card processing, so I figured I’d bring in strong_params.
Getting it across the board will be a big undertaking (probably will do
it with the Rails 4 upgrade), but this starts laying the groundwork.
Two commits. First one is the actual change, second one is rubocop.
> Add Strong Params to Facilities

- app/views/admin/shared/_sidenav_admin.html.haml
This will be used for a link to the editing/updating of merchant ids per facility for credit cards
> [#103993] Add hook in facility admin sidebar

- README.md
- config/locales/en.yml
- config/locales/override/en.yml
- doc/FACTORIES.md
- doc/HOWTO_daemons.txt
- doc/HOWTO_forks.md
- doc/HOWTO_ldap.md
- doc/coding_standards.md
- lib/daemons/base.rb
I'll have a separate PR for UIC where I fix a few merge conflicts and update a couple overrides.
> [#122002] Update spacing/capitalization to "NUcore"

- config/environments/production.rb
We'll need to add it to the staging environments in NU/UIC.
> [#122054] Add print.css to asset precompile list.

- Gemfile
- Gemfile.lock
- README.md
- config/environments/development.rb
We'll need to smoke screen test this gem with delayed jobs.  I imagine we shouldn't run into any problems, but let's try it out before merging.  I'll test when time permits.
https://github.com/ryanb/letter_opener
> Install letter_opener gem

- config/environment.rb
> Do not load mysql patch for 5.7 in oracle mode

- app/views/order_management/order_details/edit.html.haml
This accidentally got committed with the check for the feature flag commented
out.
> [#121871] Make print button respect feature setting

- app/services/nufs_account_builder.rb
- spec/services/nufs_account_builder_spec.rb
https://www.pivotaltracker.com/story/show/115368465
This is an issue in NU
> Do not add validation errors for FacilityAccount#new

- config/locales/en.yml
The existing text has some awkward phrasing and typos.
> [#125280] Clean up journal creation instructions

- app/controllers/general_reports_controller.rb
- app/models/reports/export_raw.rb
- app/services/reports/querier.rb
- spec/controllers/general_reports_controller_spec.rb
- vendor/engines/split_accounts/app/services/split_accounts/order_detail_splitter.rb
- vendor/engines/split_accounts/spec/models/reports/export_raw_spec.rb
- vendor/engines/split_accounts/spec/services/order_detail_splitter_spec.rb
Adds support for split accounts and export raw.
https://www.pivotaltracker.com/story/show/114612217
> [#120455] Split accounts reports export raw

- vendor/engines/c2po/app/services/credit_card_account_builder.rb
- vendor/engines/c2po/spec/controllers/facility_accounts_controller_extension_spec.rb
Broken by e5da7ffb5c68dd63fb9b63f051bad506903476bb when we starting
using the AccountBuilders for #new.
Pivotal #115799169
> [#120455] Fix "invalid date" error on Credit Card new

- app/controllers/general_reports_controller.rb
- app/models/reports/export_raw.rb
- config/locales/en.controllers.yml
- config/settings.yml
- lib/hash_helper.rb
- lib/reports/export_raw_factory.rb
- spec/controllers/general_reports_controller_spec.rb
- vendor/engines/split_accounts/app/models/split_accounts/reports/export_raw_transformer.rb
- vendor/engines/split_accounts/config/locales/en.yml
- vendor/engines/split_accounts/lib/split_accounts/engine.rb
- vendor/engines/split_accounts/spec/models/reports/export_raw_spec.rb
This is a rebase of #494. There’s some good history of the thought process and different attempts.
Pivotal #115081455
> [#120455] Refactor Export Raw and show percentage of split charges [rebase]

- lib/transaction_search.rb
Pull up https://github.com/tablexi/nucore-nu/commit/885c8036b9a1e2ac54147eea91ee19eed682ccf0
Found this conflict while pulling rubocop changes into NU
> Force no reorder to correct Oracle query issue

- vendor/engines/split_accounts/app/models/split_accounts/reports/export_raw_transformer.rb
Per Aaron: “we have distributed Excel templates that auto-sort "Export
Raw" reports, and we are not in a position to edit and redistribute
these templates at the moment.”
Pivotal #116148175
> [#120455] Move split percent column to end

- vendor/engines/split_accounts/app/views/split_accounts/shared/_show_splits.html.haml
- vendor/engines/split_accounts/config/locales/en.yml
On the show_splits view and the #new form
> [#120455] Update I18n for split account attributes

- .rubocop_todo.yml
- app/support/orders/item_adder.rb
- spec/app_support/notification_sender_spec.rb
- spec/controllers/facility_journals_controller_spec.rb
- spec/controllers/facility_orders_controller_spec.rb
- spec/models/account_spec.rb
- spec/models/order_detail_spec.rb
- spec/models/product_spec.rb
- spec/models/reports/instrument_utilization_report_spec.rb
- vendor/engines/c2po/spec/models/order_detail_spec.rb
Replace `.times.map` and `.times.collect` with `Array.new(n) { }`
> Rubocop: Performance/TimesMap

- vendor/engines/split_accounts/README.md
@benlinton Any suggestions of other things to add?
> [#120455] Readme for Split Accounts engine

- app/controllers/global_search_controller.rb
- app/services/global_search/statement_searcher.rb
- spec/controllers/global_search_controller_spec.rb
This should address the test failures on uic/develop.
> [#86777] Disable statement search specs if statements are disabled

- app/models/user.rb
- config/locales/en.yml
- spec/controllers/devise/sessions_controller_spec.rb
And kick them out if they have a current session.
> [#124331] Prevent deactivated users from logging in

- .rubocop-txi.yml
- app/controllers/order_details_controller.rb
- app/presenters/reservation_user_action_presenter.rb
- config/routes.rb
- spec/controllers/order_details_controller_spec.rb
- spec/factories.rb
- spec/factories/journals.rb
- spec/models/reservation_spec.rb
- spec/presenters/reservation_user_action_presenter_spec.rb
This will prepare us for being able to update the account on order details.
> [#47665] Add specs for reservation cancelation

- spec/factories/account_users.rb
And add business_administrator trait
> Use constants for AccountUser factories

- spec/controllers/search_controller_spec.rb
> Remove :focus in specs

- spec/controllers/search_controller_spec.rb
Pulled up from https://github.com/tablexi/nucore-uic/pull/67
> Enable necessary features for search spec

- app/models/account_config.rb
- spec/controllers/facility_accounts_controller_spec.rb
- vendor/engines/split_accounts/spec/controllers/facility_accounts_controller_spec.rb
Cherry-picked from https://github.com/tablexi/nucore-dartmouth/pull/29
> Fix specs when NufsAccount creation is disabled

- .codeclimate.yml
- Gemfile
- Gemfile.lock
- db/schema.rb
- vendor/engines/projects/app/models/projects/facility_extension.rb
- vendor/engines/projects/app/models/projects/project.rb
- vendor/engines/projects/db/migrate/20160328144628_create_projects.rb
- vendor/engines/projects/lib/projects.rb
- vendor/engines/projects/lib/projects/engine.rb
- vendor/engines/projects/lib/projects/version.rb
- vendor/engines/projects/projects.gemspec
- vendor/engines/projects/spec/factories/projects.rb
- vendor/engines/projects/spec/models/projects/project_spec.rb
This adds engine boilerplate, a Project model with migration, Facility association, and validation specs.
I wanted to get a foundation out for review with changes to add routes, controller(s), view and Ability hooks coming in the next PR.
> [#116373301] Add "projects" engine

- vendor/engines/projects/app/controllers/projects/projects_controller.rb
- vendor/engines/projects/app/models/projects/ability_extension.rb
- vendor/engines/projects/app/views/projects/projects/index.html.haml
- vendor/engines/projects/app/views/projects/projects/show.html.haml
- vendor/engines/projects/config/routes.rb
- vendor/engines/projects/spec/controllers/projects/projects_controller_spec.rb
- vendor/engines/projects/spec/models/projects/ability_extension_spec.rb
This adds a bare-bones show view for a `Project`, and adds links to these from project index listings.
> [#116373789] Add Project show view

- app/controllers/bulk_email_controller.rb
- app/inputs/transaction_chosen_input.rb
- app/models/order_detail.rb
- app/services/transaction_search/account_owner_searcher.rb
- app/services/transaction_search/account_searcher.rb
- app/services/transaction_search/base_searcher.rb
- app/services/transaction_search/date_range_searcher.rb
- app/services/transaction_search/facility_searcher.rb
- app/services/transaction_search/order_status_searcher.rb
- app/services/transaction_search/product_searcher.rb
- app/views/general_reports/_report_controls.html.haml
- app/views/shared/transactions/_search.html.haml
- config/locales/views/admin/en.transaction_search.yml
- lib/transaction_search.rb
- spec/controllers/facility_statements_controller_spec.rb
- spec/lib/transaction_history_search_spec.rb
- spec/transaction_search_spec_helper.rb
- vendor/engines/projects/app/services/projects/project_searcher.rb
- vendor/engines/projects/app/views/projects/shared/transactions/_search.html.haml
- vendor/engines/projects/lib/projects/engine.rb
- vendor/engines/projects/spec/controllers/facilities_controller_spec.rb
There is definitely more refactoring I would love to do to TransactionSearch to get rid of a lot of the metaprogramming and get it more wrapped up in tighter objects rather than making very large controllers, but this felt like a good stopping point.
First commit is a refactor; second is actually adding the project search.
> [#116374999] Project filter on transaction search

- config/application.rb
- spec/app_support/reservations/date_support_spec.rb
- spec/app_support/reservations/rendering_spec.rb
- spec/models/instrument_price_policy_spec.rb
- spec/models/item_price_policy_spec.rb
- spec/models/old_instrument_price_policy_spec.rb
- spec/models/service_price_policy_spec.rb
- spec/presenters/statement_presenter_spec.rb
https://github.com/rails/rails/commit/39374aa925a7d670b039c0c0c9aa9f4aef19466b
I pulled in some spec changes after seeing failing tests when DC ran in Eastern time. I set this to run in Pacific to make sure it works that way as well. We'll revert that change before merging.
> Ensure tests work in timezones other than Central

- app/models/order_status.rb
- app/models/reports/instrument_utilization_report.rb
- vendor/engines/projects/app/controllers/projects/reports_extension.rb
- vendor/engines/projects/spec/controllers/reports/general_reports_controller_spec.rb
- vendor/engines/projects/spec/controllers/reports/instrument_reports_controller_spec.rb
> [#117175831] Instrument report was shifting left on the no-project row

- vendor/engines/projects/app/controllers/projects/projects_controller.rb
- vendor/engines/projects/app/models/projects/project.rb
These were onordered previously.
> List Projects in name order on indexes

- app/controllers/order_details_controller.rb
- spec/controllers/order_details_controller_spec.rb
- spec/factories/orders.rb
- spec/factories/products.rb
- spec/factories/stored_files.rb
> [#126252] Could not upload files when adding to existing order

- app/views/notifier/review_orders.html.haml
- app/views/notifier/statement.html.haml
- app/views/notifier/statement.text.erb
- app/views/notifier/user_update.html.haml
- config/locales/en.notifier.yml
See commit messages for more info
> [#126287] Email fixes

- app/mailers/notifier.rb
This is needed by UIC in one of their locale overrides.
> [#125690] Add facility to statement subject interpolations

- db/schema.rb
- vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/submissions_controller.rb
- vendor/engines/sanger_sequencing/app/models/sanger_sequencing/sample.rb
- vendor/engines/sanger_sequencing/app/models/sanger_sequencing/submission.rb
- vendor/engines/sanger_sequencing/app/presenters/sanger_sequencing/link_collection_extension.rb
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/submissions/new.html.haml
- vendor/engines/sanger_sequencing/config/locales/en.yml
- vendor/engines/sanger_sequencing/config/routes.rb
- vendor/engines/sanger_sequencing/db/migrate/20160526192926_add_customer_sample_id_to_sanger_sequencing.rb
- vendor/engines/sanger_sequencing/lib/sanger_sequencing/engine.rb
- vendor/engines/sanger_sequencing/spec/factories/submissions.rb
- vendor/engines/sanger_sequencing/spec/features/purchasing_spec.rb
- vendor/engines/sanger_sequencing/spec/models/sanger_sequencing/sample_spec.rb
This extends from #625, which is where most of the commits come from. Only the last two are specific to this PR.
> [#119570591] Pre-populate Sanger Customer Sample IDs

- vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/submissions_controller.rb
- vendor/engines/sanger_sequencing/app/models/sanger_sequencing/order_detail.rb
- vendor/engines/sanger_sequencing/app/models/sanger_sequencing/sample.rb
- vendor/engines/sanger_sequencing/app/models/sanger_sequencing/submission.rb
- vendor/engines/sanger_sequencing/app/services/sanger_sequencing/submission_updater.rb
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/submissions/new.html.haml
- vendor/engines/sanger_sequencing/config/locales/en.yml
- vendor/engines/sanger_sequencing/config/routes.rb
- vendor/engines/sanger_sequencing/spec/features/purchasing_spec.rb
- vendor/engines/sanger_sequencing/spec/models/sanger_sequencing/sample_spec.rb
This is the basic edit functionality. This does not have the JS add/remove functionality yet.
> [#119570693] Sanger sequencing edit form

- app/assets/javascripts/app/cart.coffee
- app/views/orders/_form.html.haml
- app/views/orders/_service_desc.html.haml
- spec/javascripts/app/cart_quantity_replacer_spec.coffee
- vendor/engines/sanger_sequencing/spec/features/purchasing_spec.rb
Only the last commit is relevant here, the rest of the commits are from #637, primarily for the poltergeist integration.
> [#119570551] Pass quantity to Sanger even without clicking "Update"

- lib/nucore.rb
- spec/controllers/facility_facility_accounts_controller_spec.rb
- spec/helpers/date_helper_spec.rb
This is a redo of #647 against `master` since that is now on Rails 4.2.
> Rails upgrade loose ends

- db/schema.rb
- vendor/engines/sanger_sequencing/app/presenters/sanger_sequencing/link_collection_extension.rb
- vendor/engines/sanger_sequencing/db/migrate/20160606205228_add_sanger_option_to_facility.rb
- vendor/engines/sanger_sequencing/spec/features/administering_spec.rb
I chose to not add a way to do this in the UI, since the vast majority
of facilities will not need it. We can turn it on for facilities as
needed.
> [#120813297] Enable Sanger tab per-facility

- vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/submissions_controller.rb
- vendor/engines/sanger_sequencing/app/models/sanger_sequencing/submission.rb
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/submissions/show.html.haml
- vendor/engines/sanger_sequencing/config/routes.rb
- vendor/engines/sanger_sequencing/spec/controllers/sanger_sequencing/submissions_controller_spec.rb
- vendor/engines/sanger_sequencing/spec/features/purchasing_spec.rb
And prevent editing by user after purchase.
Continues on from #642.
> [#120858001] Sanger Submission Show View for After Purchase

- vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/admin/submissions_controller.rb
- vendor/engines/sanger_sequencing/app/models/sanger_sequencing/ability.rb
- vendor/engines/sanger_sequencing/app/models/sanger_sequencing/submission.rb
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/submissions/index.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/submissions/show.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/submissions/_samples_table.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/submissions/show.html.haml
- vendor/engines/sanger_sequencing/config/locales/en.yml
- vendor/engines/sanger_sequencing/config/routes.rb
- vendor/engines/sanger_sequencing/spec/controllers/sanger_sequencing/submissions_controller_spec.rb
- vendor/engines/sanger_sequencing/spec/features/administering_spec.rb
Also a basic submission show view. This will likely get cleaned up as we get further along.
> [#119570851] Sanger admin index view

- app/models/order_detail.rb
- vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/admin/batches_controller.rb
- vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/admin/submissions_controller.rb
- vendor/engines/sanger_sequencing/app/models/sanger_sequencing/submission.rb
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/batches/new.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/submissions/_sidenav.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/submissions/index.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/submissions/show.html.haml
- vendor/engines/sanger_sequencing/config/locales/en.yml
- vendor/engines/sanger_sequencing/config/routes.rb
Plus initial batch view.
First three commits are from #660.
> [#119570851] Admin view of purchased Sanger sequencing submissions

- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/batches/new.html.haml
The functionality doesn't work yet and currently errors. This will avoid errors
while we're building out the next feature.
> [#120869561] Temporarily disable "Save Batch" for Sanger well plates

- vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/admin/batches_controller.rb
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/batches/index.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/shared/_sidenav.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/submissions/index.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/submissions/show.html.haml
- vendor/engines/sanger_sequencing/config/locales/en.yml
- vendor/engines/sanger_sequencing/config/routes.rb
Continues from #673 
This doesn't do much yet, just a listing. We'll have deletion and downloading the export file next.
> [#120869959] Sanger Sequencing Batch Index

- db/schema.rb
- vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/admin/admin_controller.rb
- vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/admin/batches_controller.rb
- vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/admin/submissions_controller.rb
- vendor/engines/sanger_sequencing/app/models/sanger_sequencing/ability.rb
- vendor/engines/sanger_sequencing/app/models/sanger_sequencing/batch.rb
- vendor/engines/sanger_sequencing/app/models/sanger_sequencing/batch_form.rb
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/batches/index.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/submissions/index.html.haml
- vendor/engines/sanger_sequencing/config/locales/en.yml
- vendor/engines/sanger_sequencing/config/routes.rb
- vendor/engines/sanger_sequencing/db/migrate/20160629170900_add_facility_to_sanger_batch.rb
- vendor/engines/sanger_sequencing/spec/factories/batches.rb
- vendor/engines/sanger_sequencing/spec/features/batches/creating_a_batch_spec.rb
- vendor/engines/sanger_sequencing/spec/features/batches/deleting_a_batch.rb
- vendor/engines/sanger_sequencing/spec/models/sanger_sequencing/batch_form_spec.rb
Extends from #674 and #673.
This also adds authorization around Batch actions and locks them to a facility.
> [#123479051] Sanger sequencing deleting a batch

- lib/tasks/demo_seed.rake
I needed to do a complete database reset and ran into some issues in the demo seed. This should allow the demo seed to work from a completely empty database.
> Replace old-style finders in the demo seed

- vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/vue_bootstrap.coffee
- vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/vue_well_plate_displayer_app.coffee
- vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/vue_well_plate_editor_app.coffee
- vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/well_plate.js
- vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/well_plate_displayer.coffee
- vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/admin/batches_controller.rb
- vendor/engines/sanger_sequencing/app/models/sanger_sequencing/ability.rb
- vendor/engines/sanger_sequencing/app/models/sanger_sequencing/well_plate.rb
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/batches/_submission_list.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/batches/_vue_well_plate.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/batches/index.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/batches/new.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/batches/show.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/submissions/show.html.haml
- vendor/engines/sanger_sequencing/config/locales/en.yml
- vendor/engines/sanger_sequencing/config/routes.rb
> [#120869885] Sanger Sequencing batch show view

- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/submissions/index.html.haml
There was already a number from before I added the show views, so this just links
it up.
> Sanger sequencing: link to batch from submission index

- vendor/engines/sanger_sequencing/app/assets/stylesheets/sanger_sequencing/application.scss
- vendor/engines/sanger_sequencing/app/models/sanger_sequencing/submission.rb
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/batches/_submission_list.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/batches/_vue_well_plate.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/batches/new.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/submissions/_samples_table.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/submissions/show.html.haml
- vendor/engines/sanger_sequencing/config/locales/en.yml
Adds some style and additional information to the sanger views
> Sanger Polish

- app/controllers/my_files_controller.rb
Prevent a 500 error when trying to access the page while not logged in.
Also prevent access while acting as.
> [#126425461] Restrict access to my files

- app/models/email_event.rb
In a multithreaded environment, a second find_or_initialize_by might do the SELECT
before the save in the other thread has happened, causing a duplicate key violation
in the database when the second one tries to save. This locks the table so the second
doesn't do the select until the first one is done.
This seemed to be a little clearer than rescuing from ActiveRecord::RecordNotUnique
and RecordInvalid errors and throwing them away, although those might be slightly
more performant. In my local tests, the lock seemed just fine, even when uploading
10+ files at once.
> Prevent race conditions when debouncing email sending

- app/models/email_event.rb
The major change here is that we will simply bail in the case of
getting a record not unique error. We also don’t need to lock the table
in this case.
In the case where the uniqueness validation becomes invalid in the race
condition, then `update_attributes` will fail, so we won’t yield and
bail instead.
I actually tested this code on the staging server, and looks to be working better than the previous code.
I spent about an hour trying to write a spec for this and was unable to come up with anything that worked.
> Attempt 2: Prevent race conditions when debouncing email sending

- vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/columns_first_ordering_strategy.coffee
- vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/odd_first_ordering_strategy.coffee
- vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/rows_first_ordering_strategy.coffee
- vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/util.coffee
- vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/well_plate_builder.js.coffee
- vendor/engines/sanger_sequencing/spec/javascripts/columns_first_ordering_strategy_spec.js.coffee
- vendor/engines/sanger_sequencing/spec/javascripts/rows_first_ordering_strategy_spec.js.coffee
- vendor/engines/sanger_sequencing/spec/javascripts/util_spec.js.coffee
I’m planning to use the RowsFirstOrderingStrategy and
ColumnsFirstOrderingStrategy in an NU customization, so I wanted to
pull them into their own files in order to use just those pieces.
> Refactor sequencing ordering strategies into own files

- vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/submissions_controller.rb
I’ll be using this in NU for adding a well plate fill order parameter.
> [#127246] Add extension point for sanger submission params

- app/models/order_detail.rb
- app/support/reconcilable_account.rb
This is https://github.com/tablexi/nucore-nu/pull/188 pulled into open.
> Fix Oracle 1000 where in error on reconcilable accounts

- app/models/order.rb
- app/support/order_row_importer.rb
- spec/app_support/order_row_importer_spec.rb
- spec/controllers/orders_controller_spec.rb
- spec/controllers/reservations_controller_spec.rb
Also, do a little refactoring to the order state machine to remove a predicate
that had side-effects.
> [#130619] Do not send pending approval email on order import

- app/views/facilities/_facility_fields.html.haml
- app/views/facilities/manage.html.haml
- app/views/facility_users/index.html.haml
- vendor/engines/c2po/app/views/c2po/facilities/_manage.html.haml
* Facility admin show/edit
* Facility Staff listing
There are probably more, but I ran across these in #757.
> Fix missing translation errors

- app/helpers/facility_reservations_helper.rb
- app/models/offline_reservation.rb
- config/locales/en.yml
- spec/controllers/reports/instrument_unavailable_reports_controller_spec.rb
- spec/models/offline_reservation_spec.rb
This updates the list of offline categories to use the one NU provided. This change also uses locales as the source of the category list.
> [#126393] Update instrument down category list

- app/views/order_imports/new.html.haml
- config/locales/views/admin/en.order_imports.yml
- db/migrate/20160907170059_change_order_import_processed_at_type.rb
- db/migrate/20160908162845_update_timestamp_types.rb
- db/schema.rb
See notes in the commits for more information.
> [#132270] & [#132271] Order import page problems

- app/assets/stylesheets/nucore.scss
- app/assets/stylesheets/print.scss
- app/views/order_management/order_details/_copy_actuals_from_reservation.html.haml
- vendor/engines/projects/app/views/projects/shared/_select_project.html.haml
https://pm.tablexi.com/issues/130583
This updates the styles so printing order details (happening specifically in UIC) only takes up a single page.
> [#130583] Updates styles for printing order details

- spec/support/helper_methods.rb
This is @jhanggi's change pulled from https://github.com/tablexi/nucore-nu/issues/214.
> Add settings.local.yml to Settings reload

- lib/tasks/demo_seed.rake
This wasn't so much an issue with this fork as with NU's due to its account validations. I was able to seed a clean database on the NU fork with this patch.
> Update demo seed to pass NU validations

- app/validators/email_format_validator.rb
- spec/models/user_spec.rb
https://pm.tablexi.com/issues/133975
This allows apostrophes in emails, since there are those that have them that need to sign up.
> [#133975] Allow apostrophes in emails

- vendor/engines/bulk_email/app/mailers/bulk_email/mailer.rb
- vendor/engines/bulk_email/app/models/bulk_email/delivery_form.rb
- vendor/engines/bulk_email/spec/mailers/bulk_email/mailer_spec.rb
https://pm.tablexi.com/issues/134549
> [#134549] facility name displayed in From for bulk email

- app/controllers/instruments_controller.rb
- app/controllers/price_policies_controller.rb
- app/controllers/products_common_controller.rb
- app/helpers/price_policies_helper.rb
- app/models/facility.rb
- app/views/admin/shared/_sidenav_product.html.haml
- app/views/bundles/show.html.haml
- app/views/instruments/_instrument_fields.html.haml
- app/views/instruments/_instrument_manage_fields.html.haml
- app/views/instruments/_relay_manage.html.haml
- app/views/instruments/instrument_status.html.haml
- app/views/instruments/public_schedule.html.haml
- app/views/instruments/schedule.html.haml
- app/views/items/show.html.haml
- app/views/price_policies/_table.html.haml
- app/views/price_policies/edit.html.haml
- app/views/price_policies/index.html.haml
- app/views/price_policies/new.html.haml
- app/views/products_common/manage.html.haml
- app/views/products_common/show.html.haml
- app/views/services/show.html.haml
- config/locales/en.yml
- config/locales/views/admin/en.price_policies.yml
- spec/controllers/bundles_controller_spec.rb
- spec/controllers/instruments_controller_spec.rb
- spec/controllers/items_controller_spec.rb
- spec/controllers/services_controller_spec.rb
- spec/helpers/price_policies_helper_spec.rb
- vendor/engines/bulk_email/app/views/bulk_email/instruments/_send_mail_button.html.haml
Extends from #886. This cleans up some of the price policy views to make adding new products simpler.
> Homogenize price policy views

- Gemfile.lock
This includes an upgrade to `excon` as a dependency.
> [#134073] Upgrade fog-core

- Gemfile.lock
https://pm.tablexi.com/issues/134085
> [#134085] update therubyracer gem

- app/controllers/facility_statements_controller.rb
- app/services/statement_creator.rb
- spec/controllers/facility_statements_controller_spec.rb
https://pm.tablexi.com/issues/125661
Remove displayed <br/> from statement notification flash message.
> [#125661] statement flash notification

- Gemfile.lock
This is a dependency of `prawn`. I ran test statements with all forks and rendering appears unchanged.
> [#134078] Upgrade pdf-reader

- app/controllers/product_access_groups_controller.rb
- app/controllers/schedule_rules_controller.rb
- app/views/schedule_rules/index.html.haml
https://pm.tablexi.com/issues/134996
Resolved issue: tabs disappear when on either Scheduling or Scheduling Groups tab of an instrument on Stage
> [#134996] fix for tab nav

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/initializers/notifications.rb
- config/initializers/rollbar.rb
- config/secrets.yml.template
This also does some re-organization of gems in the Gemfile.
> [#141036111] Add Rollbar for Open Deployment

- config/locales/en.yml
- vendor/engines/c2po/app/views/facility_accounts/account_fields/_affiliate.html.haml
- https://pm.tablexi.com/issues/135123
> [#135123] update affiliate labels in payment source form

- circle.yml
It looks like Matt already set up the deployment keys, so this should be good to go.
> [#141036203] Deploy to stage on successful CI run

- vendor/engines/secure_rooms/README.md
- vendor/engines/secure_rooms/app/controllers/secure_rooms_api/scans_controller.rb
- vendor/engines/secure_rooms/app/presenters/secure_rooms/account_presenter.rb
- vendor/engines/secure_rooms/spec/controllers/secure_rooms_api/scans_controller_spec.rb
- vendor/engines/secure_rooms/spec/presenters/secure_rooms/account_presenter_spec.rb
* Currently just stubs out accounts_for_product cause I didn't have a chance to set up full accounts/pricing. I'd vote can make a separate story for it if necessary.
> [#140891951] Return list of accounts for SecureRoom

- app/controllers/global_settings_controller.rb
- app/views/shared/_head.html.haml
[#135271](https://pm.tablexi.com/issues/135271)
> [#135271] admin parts of the site - manage facilities and global settings - not responsive

- app/controllers/orders_controller.rb
- app/services/order_purchaser.rb
Companion to https://github.com/tablexi/nucore-nu/pull/239. Required for NU research safety.
> [#134985] refactor to allow additional validations for research safety

- vendor/engines/split_accounts/app/services/split_accounts/order_detail_splitter.rb
- vendor/engines/split_accounts/spec/services/order_detail_splitter_spec.rb
Between Rails 4.1 & 4.2, the behavior of has_one changed. Now, if the model (i.e.) the
order_detail is persisted, calling `order_detail.reservation =` will trigger
a `DELETE FROM reservations where order_detail_id = ?`.
Our `dup`ed order detail was being considered persisted because we copy over
the ID (which we need for reporting).
By moving the ID copying until last, Rails will assume that the order detail
is not persisted when we assign the reservation, so it won't trigger the DELETE.
I still need to look into if there is a good way to recover the lost data.
> [#135513] Reservations on split accounts were being deleted

- app/models/reports/export_raw.rb
- app/views/order_management/order_details/_shared_details.html.haml
- https://pm.tablexi.com/issues/135296
> [#135296] hide reviewed_at from views if zero-day review period

- config/initializers/mail_logger.rb
- https://pm.tablexi.com/issues/134989
> [#134989] basic email logger

- db/schema.rb
- vendor/engines/secure_rooms/app/controllers/secure_rooms_api/scans_controller.rb
- vendor/engines/secure_rooms/app/models/secure_rooms/event.rb
- vendor/engines/secure_rooms/app/presenters/secure_rooms/scan_response_presenter.rb
- vendor/engines/secure_rooms/app/services/secure_rooms/access_manager.rb
- vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/account_selection_rule.rb
- vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/archived_product_rule.rb
- vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/base_rule.rb
- vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/deny_all_rule.rb
- vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/egress_rule.rb
- vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/operator_rule.rb
- vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/requires_approval_rule.rb
- vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/schedule_rule.rb
- vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/verdict.rb
- vendor/engines/secure_rooms/app/services/secure_rooms/check_access.rb
- vendor/engines/secure_rooms/config/locales/en.yml
- vendor/engines/secure_rooms/db/migrate/20170406162317_create_events.rb
- vendor/engines/secure_rooms/spec/factories/event.rb
- vendor/engines/secure_rooms/spec/models/secure_rooms/event_spec.rb
- vendor/engines/secure_rooms/spec/services/secure_rooms/access_manager_spec.rb
- vendor/engines/secure_rooms/spec/services/secure_rooms/access_rules/account_selection_rule_spec.rb
- vendor/engines/secure_rooms/spec/services/secure_rooms/access_rules/egress_rule_spec.rb
**In Progress**: Adds event concept to scanning and updates `SecureRoomsApi::ScansController` with an `AccessManager` that handles validating access and creating events.
> [#140849913] Add events

- db/schema.rb
- vendor/engines/secure_rooms/app/controllers/secure_rooms/occupancies_controller.rb
- vendor/engines/secure_rooms/app/models/secure_room.rb
- vendor/engines/secure_rooms/app/models/secure_rooms/ability_extension.rb
- vendor/engines/secure_rooms/app/models/secure_rooms/event.rb
- vendor/engines/secure_rooms/app/models/secure_rooms/occupancy.rb
- vendor/engines/secure_rooms/app/services/secure_rooms/access_handlers/event_handler.rb
- vendor/engines/secure_rooms/app/services/secure_rooms/access_handlers/occupancy_handler.rb
- vendor/engines/secure_rooms/app/services/secure_rooms/access_manager.rb
- vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/verdict.rb
- vendor/engines/secure_rooms/app/views/secure_rooms/occupancies/index.html.haml
- vendor/engines/secure_rooms/app/views/secure_rooms/shared/_tabnav_secure_room.html.haml
- vendor/engines/secure_rooms/config/locales/en.yml
- vendor/engines/secure_rooms/config/routes.rb
- vendor/engines/secure_rooms/db/migrate/20170409125103_create_occupancies.rb
- vendor/engines/secure_rooms/db/migrate/20170409125104_update_events.rb
- vendor/engines/secure_rooms/spec/factories/occupancy.rb
- vendor/engines/secure_rooms/spec/features/view_occupancies_spec.rb
- vendor/engines/secure_rooms/spec/models/secure_rooms/event_spec.rb
- vendor/engines/secure_rooms/spec/models/secure_rooms/occupancy_spec.rb
- vendor/engines/secure_rooms/spec/services/secure_rooms/access_handlers/event_handler_spec.rb
- vendor/engines/secure_rooms/spec/services/secure_rooms/access_handlers/occupancy_handler_spec.rb
- vendor/engines/secure_rooms/spec/services/secure_rooms/access_manager_spec.rb
* in progress addition of `Occupancy` and its handler
> [#140938049] Add Occupancy

- vendor/engines/secure_rooms/app/services/secure_rooms/access_handlers/occupancy_handler.rb
> Log instead of Raise until error cases written

- vendor/engines/secure_rooms/app/controllers/secure_rooms/occupancies_controller.rb
- vendor/engines/secure_rooms/app/models/secure_rooms/occupancy.rb
- vendor/engines/secure_rooms/app/services/secure_rooms/access_handlers/occupancy_handler.rb
- vendor/engines/secure_rooms/app/views/secure_rooms/occupancies/index.html.haml
- vendor/engines/secure_rooms/config/locales/en.yml
- vendor/engines/secure_rooms/spec/factories/occupancy.rb
- vendor/engines/secure_rooms/spec/features/view_occupancies_spec.rb
- vendor/engines/secure_rooms/spec/services/secure_rooms/access_handlers/occupancy_handler_spec.rb
* Note: am cleaning up the `OccupancyHandler` spec, but only how it is organized, everything else is fair game for commentry
> [#140891971] Add error scanning cases

- app/controllers/product_users_controller.rb
There is no route for this controller action, it appears never to be used.
> rm unused controller action

- app/models/concerns/price_policies/usage.rb
- app/models/instrument_price_policy_calculations.rb
- app/services/price_policies/time_based_price_calculator.rb
- spec/factories/schedule_rules.rb
- spec/models/instrument_price_policy_calculations_spec.rb
- spec/models/instrument_price_policy_spec.rb
- spec/services/price_policies/time_based_price_calculator_spec.rb
Refactors the instrument price policy calculations so a good chunk of the logic is now in a separate class which I plan use for the secure rooms price policies calculations.
There's still more refactoring that could be done (I hate the interface for price policy calculations, but I didn't want to break too much). I'm not sure how much more I'll do on that side right now, but there's definitely specs to be moved or written.
> [#144318485] Refactor instrument price policy calculations

- vendor/engines/secure_rooms/app/models/secure_room_price_policy.rb
- vendor/engines/secure_rooms/spec/factories/secure_rooms_price_policies.rb
- vendor/engines/secure_rooms/spec/models/secure_room_price_policy_spec.rb
#1001 merged into the wrong branch so it didn't actually go in. This is merging it into master.
> [#144318485] Secure Room PricePolicy calculations

- app/helpers/facility_orders_helper.rb
- app/models/order_detail.rb
- app/models/reservation.rb
- app/models/time_data/null_time_data.rb
- app/models/time_data/required_time_data.rb
- app/views/shared/_problem_order_details.html.haml
- config/locales/en.models.yml
- config/locales/en.yml
- spec/models/reservation_spec.rb
- spec/models/time_data/null_time_data_spec.rb
- spec/models/time_data/required_time_data_spec.rb
- vendor/engines/secure_rooms/app/models/secure_rooms/occupancy.rb
- vendor/engines/secure_rooms/config/locales/en.yml
- vendor/engines/secure_rooms/spec/factories/secure_rooms_price_policies.rb
- vendor/engines/secure_rooms/spec/models/secure_room_price_policy_spec.rb
- vendor/engines/secure_rooms/spec/models/secure_rooms/occupancy_spec.rb
- vendor/engines/secure_rooms/spec/services/secure_rooms/access_handlers/order_handler_spec.rb
Need some feedback here:
* this uses the idea that `time_data` is one of 4 objects which can be aware of their own problems.. however it's odd that `RequiredTimeData` and `Reservation` have the same thing going on... what situation causes `RequiredTimeData` to be used?
* do we want to move the i18n somewhere else? they are under a "shared" key which could be fine, not sure of convention here
* any reason to further move `:price_policy_missing if ...blank?` or is it cool in `OrderDetail`
> [#144058895] Refactor problem descriptions

- vendor/engines/secure_rooms/app/controllers/secure_rooms/facility_occupancies_controller.rb
- vendor/engines/secure_rooms/app/models/secure_rooms/ability_extension.rb
- vendor/engines/secure_rooms/app/models/secure_rooms/order_detail_extension.rb
- vendor/engines/secure_rooms/app/presenters/secure_rooms/link_collection_extension.rb
- vendor/engines/secure_rooms/app/views/secure_rooms/facility_occupancies/index.html.haml
- vendor/engines/secure_rooms/app/views/secure_rooms/shared/_tabnav_occupancy.html.haml
- vendor/engines/secure_rooms/config/locales/en.yml
- vendor/engines/secure_rooms/config/routes.rb
- vendor/engines/secure_rooms/lib/secure_rooms/engine.rb
- vendor/engines/secure_rooms/spec/models/secure_room_price_policy_spec.rb
* naming-wise... did we want this to be "Rooms" instead of "Occupancies"?
> [#144059001] Add Admin Occupancies Tab

- app/views/facility_orders/show.html.haml
does the use of duration for quantity appear elsewhere (at least, within the scope of this story)?
> [#144059233] Duration as quantity

- vendor/engines/secure_rooms/app/controllers/secure_rooms_api/scans_controller.rb
- vendor/engines/secure_rooms/spec/controllers/secure_rooms_api/scans_controller_spec.rb
* Adds a `rescue_from` to avoid 404'ing in html
* doesn't yet address whether or not sending an error message would be helpful - need to chat with @danhodos about it
> [#145319401] Return 404s in JSON

- Gemfile
- Gemfile.lock
- Upgrades nokogiri and rubyzip for security concern
> Upgrade gems

- vendor/engines/secure_rooms/app/models/secure_rooms/event.rb
- vendor/engines/secure_rooms/app/services/secure_rooms/access_handlers/occupancy_handler.rb
- vendor/engines/secure_rooms/app/services/secure_rooms/access_handlers/order_handler.rb
- vendor/engines/secure_rooms/app/services/secure_rooms/access_manager.rb
- vendor/engines/secure_rooms/spec/factories/event.rb
- vendor/engines/secure_rooms/spec/services/secure_rooms/access_handlers/occupancy_handler_spec.rb
- vendor/engines/secure_rooms/spec/services/secure_rooms/access_manager_spec.rb
Adds guards against processing through the chain unless the event was "successful"
> [#145319377] Avoid processing denied scans

- app/controllers/reservations_controller.rb
This change is consistent with other flash invocations in this controller.
> Line Break Problem with Multiple Errors on Move Res

- app/models/product.rb
- app/views/facility_orders/_merge_order_form.html.haml
* adds a new list to which additional products should be added, if they are mergeable
> [#144059247] Exclude Rooms

- app/models/time_range.rb
https://rollbar.com/TableXI/nucore-open/items/8/
This fix exists in #1032.
> Fix errors on FacilityOrder#show for problem reservations

- app/controllers/accounts_controller.rb
- app/controllers/facility_notifications_controller.rb
- app/controllers/transactions_controller.rb
- app/models/order_detail.rb
`in_review` wasn’t being used anywhere, so I removed it and renamed
`all_in_review` to just `in_review`.
> Remove duplicate `in_review` scope

- app/views/notifier/review_orders.html.haml
- app/views/notifier/review_orders.text.erb
- config/locales/en.notifier.yml
Per comments on https://github.com/tablexi/nucore-dartmouth/pull/92,
moving the changes to common files to open, with the localization
overrides to come in a separate dartmouth PR.
The overrides are in https://github.com/tablexi/nucore-dartmouth/pull/95
> [#135589] -- Update emails

- app/controllers/admin/services_controller.rb
- app/support/auto_logout.rb
- config/routes.rb
- config/schedule.rb
- spec/controllers/admin/services_controller_spec.rb
- vendor/engines/secure_rooms/app/support/secure_rooms/auto_orphan_occupancy.rb
- vendor/engines/secure_rooms/lib/secure_rooms/engine.rb
- vendor/engines/secure_rooms/lib/tasks/restricted_rooms_tasks.rake
- vendor/engines/secure_rooms/spec/support/auto_orphan_occupancy_spec.rb
* the spec now relies on fixtures!!
Original PR: #1039
> [#144059389] Add task marking occupancies orphaned

- spec/controllers/users_controller_spec.rb
Resolve spec failure seen in https://github.com/tablexi/nucore-uic/pull/127
> fix fragile spec

- app/controllers/facility_journals_controller.rb
- app/models/reports/account_transactions_report.rb
- app/views/facility_journals/_problem_transactions.html.haml
- app/views/facility_journals/show.csv.erb
- app/views/reports/report.csv.haml
- app/views/reports/report_data.csv.haml
- lib/csv_helper.rb
- spec/features/creating_a_journal_spec.rb
- spec/models/order_import_spec.rb
- vendor/engines/bulk_email/app/views/bulk_email/bulk_email/create.csv.haml
- Depends on #1043, will need to be rebased once that's merged in.
- https://pm.tablexi.com/issues/135657
> [#135657] journal expired accounts csv

- vendor/engines/secure_rooms/app/views/secure_rooms/shared/_tabnav_occupancy.html.haml
* Similar to orders/reservations, this should be a `display_tab`
> [#145119365] Display count on New/IP tab

- Gemfile
- Gemfile.lock
- app/controllers/facility_journals_controller.rb
- config/environments/development.rb
This removes a couple of n+1 queries in journal row creation. I’ve also added the Bullet gem to detect these in the codebase, we can always turn it off if it gets too chatty.
> Clear n+1 in journal row creation

- app/models/message_summarizer.rb
- app/models/product.rb
- lib/configurable_array.rb
- spec/lib/configurable_array_spec.rb
- vendor/engines/secure_rooms/app/models/secure_rooms/problem_occupancy_message_summary.rb
- vendor/engines/secure_rooms/config/locales/en.yml
- vendor/engines/secure_rooms/lib/secure_rooms/engine.rb
- vendor/engines/secure_rooms/spec/controllers/facility_orders_controller_spec.rb
> [#145558575] Include problem occupancies in notices

- Gemfile.lock
NU and others are already using the newer version.
> Upgrade Unicorn

- app/controllers/order_detail_stored_files_controller.rb
- config/locales/en.controllers.yml
- https://pm.tablexi.com/issues/136226
> [#136226] prevent deletion of order form for purchased orders

- vendor/engines/secure_rooms/app/services/secure_rooms/check_access.rb
Pulled up from https://github.com/tablexi/nucore-nu/pull/256 in order to support injecting a research safety check.
> [#145049987] Ability to configure secure rooms CheckAccess list

- .haml-lint_todo.yml
- app/views/shared/_order_detail_cell.html.haml
- https://pm.tablexi.com/issues/134997
> [#134997] hide links unless permissions

- app/controllers/order_detail_stored_files_controller.rb
- https://pm.tablexi.com/issues/136226#change-377284
> [#136226] fix order form deletion error

- app/views/orders/receipt.html.haml
- config/locales/en.yml
> [#135269] Fix responsive receipt columns

- app/helpers/accounts_helper.rb
- app/views/admin/shared/_sidenav_users.html.haml
- app/views/admin/shared/_tabnav_payment_method.html.haml
- lib/ability.rb
- spec/helpers/accounts_helper_spec.rb
- spec/lib/ability_spec.rb
- https://pm.tablexi.com/issues/136391
> [#136391] hide statements and orders tabs for account managers

- app/controllers/facility_journals_controller.rb
- app/models/order_detail.rb
- app/views/facility_journals/new.html.haml
- lib/transaction_search.rb
- lib/validator/validator_factory.rb
- spec/factories.rb
- https://pm.tablexi.com/issues/134974
> [#134974] new journal page account validation

- .rubocop.yml
- app/models/charge_mode.rb
- app/models/concerns/price_policies/quantity.rb
- app/models/concerns/reports/csv_exporter.rb
- app/models/reports/export_raw.rb
- spec/models/charge_mode_spec.rb
- spec/models/reports/export_raw_spec.rb
- spec/support/matcher_specs/csv_column_matcher_spec.rb
- spec/support/matchers/csv_column_matcher.rb
- vendor/engines/secure_rooms/app/models/secure_room_price_policy.rb
- vendor/engines/secure_rooms/spec/models/reports/export_raw_spec.rb
- vendor/engines/split_accounts/spec/models/reports/export_raw_spec.rb
Continues on from #1086. 
As part of this, I set up a new custom matcher to clean up how we're testing export raw. I haven't updated the SecureRooms export raw spec yet. I wanted to make sure people liked this change first.
> [#134979] Add charge mode and invoice number to export raw

- db/schema.rb
- vendor/engines/c2po/app/services/purchase_order_account_builder.rb
- vendor/engines/c2po/app/views/facility_accounts/account_fields/_purchase_order_account.html.haml
- vendor/engines/c2po/app/views/facility_accounts/purchase_order_account/_show.html.haml
- vendor/engines/c2po/config/locales/en.yml
- vendor/engines/c2po/db/migrate/20170609131421_add_ar_number_to_accounts.rb
https://pm.tablexi.com/issues/136013
Similar structure to (https://github.com/tablexi/nucore-open/pull/1106) — the Dartmouth-specific part of the ticket are coming separately. (actually, I think they need to wait until this change gets merged down to Dartmouth)
> [#136013] New Field in PO

- app/views/facility_journals/_problem_transactions.html.haml
- config/locales/en.yml
- spec/features/creating_a_journal_spec.rb
- Make text change requested in https://pm.tablexi.com/issues/135657
> [#135657] text change for unjournalable download link

- app/controllers/facilities_controller.rb
- app/helpers/facilities_helper.rb
- app/presenters/nav_tab/link_collection.rb
- app/services/default_facility_homepage_redirector.rb
- app/views/facilities/list.html.haml
- app/views/shared/nav/_manage_facilities.html.haml
- config/routes.rb
- lib/ability.rb
- spec/controllers/facilities_controller_spec.rb
- spec/helpers/facilities_helper_spec.rb
- spec/services/default_facility_homepage_redirector_spec.rb
- Refactor logic for the "default" facility admin homepage path to allow it to be extended/overridden by school-specific engines
- https://pm.tablexi.com/issues/134990
- Accompanies https://github.com/tablexi/nucore-uic/pull/130
> [#134990] facility dash redirect

- app/controllers/application_controller.rb
- app/controllers/bundle_products_controller.rb
- app/controllers/facility_accounts_reconciliation_controller.rb
- app/controllers/facility_reservations_controller.rb
- app/controllers/price_group_products_controller.rb
- app/controllers/product_accessories_controller.rb
- app/controllers/products_common_controller.rb
- app/controllers/reservations_controller.rb
- app/controllers/surveys_controller.rb
- app/controllers/training_requests_controller.rb
- app/controllers/user_password_controller.rb
- app/controllers/users_controller.rb
- app/models/external_service/survey.rb
- app/models/instrument_price_policy.rb
- app/models/price_group.rb
- app/models/product.rb
- app/support/auto_logout.rb
- app/support/order_row_importer.rb
- app/support/product_approver.rb
- db/migrate/20100521172707_add_price_group_display_order.rb
- db/migrate/20110426221701_remove_reviewable_state.rb
- db/migrate/20111209185608_base_rate_rename.rb
- lib/tasks/order_details.rake
- spec/controller_spec_helper.rb
- spec/models/instrument_price_policy/zero_cost_order_spec.rb
- spec/models/instrument_price_policy_spec.rb
- spec/models/order_spec.rb
- spec/models/reservation_relay_support_spec.rb
- vendor/engines/c2po/spec/models/order_detail_spec.rb
- Prep codebase for Rails 5 by fixing deprecated dynamic finders
- https://pm.tablexi.com/issues/135931
> [#135931] fix deprecated finders

- app/models/order_detail.rb
- app/views/order_management/order_details/_shared_details.html.haml
- config/locales/en.models.yml
> [#98769] Add journal reference to order detail popup

- app/controllers/orders_controller.rb
- config/locales/en.yml
Cherry-pick from https://github.com/tablexi/nucore-nu/pull/278
> [#136043] Support HTML in order purchase errors

- app/models/product.rb
- app/views/admin/products/_product_fields.html.haml
- app/views/orders/_cart_row.html.haml
- app/views/products_common/manage.html.haml
- app/views/reservations/_account_field.html.haml
- config/locales/en.models.yml
- db/migrate/20170619213358_add_custom_note_field_label_to_product.rb
- db/schema.rb
- spec/features/placing_an_order_spec.rb
- spec/features/purchasing_a_reservation_spec.rb
Builds on #1111
* Adds an optional configurable label that will be displayed on the Note field to the user.
* Will only be displayed if the notes field is set to optional or required
* This also adds the required asterisk if the notes field is required
* If the label is set as blank, then it will fall back to "Note"
I still need to add a few tests, but this should generally be ready for a look.
> [#136739] Configurable user note field label

- app/models/order_detail.rb
- spec/transaction_search_shared_examples.rb
See https://github.com/tablexi/nucore-dartmouth/pull/114
> [#136521] Minor change to order detail so that it plays better with transaction search.

- app/controllers/bundle_products_controller.rb
- app/views/admin/products/_product_fields.html.haml
- app/views/admin/shared/_tabnav_product.html.haml
- app/views/products_common/manage.html.haml
- config/routes.rb
* Bundled products tab loses the tabs
* Fix "Docs" tab for bundles
* Remove "notes" field options for bundles
> [#136941] Bundle admin issues

- app/views/accounts/_member_table.html.haml
View hooks from Dartmouth https://github.com/tablexi/nucore-open/pull/1150, being pulled up into open
> [#136571] View Hooks for User Affiliations

- circle.yml
Hopefully, this will help us find timezone issues sooner.
> Do not use custom timezone for CI server config

- app/models/reports/instrument_day_report.rb
- spec/models/reports/instrument_day_report_spec.rb
UIC #137077
NU #137006
Same problem as #1139, but different report.
> [#137077, #137006] Instrument Util Actual Hours report crashes on problem res

- Gemfile
- Gemfile.lock
- https://pm.tablexi.com/issues/137110
> [#137110] update lograge

- Gemfile
- Gemfile.lock
- https://pm.tablexi.com/issues/137107
Prep for Rails 5
> [#137107] update delayed_job_active_record gem

- Gemfile
- Gemfile.lock
- https://pm.tablexi.com/issues/137104
> [#137104] update coffee-rails gem

- Gemfile
- config/environments/development.rb
- config/environments/test.rb
- https://pm.tablexi.com/issues/137108, quiet assets is now handled by sprockets
> [#137108] rm quiet assets

- spec/rails_helper.rb
Fix deprecation warnings for old style test helpers include.
> [#137321] fix devise test helpers include

- app/helpers/application_helper.rb
- app/models/order_status.rb
- app/models/reports/account_transactions_report.rb
- app/presenters/order_detail_presenter.rb
- app/views/facility_journals/_problem_transactions.html.haml
- app/views/facility_orders/_disputed_table.html.haml
- app/views/facility_orders/show.html.haml
- app/views/facility_reservations/index.html.haml
- app/views/global_search/_order_details.html.haml
- app/views/notifier/order_receipt.html.haml
- app/views/notifier/order_receipt.text.haml
- app/views/order_details/show.html.haml
- app/views/orders/receipt.html.haml
- app/views/reservations/_my_table.html.haml
- app/views/shared/_order_detail_cell.html.haml
- app/views/shared/_problem_order_details.html.haml
- app/views/shared/transactions/_table_inside.html.haml
- spec/helpers/application_helper_spec.rb
- spec/presenters/order_detail_presenter_spec.rb
Noticed these while doing some Rails 5 prep/gem upgrades. Seemed worth cleaning up.
Doing https://pm.tablexi.com/issues/137255 as well, while I'm at it.
> update deprecated calls

- app/assets/stylesheets/nucore.scss
- app/controllers/reservations_controller.rb
- app/views/facility_orders/show.html.haml
- config/initializers/mime_types.rb
- remove underscore from appearing around + icon
- allow facility staff "acting as" another user to download ical
> [#132894] ical link download fixes

- app/models/instrument_price_policy_calculations.rb
- spec/models/instrument_price_policy_calculations_spec.rb
Don't try to estimate reservation cost unless both reservation start and end times exist.
> [#137409] handle missing reserve end at

- README.md
Cherry picks from NU: https://github.com/tablexi/nucore-nu/pull/301
> Update oracle how-to link from readme

- app/controllers/facility_account_users_controller.rb
@jhanggi you had some context here--is this what was missing? were there other places we should be checking as well?
> [#137095] Log account_user events through facility

- lib/tasks/access_list.rake
File format:
`Product Name,Schedule Group Name,Username`
No headers
```
EPIC SEM Hitachi S-3400, ,abc123
EPIC SEM Hitachi S-3400,Evening & Weekend,xyz987
```
Run: `rake access_list:import[filename.csv]` for a dry run, and then
`rake access_list:import[filename.csv,true]` to run for real.
> [#137464] Rake task for importing access list from CSV

- app/models/product.rb
- config/settings.yml
Feature flag for timed services while feature is being worked on.
> [#137398] temp feature flag timed services

- app/models/product.rb
- config/settings.yml
- spec/features/admin/adding_to_an_order_spec.rb
Remove temporary feature flag added in #1211.
> rm timed services feature flag

- app/models/product.rb
Fix bug introduced in https://github.com/tablexi/nucore-open/pull/1217
> remove constant

- app/controllers/facilities_controller.rb
- app/controllers/user_preferences_controller.rb
- app/models/user.rb
- app/models/user_preference.rb
- app/models/user_preference_option.rb
- app/models/user_role.rb
- app/services/default_facility_homepage_redirector.rb
- app/views/shared/_header.html.haml
- app/views/user_preferences/edit.html.haml
- app/views/user_preferences/index.html.haml
- config/locales/en.models.yml
- config/locales/en.yml
- config/routes.rb
- db/migrate/20170829193038_create_user_preferences.rb
- db/schema.rb
- spec/factories/user_preferences.rb
- spec/services/default_facility_homepage_redirector_spec.rb
Companion PR to https://github.com/tablexi/nucore-uic/pull/151
> [#137455] user preferences

- lib/tasks/demo_seed.rake
Add facility administrator, account manager, senior staff to demo seed.
> add additional user roles to demo seed

- spec/controllers/facility_journals_controller_spec.rb
Fixes error in https://github.com/tablexi/nucore-dartmouth/pull/139
> explicitly set fiscal year feature setting in spec

- config/locales/en.models.yml
- config/locales/en.yml
https://pm.tablexi.com/issues/137630
> [#137630] rename admin reservation -> admin hold

- app/helpers/application_helper.rb
- config/settings.yml
All the schools now have this feature enabled, so let's make it always on.
> Remove responsive feature flag so it is always on

- app/presenters/nav_tab/global_link_collection.rb
Companion to https://github.com/tablexi/nucore-uic/pull/156/commits
> [#137512] refactor to allow cross-facility dash link injection from engine

- config/locales/en.yml
Bounceback on https://pm.tablexi.com/issues/139351
> [#139351] update timed services quantity message

- app/presenters/reservations/calendar_presenter.rb
- spec/app_support/reservations/rendering_spec.rb
Bounceback on https://pm.tablexi.com/issues/137630
> [#137630] instrument calendar displays as admin hold

- app/presenters/reservations/calendar_presenter.rb
- spec/app_support/reservations/rendering_spec.rb
- spec/models/reservation_spec.rb
Depends on https://github.com/tablexi/nucore-open/pull/1240, will rebase once that's merged.
> [#139062] created by display bounceback

- config/locales/en.models.yml
- https://pm.tablexi.com/issues/137631
> [#137631] update text for admin hold expiration

- Gemfile
- Gemfile.lock
- app/controllers/facility_reservations_controller.rb
- app/forms/admin_reservation_form.rb
- app/models/admin_reservation.rb
- app/models/recurrence.rb
- app/views/facility_reservations/_admin_reservation_repeat_fields.html.haml
- app/views/facility_reservations/new.html.haml
- config/locales/en.models.yml
- db/migrate/20171130224610_add_group_id_to_reservations.rb
- db/schema.rb
- spec/controllers/facility_reservations_controller_spec.rb
- spec/features/admin/creating_admin_reservation_spec.rb
- spec/forms/admin_reservation_form_spec.rb
- spec/models/recurrence_spec.rb
https://pm.tablexi.com/issues/126403
> [#126403] create multiple admin holds

- app/assets/javascripts/reservations.js
- app/controllers/facility_reservations_controller.rb
- app/views/facility_reservations/_admin_reservation_fields.html.haml
- app/views/facility_reservations/edit_admin.html.haml
- app/views/facility_reservations/new.html.haml
https://pm.tablexi.com/issues/139070
https://pm.tablexi.com/issues/139097
> [#139070] retroactive admin reservations

- app/models/order.rb
- app/models/order_detail.rb
- app/support/price_displayment.rb
- app/views/facility_orders/show.html.haml
- app/views/purchase_notifier/order_receipt.html.haml
- app/views/purchase_notifier/order_receipt.text.haml
- spec/factories/order_details.rb
- spec/models/order_spec.rb
https://pm.tablexi.com/issues/137694
> [#137694] email footer

- app/views/orders/_form.html.haml
Companion to https://github.com/tablexi/nucore-dartmouth/pull/154
> [#139682] use html to enable line breaks in i18n

- app/controllers/concerns/new_inprocess_controller.rb
- app/controllers/concerns/sortable_column_controller.rb
- app/controllers/facility_orders_controller.rb
- app/controllers/facility_reservations_controller.rb
- app/controllers/training_requests_controller.rb
- app/views/training_requests/index.html.haml
- spec/features/admin/managing_training_requests_spec.rb
- vendor/engines/secure_rooms/app/controllers/secure_rooms/facility_occupancies_controller.rb
https://pm.tablexi.com/issues/137157
> [#137157] training requests are sortable

- vendor/engines/bulk_email/app/assets/javascripts/bulk_email/bulk_email.js.coffee
- vendor/engines/bulk_email/app/services/bulk_email/recipient_searcher.rb
- vendor/engines/bulk_email/config/locales/en.yml
- vendor/engines/bulk_email/spec/controllers/bulk_email/bulk_email_controller_spec.rb
- vendor/engines/bulk_email/spec/features/bulk_emailer_searching_spec.rb
https://pm.tablexi.com/issues/137159
> [#137159] add training requested filter to bulk emailer

- app/views/orders/receipt.html.haml
https://pm.tablexi.com/issues/137633
> [#137633] Add accessories when backdating

- app/views/facility_reservations/_admin_reservation_fields.html.haml
https://pm.tablexi.com/issues/139952
> [#139952] ensure labels appear properly in all contexts

- spec/features/admin/managing_training_requests_spec.rb
Fix test failure when training request feature is turned off
https://github.com/tablexi/nucore-uic/pull/173
> enforce training request feature in spec

- vendor/engines/bulk_email/app/controllers/bulk_email/bulk_email_controller.rb
- vendor/engines/bulk_email/app/services/bulk_email/recipient_searcher.rb
UIC shouldn't see the option for bulk emailing users on the training request list, since they have that feature turned off.
> feature flag bulk email training request group

- app/assets/javascripts/app/manage_orders.coffee
- app/models/order_detail.rb
- app/models/reports/export_raw.rb
- app/services/order_details/param_updater.rb
- app/support/order_details/price_checker.rb
- app/views/order_management/order_details/_form.html.haml
- config/locales/en.models.yml
- config/settings.yml
- db/migrate/20180111200920_add_price_change_reason_to_order_details.rb
- db/schema.rb
- spec/controllers/order_management/order_details_controller_spec.rb
https://pm.tablexi.com/issues/137168
> [#137168] price change reason

- app/views/shared/_problem_order_details.html.haml
https://pm.tablexi.com/issues/137632
> [#137632] add 'add accessories' + to problem order table

- app/controllers/concerns/nav_tab.rb
- app/controllers/reports/export_raw_reports_controller.rb
- app/models/facility.rb
- app/models/reports/export_raw.rb
- app/views/facilities/list.html.haml
- config/settings.yml
- spec/models/reports/export_raw_spec.rb
- vendor/engines/secure_rooms/spec/models/reports/export_raw_spec.rb
- vendor/engines/split_accounts/spec/models/reports/export_raw_spec.rb
https://pm.tablexi.com/issues/139681
> [#139681] link to cross facility reports, fix export raw in cross facility

- Gemfile
- Gemfile.lock
https://pm.tablexi.com/issues/139851
> [#139851] Audit gemfile

- app/controllers/concerns/price_group_members_controller.rb
- app/models/price_group.rb
- app/views/price_groups/_accounts.html.haml
- app/views/price_groups/_users.html.haml
- app/views/price_groups/show.html.haml
- config/settings.yml
- spec/controllers/account_price_group_members_controller_spec.rb
- spec/controllers/order_management/order_details_controller_spec.rb
https://pm.tablexi.com/issues/102967
> [#102967] feature gate global price group management

- config/settings.yml
Dartmouth and NU should have true, UIC should have false.
> switch default for can_manage_global_price_groups to true

- Gemfile
- Gemfile.lock
I don't think we actually use the test-unit gem.
> rm test unit

- spec/features/admin/managing_user_spec.rb
- spec/models/reports/export_raw_spec.rb
Specs were fragile, failing on Dartmouth: https://circleci.com/gh/tablexi/nucore-dartmouth/815?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
> make specs less fragile

- spec/features/admin/managing_user_spec.rb
Fix spec failure in UIC: 
https://circleci.com/gh/tablexi/nucore-uic/731?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
> fix feature setting in spec

- app/models/instrument.rb
- app/models/order_detail.rb
- app/support/order_details/price_checker.rb
- config/settings.yml
- vendor/engines/secure_rooms/app/models/secure_room.rb
- vendor/engines/secure_rooms/spec/features/admin_edit_occupancy_spec.rb
Need to deep-dup occupancy as well as reservation for pricing calculations.
> [#140081] Fix occupancy price change reason bug

- app/models/product.rb
Add a space between the words "Secure" and "Rooms" on the individual User "Access List" page
> [#139827] use humanized name for grouping

- app/controllers/training_requests_controller.rb
- app/mailers/training_request_mailer.rb
- app/views/training_request_mailer/notify_facility_staff.html.haml
- app/views/training_request_mailer/notify_facility_staff.text.erb
- config/locales/en.yml
- config/locales/views/en.training_requests.yml
- lib/nucore.rb
- spec/mailers/previews/training_request_mailer_preview.rb
* Change to use GlobalID
* Share markdown between text and HTML emails
* Add a way to get a random item from the database
> [#139481] Add email address to training request notification

- app/controllers/global_search_controller.rb
- app/models/product.rb
- app/services/global_search/product_searcher.rb
- app/views/global_search/_products.html.haml
- config/locales/en.yml
- spec/services/global_search/product_searcher_spec.rb
Search on product name.
Searching on "example":
Searching "scope" against Dartmouth data:
> [#140077] product name search

- .rubocop_todo.yml
- Gemfile.lock
- app/controllers/order_management/order_details_controller.rb
- app/models/order.rb
- app/models/price_policy.rb
- app/support/accessories/update_response.rb
- spec/controller_spec_helper.rb
Rubocop: Fix Lint/AmbiguousOperator violations
> Update rubocop name and do a little linting

- app/controllers/account_users_controller.rb
- app/controllers/bundle_products_controller.rb
- app/controllers/facility_account_users_controller.rb
- app/controllers/facility_facility_accounts_controller.rb
https://pm.tablexi.com/issues/140237
> Strong params part 2

- app/controllers/facilities_controller.rb
- app/helpers/reassign_chart_strings_helper.rb
- app/views/facilities/confirm_transactions.html.haml
- app/views/facilities/movable_transactions.html.haml
- app/views/facilities/reassign_chart_strings.html.haml
- config/locales/en.yml
- spec/controllers/facilities_controller_spec.rb
- spec/features/admin/moving_transactions_spec.rb
* Add feature spec
* Lint haml
* Fix some strings to be more consistent with other pages (e.g. labeling accounts as "Payment Source")
* Get rid of TransactionSearch metaprogramming
> [#140402] Replace movable_transactions with newer filtering

- app/controllers/products_common_controller.rb
- config/application.rb
- config/environments/development.rb
- spec/controllers/facility_accounts_controller_spec.rb
- spec/controllers/facility_facility_accounts_controller_spec.rb
- spec/controllers/instruments_controller_spec.rb
- spec/controllers/users_controller_spec.rb
- spec/services/account_builder_spec.rb
https://pm.tablexi.com/issues/140237
> [#140237] Strong params

- Gemfile.lock
ref: https://github.com/onelogin/ruby-saml/commit/048a544730930f86e46804387a6b6fad50d8176f
> Upgrade ruby-saml gem for security warning.

- spec/controllers/global_search_controller_spec.rb
Fix sporadically failing test. Example: https://circleci.com/gh/tablexi/nucore-open/5517
> [#140353] replace problematic test

- app/controllers/global_search_controller.rb
- app/views/shared/_nav.html.haml
- app/views/shared/nav/_nav_links.html.haml
- spec/controllers/global_search_controller_spec.rb
https://pm.tablexi.com/issues/140080
> [#140080] enable product search without logging in or when acting as

- app/controllers/api/order_details_controller.rb
- config/initializers/add_settings_overrides.rb
- config/initializers/devise.rb
- config/secrets.yml.template
- config/settings/development.yml
- config/settings/override.yml
- config/settings/stage.yml
- vendor/engines/secure_rooms/app/controllers/secure_rooms_api/api_controller.rb
- vendor/engines/secure_rooms/spec/controllers/secure_rooms_api/events_controller_spec.rb
- vendor/engines/secure_rooms/spec/controllers/secure_rooms_api/scans_controller_spec.rb
- vendor/engines/secure_rooms/spec/features/scanning_in_and_out_spec.rb
TECH TASK: Continue work on reorganizing secrets/settings.
> Fix cap deploy on stage

- Gemfile.lock
- config/deploy.rb
TECH TASK: Update a gem version that is no longer available, remove unneeded reference to settings.local.yml
> bundle update parser, remove settings.local.yml from linked files

- config/settings.yml
- vendor/engines/saml_authentication/lib/saml_authentication/devise_configurator.rb
- vendor/engines/saml_authentication/spec/controllers/saml_authentication/sessions_controller_spec.rb
Feature flag new user creation/updating via SAML.
> [#140997] feature flag saml create/update user

- app/controllers/facilities_controller.rb
- app/views/facilities/disputed_orders.html.haml
- app/views/facility_notifications/index.html.haml
- spec/controllers/facilities_controller_spec.rb
- spec/features/admin/disputed_orders_search_spec.rb
Replace old filtering functionality with newer code on disputed orders page.
> [#140403] replace filtering disputed orders

- app/assets/stylesheets/application.scss
Fix "X" display issue on multi-select filters.
Hopefully, this is a temporary fix until the next release of chosen-rails. cf https://github.com/tsechingho/chosen-rails/issues/97
> [#141446] Fix display issue with "X" in chosen selectors

- app/controllers/facility_journals_controller.rb
- app/controllers/facility_statements_controller.rb
- app/views/facility_journals/index.html.haml
- app/views/facility_journals/new.html.haml
- app/views/facility_statements/new.html.haml
- config/locales/en.yml
- spec/controllers/facility_journals_controller_spec.rb
- spec/controllers/facility_statements_controller_spec.rb
- spec/features/admin/facility_journals_search_spec.rb
- spec/features/admin/facility_statements_search_spec.rb
Replace filtering code in journals/statements tabs with newer, more maintainable standard.
> [#140404] Replace filtering in journals/statements tabs

- app/controllers/transactions_controller.rb
- app/views/shared/transactions/_in_review.html.haml
- spec/controllers/transactions_controller_spec.rb
- spec/features/transactions_search_spec.rb
Replace filtering code with newer paradigm for the My Transactions/In Review page.
> [#141487] replace filtering for my transactions in review

- app/inputs/transaction_chosen_old_input.rb
Update placeholder text for bulk email filtering.
> [#139182] update placeholder text

- config/locales/views/en.reservations.yml
> [#137478] update hint text

- app/controllers/facilities_controller.rb
- app/controllers/transactions_controller.rb
Fix bug where CSV export failed for the My Transactions view, as well as the All Transactions view in the billing tab.
> [#141677] fix csv export error when module is not included

- Gemfile
- Gemfile.lock
- app/helpers/application_helper.rb
- app/models/order_import.rb
- app/presenters/view_hook.rb
- app/views/facility_journals/_problem_transactions.html.haml
- app/views/facility_orders/index.html.haml
- app/views/facility_orders/show_problems.html.haml
- app/views/facility_reservations/index.html.haml
- app/views/facility_reservations/show_problems.html.haml
- app/views/shared/transactions/_table.html.haml
- config/application.rb
- spec/helpers/view_hook_helper_spec.rb
- spec/models/instrument_spec.rb
- spec/models/journal_spec.rb
- spec/models/order_import_spec.rb
- spec/models/price_policy_spec.rb
- vendor/engines/bulk_email/app/helpers/bulk_email/application_helper.rb
- vendor/engines/c2po/spec/controllers/facility_accounts_controller_spec.rb
- vendor/engines/secure_rooms/app/views/secure_rooms/facility_occupancies/index.html.haml
- vendor/engines/secure_rooms/app/views/secure_rooms/facility_occupancies/show_problems.html.haml
TECH TASK: Updates to make the codebase compatible with future upgrade to Rails 5.0.7.
> Rails 4 compatible 5.0 prep

- Gemfile
- Gemfile.lock
- README.md
- circle.yml
TECH TASK: Simplify management of Oracle-related gems
> Remove :oracle group from Gemfile

- lib/ability.rb
- spec/features/admin/managing_user_spec.rb
- spec/lib/ability_spec.rb
Remove ability for account managers to edit user details
> [#141837] Remove ability for account managers to edit user details

- Gemfile.lock
- app/controllers/product_accessories_controller.rb
- app/views/notifier/new_user.html.haml
- app/views/notifier/new_user.text.erb
- spec/controllers/product_accessories_controller_spec.rb
Backport #1594, #1595, and #1598 to the Rails 4.2 branch.
> Backport #1594, #1595, and #1598 to the Rails 4.2 branch

- app/assets/javascripts/app/calendar.js.coffee
- app/models/order_detail.rb
- app/support/reservations/relay_support.rb
- app/views/facility_reservations/edit.html.haml
- app/views/facility_reservations/edit_admin.html.haml
- app/views/facility_reservations/show.html.haml
- spec/models/order_detail_spec.rb
- spec/models/reservation_spec.rb
Backports the fixes for tickets #136143 and #139111 into the Rails 4.2 branch so they can be applied for NU.
> Backport PRs #1596, #1600, and #1601 into Rails 4.2 branch

- app/controllers/product_accessories_controller.rb
- spec/controllers/product_accessories_controller_spec.rb
Do not exclude hidden products from accessories dropdown (fix for #1594)
> [#139184] Do not exclude hidden products from accessories dropdown

- app/controllers/product_accessories_controller.rb
- spec/controllers/product_accessories_controller_spec.rb
Backport #1604 to Rails 4.2 branch.
> Backport #1604 to Rails 4.2

- vendor/engines/saml_authentication/README.md
Add README instructions for generating a certificate for SAML configuration.
> [#142508] Add instructions for creating a certificate for SAML

- app/helpers/application_helper.rb
- app/helpers/facility_reservations_helper.rb
- app/helpers/order_statuses_helper.rb
- app/helpers/reports_helper.rb
TECH TASK: Remove unused methods from helpers
While working on #137154, I ran into a couple of unused methods in our helpers. That prompted me to take a look if there any more, and I quickly found the bunch that this PR removes! None of these are called anywhere that I could find.
> Remove unused methods from helpers

- lib/tasks/price_policies.rake
Fixes an issue in #1621 where it was not including hidden services.
> Include hidden services when copying over price policies

- Gemfile.lock
- spec/factories.rb
- vendor/engines/bulk_email/spec/factories/bulk_email/jobs.rb
- vendor/engines/c2po/spec/factories.rb
- vendor/engines/projects/spec/factories/projects.rb
- vendor/engines/sanger_sequencing/spec/factories/batches.rb
- vendor/engines/sanger_sequencing/spec/factories/product_groups.rb
- vendor/engines/secure_rooms/spec/factories/card_reader.rb
- vendor/engines/secure_rooms/spec/factories/event.rb
- vendor/engines/secure_rooms/spec/factories/secure_rooms_price_policies.rb
- vendor/engines/split_accounts/spec/factories/split_accounts.rb
- vendor/engines/split_accounts/spec/factories/splits.rb
Tech task: Update FactoryBot definitions to use dynamic attributes. Continues on from https://github.com/tablexi/nucore-open/pull/1656
Also contains https://github.com/tablexi/nucore-open/pull/1655
> Fix factory bot in engines

- app/controllers/product_notifications_controller.rb
Fix error when submitting product notifications tab with an invalid value.
> [#143505] Fix rendering error on invalid product notifications

- spec/models/instrument_spec.rb
TECH TASK: Fix specs in instrument_spec that relied on edge-case time comparisons
Non-NU specific changes that came up during their Rails 5 upgrade.
> Fix specs in instrument_spec that relied on edge-case time comparisons

- app/models/concerns/products/scheduling_support.rb
- app/models/instrument.rb
- vendor/engines/secure_rooms/app/models/secure_room.rb
TECH TASK: Remove unused methods
I ran into these unused fellows, so I got rid of them!
> Remove unused methods (2018-11-02)

- app/models/product.rb
- app/models/schedule.rb
- app/views/instruments/_instrument_fields.html.haml
TECH TASK: Refactor scopes on Schedule
I ran into these and noticed they can be simpler by using ActiveRecord built-ins (and the existing query was unnecessarily taxing by including a GROUP BY clause when no aggregation is needed), so I refactored them!
> Refactor scopes on Schedule

- app/models/account.rb
- app/models/chart_string_reassignment_form.rb
- app/models/instrument.rb
- app/models/order_detail.rb
- app/models/price_group_product.rb
- app/presenters/order_detail_presenter.rb
- lib/nucore.rb
- lib/tasks/demo_seed.rake
- spec/controller_spec_helper.rb
- spec/controllers/affiliates_controller_spec.rb
- spec/controllers/facility_order_details_controller_spec.rb
- spec/controllers/reports/instrument_day_reports_controller_spec.rb
- spec/controllers/reports/instrument_reports_controller_spec.rb
- spec/report_spec_helper.rb
- spec/support/helper_methods.rb
- vendor/engines/ldap_authentication/spec/ldap_authentication/user_updater_spec.rb
TECH TASK: Remove unused methods (2018-11-15 edition)
I found several more unused methods in NUCore, so this PR removes today’s batch!
> Remove unused methods (2018-11-15 edition)

- spec/rails_helper.rb
Tech task: Improve stack traces in failing tests by filtering out irrelevant lines.
* Filter out all rails gems
* Leave out `rails_helper` lines that were included even when `billing_review_period` and `feature_setting` tags were not present
There are probably a couple other gems we could filter by default, but this gets the big ones that were causing me noise.
> Improve stack traces in failing tests

- app/assets/stylesheets/nucore-variables.scss
- app/assets/stylesheets/nucore.scss
The UCONN redesign for tables.
> Use-Manage Table

- app/assets/stylesheets/nucore.scss
Give forms and inputs UCONN design.
> Use-Manage Form

- vendor/engines/secure_rooms/app/services/secure_rooms/access_handlers/occupancy_handler.rb
- vendor/engines/secure_rooms/app/services/secure_rooms/access_handlers/order_handler.rb
- vendor/engines/secure_rooms/app/services/secure_rooms/access_manager.rb
- vendor/engines/secure_rooms/spec/services/secure_rooms/access_handlers/order_handler_spec.rb
Fix completion of occupancies when a user scans out after the schedule’s end
> [#144074] Some Occupancies remain "In Progress"

- app/assets/stylesheets/app/product_list.scss
- app/controllers/facilities_controller.rb
- app/views/facilities/show.html.haml
- spec/features/purchasing_a_reservation_on_behalf_of_spec.rb
- spec/features/purchasing_a_reservation_spec.rb
Duplicate Create Button at top of Facility Home Page
> [#139380] Duplicate Create Button at top of Facility Home Page

- config/locales/views/en.instrument_issues.yml
Improve "Report an Issue" wording on form and email to facility.
Changes per NU feedback.
> [#137686] Improve "Report an Issue" wording

- vendor/engines/split_accounts/spec/models/reports/export_raw_spec.rb
Tech task: rubocop split_accounts export raw spec
Not sure how this just started showing up in codeclimate.
> Tech task: rubocop split_accounts export raw spec

- .github/CODEOWNERS
Add [GitHub code owners](https://help.github.com/articles/about-code-owners/)
Saves us a few clicks by automatically requesting reviews from all three of us on pull requests.
> Add GitHub code owners

- app/helpers/accounts_helper.rb
- app/views/admin/shared/_tabnav_payment_method.html.haml
- spec/controllers/facility_accounts_controller_spec.rb
Fix PO page when multi_facility_accounts is turned off
> [#147756] Fix PO page when multi_facility_accounts is turned off

- Gemfile.lock
> Update shoulda-matchers to 4.0.1

- README.md
Fix #1882 by updating the link to oracle documentation.
Optional.
> [#1882] Updated link to oracle doc in README

- lib/tasks/demo_seed.rake
Seed user_senior_staff and user_student were same user.  make them different users.
> Fix conflicting users in seed data

- app/presenters/nav_tab/link_collection.rb
Change Default Landing Page for Billing
> [#148408] Change Default Landing Page for Billing

- app/models/facility.rb
- spec/models/order_spec.rb
Remove unused association method order_details#accounts
> Remove unused association method order_details#accounts

- app/models/reports/export_raw.rb
Include billable minutes in export raw
> [#142338] Include billable minutes in export raw

- app/mailers/notifier.rb
- app/views/notifier/order_detail_status_changed.html.erb
- app/views/notifier/order_detail_status_changed.text.erb
Update subject and body of email for order status change
> [#146050] Update subject and body of email for order status change

- app/views/notifier/order_detail_status_changed.text.erb
Fix typo in text version of email
> [#146050] Fix typo in text version of email

- vendor/engines/bulk_email/app/services/bulk_email/content_generator.rb
- vendor/engines/bulk_email/app/views/bulk_email/bulk_email/create.html.haml
- vendor/engines/bulk_email/config/locales/en.yml
- vendor/engines/bulk_email/spec/models/bulk_email/delivery_form_spec.rb
- vendor/engines/bulk_email/spec/services/bulk_email/content_generator_spec.rb
Remove unneeded footer from bulk email.
> [#140481] remove footer from bulk email

- app/controllers/concerns/nav_tab.rb
- app/presenters/nav_tab/link_collection.rb
- app/views/accounts/index.html.haml
- config/locales/en.yml
- config/locales/views/en.accounts.yml
- spec/features/disputing_an_order_spec.rb
Move a link to Transactions In Review into nav under My Payment Sources
> [#141584] move transactions in review into nav

- spec/models/price_policy_spec.rb
Fix failing spec due to now being in fiscal year 2020.
We're now in fiscal year 2020, so a test was failing because it was hard coded
to mean 2020 was in the future.
> Fix spec broken by passing the fiscal year boundry

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
Remove gem for now-unused Code Climate
> Remove gem for now-unused Code Climate

- vendor/engines/saml_authentication/config/initializers/saml_log_subscriber.rb
- vendor/engines/saml_authentication/lib/saml_authentication/devise_configurator.rb
- vendor/engines/saml_authentication/lib/saml_authentication/saml_attributes.rb
- vendor/engines/saml_authentication/lib/saml_authentication/user_locator.rb
- vendor/engines/saml_authentication/spec/lib/saml_authentication/saml_attributes_spec.rb
- vendor/engines/saml_authentication/spec/lib/saml_authentication/user_locator_spec.rb
- vendor/engines/saml_authentication/spec/saml_spec_helper.rb
- vendor/engines/saml_authentication/spec/support/shared_contexts/saml_response_shared_context.rb
Add more logging to the SAML engine for debugging purposes
> Add additional SAML logging

- vendor/engines/saml_authentication/README.md
- vendor/engines/saml_authentication/lib/saml_authentication/devise_configurator.rb
Update SAML Readme based on findings from UMass implementation. This also adds a tiny bit of logging on startup.
> Improve SAML setup instructions

- app/models/reports/export_raw.rb
- spec/models/reports/export_raw_spec.rb
Update headers/text for problem resolution fields in export raw.
Update column header to "Problem Description" and humanize `missing_actuals`.
> [#146482] Fix text for problem resolution fields in export raw

- app/views/order_management/order_details/files.html.haml
- config/locales/en.yml
Adds a link to "Download all as zip" from the file selector modal.
> [#144526] Add link to download results as zip file

- app/mailers/notifier.rb
- app/models/account.rb
- app/support/notification_sender.rb
- app/views/notifier/review_orders.html.haml
- app/views/notifier/review_orders.text.erb
- config/locales/en.notifier.yml
- spec/app_support/notification_sender_spec.rb
- spec/mailers/notifier_spec.rb
- spec/mailers/previews/notifier_preview.rb
- vendor/engines/c2po/app/models/purchase_order_account.rb
Update text of "send notifications" email.
> [#149133] Update send notifications text

- app/models/timed_service_price_policy.rb
- spec/factories/price_policies.rb
- spec/models/reports/export_raw_spec.rb
In the Raw Export for “Timed Services”, the “Charge For” column will populate with  “Minutes”
> [#151208] Export Raw "Timed Services" enhancement

- app/views/facilities/_facility_fields.html.haml
- app/views/facilities/manage.html.haml
- config/locales/views/admin/en.facilities.yml
Update label for enabling the instrument dashboard.
See #2205 for the original implementation.
> [#148698] Update instrument dashboard label

- app/controllers/facility_journals_controller.rb
- app/views/facility_journals/index.html.haml
- config/locales/en.yml
Remove "There is a pending journal, but you don't have rights to manage it" message from the Manage Journals Index. 
Pending journals will only come up on the first page of the Manage Journals Index
> [#137504] Manage Journals-Pending Journal Banner Message

- app/controllers/order_details_controller.rb
- app/models/order_detail.rb
- app/services/log_event_searcher.rb
- app/services/order_details/dispute_resolved_notifier.rb
- app/services/order_details/param_updater.rb
- config/locales/views/admin/en.log_events.yml
- spec/controllers/order_details_controller_spec.rb
- spec/services/log_event_searcher_spec.rb
- spec/services/order_details/dispute_resolved_notifier_spec.rb
Log the following event: Who/when someone disputes and resolve an order
> [#152869] Log resolve disputed order

- app/controllers/facility_notifications_controller.rb
- app/models/order_detail.rb
- app/services/log_event_searcher.rb
- app/support/notification_sender.rb
- config/locales/views/admin/en.log_events.yml
- spec/controllers/facility_notifications_controller_spec.rb
Log the following event: Who/when someone sends the billing notifications (record each order)
> [#152869] Log send billing notification

- app/controllers/facility_notifications_controller.rb
- app/services/log_event_searcher.rb
- app/support/notification_sender.rb
- config/locales/views/admin/en.log_events.yml
- spec/controllers/facility_notifications_controller_spec.rb
Log the following event:  Who/when someone Marks an Order as Reviewed (record each order)
> [#152869] Log mark as review order

- app/services/log_event_searcher.rb
- app/services/order_details/param_updater.rb
- config/locales/views/admin/en.log_events.yml
- spec/controllers/order_management/order_details_controller_spec.rb
Log the following event: Who/when someone manually reprices an Order
> [#152869] Log when a price is manually change

- app/models/order_detail.rb
- app/services/order_details/dispute_resolved_notifier.rb
- spec/services/order_details/dispute_resolved_notifier_spec.rb
- spec/system/admin/manage_order_detail_spec.rb
Fix issue with logging and notifying orders with accessories
> Dispute resolution logging

- app/controllers/price_groups_controller.rb
- app/models/price_group.rb
- app/services/log_event_searcher.rb
- config/locales/views/admin/en.log_events.yml
- db/migrate/20200514131654_add_soft_delete_to_price_group.rb
- db/migrate/20200514155649_remove_unique_index_price_group.rb
- db/schema.rb
- spec/controllers/price_groups_controller_spec.rb
- spec/models/price_group_spec.rb
- spec/system/admin/price_group_management_spec.rb
Log the following event: Price group gets created or deleted
Adds soft delete to PriceGroup and also adds an irreversible migration to avoid issues with duplication
> [#152869] Log creation of price group

- app/controllers/relays_activations_controller.rb
- app/services/log_event_searcher.rb
- config/initializers/notifications.rb
- config/locales/views/admin/en.log_events.yml
- spec/controllers/relays_activations_controller_spec.rb
Log the following event: Who/when the Relay Tool is used
Add Rollbar report to ActiveSupport::Notifications
> [#152869] Log relay tool use

- app/controllers/concerns/price_group_members_controller.rb
- app/models/price_group_member.rb
- app/services/log_event_searcher.rb
- config/locales/views/admin/en.log_events.yml
- db/migrate/20200519230633_add_soft_delete_to_price_group_member.rb
- db/schema.rb
- spec/models/price_group_spec.rb
- spec/presenters/statement_presenter_spec.rb
- spec/system/admin/price_group_management_spec.rb
Log the following event: Who/when someone added a user to a price group
> #[152869] Log when a user gets added or removed from a price group

- app/controllers/concerns/csv_email_action.rb
- app/controllers/concerns/order_details_csv_export.rb
- app/controllers/facility_accounts_controller.rb
- app/controllers/facility_statements_controller.rb
- app/controllers/log_events_controller.rb
- app/controllers/reports/csv_export_controller.rb
- app/models/concerns/reports/csv_exporter.rb
- app/models/reports/log_events_report.rb
- app/views/log_events/index.html.haml
Add the ability to export the audit log (with filtering) to CSV.
> [#153049] Export audit log to CSV

- app/helpers/log_events_helper.rb
- app/services/log_event_searcher.rb
- app/views/log_events/index.html.haml
[Alphabetize the audit log](https://pm.tablexi.com/issues/153851)
> [#153851] Sort log event options alphabetically

- app/services/order_row_importer.rb
- config/locales/services/en.order_row_importer.yml
- spec/files/order_imports/blank.csv
- spec/files/order_imports/first_od_error.csv
- spec/files/order_imports/second_od_error.csv
- spec/models/order_import_csv_spec.rb
- spec/models/order_import_spec.rb
- spec/services/order_row_importer_spec.rb
Add the Reference ID field to the bulk import flow.
https://pm.tablexi.com/issues/152870
> [#152870] Add Reference ID to bulk import

- public/templates/bulk_import_template.csv
Add new Reference ID header to template for bulk imports
https://pm.tablexi.com/issues/152870
> [#152870] Add new header to template for bulk imports

- public/templates/bulk_import_template.csv
The template should have "Reference ID" in the header.
https://pm.tablexi.com/issues/152870
> [#152870] Fix typo

- lib/tasks/users.rake
Tech task: Fix documentation for internal-external user conversion task
I think the comments were copy/pasted from the external_to_internal comments.
> Tech task: Fix documentation for internal-external user conversion task

- config/initializers/sanitized_allowed.rb
- config/initializers/sanitizer.rb
Tech task: Update sanitizer configuration
This will allow it to work on Rails 6.
> Tech task: Update sanitizer configuration

- app/models/reports/log_events_report.rb
Adds the new facility column to the csv report for log events.
> [#153876] Add facility column to csv report for log events

- bin/merge_describer
PR numbers in the thousands are from nucore-open, in the hundreds and below are from the forks.  At the moment NU has the most PRs, with almost 600, so I think this will last us a while.
> TECH TASK: Update merge_describer script

- config/database.yml.oracle.template
Cleans up a bit of duplicated logic
> Tech Task: Clean up oracle config

- .circleci/config.yml
- .gitignore
- README.md
- app/models/concerns/downloadable_file.rb
- config/database.yml.mysql.template
- config/database.yml.oracle.template
- config/initializers/paperclip.rb
- doc/migrating_to_s3.md
A couple of small fixes were made directly to the Dartmouth fork, this is pulling them into open.
Also:
- Remove references to fog
- Update README
- Update gitignore
- Update db templates
> Tech Task: Update paperclip config for aws-sdk-s3

- config/locales/views/admin/en.instrument_schedule_positions.yml
> [#153890] Update helper text

- README.md
- doc/HOWTO_oracle.md
Update the readme for Oracle db to explain usage with docker compose.
> Tech Task: Update readme for oracle setup

- app/views/facilities/index.html.haml
- config/locales/views/en.facilities.yml
- doc/coding_standards.md
Adds a view hook for adding helper text to the welcome page.
> Add view hook for welcome helper text

- app/controllers/users_controller.rb
- app/views/users/edit.html.haml
- app/views/users/new_external.html.haml
- app/views/users/show.html.haml
In support of https://github.com/tablexi/nucore-nu/pull/598
> [#155189] Add hooks for additional user fields

- vendor/engines/ldap_authentication/lib/tasks/ldap_authentication.rake
It is possible that some users may be missing email or other required attributes in the LDAP response.  When updating all unexpired users with this rake task, we want to log the errors and keep going.
The error I saw while testing on staging is:
`NoMethodError (undefined method 'mail' for #<Net::LDAP::Entry:0x000000000b71b398>)`
> Handle missing attributes when updating from LDAP

- app/models/reports/export_raw.rb
- app/presenters/order_detail_notice_presenter.rb
- spec/models/reports/export_raw_spec.rb
- spec/presenters/order_detail_notice_presenter_spec.rb
Add notice badges to the export raw report
> [#155217] Add notices to export raw report

- app/controllers/transactions_controller.rb
- app/services/transaction_search/searcher.rb
- app/views/shared/transactions/_in_review.html.haml
- config/locales/en.yml
- config/routes.rb
- spec/controllers/transactions_controller_spec.rb
Adds the Mark as Reviewed button to the My Transactions in Review page
> [#154524] Add Mark as Reviewed button to My Transactions in Review page

- app/views/order_imports/new.html.haml
- config/locales/views/admin/en.order_imports.yml
Updates to helper text for clarity, and also adds a link to the import template where it is mentioned in the text.
> [#155388] Update bulk import helper text

- app/controllers/facilities_controller.rb
- app/controllers/kiosk_reservations_controller.rb
- app/models/facility.rb
- app/views/facilities/_facility_fields.html.haml
- app/views/facilities/manage.html.haml
- app/views/facility_reservations/timeline.html.haml
- config/locales/views/admin/en.facilities.yml
- db/migrate/20200904185502_add_position_to_schedules.rb
- db/migrate/20210129224222_add_kiosk_enabled_to_facilities.rb
- db/schema.rb
- spec/system/admin/launch_kiosk_view_spec.rb
- spec/system/kiosk_view_spec.rb
Allow toggling the kiosk view on or off per facility.
> Configure kiosk view per facility

- app/services/users/auth_checker.rb
- config/settings.yml
- spec/rails_helper.rb
- spec/services/users/auth_checker_spec.rb
- spec/system/kiosk_view_spec.rb
- vendor/engines/ldap_authentication/README.md
Only NU uses LDAP authentication.
> [#152645] Handle LDAP auth when LdapAuthentication gem isn't installed

- spec/services/users/auth_checker_spec.rb
- spec/system/kiosk_view_spec.rb
Update specs for kiosk mode with the `bypass_kiosk_auth` flag set true and false.
> [#155874] Update specs

- config/locales/views/en.kiosk_reservations.yml
The Kiosk View page should have a more user friendly title :)
> [#155874] Update page title to Upcoming Reservations

- app/views/facility_accounts/show.html.haml
- vendor/engines/c2po/app/views/c2po/facility_accounts/show/_additional_account_fields.html.haml
- vendor/engines/c2po/app/views/c2po/facility_accounts/show/_remittance_information.html.haml
- vendor/engines/c2po/app/views/facility_accounts/credit_card_account/_show.html.haml
- vendor/engines/c2po/app/views/facility_accounts/purchase_order_account/_show.html.haml
- vendor/engines/c2po/lib/c2po.rb
Using a ViewHook here for consistency.
> [#153934] Use a view hook instead of dynamic template lookup

- app/helpers/application_helper.rb
- config/locales/en.yml
These translations were removed in https://github.com/tablexi/nucore-open/commit/6807769fdc11c5298a8947dd051e27d85a6517f4#diff-0965c1160f97e672fd80602e1204a1c216266722e449bbd84d955fe43dd2a722L19
> Tech task: clean up

- app/controllers/facility_account_users_controller.rb
- app/mailers/notifier.rb
- app/views/notifier/user_update.html.haml
- app/views/notifier/user_update.text.erb
- config/locales/en.notifier.yml
- spec/controllers/facility_account_users_controller_spec.rb
- spec/mailers/notifier_spec.rb
- spec/mailers/previews/notifier_preview.rb
Also send the email to BusinessAdmins associated with an account.
> [151925] Adjust Subject and body of AccountUser email.

- lib/tasks/demo_seed.rake
Different schools have different default values, and 75340 fails validations for some schools
> Tech Task: Update seed file

- app/services/order_details/param_updater.rb
This logging was added as part of #2497.  The problem there was that if a user enters "0" for the actual duration, the reservation would silently fail validations and the order detail would move out of the problem queue (which it shouldn't).  I added this logging to try to understand why reservations are failing, but I don't think this provides much value since #2497 prevents silent failures.
> Tech Task: Remove temporary logging

- Gemfile.lock
- app/models/user.rb
- config/initializers/devise.rb
- config/locales/views/admin/en.log_events.yml
- config/locales/views/en.devise.yml
- db/migrate/20210323212200_add_lockable_to_users.rb
- db/schema.rb
https://pm.tablexi.com/issues/155426
- Devise set up for locking accounts with custom error message
- Set User as lockable
- Create LogEvent when User becomes locked
> [#155426] Lockout password-based user after 5 failed login attempts

- app/controllers/product_users_controller.rb
- app/models/reports/instrument_access_list_export_raw.rb
- app/models/reports/product_access_list_csv_report.rb
- app/views/product_users/_table.html.haml
- app/views/product_users/index.html.haml
- app/views/users/access_list.html.haml
- config/locales/en.yml
- spec/models/reports/product_access_list_csv_report_spec.rb
- spec/system/admin/user_access_list_spec.rb
Creates a new Report that is a CSV export for data about Product Access lists and send it to the email address supplied by the user.  Importing Product Access Lists will come in a follow up PR.
> [#142305] New Product Access List CSV export

- app/forms/user_form.rb
- app/views/users/new_external.html.haml
- config/locales/en.yml
Sets the stage for further refactoring for consistency between Dartmouth, NU and UMass.
> [#157512] Refactor new external flow

- spec/system/admin/facility_statements_spec.rb
Otherwise this spec will fail for schools that have the feature flag switched off.
> Add feature flag to spec

- app/models/timed_service_price_policy.rb
Supports https://github.com/tablexi/nucore-dartmouth/pull/359
> [#157227] Don't attempt to calculate costs without a usage_rate

- app/models/holiday.rb
- config/locales/en.yml
Updates a scope to be Oracle-friendly.  
Also makes the caption a bit broader and puts more detail info in hint text at the bottom of the page.
> [#142306] Update future scope and helper text

- README.md
- doc/coding_standards.md
> Tech task: Add note about using dependabot

- doc/HOWTO_external_services.md
Adding some notes on working with Form.io
> [#157154] Add documentation for form.io integration

- app/views/order_management/order_details/_split_costs.html.haml
>  [#155286] Clean up table markup

- app/views/layouts/formio.html.haml
Binging the fix from nucore-nu upstream
> Fix form.io asset urls

- config/locales/en.models.yml
- config/locales/en.yml
There was confusion about the connection between the cancellation fee and the cancellation window. Updated copy to make it more clear they are related.
> [#157429] Updates copy to clarify how cancellation fees work

- README.md
- app/models/order_status.rb
- config/database.yml.oracle.template
- spec/rails_helper.rb
- spec/teaspoon_env.rb
Bringing a few small test suite improvements upstream from https://github.com/tablexi/nucore-nu/pull/778
> [#158430] Assorted clean up and improvements from working on Github Actions

- lib/tasks/price_policies.rake
A task to reset values so we can start using improved precision.
See https://github.com/tablexi/nucore-open/pull/2914 and https://github.com/tablexi/nucore-open/pull/2927
> [#159929] Add rake task for updating price policy usage_rate and usage_subsidy

- app/models/nufs_account.rb
- app/validators/account_validator/validator_default.rb
- doc/coding_standards.md
Just a few stray comments that need an update
> Tech task: Update code comments

- config/locales/en.models.yml
One more spot where this needs to get changed.
> [#159906] Update the label to Reservation Cost Window (hours)

- config/locales/en.yml
- spec/models/instrument_price_policy_calculations_spec.rb
I think I got the last one here.
> [#159906] One more reservation cost update

- CHANGELOG.md
- doc/HOWTO_recurring_tasks.md
> Add howto doc for recurring tasks

- config/initializers/development_authentication.rb
This file got moved as part of https://github.com/tablexi/nucore-open/pull/2952
> Tech task - Load username_only_authenticatable properly

- db/schema.rb
- docker-compose.yaml
Upgrade the default mysql version to 8
> Tech task - Upgrade to mysql 8

- .circleci/config.yml
- CHANGELOG.md
- db/migrate/20111209185608_base_rate_rename.rb
- db/migrate/20190409205259_rename_billing_administrator_role.rb
- docker-compose.yaml
> Tech task - Set a specific node version in CircleCI config

- app/assets/stylesheets/app/header.scss
- app/assets/stylesheets/nucore-variables.scss
- app/views/shared/_header.html.haml
- config/settings.yml
Adds some `settings.yml` and sass variables to make the header more customizable.
> [#160270] Pulls in style changes from OSU

- app/helpers/application_helper.rb
- app/views/shared/_header.html.haml
- config/settings.yml
Sometimes, it's not obvious that you're working in the stage environment or the production environment.
This makes the stage environment more clear by adding an optional setting which changes the color of the site's header when it's in the stage environment.
> [#158988] Adds setting for stage header color

- app/views/shared/_header.html.haml
- config/locales/en.yml
Adds in alt text for the logo image in the site header (if present).
> Tech task - Add alt text for logo image

- spec/system/admin/managing_user_spec.rb
Schools handle user creation slightly differently from one another.
We should get things more consistent eventually.
> Tech task - Handle user creation for all schools

- app/helpers/users_helper.rb
- config/locales/views/admin/en.users.yml
- spec/system/admin/managing_user_spec.rb
Updates copy of of user create success flash text
> 157969 update user creation text

- app/inputs/transaction_chosen_input.rb
This will affect the Order status filter on all pages where it appears.
> [#160285] Show all available order statuses by default

- app/helpers/account_fields_helper.rb
- app/views/shared/_account_fields.html.haml
Adds `account_field_value` helper from OSU
> Adds `account_field_value` helper from OSU

- vendor/engines/split_accounts/spec/services/journal_row_builder_spec.rb
OSU patches #revenue_account to return a formatted string
> [#160499] Compare integer to integer in journal row builder spec

- config/settings.yml
- vendor/engines/saml_authentication/lib/saml_authentication/devise_configurator.rb
Testing a possible solution for UMass
> [#160776] Allow configuring clock drift for SAML sign in

- app/views/product_users/index.html.haml
- config/locales/views/admin/en.product_users.yml
Streamlines layout of the product users page
> [#158382] Streamlines layout of the product users page

- app/helpers/translation_helper.rb
- app/views/admin/shared/_tabnav_payment_method.html.haml
- app/views/facilities/confirm_transactions.html.haml
- app/views/facilities/reassign_chart_strings.html.haml
- app/views/facility_accounts/_account_table.html.haml
- app/views/facility_accounts/statements.html.haml
- app/views/facility_notifications/in_review.html.haml
- app/views/facility_statements/index.html.haml
- app/views/facility_statements/new.html.haml
- app/views/shared/_tabnav_account.html.haml
- app/views/statements/list.html.haml
- config/locales/en.controllers.yml
- config/locales/en.models.yml
- config/locales/en.yml
- config/locales/override/en.yml
- config/locales/views/admin/en.facilities.yml
- config/locales/views/admin/en.facility_facility_accounts.yml
- config/locales/views/admin/en.facility_statements.yml
- config/locales/views/admin/en.log_events.yml
- config/locales/views/admin/en.order_imports.yml
- config/locales/views/admin/en.products.yml
- config/locales/views/admin/en.shared.yml
- config/locales/views/admin/en.statement_search_result_mailer.yml
- config/locales/views/admin/en.transaction_search.yml
- vendor/engines/c2po/config/locales/en.yml
No all school use the "statement" and "chart string" language. This adds statement and chart string as variables in the translation files so they can easily be changed. It also documents overrides that need to be written.
> [#160766] Define statement and chart string in translation file

- app/views/statements/list.html.haml
I could find no reference to this file - no controller action, route, or rendering.
> Add logging for likely unused file

- app/presenters/order_detail_notice_presenter.rb
- app/services/transaction_search/statement_searcher.rb
- config/locales/en.controllers.yml
- config/locales/en.yml
- config/locales/override/en.yml
- config/locales/views/admin/en.facility_facility_accounts.yml
- config/locales/views/admin/en.facility_statements.yml
- config/locales/views/admin/en.log_events.yml
- config/locales/views/admin/en.order_imports.yml
- config/locales/views/admin/en.products.yml
- config/locales/views/admin/en.statement_search_result_mailer.yml
- spec/controllers/facility_accounts_reconciliation_controller_spec.rb
- spec/controllers/facility_statements_controller_spec.rb
- spec/presenters/order_detail_notice_presenter_spec.rb
- spec/system/admin/moving_transactions_spec.rb
- vendor/engines/c2po/config/locales/en.yml
- vendor/engines/c2po/spec/system/account_reconciliation_spec.rb
Cherry picks spec changes from https://github.com/Oregon-State/nucore-osu/pull/185. Also removes `_upcase` from translation keys.
There's an adjustment in the override file here that needs to be reflected in other schools that are using it
> Translation updates

- app/services/journal_row_builder.rb
See https://github.com/tablexi/nucore-open/pull/2162/files#diff-5bc9292ed8e908186bc21960c44e6425581c149ee6ea2e4aadb4070151d7a342L158
> Tech task: Clean up references to unused recharge_enabled attribute

- app/models/statement.rb
- app/views/shared/_statements_table.html.haml
- spec/system/admin/facility_statements_spec.rb
Adds a confirmation dialog box to "Resend" button on statement page
> [#157937] Adds confirm dialog box to "Resend" button on statement page

- .gitignore
- Gemfile
- Gemfile.lock
- README.md
- app/controllers/order_imports_controller.rb
- app/models/concerns/active_storage_file.rb
- app/models/concerns/downloadable_file.rb
- app/models/concerns/paperclip_file.rb
- app/models/order_import.rb
- app/models/product_user_import.rb
- app/models/stored_file.rb
- app/services/stored_file_zipper.rb
- config/application.rb
- config/secrets.yml.template
- config/settings.yml
- config/storage.yml
- db/migrate/20220810152735_create_active_storage_tables.active_storage.rb
- db/schema.rb
- spec/controllers/file_uploads_controller_spec.rb
- spec/models/concerns/downloadable_file_spec.rb
- spec/models/journal_spec.rb
- spec/models/order_import_spec.rb
- spec/models/stored_file_spec.rb
- vendor/engines/sanger_sequencing/app/services/sanger_sequencing/sample_result_file_saver.rb
> [#160616] Adds ActiveStorage feature flag

- app/mailers/notifier.rb
- app/views/notifier/review_orders.html.haml
- app/views/notifier/review_orders.text.erb
- config/locales/en.notifier.yml
Updates the language of the review orders email
If the facility has an email address
If the facility does not have an email address
> [#159491] Updates language in review orders email

- doc/HOWTO_feature_flags.md
Lists and describes all the feature flags in a HOW TO doc
> Adds feature flag HOW TO

- config/secrets.yml.template
Adds code comments and a fix to escape special characters when reading an RSA key from the ENV.
https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml
> [#160883] Fix reading RSA key for SciShield API

- spec/models/order_status_spec.rb
These changes allow the specs to pass and provide coverage whether or not the school is using any custom root order statuses.
> [#161123] Update specs to be more flexible

- spec/mailers/notifier_spec.rb
Changes a notifier spec to use a translation key
> Changes a notifier spec to use a translation key

- doc/HOWTO_research_safety_adapters.md
Adds documentation for SciShield API as well as known issues with syncing server time
> [#160883] Add docs for SciShield

- app/controllers/surveys_controller.rb
- app/views/file_uploads/product_survey.html.haml
- config/locales/en.yml
This updates the copy on the product survey page.
> [#156658] Remove outdated reference to the Surveyor app

- app/controllers/user_file_uploads_controller.rb
- app/models/stored_file.rb
- app/models/user.rb
- app/views/admin/shared/_tabnav_users.html.haml
- app/views/user_file_uploads/index.html.haml
- config/locales/en.yml
- config/routes.rb
- db/migrate/20221212231558_add_user_to_stored_file.rb
- db/schema.rb
- spec/system/admin/user_file_uploads_spec.rb
This adds a document tab for users that admins can use to upload files associated with a user.
This PR is a cherry-picked of https://github.com/Oregon-State/nucore-osu/pull/238
> [#161127] Docs tab for users

- app/controllers/file_uploads_controller.rb
Correcting an old copy/paste error
> Tech task: Fix code comment

- Gemfile
- Gemfile.lock
- lib/tasks/order_details.rake
- The awesome_print gem is stale and has been causing some issues in local development
- Pulling in some updates to a rake task that was updated a while back
> Tech task - Update pricing rake task, amazing_print

- doc/HOWTO_feature_flags.md
This updates `HOWTO_feature_flags.md` given the addition of the `facility_tile_list_admin` flag.
> [#161102] Update feature flag howto doc with `facility_tile_list_admin`

- Gemfile.lock
- vendor/engines/dataprobe/dataprobe.gemspec
- vendor/engines/dataprobe/spec/lib/dataprobe/ipio_spec.rb
Bumps the patch version
Use consistent ruby hash style
> Tech task: A few dataprobe clean up items

- app/controllers/user_file_uploads_controller.rb
- app/models/concerns/paperclip_file.rb
- app/models/stored_file.rb
- app/views/user_file_uploads/index.html.haml
- config/locales/en.models.yml
* The size error message now only appears once
* The headers of the file list are now lined up correctly.
> [#161127] Fixes some user docs tab bugs

- app/models/concerns/active_storage_file.rb
- app/views/instrument_issues/new.html.haml
- db/migrate/20111219220830_alter_products_remove_relays.rb
- vendor/engines/secure_rooms/db/migrate/20170526170933_create_alarm_events.rb
Some migration cleanup
Fixes activestorage file_path
> Tech task: Cleanup tasks

- app/controllers/user_file_uploads_controller.rb
- app/models/concerns/paperclip_file.rb
Move paperclip validations patch into PaperclipFile module
> Tech Task - Move paperclip validations patch into PaperclipFile module

- bin/latest_from_open
- docs/PULL_REQUEST_TEMPLATE/release_pr_template.md
Adds a release template, and adds logic to the "latest" script to print out a URL that will create a PR using the new release template.
> Tech task: Add release PR template

- app/helpers/accounts_helper.rb
- spec/system/admin/manage_order_detail_spec.rb
Addresses a bug introduced during [refactoring](https://github.com/tablexi/nucore-open/pull/3365/files).
> Fix account input

- lib/tasks/order_details.rake
- lib/tasks/orders_to_remove.txt
This logic was in nucore-nu but could be useful for other schools as well.
> Tech task: Add rake task for cleaning up order detail records

- app/assets/javascripts/app/checkbox_form.js
Brings in UMass updates to checkbox_form.js
> [#161091] Brings in UMass updates to checkbox_form.js

- app/views/order_imports/new.html.haml
Reference the template file named in settings.yml in both links
> Fix: We have 2 template download links

- app/validators/account_validator/account_number_format_error.rb
Northwestern has been tested, so this comment is no longer needed.
> TECH TASK: Removes unneeded comment

- doc/HOWTO_relays.md
- vendor/engines/dataprobe/README.md
Adds some basic docs for relays
> Tech task - Add better docs for relays

- app/helpers/users_helper.rb
- spec/helpers/users_helper_spec.rb
Adds changes from https://github.com/northwestern-nucore/nucore-nu/pull/917 that need to be in Open
> [#161839] Adds UsersHelper changes from NU

- .github/workflows/test-suite.yaml
- app/models/order_detail.rb
- app/views/order_management/order_details/_shared_details.html.haml
> Tech task - Add code comments

- spec/system/admin/manage_order_detail_spec.rb
Tightens up spec coverage a bit
> [#161896] Improve spec coverage for changing `fulfilled_at` dates

- app/mailers/problem_order_mailer.rb
- docker-compose.yaml
change send reply to email in problem notification mail
> [#161743]: Problem notification email

- app/controllers/file_uploads_controller.rb
- spec/system/admin/creating_a_service_spec.rb
Remove `return` statements - behavior changed in rails 7
> [#160235] Fix services with forms

- Dockerfile
- Dockerfile.github-actions
TECH TASK: Node changed its repo, so the nodesource needed to be changed in our Dockerfiles.
> [#161941] Update Dockerfile to use new nodesource

- app/views/schedule_rules/_schedule_rule_fields.html.haml
This simplifies conditional statement, based on the comment https://github.com/tablexi/nucore-open/pull/3728/commits/3e8216d73268c28884f166c244ff6e6a43cea2ef#r1357105635
> [#161895] Slight refactor in schedule rule fields view

- app/views/instruments/_instrument_fields.html.haml
Pricing mode field only to be set when creating an instrument.
> Show Pricing mode field only when creating an instrument

- app/views/schedule_rules/_schedule_rule_fields.html.haml
- app/views/schedule_rules/index.html.haml
- spec/factories/products.rb
- spec/system/admin/secure_room_scheduling_tab_spec.rb
Fixes bug that prevented Schedule tab from opening for Secure Rooms
https://github.com/northwestern-nucore/nucore-nu/actions/runs/6739304990/job/18320535279?pr=946
> Check product is an instrument before checking pricing mode

- app/services/price_policy_updater.rb
- spec/system/admin/instrument_price_policies_controller_spec.rb
Fix bug when adding pricing rules where some groups can't purchase
> [#162031] Fix pricing rules

- app/mailers/notifier.rb
- app/views/notifier/new_user.html.haml
This adds .png to the email image
> [#162029] email image name update

- app/controllers/price_policies_controller.rb
- app/models/duration_rate.rb
- app/models/price_group.rb
- app/models/price_policy.rb
- app/models/rate_start.rb
- app/services/price_policy_updater.rb
- app/views/time_based_price_policies/_stepped_billing_price_policy_fields.html.haml
- db/migrate/20231108210613_change_associations_duration_rates.rb
- db/schema.rb
- spec/system/admin/instrument_price_policies_controller_spec.rb
[Tech task] Update DB so Stepped billing rates can be validated agains Price policy usage rate
> [#162084] Change model association for DurationRate

- db/migrate/20231102000551_add_global_boolean_column_to_price_groups.rb
Pulling this up into the open source repo.
Oracle boolean values are 1/0:
https://stackoverflow.com/questions/19435160/how-to-update-a-boolean-field-in-oracle-table
> Tech task: Properly handle oracle in db migration

- app/models/account.rb
- app/models/order.rb
- app/models/order_detail.rb
- app/services/order_row_importer.rb
Adds handling for order validations.
Order detail handling was implemented in https://github.com/tablexi/nucore-open/pull/3795/
Still need to add specs in a future PR
> [#161345] Handle expired accounts in order imports

- app/models/account.rb
- app/models/order_detail.rb
- app/services/order_row_importer.rb
There were a few more places that logic needed to be updated.
> [#161345] FIX: Order imports for expried accounts

- app/services/research_safety_adapters/scishield_training_synchronizer.rb
Sometimes a request for a single user's trainings fails when sync'ing, and this user is skipped and their trainings are not sync'd.
This PR adds retries in the case of a failed request. `ScishieldTrainingSynchronizer#synchronize` will now retry up to 5 times, spacing out tries by 25% more sleep each time.
> [#162000] Scishield sync retry

- doc/HOWTO_external_services.md
Adds steps for upgrading Form.io premium module
> [#159468] Update readme

- app/models/duration_rate.rb
- db/migrate/20231206192754_delete_all_duration_rates.rb
- db/migrate/20231212185627_update_duration_rate_rate_for_internal_price_groups.rb
- db/schema.rb
- spec/models/duration_rate_spec.rb
* Update previous Duration Rate in DB so they are all valid.
**Before merging: manually rollback the last migration.**
> [#161995] Update migration

- app/assets/javascripts/price_policy.js
- app/views/time_based_price_policies/_stepped_billing_price_policy_fields.html.haml
- spec/system/admin/instrument_price_policies_controller_spec.rb
* Fix External price group's rate being changed when base rate changed.
> [#161995] Fix bug for external price groups

- .gitignore
- doc/HOWTO_external_services.md
Updates documentation and the `.gitignore` file.
> [Tech task] Update formio readme

- spec/rails_helper.rb
- spec/system/creating_a_journal_spec.rb
* TECH TASK: In Journal specs, click button again if it's still visible.
Optional.
> TECH TASK: [#162110] New attempt at fixing Journal specs

- lib/tasks/cleanup.rake
Updates `cleanup:carts:destroy_abandoned` to accept days
> TECH TASK: [#161936] Updates abandoned cart rake task to accept days

- app/controllers/price_groups_controller.rb
- app/views/price_groups/_users.html.haml
- app/views/price_groups/_users_results.html.haml
- app/views/price_groups/users_search.html.haml
- config/locales/en.yml
- config/routes.rb
- spec/system/admin/price_group_management_spec.rb
* Add search to Price group's User tab.
* Change page size to 50 for results in Price group's User tab.
> [#161915] Price Group Users tab enhancements

- Dockerfile
This updates Dockerfile with contents of Dockerfile.github-actions to fix an issue with Node.js, npm not being found
> TECH TASK: Fix Dockerfile

- vendor/engines/sanger_sequencing/README.md
Puts feature explanation in Sanger README
> TECH TASK: Updates Sanger README

- .github/workflows/test-suite.yaml
- spec/system/admin/billing_mode_workflow_spec.rb
https://github.com/SeleniumHQ/selenium/pull/12037
https://github.com/SeleniumHQ/selenium/issues/13307
https://github.com/SeleniumHQ/docker-selenium/issues/2052
This should be resolved as of:
https://github.com/tablexi/nucore-open/pull/3997
> [WIP] Test out selenium/standalone-chrome:latest

- config/settings.yml
- spec/services/research_safety_adapters/scishield_training_synchronizer_spec.rb
This adds specs for `ScishieldTrainingSynchronizer` that test the type returned by its methods that wrap `Settings`
> TECH TASK: Add specs to catch ScishieldTrainingSynchronizer settings typo

- app/controllers/product_users_controller.rb
- spec/system/admin/access_list_tab_spec.rb
* Make Access List tab search case insensitive
> [#161789] Make Access List case insensitive

- doc/HOWTO_research_safety_adapters.md
This adds a section on how to generate keys for SciShield
> TECH TASK: Research Safety Adapters HOWTO update

- app/services/order_row_importer.rb
- config/locales/services/en.order_row_importer.yml
- spec/services/order_row_importer_spec.rb
- vendor/engines/projects/app/models/concerns/projects/order_row_importer_extension.rb
- vendor/engines/projects/config/locales/en.yml
- vendor/engines/projects/lib/projects/engine.rb
- vendor/engines/projects/spec/models/projects/order_row_importer_extension_spec.rb
This adds a project id to the bulk order importer, using the projects engine
> [#161990] Add project to bulk order import

- docs/pull_request_template.md
* TECH TASK: Update Pull request template.
Optional.
> TECH TASK: Add accessibility checklist mention to PR template

- docs/pull_request_template.md
This adds a question about specs to the check list
> Add to the accessibility check list

- app/controllers/facility_orders_controller.rb
- app/forms/add_to_order_form.rb
- app/views/facility_orders/_merge_order_form.html.haml
- app/views/facility_orders/show.html.haml
- config/settings.yml
- spec/system/admin/adding_to_an_order_spec.rb
* Use feature flag for Cross core projects.
> Hide Cross core project changes behind feature flag

- app/assets/stylesheets/app/quick_reservation.scss
- app/controllers/quick_reservations_controller.rb
- app/views/quick_reservations/_reservation_information.html.haml
- config/locales/views/en.quick_reservations.yml
- spec/system/quick_reservations_spec.rb
This adds a "Report an issue" link the quick reservation page
> [#162190] QR walk up: Reporting an issue

- app/controllers/facility_order_details_controller.rb
- app/controllers/facility_orders_controller.rb
- app/controllers/reservations_controller.rb
- app/forms/add_to_order_form.rb
- app/helpers/reservations_helper.rb
- app/lib/ability.rb
- app/models/order_detail.rb
- app/support/reservations/validations.rb
- app/views/facility_orders/_merge_order.html.haml
- app/views/facility_orders/_order_table.html.haml
- app/views/reservations/_account_field.html.haml
- app/views/reservations/new.html.haml
- spec/system/admin/adding_to_an_order_spec.rb
- Update permissions so admins can perform actions on Orders.
> [SHARED DEV] [#162195] Update permissions so admins can perform actions

- spec/system/admin/adding_to_an_order_spec.rb
* Fix Cross-Core spec.
Optional.
> Fix Cross Core spec

- app/views/facility_orders/_merge_order_form.html.haml
* [Tech task] Remove redundant label
Optional.
> [Tech task] Remove redundant label

- spec/support/select_from_chosen.rb
- spec/system/admin/adding_to_an_order_spec.rb
A one- or two-sentence explanation of what the change is and why, phrased for a non-technical audience. This should be copy-pasted as your commit message when the PR is merged. (Required)
Please preface your release note with "TECH TASK: " if the change is a technical task such as a gem upgrade or changes to a configuration file.
Optional.
> TECH TASK: Fix spec for selecting account

- app/views/shared/transactions/_search.html.haml
- config/settings.yml
- vendor/engines/projects/app/controllers/projects/projects_controller.rb
- vendor/engines/projects/app/views/projects/projects/_tabnav.html.haml
Most of the time users won't be looking for these in the projects tab
> [#162174] Adjust default order statuses

- app/controllers/order_details_controller.rb
- app/presenters/reservation_user_action_presenter.rb
- spec/system/admin/reservation_actions_spec.rb
* Redirect to correct order after "Cancel reservation"
> [Shared dev] [#162254] Redirect to correct order after "Cancel reservation" 

- app/views/facility_orders/_order_table.html.haml
- app/views/facility_orders/_order_table_actions.html.haml
- app/views/facility_orders/_order_table_footer.html.haml
- app/views/facility_orders/_order_table_headers.html.haml
* Move actions to product column
> [Shared dev] [#162254] Move actions to product column

- app/models/concerns/users/roles.rb
- app/views/shared/transactions/_table.html.haml
- app/views/shared/transactions/_table_headers.html.haml
- app/views/shared/transactions/_table_inside.html.haml
- spec/system/admin/projects_search_spec.rb
- spec/system/admin/projects_show_spec.rb
- vendor/engines/projects/app/controllers/projects/projects_controller.rb
- vendor/engines/projects/app/models/projects/ability_extension.rb
- vendor/engines/projects/app/models/projects/project.rb
- vendor/engines/projects/app/views/projects/projects/index.html.haml
- vendor/engines/projects/app/views/projects/projects/show.html.haml
- vendor/engines/projects/spec/models/projects/ability_extension_spec.rb
> [#162198] Improve project show

- bin/merge_describer
> TECH TASK: Update merge describer logic to better handle PR numbering

- vendor/engines/projects/app/controllers/projects/projects_controller.rb
- vendor/engines/projects/config/routes.rb
> [Shared dev] [#162198] Remove references to inactive tab

- spec/support/contexts/cross_core_context.rb
- vendor/engines/projects/app/controllers/projects/projects_controller.rb
> [Tech task] [#162198] Remove unnecessary code

- app/lib/ability.rb
- spec/system/admin/projects_show_spec.rb
* Fix bug for disappearing Users tab when creating  project.
> [#162319] Prevent Users tab from disappearing

- app/models/concerns/users/roles.rb
- vendor/engines/projects/app/services/projects/global_search/project_searcher.rb
- vendor/engines/projects/spec/services/projects/global_search/project_searcher_spec.rb
> [#162200] Add Projects search by id to global search

- app/models/order_detail.rb
- app/models/reports/account_transactions_report.rb
- app/views/shared/transactions/_cross_core_icon.html.haml
- spec/system/admin/all_transactions_search_spec.rb
- vendor/engines/projects/app/controllers/projects/projects_controller.rb
- vendor/engines/projects/lib/projects/engine.rb
* Fix bug when navigating to My Transactions
> [#162199] Fix bug when navigating to My Transactions

- app/assets/javascripts/app/bootstrap.coffee
- config/locales/en.yml
> [#162199] Fix tooltip in transactions

- app/services/order_row_importer.rb
- config/locales/services/en.order_row_importer.yml
- config/locales/views/admin/en.order_imports.yml
- spec/models/order_import_csv_spec.rb
* Add ability to bulk import Nonbillable products
Optional.
> [#162153] Add ability to bulk import Nonbillable products

- app/models/reports/export_raw.rb
* [#161679] Move Deposit Number column to the right
> [#161679] Move Deposit Number column to the right

- app/forms/admin_reservation_form.rb
- app/views/instruments/schedule.html.haml
- config/settings.yml
* Move calendar above admin holds.
* Make admin holds end date configurable.
> [#162286] Instrument reservations updates

- app/services/order_detail_batch_updater.rb
- app/views/facility_orders/_table_controls.html.haml
- app/views/shared/_order_detail_action_form.html.haml
- spec/services/order_detail_batch_updater_spec.rb
> [#162284] Store canceled information

- app/controllers/order_detail_stored_files_controller.rb
- app/controllers/order_management/order_details_controller.rb
- app/lib/ability.rb
- app/views/order_detail_stored_files/order_file.html.haml
- app/views/orders/_service_desc.html.haml
- spec/system/admin/adding_to_a_cross_core_order_spec.rb
* Fix bug when form is required for cross core order
> [#162345] Fix bug when form is required for cross core order

- app/controllers/order_detail_stored_files_controller.rb
- spec/system/placing_an_order_spec.rb
> [#162396] Fix order forms redirect

- app/assets/javascripts/app/load_cart_count.js
- app/controllers/orders_controller.rb
- app/views/shared/_header.html.haml
- config/routes.rb
* Tech task: Improve page load times
> [Tech task] [#162384] Make cart link be loaded with AJAX

- spec/system/admin/facility_statements_spec.rb
> [#162311] Fix specs that failed for OSU

- app/controllers/facility_accounts_reconciliation_controller.rb
- config/locales/en.controllers.yml
* Make only Global admin and Global Billing admin allowed to
> [#162311] Make only Global admin and Global Billing admin allowed

- spec/system/admin/adding_to_a_cross_core_order_spec.rb
- spec/system/admin/all_transactions_search_spec.rb
- spec/system/admin/facility_orders_search_spec.rb
- spec/system/admin/instrument_schedule_positions_spec.rb
- spec/system/admin/reservation_actions_spec.rb
> Tech task: [#162322] Fix flaky specs

- .github/workflows/test-suite.yaml
Speed up CI tests by using parallel specs.
> [#162450] Tech task: run parallel:spec on CI

- Gemfile.lock
Run bundle install and commited.
> Fix factory_bot_rails in Gemfile.lock

- spec/system/admin/item_price_policies_controller_spec.rb
Same as https://github.com/tablexi/nucore-open/pull/4705, there was one more case.
> [Fix] Enable director edit price policy flag on test

- app/models/time_range.rb
- app/services/price_policies/strategy.rb
- app/services/price_policies/time_based_price_calculator.rb
- spec/services/price_policies/time_based_price_calculator_spec.rb
- Refactor `PricePolicies::TimeBasedPriceCalculator` by splitting the logic based on the pricing strategy
- Fix formatting on spec file
- Add tests for daily rate pricing calculation
> [#162415][Daily Rate] Charge for daily rated instruments

- app/models/schedule_rule.rb
- app/support/reservations/moving_up.rb
- app/support/reservations/validations.rb
- spec/factories/reservations.rb
- spec/factories/schedule_rules.rb
- spec/models/reservations_validations_spec.rb
- spec/system/editing_a_reservation_spec.rb
- spec/system/purchasing_a_reservation_spec.rb
- Update schedule rules checks for daily booking instrument's reservations to just check availability of the start date
- Add tests for create and move reservations
> [#162412][Daily Rate] Schedule rules updates

- app/models/reservation.rb
- app/support/reservations/validations.rb
- spec/factories/reservations.rb
- spec/models/reservation_spec.rb
- spec/models/reservations_validations_spec.rb
- spec/system/purchasing_a_reservation_spec.rb
Cutoff hours weren't checked because `admin?` evaluated to true.
> [#162490] Fix cutoff hours validation

- app/lib/staging_mail_interceptor.rb
- config/settings/stage.yml
- spec/lib/staging_mail_interceptor_spec.rb
Change email interceptor fallback email add `wyeworks.com` to allow domains.
> [#162465] Change staging interceptor mail config

- app/models/product.rb
- spec/models/product_spec.rb
Missed the base class method when I added it to Instrument
> [Fix] Add Product#can_apply_discounts?

- app/views/facility_reservations/_table_controls.html.haml
- app/views/facility_reservations/index.html.haml
There was a weird space to the right due to colpsan being too large on the controls header. See screenshots.
I also removed some colspans=2 that were not needed.
> [#162522] Fix facility reservations table columns

- spec/support/c2po_test_helper.rb
- vendor/engines/c2po/spec/controllers/facility_accounts_controller_spec.rb
- vendor/engines/c2po/spec/routing/reconciliation_spec.rb
- vendor/engines/c2po/spec/system/account_reconciliation_spec.rb
Skip more tests that relied on credit card being reconcilable.
> [#161265] Skip tests that need reconcile credit card flow

- app/controllers/reservations_controller.rb
- app/support/reservations/date_support.rb
- config/locales/en.models.yml
- spec/support/shared_examples/reservations_new_daily.rb
- spec/system/editing_a_reservation_spec.rb
Fix (implement actually) editing a daily reservation reservation start date and duration.
> [#162525] Fix reservation edit not working

- spec/support/shared_examples/schedule_rules_controller_shared_examples.rb
* Fix specs related to schedule rules that were broken for Secure rooms
> Fix secure room specs

- .github/workflows/nucore-heroku-auto-deploy-staging.yml
* Fix deploy to Heroku but installing heroku-cli before attempting to deploy.
> Fix Heroku deploy

- README.md
- doc/HOWTO_oracle.md
While setting up a repository that uses Oracle on a Macbook with an M2 processor, I encountered some Oracle instant client compatibility issues. The different architectures of the client, Ruby, and the computer caused these issues, so I'm documenting some solutions.
> Add documentation on apple silicon pc oracle issues

- vendor/engines/sanger_sequencing/spec/system/sanger_products_spec.rb
- Add hook to render error pages in failing test
> [Fix] Sanger engine error pages tests

- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/purchase_notifier/_samples_table.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/submissions/_samples_table.html.haml
- vendor/engines/sanger_sequencing/spec/system/purchasing_spec.rb
- vendor/engines/sanger_sequencing/spec/system/submissions_spec.rb
- Show primer name in submission details if sanger service needs a primer on submissions
Order receipt
Submission details
> [OSU-117] Show primers on submission detail

- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/batches/new.html.haml
- vendor/engines/sanger_sequencing/spec/system/batches/creating_a_batch_spec.rb
Fix Sanger Sequencing Plate column order input enabled when feature flag is on.
> [Fix] Show column order input when ff is on

- db/schema.rb
- spec/rails_helper.rb
- spec/support/capybara_requests.rb
- vendor/engines/sanger_sequencing/app/assets/stylesheets/sanger_sequencing/application.scss
- vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/admin/primers_controller.rb
- vendor/engines/sanger_sequencing/app/models/concerns/sanger_sequencing/sanger_enabled_facility.rb
- vendor/engines/sanger_sequencing/app/models/sanger_sequencing/ability.rb
- vendor/engines/sanger_sequencing/app/models/sanger_sequencing/primer.rb
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/primers/edit.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/primers/index.html.haml
- vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/shared/_sidenav.html.haml
- vendor/engines/sanger_sequencing/config/locales/en.yml
- vendor/engines/sanger_sequencing/config/routes.rb
- vendor/engines/sanger_sequencing/db/migrate/20250127211156_add_facility_to_primer.rb
- vendor/engines/sanger_sequencing/lib/sanger_sequencing/engine.rb
- vendor/engines/sanger_sequencing/lib/tasks/sanger_sequencing.rake
- vendor/engines/sanger_sequencing/spec/requests/sanger_sequencing/admin/primers_spec.rb
- vendor/engines/sanger_sequencing/spec/system/purchasing_spec.rb
- vendor/engines/sanger_sequencing/spec/system/sanger_products_spec.rb
- vendor/engines/sanger_sequencing/spec/system/submissions_spec.rb
- Add "Manage Core Primers" section to Facility Sanger tab
- Primer belongs to Facility
- Add Capybara page to requests specs
> [OSU-121] Manage Primers per facility

- vendor/engines/sanger_sequencing/lib/sanger_sequencing/engine.rb
Asset was missing from precompile list 🙈
> [Fix] Add missing asset to precompile list

- vendor/engines/sanger_sequencing/lib/sanger_sequencing/engine.rb
Missed the directory in the previous one.
> [Fix] Add sanger_sequencing/submission.css to precompile

- .github/workflows/nucore-heroku-auto-deploy-staging.yml
- README.md
- bin/merge_describer
- bin/release_describer
- config/deploy.rb
* Fix release describer script
> Replace some occurrences of tablexi with wyeworks

- app/controllers/concerns/new_inprocess_controller.rb
- app/controllers/concerns/problem_order_details_controller.rb
- app/controllers/facility_orders_controller.rb
- app/controllers/order_detail_stored_files_controller.rb
- app/controllers/reservations_controller.rb
- app/forms/add_to_order_form.rb
- app/lib/ability.rb
- app/models/order.rb
- app/views/facility_orders/_merge_order_form.html.haml
- app/views/facility_orders/index.html.haml
- app/views/facility_orders/show.html.haml
- app/views/projects/_tabnav.html.haml
- app/views/projects/cross_core_orders.html.haml
- app/views/shared/_problem_order_details.html.haml
- config/settings.yml
- spec/system/admin/adding_to_a_cross_core_order_spec.rb
- spec/system/admin/adding_to_an_order_spec.rb
- spec/system/admin/facility_orders_search_spec.rb
- spec/system/admin/projects_edit_spec.rb
- spec/system/admin/projects_show_spec.rb
- spec/system/admin/reservation_actions_spec.rb
- spec/system/cross_core_orders_spec.rb
* Remove feature flags that have been ON for a while.
> [NUOPEN-214] [Tech task] Remove `cross_core_projects` and `cross_core_order_view`

- app/controllers/order_management/order_details_controller.rb
- app/services/order_details/param_updater.rb
- app/views/order_management/order_details/_costs.html.haml
- config/settings.yml
- spec/system/admin/manage_order_detail_spec.rb
* Allow Global Billing admins to update actual cost
> [UMASS-175] Allow Global Billing admins to update actual cost

- app/controllers/order_management/order_details_controller.rb
- spec/system/admin/manage_order_detail_spec.rb
Preserve previous behavior when ff off
> [UMASS-175] Fix condition when ff on

- app/controllers/order_management/order_details_controller.rb
- app/support/order_details/price_checker.rb
- spec/system/admin/manage_order_detail_spec.rb
* Fix Recalculate pricing when FF is ON
> [UMASS-175] Fix Recalculate pricing when FF is ON

- app/views/order_management/order_details/_form.html.haml
* Remove autocomplete for fulfilled_at
> [OSU-113] Remove autocomplete for fulfilled_at

- Gemfile
- config/environments/development.rb
- config/environments/test.rb
* Add Bullet config to detect N+1 queries.
* Added rules to avoid errors. When I tried to fix some of them, I got failing specs 😕
> [NUOPEN-222] Add Bullet config

- app/assets/javascripts/app/chosen_search_options.js
- app/assets/javascripts/app/estimate_search_users.js
- app/controllers/facility_estimates_controller.rb
- app/helpers/facility_estimates_helper.rb
- app/inputs/date_picker_input.rb
- app/lib/ability.rb
- app/models/estimate.rb
- app/models/facility.rb
- app/presenters/nav_tab/link_collection.rb
- app/views/facility_estimates/index.html.haml
- app/views/facility_estimates/new.html.haml
- app/views/facility_estimates/show.html.haml
- config/locales/en.models.yml
- config/locales/en.yml
- config/routes.rb
- config/settings.yml
- db/migrate/20250326164916_create_estimates.rb
- db/schema.rb
- spec/system/admin/creating_an_estimate_spec.rb
* Estimation tab, with new and show views.
> [NUOPEN-224] Estimation create and show

- db/schema.rb
Fix incorrectly resolved conflict
> [Fix] Schema version

- app/controllers/formio/submissions_controller.rb
- config/initializers/assets.rb
- spec/requests/formio/submissions_spec.rb
- Add jquery and jquery_ujs to precompile list and add simple specs for formio submissions controller.
> [NUOPEN-240] Precompile jquery and jquery_ujs

- app/assets/javascripts/app/chosen_search_options.js
- app/views/facility_estimates/new.html.haml
- spec/system/admin/creating_an_estimate_spec.rb
* Allow to search when there are no options
> [NUOPEN-224] Allow to search when there are no options

- app/assets/javascripts/app/hide_reconcile_fields.js
- app/views/facility_accounts_reconciliation/_table.html.haml
- app/views/facility_accounts_reconciliation/index.html.haml
- app/views/facility_statements/index.html.haml
- app/views/order_management/order_details/_form.html.haml
- app/views/shared/_statements_table.html.haml
- config/settings.yml
- spec/system/admin/facility_statements_spec.rb
- vendor/engines/c2po/spec/system/account_reconciliation_spec.rb
- Remove umass-167 and umass-178 ff
> [Chore] Remove umass 167 umass 176 ff

- vendor/engines/c2po/spec/system/account_reconciliation_spec.rb
Some schools don't use Credit Card accounts so these tests fail. Move them to use purchase orders instead.
> [Fix] Account reconciliation specs when credit cards not used

- app/assets/javascripts/app/estimate_products_table.js
- app/controllers/facility_estimates_controller.rb
- app/models/concerns/price_policies/quantity.rb
- app/models/estimate.rb
- app/models/estimate_detail.rb
- app/models/instrument_price_policy_calculations.rb
- app/models/product.rb
- app/models/timed_service_price_policy.rb
- app/views/facility_estimates/new.html.haml
- config/locales/en.yml
- db/migrate/20250410211418_create_estimate_details.rb
- db/schema.rb
- spec/system/admin/creating_an_estimate_spec.rb
- vendor/engines/secure_rooms/app/models/secure_room_price_policy.rb
* Add Items and Services to Estimate
There will be another PR for showing the products in the Show page.
> [NUOPEN-226] Add Items and Services to Estimate

- app/controllers/facility_estimates_controller.rb
- app/services/user_finder.rb
- spec/services/user_finder_spec.rb
- vendor/engines/secure_rooms/spec/services/user_finder_spec.rb
* Show username in dropdown.
* Include only active accounts.
> [NUOPEN-224] Tweaks for User find

- app/views/shared/_footer.html.haml
- config/locales/en.yml
- config/settings.yml
add URL config setting and link to the footer logo
> [UMASS-104] Add footer logo link

- .rubocop_todo.yml
- app/assets/stylesheets/app/email_log_events.scss
- app/assets/stylesheets/application.scss
- app/controllers/email_log_events_controller.rb
- app/helpers/email_log_events_helper.rb
- app/mailers/notifier.rb
- app/models/log_event.rb
- app/models/statement.rb
- app/presenters/email_log_event_presenter.rb
- app/services/log_event_searcher.rb
- app/services/notification_sender.rb
- app/views/admin/shared/_sidenav_global.html.haml
- app/views/email_log_events/index.html.haml
- config/locales/en.yml
- config/locales/views/admin/en.email_log_events.yml
- config/routes.rb
- config/settings.yml
- db/migrate/20250421145232_add_log_event_eventy_type_index.rb
- db/migrate/20250421145232_change_log_events.rb
- db/schema.rb
- spec/mailers/notifier_spec.rb
- spec/requests/email_log_events_spec.rb
- spec/requests/log_events_spec.rb
- Add specs for log_event index page
- Log billing email sending to log event
- Add section to list email log events
- Exclude email log events from other log events
- Add feature flag
> [UMASS-142] Billing email log

- config/settings.yml
Turn off feature flag by default.
> [UMASS-142] Disable email log events by default

- spec/system/resolving_a_disputed_order_spec.rb
- Fix ambiguos link click, for example: https://github.com/wyeworks/nucore-open/actions/runs/14253984228/job/39952989977
> [Tech task][NUOPEN-223] Flaky spec: ambiguous find link by text

- app/assets/javascripts/app/estimate_products_table.js
- app/controllers/facility_estimates_controller.rb
- app/models/estimate_detail.rb
- app/models/instrument.rb
- app/models/instrument_price_policy_calculations.rb
- app/models/product.rb
- app/models/timed_service.rb
- app/models/timed_service_price_policy.rb
- app/services/price_policies/strategy.rb
- app/services/price_policies/time_based_price_calculator.rb
- app/views/facility_estimates/new.html.haml
- app/views/facility_estimates/show.html.haml
- config/locales/en.models.yml
- config/locales/en.yml
- db/migrate/20250421214236_add_duration_to_estimation_details.rb
- db/schema.rb
- spec/system/admin/creating_an_estimate_spec.rb
* Add ability to add Instrument and Timed services to Estimate
> [NUOPEN-227] Add instrument and Timed Service to Estimate

- app/views/admin/shared/_sidenav_billing.html.haml
Show entry in billing menu if ff is on.
> [UMASS-142] Show global admin billing log menu when ff is on

- app/controllers/transactions_controller.rb
- app/views/shared/transactions/_in_review.html.haml
Similar to the main All Transactions page.
This file would only contain orders to be reviewed.
> [UMass 157] Add "Export as CSV" link to the Orders in Review page

- Gemfile
- Gemfile.lock
Reverts wyeworks/nucore-open#5251
> Revert "Bump jquery-ui-rails from 6.0.1 to 8.0.0"

- app/controllers/facility_estimates_controller.rb
- app/models/estimate.rb
- config/locales/en.models.yml
- spec/system/admin/filtering_estimates_spec.rb
* Add validation for expiration date
> [NUOPEN-228] Add validations for date

- Gemfile
- Gemfile.lock
Add `rack-mini-profiler` to dev gems
> [Chore] Add rack-mini-profiler

- app/mailers/purchase_notifier.rb
- app/models/order.rb
- config/locales/en.purchase_notifier.yml
- spec/mailers/purchase_notifier_spec.rb
Set subject to "<facility name> Order Received for Multiple Items" or "<facility name> Order Received for <product name>" depending on the amount of products purchased (1 or more).
> [UMASS-179] Show facility and product on order notification

- app/controllers/order_imports_controller.rb
- app/jobs/order_import_job.rb
- app/models/reports/order_import.rb
- spec/controllers/order_imports_controller_spec.rb
Part of ticket [NUOPEN-237].
Refactor `OrderImport` async run to an active job
> [NUOPEN-237] Refactor OrderImport processing into a job

- app/assets/javascripts/app/estimate_products_table.js
- app/assets/javascripts/app/merge_orders.js
- app/controllers/facility_estimates_controller.rb
- app/controllers/products_controller.rb
- app/models/estimate.rb
- app/models/product.rb
- app/views/facility_estimates/_estimate_detail.html.haml
- app/views/facility_estimates/new.html.haml
- app/views/facility_estimates/show.html.haml
- spec/system/admin/creating_an_estimate_spec.rb
* Add products from another facility to the estimate
> [NUOPEN-229] Add products from another facility to the estimate

- app/controllers/facility_estimates_controller.rb
- app/services/estimates/estimate_csv_service.rb
- app/views/facility_estimates/show.html.haml
- config/locales/en.yml
- spec/factories/estimates.rb
- spec/services/estimates/estimate_csv_service_spec.rb
* Download estimate as CSV
Note: format is because of Numbers app
> [NUOPEN-231] Download estimate as CSV

- config/locales/en.controllers.yml
- vendor/engines/sanger_sequencing/app/presenters/sanger_sequencing/receipt_submission_presenter.rb
- vendor/engines/sanger_sequencing/config/locales/en.yml
- Remove label to print sanger submission
- Fix sanger enable flash message regarding Order Form activation
> [OSU-139] Remove "print me" label on sanger submission

- app/controllers/facility_estimates_controller.rb
- app/models/estimate.rb
- app/models/estimate_detail.rb
- app/views/facility_estimates/show.html.haml
- config/locales/en.yml
- config/routes.rb
- spec/system/admin/recalculating_estimate_spec.rb
* Add ability to recalculate the estimate cost
> [NUOPEN-243] Add ability to recalculate the estimate cost

- app/controllers/users_controller.rb
- spec/system/admin/user_access_list_spec.rb
Use non archived product scope instead of using the active scope which is non archived non hidden.
> [UMASS-161] Show hidden products in user access list

- spec/system/admin/creating_an_estimate_spec.rb
"Facility" is named differently depending on the school.
> [Fix] Use facility human name on facility field

- app/controllers/facility_estimates_controller.rb
- app/models/estimate.rb
- app/models/estimate_detail.rb
- app/views/facility_estimates/new.html.haml
- app/views/facility_estimates/show.html.haml
- db/migrate/20250519201017_add_price_group_to_estimates.rb
- db/schema.rb
- spec/factories/estimates.rb
- spec/services/estimates/estimate_csv_service_spec.rb
- spec/system/admin/creating_an_estimate_spec.rb
- spec/system/admin/recalculating_estimate_spec.rb
* Add price group select to Estimate new
> [Shared dev][NUOPEN-248] Add price group select to Estimate

- app/lib/ability.rb
- spec/lib/ability_spec.rb
* Add missing abilities for Estimate
> [Shared dev] [Estimate] Add missing abilities

- app/views/facility_estimates/index.html.haml
Fix estimates filter form spacing and alignment.
> [Fix] Estimates filter spacing

- spec/system/admin/duplicating_an_estimate_spec.rb
* Use facility price groups in Duplicate spec
> [Shared dev] Use facility price groups in Duplicate spec

- app/views/facility_estimates/show.html.haml
- config/locales/en.yml
When an estimate does not have products hide the table and show a message.
> Handle estimates empty state

- app/controllers/errors_controller.rb
- app/views/errors/internal_server_error.html.erb
- public/500.html
- spec/controllers/errors_controller_spec.rb
Use a static page for 500 errors.
> [NUOPEN-244] Add static 500 error view

- app/views/admin/shared/_tabnav_payment_method.html.haml
- config/settings.yml
- spec/system/admin/facility_account_price_groups_spec.rb
- Add ff to show account price groups tab
> [UMASS-184] Add ff

- spec/system/admin/adding_to_an_order_spec.rb
- Use facility model locale in system spec
> [Chore ] Use facility locale on system spec

- app/controllers/facility_account_price_groups_controller.rb
Fix account param key which depends on account type.
> [UMASS-184] Fix account param key

- app/controllers/facilities_controller.rb
Remove eager load that breaks on Oracle DB.
> [Fix] Remove eager load that breaks on Oracle

- app/models/account_config.rb
- config/settings.yml
- spec/models/account_config_spec.rb
- spec/support/c2po_test_helper.rb
- vendor/engines/c2po/spec/controllers/facility_accounts_controller_spec.rb
* Show reconcile Credit Card
* https://github.com/northwestern-nucore/nucore-nu/pull/1139
* https://github.com/UMass-CORUM/nucore-umass/pull/743
> [NU-412] Show Reconcile Credit Card

- app/controllers/concerns/movable_transactions.rb
- app/controllers/facilities_controller.rb
- app/controllers/transactions_controller.rb
- app/helpers/reassign_chart_strings_helper.rb
- app/lib/ability.rb
- app/models/chart_string_reassignment_form.rb
- app/presenters/nav_tab/link_collection.rb
- app/views/facilities/confirm_transactions.html.haml
- app/views/facilities/reassign_chart_strings.html.haml
- app/views/shared/transactions/_confirm_transactions_content.html.haml
- app/views/shared/transactions/_reassign_chart_strings_form.html.haml
- app/views/shared/transactions/_table_inside.html.haml
- app/views/transactions/confirm_transactions.html.haml
- app/views/transactions/movable_transactions.html.haml
- app/views/transactions/reassign_chart_strings.html.haml
- config/locales/en.yml
- config/routes.rb
- config/settings.yml
- spec/controllers/transactions_controller_spec.rb
- spec/system/move_transactions_spec.rb
* Allow business admins to change Payment Sources in bulk
> [DART-59] Allow business admins to change Payment Sources in bulk

- app/controllers/instrument_relays_controller.rb
- app/controllers/products_common_controller.rb
- app/models/product.rb
- app/models/relay.rb
- config/locales/en.log_event_types.yml
- spec/models/product_spec.rb
* Add log events for Product and Relay
> [NU-58] Add log events for Product and Relay

- app/controllers/facility_estimates_controller.rb
- app/controllers/facility_journals_controller.rb
- app/controllers/instruments_controller.rb
- app/controllers/kiosk_reservations_controller.rb
- app/controllers/offline_reservations_controller.rb
- app/controllers/orders_controller.rb
- app/controllers/quick_reservations_controller.rb
- app/controllers/single_reservations_controller.rb
- app/controllers/users_controller.rb
* Avoid showing the flash messages when navigating to another page.
> [NUOPEN-267] Prefer `flash.now` where possible

- Gemfile
- Gemfile.lock
* [Tech task] Add deps that are causing warning messages
> [Tech task] Add deps that are causing warning messages

- app/models/power_relay.rb
- spec/models/power_relay_spec.rb
* Retry connection for relay status
> [NU-12] Retry connection for relay status

- app/models/reports/log_events_report.rb
> [NU-58] Add events to searcher

- app/models/reports/log_events_report.rb
> [NU-58] Add missing events

- app/models/reports/log_events_report.rb
* Add event for searching bulk import creation
> [OSU-137] Add event for searching bulk import creation

- app/javascript/form_io_submission.js
Fix form io function not being compiled because it's not attached to global objects nor exported.
> [Fix] Form IO script bundle

- db/migrate/20250820223416_update_statements.rb
- db/migrate/20250903124148_statements_invoice_number_unique_index.rb
- db/schema.rb
Add unique index attempted on a previous migration.
> [UMASS-192] Add unique index on invoice number

- app/models/statement.rb
- spec/services/statement_creator_spec.rb
- spec/system/admin/facility_statements_spec.rb
* Make invoice_number overrides work
> [UMASS-192] Make invoice_number overrides work

- config/settings.yml
> [Fix] Remove duplicate ff setting

- spec/models/statement_spec.rb
* Fix statement specs that depend on invoice_number implementation
> [UMASS-192] Fix statement specs that depend on invoice_number implementation

- app/services/statement_creator.rb
- config/locales/en.services.yml
- spec/services/statement_creator_spec.rb
- spec/system/admin/facility_statements_spec.rb
Handle other invoice number formats when looking up parent statement on statement creation.
> [UMASS-192] Find parent statement by invoice number on create

- spec/system/admin/facility_statements_spec.rb
* Fix message expected when FF in ON
> [UMASS-192] Fix message expected when FF in ON
