wyeworks/nucore-open

app/models/reports/instrument_utilization_report.rb

This should eliminate the "comparison of Array with Array" exceptions. It was something we were only seeing in the NU fork.

[#88306] Remove nils from Arrays before sorting

---

app/controllers/orders_controller.rb
config/routes.rb

Using update quantity takes you to update_or_purchase. When leaving to the external service, that becomes the referer, so we would get a 404 when coming back from the service.
This isn't the most elegant solution, but in order to maintain support for #61929 'More options' date reset in cart, we can't do a redirect to show after updating quantities, so this was the simplest.

[#94303] Could not update quantity before using external service

---

app/models/journal.rb
lib/validator/validator_default.rb
spec/controllers/facility_journals_controller_spec.rb

Order details that were fulfilled before a chart string expired was not being accepted because we weren't looking at the fulfilled_at. This is a regression in the [NU code](https://github.com/tablexi/nucore-nu/commit/b7b5773fcb1a321e9861ea1c32e4aed3ed52d54f).

[#94276] Pass fulfilled_at into account_is_open when journaling

---

app/models/journal.rb

CI suddenly started generating the XLS files with the content type
`application/CDFV2-encrypted`. Cause of this change is unknown, but
this was the easiest way to work around it.

Fix CI failure on invalid files

---

app/support/auto_logout.rb
spec/app_support/auto_logout_spec.rb

Currently we're complete the reservation which sets completes the order, sets actuals, and prices. We want to only complete the order so the order goes into the problem queue.

Auto logout orders are set to problem orders

---

config/locales/en.models.yml

From Aaron,
> On the Instrument Details tab, please change the following fields: "Automatic Logout?" change to "Auto-Relay Shutoff?" (both on "display" and "edit" screens). "Automatic Logout After Minutes" change to "Auto-Relay Shutoff After X Minutes" (just on "display" screen). This is more accurate, since NUCore doesn't really log users out.
https://pm.tablexi.com/issues/73235

[#73235] Label changes per Aaron's feedback

---

app/controllers/reservations_controller.rb
app/models/reservation.rb
spec/app_support/auto_logout_spec.rb
spec/controllers/reservations_controller_spec.rb
spec/models/reservation_spec.rb

https://pm.tablexi.com/issues/77963
Fixed: 
1. When clicking "End Reservation" check if other reservations using relay before switching off
2. When clicking "Start Reservation" we should end reservations for other reservations on the shared calendar
I also added a spec to make sure AutoLogout checks the shared calendar before deactivating the relay.

Couple fixes for the start/end reservation functionality

---

app/models/nufs_account.rb

OrderDetail.need_journal was loading ~3500 records. When there are
several order details on the Orders#show view, this got very slow.
This pushes the lookup for existence into SQL.

[#96853] Use SQL for query instead of loading all

---

app/support/products/scheduling_support.rb
spec/app_support/reservation_instrument_switcher_spec.rb
spec/factories/reservations.rb

when there are canceled reservations that do have actual_start_at and
no actual_end_at, we were trying to move them to complete.

[#96992] Unable to start reservations

---

app/views/facility_reservations/_reservation_fields.html.haml

As part of "#94617 Add ability to enter end time during reservation creation"
a change was made adding a couple extraneous fields to the facility admin
reservation form. As we had decided that the change should only affect
the user-side, and not the facility admin side, I am reverting the changes to
this view.
https://github.com/tablexi/nucore-open/pull/288

[#94617] Fix ability to create admin reservations

---

app/assets/javascripts/app/reservation_time_checker.coffee
app/assets/javascripts/app/reservation_time_field_adjustor.js.coffee

The admin reservation new/edit pages were not showing the calendar
because of JS errors caused by referencing variables that don’t exist
on those pages.
The ReservationTimeChecker error has been happening for a while, but
has no visible effect, just an error to the console.

[#94617] Do not run some reservation JS on admin reservations

---

spec/controllers/bundles_controller_spec.rb

The account needed to be added to one of the products within the bundle,
not the bundle itself.
https://github.com/tablexi/nucore-open/pull/298/files#diff-a4df8e7f76722c53491b648a90dfe540L85

Fix spec that is broken when merging into the NU branch.

---

Gemfile
Gemfile.lock
README.md
app/models/journal.rb
app/models/order_import.rb
app/models/stored_file.rb
config/initializers/paperclip.rb
config/settings.yml
lib/tasks/store_files_on_s3.rake
spec/models/order_import_spec.rb
spec/models/stored_file_spec.rb

This moves the hardcoded paperclip settings into `settings/`. I've included instructions in the README on configuring the app to use S3.
It also includes a rake task that should migrate all `StoredFile`s on the filesystem to S3, to be run after configuring the system to use S3: `bundle exec rake paperclip:move_to_s3`. We should save the output of this run to track down any files it was unable to migrate.
Something to watch out for: I tried upgrading the paperclip gem to 4.3, but it seems to break journaling here: https://github.com/tablexi/nucore-open/blob/master/spec/models/journal_spec.rb#L170

Make paperclip configurable to support S3

---

app/views/shared/_nav.html.haml

This is specifically for UI Core where there is no review period, which means the notifications is a 404.
A big TODO that remains: extract and refactor the first 20 lines of this view.

[#102824] Use has_review_period? to determine Billing tab URL

---

app/controllers/facility_reservations_controller.rb

`facility_reservations#new (NoMethodError) "undefined method `reserve_interval' for nil:NilClass"`
When @instrument.next_available_reservation is nil

[#103115] Fix error on next_available not found for admin reservation

---

app/views/facility_reservations/index.html.haml

When ending a reservation from the new/in process queue, the accessory
window was not popping up properly. The `#pick_accessories_dialog`
needs a couple classes (modal, fade, etc) in order to display properly.
Without explicitly declaring it on the page, the javascript will create
the element with all the necessary attributes.

[#98879] Accessory popup error in New/In Process Queue

---

spec/spec_helper.rb

Without the route reloading, if the flag was originally false, routes would not be available even after enabling the feature.
This should address the test failures on UIC.

Reload routes when using the feature flag metadata helper

---

doc/HOWTO_daemons.txt
lib/daemons/base.rb

Allow passing a command line argument that disables the daemon monitoring.
This is useful if you are using something external like eye to do your
monitoring.
This also moves the daemon pids into tmp/pids

[#102969] Allow skipping monitoring of daemons

---

app/assets/stylesheets/app/order_management.scss

This change is @mgreich -approved.
Before:
After (you'll have to take my word that a scrollbar appears along the right side):

[#98771] Remove modal height override to restore overflow scrolling

---

app/assets/stylesheets/app/header.scss

When clicked, the "Notices" tab's style would revert to the bootstrap default, ignoring what might be defined in nucore-overrides.scss.
It should have no real effect on this fork, but it's noticeable with NU's and UIC's styles.

[#60973] Ensure notices tab style matches the nav

---

app/controllers/price_groups_controller.rb
app/models/price_group.rb
spec/controllers/price_groups_controller_spec.rb

There was no ordering applied previously. This also fixes the query so
it doesn’t load all of the members into an array.

[#119594] Order users and accounts in Price Groups views

---

app/models/concerns/downloadable_file.rb

Paperclip gets really fussy when you try to upload a file and the MIME
type it detects does not match the file extension. This was happening
occasionally on NU for order uploads, and started happening for UIC.
This disables paperclip’s validations.
Already done in NU on https://github.com/tablexi/nucore-nu/pull/79
I’ve done this as a hotfix on UIC to verify that this fixes their issue.

[#119628] Do not validate media type for DownloadableFiles

---

circle.yml

I played with 2.2.3, but that's a little more troublesome, partly due to needing to upgrade to rails 3.2.22 to support Ruby 2.2.

Test on Circle with Ruby 2.1.7

---

spec/factories/price_groups.rb
spec/price_policies_controller_shared_examples.rb

We were getting an odd test failure where we’re looking for price
groups in a specific order. It was failing when that order spanned
“Price Group 999” to “Price Group 1000” because “1000” comes before
“999” alphabetically.

Use alphabetic sequnce for PriceGroup name

---

app/views/shared/_message_summary.html.haml

It's not obvious with the open color scheme, but on NU, the text for
"Notices (0)" in the header was gray as opposed to the white that it's
supposed to be.

[#60973] Fix color of "Notices (0)"

---

config/schedule.rb

This will prevent the —silent option from being included in cron tasks created by whenever. That makes sure that any output is sent via email as configured within the crontab.

Remove --silent from rake tasks created via whenever/cron

---

lib/ability.rb
spec/lib/ability_spec.rb

This merges the abilities of Facility Administrators and Directors, which should correct the issue where Facility Administrators could not access disputed orders but Directors could.

[#60973] Refine facility administrator abilities

---

config/schedule.rb

It feels a little weird to put capistrano-based functionality in the
open branch, but it will still work fine without capistrano, and `:db`
is the standard role for a single server (usually the one used for
running db:migrate).
PR for NU coming soon.

[#121286] Only run cron jobs on a single server

---

config/environments/production.rb

We’ve been running without these in NU for a while.

Remove unneeded precompile asset files

---

app/models/account.rb

We had a test that would fail about 20% of the time because the
`owner_user` association was losing the `user_role` conditional.
Calling `Account.first.owner_user` would result in the SQL:
`SELECT `users`.* FROM `users` INNER JOIN `account_users` ON
`users`.`id` = `account_users`.`user_id` WHERE
`account_users`.`account_id` = 204 AND `account_users`.`deleted_at` IS
NULL LIMIT 1`. If I flipped the order of the keys in the hash, I would
get the “Owner” condition, but not the deleted_at.
This seems like it could be a bug in ActiveRecord, but since we’re
still on 3.2, so I didn’t want to delve too far down.

Clean up owner_user association

---

app/models/user.rb
config/initializers/ldap.rb
lib/ldap/search.rb

The recent upgrade of the Devise LDAP adapter changed its behavior so
external users would no longer fall back to the
database_authenticatable strategy.

[#121342] Restore external users' ability to log in

---

app/support/notification_sender.rb
spec/app_support/notification_sender_spec.rb

If the review period feature is off, then the test fails.

Ensure NotificationHelper tests get run with review period disabled

---

app/controllers/facility_order_details_controller.rb
app/views/notifier/order_status_changed_to_pending_approval.html.haml
app/views/notifier/order_status_changed_to_pending_approval.text.erb
config/routes.rb

As part of the new order detail management popup we removed the old
actions for editing an order detail. This points to the proper place,
also adding a redirect for the now-non-existent path.

[#121571] Fix link in "needs approval" email

---

db/migrate/20100701183019_create_facility_accounts.rb

When running the migration for a new project, the `change_column
:products, :facility_account_id, :integer, null: false` was failing
because there was a foreign key attached to it. Oddly, it was only
failing when run on the stage server database; it worked fine locally.
This changes the order of operations so the index doesn’t exist until
the column is in the state it needs to be. It also changes from
explicit sql to `add_foreign_key`.

Fix migration from scratch issue

---

app/models/message_summarizer/training_requests_summary.rb
spec/models/message_summarizer_spec.rb

I ran into an exception while running with training requests off. If a training request exists, it would try to put a link in the drop-down whether the feature was enabled or not. But creating that link fails because the route to it only exists when the feature is enabled.
With this, if the feature is off, the notifications for it are off too.

Suppress training request notifications when the feature is off

---

config/database.yml.mysql.template
config/database.yml.oracle.template

Minor change.  Database names with dashes technically work in mysql, but they can get hairy with certain mysql commands.  It's easier/cleaner to use underscores rather than dashes so you don't ever have to quote/tick the database name within the mysql console.  Also, the oracle and mysql database yml's should probably use the same database names.

Update database.yml templates default database names

---

app/controllers/facilities_controller.rb
config/routes.rb
lib/ability.rb

I noticed these while I was cleaning up something else, and realized
these aren’t used anywhere (plus they’re broken—there’s no `product`
layout, and hasn’t been since the initial fork in github).

Remove unused actions

---

app/models/reports/account_transactions_report.rb

Based on https://github.com/tablexi/nucore-uic/pull/39, this also adds the account description (for NU) and the owner so it matches more closely to the html view.

[#122107] Add account and owner to transaction CSV export

---

app/helpers/application_helper.rb

This should prevent titles like " - NU Core" slipping through. It's something I noticed on `/facilities/:facility:id/accounts/user/:user_id` but could be elsewhere.

Treat the full_title as an empty string when blank

---

spec/presenters/statement_presenter_spec.rb

UIC does not have statements enabled so the route generated here does not exist.

Fix spec broken when not using statements

---

spec/factories/accounts.rb
spec/factories/nufs_accounts.rb
vendor/engines/split_accounts/spec/factories/split_accounts.rb

I’m doing this so I can use the `with_owner` trait on purchase orders and credit cards easily within  my credit card branch.

Make account owner trait share-able among subclasses

---

Gemfile
Gemfile.lock

NU stopped being able to connect over the git protocol due to firewall
changes. Using SSH is better anyways.

Use SSH for github gems

---

lib/ability.rb
spec/controllers/facility_orders_controller_spec.rb
spec/controllers/facility_reservations_controller_spec.rb
spec/lib/ability_spec.rb

I didn’t want to get into the black hole that could be writing the missing specs for this method; I just wanted to get the bug fixed.

[#122474] Restore ability for facility staff to batch update reservations

---

app/models/account_user.rb
spec/factories/account_users.rb
spec/models/account_user_spec.rb

Since Account Managers are not considered managers of the "all" facility, they were not given an option to assign the "Owner" role. This change should make "Owner" appear as an option on the form at `/facilities/all/accounts/:account_id/account_users/new?user_id=:user_id` for an Account Manager.
There's a lot of refactoring and cleanup here, but I kept the `manager_of?` check because it felt weird to bring `Ability` checks into a model. Maybe that means `.selectable_user_roles` doesn't belong in the `AccountUser` model at all?
This method is only used in two places that I see, so moving it shouldn't be a big effort, if it's worth taking on.

[#98883] Allow Account Managers to assign account ownership

---

app/models/user_role.rb
config/locales/en.yml

While trying to pull the latest open/master into UIC, we were getting
a test failure on a missing translation. I'm not 100% why it wasn't
finding the translation, especially, why it was working in open, but not uic, but this appears to work. There's a circle branch running with the latest from open/master and this change.

Fix missing translation error

---

app/helpers/application_helper.rb
app/helpers/transaction_history_helper.rb
app/views/facility_accounts/show_statement.html.haml
app/views/shared/_problem_order_details.html.haml
app/views/shared/transactions/_table_inside.html.haml

Introduced as part of a refactoring of the OrderDetailPresenter.
`row_class` returns either “reconcile-warning” or “”. “” was evaluating
to true in `needs_reconcile_warning?`.
This removes the `needs_reconcile_warning?` helper method. There could
still be the next step of removing `row_class` helper in favor of the
`Presenter.wrap`, but that was a bigger change than I wanted to make to
get a quick fix.

[#123960] All transactions in billing tab were red

---

app/services/account_builder.rb
spec/services/account_builder_spec.rb

`AccountBuilder.for(nil)` should return `AccountBuilder` but was instead returning `Builder`.  Added a guard to squash this bug and provided a spec to verify.

Handle nil param for AccountBuilder.for

---

spec/controller_spec_helper.rb
spec/controllers/accounts_controller_spec.rb
spec/controllers/facility_reservations_controller_spec.rb
spec/controllers/orders_controller_spec.rb
spec/helpers/date_helper_spec.rb
spec/models/account_spec.rb
spec/models/old_instrument_price_policy_spec.rb
spec/models/order_detail_spec.rb
spec/models/order_spec.rb
spec/models/user_spec.rb
vendor/engines/c2po/spec/controllers/facility_accounts_controller_extension_spec.rb

Remove specs that are `not implemented yet` since they are noise at this point in time.  We can refer back to this pull request to implement any missing tests in the future.
```
1) FacilityJournalsController#show should test more than auth
2) FacilityAccountsController accounts_receivable should test more than auth
3) FacilitiesController disputed_orders behaves like transactions should test more than auth
4) FacilitiesController transactions behaves like transactions should test more than auth
5) FacilitiesController movable_transactions behaves like transactions should test more than auth
6) OrderDetail auto scaled accessory defaults to 1 if less than a minute
7) OrderDetail manual scaled accessory defaults to 1 if less than a minute
8) Order validate_order state transition should …
```

Remove not implemented specs

---

app/assets/javascripts/app/manage_orders.coffee

The `_method` input was being disabled, along with the `utf8` and `authentication_token`
when the other form fields were getting disabled. Because `_method=put` was not
being submitted, the router was treating it as a POST resulting in a route not
found.

[#88724] Error when editing a reconciled OD's reconcile note.

---

app/assets/javascripts/app/manage_orders.coffee

Proper behavior: if any visible/non rails input (utf8, _method) is active, then
the submit button should be enabled. If they are all disabled, then the submit
button should be disabled as well.
After the recent change where we don't disable the hidden utf8, etc fields, the
submit button was always visible.

[#88724] Ignore rails hidden form fields when deciding when to disable the submit button

---

app/models/nufs_account.rb
app/services/nufs_account_builder.rb
lib/tasks/demo_seed.rake
lib/validator/validator_factory.rb
spec/services/nufs_account_builder_spec.rb

Errors in NU such as BlacklistError were getting raised all the way up
to the view as opposed to caught and displayed in a pretty error
message. This changes the behavior so that `set_expires_at` will never
raise its own errors (I’m not clear why it did before).

Better handling of validator errors during expiration setting

---

app/controllers/facility_accounts_controller.rb
app/models/nufs_account.rb
app/services/nufs_account_builder.rb
config/locales/en.controllers.yml
config/locales/en.models.yml

Move load_components call to only be for NufsAccount. This should fix problems
with the call for credit cards and purchase orders.
Correct error messages on account creation
There were extra error messages appearing for invalid accounts such as
“Expiration cannot be blank” and longer text when the GL066 could not
be found. This should revert to the behavior prior to the account
builder refactor
Cherry-pick and rebase of the main-app changes of https://github.com/tablexi/nucore-nu/pull/116

Fixes for AccountBuilder

---

Gemfile
Gemfile.lock
circle.yml

I'd like to upgrade nucore to Ruby 2.2.4 as part of the next staging release, partly to see if it resolves occasional segfaults we get from our cronjobs (order_details:expire_reservations, order_details:auto_logout, etc).
```
[BUG] Segmentation fault at 0x00000000000630
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]
-- C level backtrace information -------------------------------------------
```

Use Ruby 2.2.4 for Circle

---

app/assets/javascripts/app/reports.coffee

Since all inputs on the reports form trigger a tab content load when changed, it was easy for a user to fire off a series of Ajax requests, even though the user likely only cared about the result of the one fired last.
It also caused some confusion, because after a successful XHR return, it would update the date start and end input fields, which may have been changed since.
8a8e5ec changes this behavior so if a request is in-flight (that is, triggered by a previous form input change), it should abort that old XHR before making a new one.
adfea82 is cleanup based on CoffeeLint suggestions.

[#99279] Abort in-flight XHR when report parameters change

---

vendor/engines/c2po/app/services/purchase_order_account_builder.rb
vendor/engines/c2po/spec/controllers/facility_accounts_controller_extension_spec.rb

This field uses `formatted_expires_at` to get the correct formatting. It was not
being allowed by strong params. I also discovered a bug in the spec where it
was testing for inverted month/day (May 12 v Dec 5), otherwise we should have
seen this bug.

[#120455] Fix Purchase Order creation after AccountBuilder refactor

---

lib/engine_manager.rb

The engine_manager used to look at engine names that starts_with
a given string. Which was causing false negatives when I was
trying it out. I updated so it only returns true if you provide
the exact engine name.

Update engine_manager to prevent false positives

---

spec/app_support/order_detail_journal_remover_spec.rb

Ignore order of order details for journal remover spec.
Cherry pick a commit from https://github.com/tablexi/nucore-nu/pull/121

Ignore order of order details for journal remover spec

---

Gemfile

It is not included by default in Ruby 2.2, and the rails console requires it. Without
including it everywhere, we can't run `rails console` on staging or production.
https://github.com/rails/rails/blob/3-2-stable/railties/lib/rails/console/app.rb

Move test-unit out of development/test group

---

app/models/reports/export_raw.rb

Some of the time, especially if export raw is the first thing I do on server start,
the CSV module is not loaded yet so `Array#to_csv` is undefined. I even found if
I started the rails console and ran `["a", "b"].to_csv` I would get `NoMethodError: undefined method `to_csv' for ["a", "b"]:Array`.
This makes sure CSV is loaded before trying to call `to_csv`.

Explicitly require `csv` in ExportRaw

---

vendor/engines/split_accounts/app/views/facility_accounts/account_fields/split_accounts/_splits.html.haml

https://www.pivotaltracker.com/story/show/114612023
The subaccount dropdown was unwieldy with a large data set, so we are now using `chosen` for that particular dropdown.
**Note:** The vertical alignment of the inputs is slightly off due to loading chosen.  This did not appear to be a trivial fix and will require some investigation.

[#120455] Add chosen to split account dropdown

---

app/helpers/translation_helper.rb
vendor/engines/split_accounts/app/views/split_accounts/shared/_show_splits.html.haml

I’d like to keep the ticket number of the redmine task since future people probably won’t have access to the pivotal queue we’re using. It’s all sub-parts of the same feature.

[#120455] Nicer display of extra penny boolean

---

vendor/engines/split_accounts/app/models/split_accounts/split_account.rb
vendor/engines/split_accounts/config/locales/en.yml
vendor/engines/split_accounts/spec/factories/split_accounts.rb
vendor/engines/split_accounts/spec/models/split_account_spec.rb

The split account form should gracefully error out if a user attempts to create a split account with only one 100% split.  We will display an error message that they must have two or more subaccounts.
https://www.pivotaltracker.com/story/show/114612937

[#120455] Ensure split accounts have two or more splits

---

vendor/engines/split_accounts/app/models/split_accounts/split.rb
vendor/engines/split_accounts/spec/models/split_spec.rb

https://www.pivotaltracker.com/story/show/114611681
Users should not be able to create splits with 200% and -100%; that add up to 100% but venture outside of a valid percentage range.

[#120455] Ensure split percent is within range

---

vendor/engines/split_accounts/app/models/split_accounts/split_account.rb

The `earliest_expiring_subaccount` method in the `split_account` model was expecting valid subaccounts which was resulting in 500 errors when submitting a split account without any subaccounts selected.  This PR fixes the issue.
https://www.pivotaltracker.com/story/show/114804481

[#120455] Prevent 500 when submitting split account without any splits

---

app/controllers/facility_accounts_controller.rb
app/views/facility_accounts/show.html.haml
vendor/engines/split_accounts/app/controllers/split_accounts/facility_accounts_controller_extension.rb
vendor/engines/split_accounts/app/models/split_accounts/split_account_ability.rb
vendor/engines/split_accounts/lib/split_accounts/engine.rb
vendor/engines/split_accounts/spec/controllers/facility_accounts_controller_spec.rb

This prevents non-admins from being able to edit as well.
Pivotal #114612043

[#120455] Only global admins can manage SplitAccounts

---

app/views/general_reports/_report_rows.html.haml

Only show decimals in quantities where needed on reports. Don’t show if
it’s .0 (which will be the majority of time since split accounts will
be the special case).
Pivotal #115081495

[#120455] Hide insignificant decimals on reports

---

app/controllers/general_reports_controller.rb
spec/controllers/general_reports_controller_spec.rb

This has negligible performance implications in open, but in NU where
`to_s` does a query to pmu_department, this saves quite a bit of time
when many OrderDetails use the same account. Testing against 1000 order
details on the same account, it cuts the load time from ~3.2 seconds
down to ~2.5 due to the savings of N+1 queries.
This really only works because the report view itself will call `to_s`
implicitly when outputting the account as the first column, but it does
improve performance, so I think it’s worth it.
I'll let the rubocop changes later deal with the spacing and 1.9 syntax on the spec.

Improve performance of Account General Report

---

vendor/engines/split_accounts/app/services/split_accounts/order_detail_list_transformer.rb

Testing against NU/Oracle with 1000 OrderDetails all being on a
SplitAccounts, using each_with_object instead of the map/flatten had a
30% speed increase (~7.2 seconds down to ~4.7).
I also tried order_details.flat_map and while that's an improvement
over the map/flatten, it still tended to be slower than the
each_with_object, running around ~5.2 seconds.

[#120455] Improve performance of OrderDetail split transformer

---

vendor/engines/split_accounts/app/services/split_accounts/split_account_builder.rb
vendor/engines/split_accounts/spec/services/split_account_builder_spec.rb

I considered `params[:action] == “new”` as another option, but think I
like this better. If you remove all the sub accounts and try to create,
this rebuilds them, and since the account is blank on them, it’s
invalid. The messaging does get a little funky in that it shows “Splits
subaccount may not be blank” and “Splits must have unique subaccounts”,
but maybe that can be addressed in #114804299. I’m not sure where you’re at with that, @benlinton.
Also addresses #114611991.

[#114611969] Default to having two splits on #new

---

config/locales/en.yml

Forks may customize this by editing `config/locales/override/en.yml`.

[#125280] Remove reference to NU Financials from journal instructions

---

app/models/account.rb
vendor/engines/split_accounts/app/models/split_accounts/account_extension.rb
vendor/engines/split_accounts/app/models/split_accounts/split_account.rb
vendor/engines/split_accounts/spec/factories/split_accounts.rb
vendor/engines/split_accounts/spec/models/split_account_spec.rb

When suspending a subaccount, any parent split accounts will inherit the farthest out `suspended_at` timestamp from its subaccounts.  If all subaccounts become unsuspended for a suspended split account, the split account does **NOT** un-suspend.
When expiring a subaccount, any parent split accounts will inherit the most recent `expires_at` timestamp from its subaccounts.  If all subaccounts become unexpired for an expired split account, the split account will become unexpired as well.
https://www.pivotaltracker.com/story/show/114611945
https://www.pivotaltracker.com/story/show/114611905
This approach does have some potential pitfalls.  If the database fails or network fails during the `account_extension.rb` `after_save` callback (which would update the parent split account), then the …

[#120455] Suspend a parent account if any subaccount is suspended

---

.codeclimate.yml

Code Climate is not currently looking at `/vendor/engines`, but should for this project.
This also should make Code Climate's coffelinter use `.coffeelint.json` (added in #445).
https://www.pivotaltracker.com/story/show/115736563

Add custom Code Climate configuration

---

vendor/engines/split_accounts/app/models/split_accounts/split_account.rb
vendor/engines/split_accounts/app/services/split_accounts/split_account_builder.rb
vendor/engines/split_accounts/config/locales/en.yml

https://www.pivotaltracker.com/story/show/114804299
Includes small changes to improve the SplitAccount form errors.
- A blank `percent` input will no longer responds with a 500 error
- Minor enhancements to error message language
- Suppress unique subaccounts error if subaccount dropdowns are blank
- We'll no longer get an `expires at can not be blank` error message when submitting the form without a subaccount selected

[#120455] Improve split account form errors

---

vendor/engines/split_accounts/app/models/split_accounts/reports/export_raw_transformer.rb

This got lost in the rebase of #494 and #495

[#120455] Use HashHelper in SplitAccounts::Reports::ExportRawTransformer

---

config/settings.yml

DC will want this, but UIC will not.

[#120455] Turn on split accounts by default.

---

.codeclimate.yml

duplication in specs is not really a sign of a problem.

Exclude spec directories from codeclimate duplication checks

---

vendor/engines/split_accounts/app/views/facility_accounts/account_fields/split_accounts/_splits.html.haml

The available_subaccounts list gets very big, and the
`available_subaccounts` query gets run for every nested sub account.
Since we’re starting with 2, it doubles the load. This especially gets
bad if you try to submit 4 or more sub accounts with a validation
error. This cuts it down so we only do a single query.

[#120455] Improve new split account view render

---

app/models/reports/instrument_day_report.rb
vendor/engines/split_accounts/spec/controllers/instrument_day_reports_controller_spec.rb

This also fixes a bug where the actual hours report was using the
reservation hours. It got changed, by what appears to be an accident in
978ac8a

[#120455] Do not double count reservations in utilization reports

---

vendor/engines/split_accounts/app/models/split_accounts/split_account.rb
vendor/engines/split_accounts/spec/models/split_account_spec.rb

If a sub account gets suspended and unsuspended and re-suspended, the
parent should use maintain the first suspension date.
If you set the suspended_at of a sub account to some time in the past
before the parent’s set suspended_at, it won’t update. The logic to
make this update was much uglier and harder to understand without
significant commenting, so I decided not to worry about it because the
act of `suspend!` always happens “now” in the context of the app.

[#120455] Maintain first suspended_at in split accounts

---

app/views/shared/_footer.html.haml
config/locales/en.yml

This is something I noticed when updating the footer for #516. Is there any reason to keep that 2010 check?

Remove 2010 check when generating copyright dates

---

config/locales/en.yml

Forks that require site-specific language should make overrides in `config/locales/override/en.yml`.

[#115962443] Remove NU-specific language from locales

---

app/controllers/accounts_controller.rb
app/models/account.rb
app/models/account_user.rb
spec/controllers/facility_account_users_controller_spec.rb
spec/models/account_spec.rb

In the order detail modal, the payment source dropdown was showing
duplicate payment sources if the user had deleted AccountUsers.
This now makes the association always exclude `deleted_at`. The
association from the User side was already ready doing this

[#125502] Hide deleted AccountUsers

---

app/controllers/general_reports_controller.rb
app/models/reports/export_raw.rb

The export raw actually has nothing to do with the current action
(product, account_owner, price_group, etc). This also removes the need
for that parameter.

[#125414] Update Export Raw email subject and filename

---

app/views/users/accounts.html.haml

Facility directors were using this button thinking they were going to
add the user as a purchaser and instead adding them as the owner.
Also of note, the feature flag check was probably referencing the wrong
flag.

[#125047] Remove "Add Payment Source" button from user

---

vendor/engines/c2po/config/locales/en.yml

This would be overridden in the forks that use `c2po`.

[#115962443] Remove "NU" from payment option text

---

lib/tasks/demo_seed.rake

Missed in 3c42afd076cc4b6612ff5c84129eb58af2994e2f when `set_expires_at!` lost its `!`.

Update method name

---

app/assets/javascripts/app/flash.coffee

While testing some issues around the credit card provider for NU, it
felt that hiding the flash after 10 seconds could obscure the errors.
This will leave the flash message in place until the page is refreshed.
If a new flash is added, the old one is still removed, so we don’t have
to worry about flash messages piling up.

[#125686] Remove JS flash removal after 10 seconds

---

app/views/reservations/new.html.haml
db/migrate/20160415231343_clean_duplicate_reservations.rb
db/schema.rb

It is possible for two reservations to be created for the same user if
they double click the “Create” button in quick succession and the
transactions overlap. This only happens on a multi-threaded server like
unicorn.
This also cleans up duplicates and adds a unique constraint on
`reservations.order_detail_id`. All duplicates I found in practice are
exact duplicates.
Also related to NU #124969, UIC #122397.

[#122397] Prevent multiple reservations on the same order detail

---

app/assets/stylesheets/app/typography.scss
app/controllers/order_details_controller.rb
app/controllers/orders_controller.rb
app/helpers/breadcrumb_helper.rb
app/models/order_detail.rb
app/services/available_accounts_finder.rb
app/views/order_details/edit.html.haml
app/views/order_details/show.html.haml
config/locales/en.yml
config/routes.rb
lib/ability.rb
spec/controllers/order_details_controller_spec.rb
spec/support/matchers/controller_matchers.rb

I’ve implemented this so that a user may change the account up to the end of the review period (unless it gets disputed, then the feature continues to work until the dispute gets resolved). I've also set it up so the user can only select non-expired, non-suspended accounts. I agree that it could be problematic if users are given the ability to assign it to an expired account. We could implement logic that takes fulfillment date into account, but that logic will get messy, and I'm not sure that it's worth the effort and additional complexity. If a user need to move the order to an expired account, they can always contact the facility directly.
The original purchaser, account owners and business admins have this interface. Account Purchasers don't have access (they currently can't even see …

[#47665] Purchaser/Owner/BA can change change order detail account

---

app/views/notifier/order_receipt.html.haml
app/views/notifier/order_receipt.text.haml
spec/mailers/notifier_spec.rb

This adds a payment source line to order notifications and receipts, taken from https://github.com/tablexi/nucore-dartmouth/pull/21.

[#117475471] Include payment source in order notifications/receipts

---

spec/models/facility_account_spec.rb

This cherry-picks one commit from https://github.com/tablexi/nucore-nu/pull/148 which consolidates NU-specific `FacilityAccount` specs in a fork-specific engine.

Remove NUCS-specific specs from the main app

---

app/views/facility_facility_accounts/_facility_account_fields.html.haml
app/views/facility_facility_accounts/new.html.haml
app/views/shared/_account_fields.html.haml
config/locales/en.yml

This is extracted from https://github.com/tablexi/nucore-dartmouth/pull/22.
It does not address the odd taborder issue we've noticed when filling out a chart string (that's where halfway through, tabbing may bounce your cursor to the search input).

Clean up recharge chart string partials and I18n

---

app/services/order_details/param_updater.rb
spec/controllers/order_management/order_details_controller_spec.rb

Our specs were using `reserve_start_at` as the parameter instead of
what really gets submitted: `reserve_start_date, reserve_start_hour,
reserve_start_min, reserve_start_meridian` so the specs were passing,
but would error when used in the interface.

[#47665] Fix strong params for OrderDetail popup

---

app/controllers/search_controller.rb
app/views/search/_user_product_approval_link.html.haml
lib/ability.rb
spec/controllers/search_controller_spec.rb

The user approval search was broken because of a syntax error. This was
broken by the refactoring in #534 for supporting deactivated users.
While writing tests, I also discovered that this causes a problem where
facility admins cannot order for after a search. I never noticed it
because I was always testing as a global admin.

[#124331] Fix broken search result

---

app/controllers/order_details_controller.rb
app/views/order_details/show.html.haml
config/locales/en.yml
spec/controllers/order_details_controller_spec.rb

#update was already using logic to determine whether you could modify
the order. This adds the logic to edit and the “Change” link.

[#47665] Fix edit account permissions based on state

---

app/controllers/order_details_controller.rb
app/models/order_detail.rb
spec/controllers/order_details_controller_spec.rb

Per NU’s request, a customer should be allowed to change the payment
source up until the time the order detail is journaled or statemented.

[#47665] Customer can change account until journaled or statement

---

app/views/order_details/show.html.haml
spec/controllers/order_details_controller_spec.rb

The user would receive a 403 when they tried to submit the dispute
reason. This now hides the box entirely from those users.

[#125794] Hide dispute box from Account Purchaser 

---

app/views/shared/sidenav_billing/_reconciliation.html.haml

Reconciliation doesn’t work in the cross-facility context, so we should
hide it from the menu (similar to statements). We have a separate story
for enabling cross-facility statements (#125702), so we can look into
enabling this when we play that story.

[#125700] Hide reconciliation links from cross-facility

---

spec/controllers/facility_accounts_controller_spec.rb

UIC uses a PNG with transparency, which is only supported by PDF 1.4+.
Prawn is apparently smart enough to use the lowest compatibility level
based on the features that get used.
https://acrobatusers.com/tutorials/understanding-pdf-compatibility-levels

Statement spec should pass for newer pdf versions

---

app/controllers/facility_accounts_controller.rb
app/models/account_config.rb
app/services/account_builder.rb

This will be used to disable the creation of NufsAccounts in branches where we are using other custom account types. Disabling just the interface for creation instead of completely is much simpler than fixing all of the tests that would be broken.

[#118500913] Ability to disable creation of certain account types

---

app/models/facility_account.rb
spec/factories/facility_accounts.rb
spec/models/facility_account_spec.rb

This pulls in the parts of https://github.com/tablexi/nucore-nu/pull/151 that are not specific to NU, to generalize the `revenue_account` validations to allow integers. Number ranges and format validations, if any, would be up to the forks to implement.

Revenue account validations

---

app/controllers/facility_facility_accounts_controller.rb
app/controllers/products_common_controller.rb
app/models/nufs_account.rb
config/settings.yml
lib/nucore.rb

There's one spec in the NU branch that uses `COMMON_ACCOUNT`, so we'll need to change that there.

[#118597103] Move default revenue and product accounts to Settings

---

app/presenters/nav_tab/link_collection.rb
vendor/engines/projects/app/controllers/projects/projects_controller.rb
vendor/engines/projects/app/models/projects/ability_extension.rb
vendor/engines/projects/app/presenters/projects/link_collection_extension.rb
vendor/engines/projects/app/views/projects/projects/index.html.haml
vendor/engines/projects/app/views/projects/projects/new.html.haml
vendor/engines/projects/config/locales/en.yml
vendor/engines/projects/config/routes.rb
vendor/engines/projects/lib/projects/engine.rb
vendor/engines/projects/spec/controllers/projects/projects_controller_spec.rb
vendor/engines/projects/spec/models/projects/ability_extension_spec.rb
vendor/engines/projects/spec/projects_spec_helper.rb

This adds a new facility admin tab for viewing lists of Projects and and creating new ones.
I initially had the tab display at the end of the admin's tab list, but committed e80bc0b to place it second to last. I think it works better there.

[#116373301] Add Projects index and new/create

---

app/assets/javascripts/account_mgmt.js
app/assets/javascripts/app/datepicker-data.coffee
app/assets/javascripts/reconciliation.js.coffee
app/controllers/facility_accounts_reconciliation_controller.rb
app/controllers/facility_journals_controller.rb
app/services/order_details/reconciler.rb
app/support/journals/closer.rb
app/views/facility_accounts_reconciliation/_action_row.html.haml
app/views/facility_accounts_reconciliation/_table.html.haml
app/views/facility_accounts_reconciliation/index.html.haml
app/views/facility_journals/show.html.haml
config/locales/en.models.yml
db/migrate/20160426231556_add_reconciliation_date_to_order_detail.rb
db/schema.rb
spec/controllers/facility_accounts_reconciliation_controller_spec.rb
spec/controllers/facility_journals_controller_spec.rb
vendor/engines/c2po/spec/controllers/facility_accounts_reconciliation_controller_spec.rb

This handles both reconciling CC/PO and "succeeded, with errors" journals. It also sets the reconciled_at to the current time for "succeeded, no errors".
There is still an open question around what we want to do with the historical manually-reconciled details (those that are not part of a statement or PR). Currently I have them being set to `reviewed_at`, but that may change.

[#125075] Manually set reconciliation date when reconciling

---

config/initializers/sanitized_allowed.rb
vendor/engines/projects/app/views/projects/projects/show.html.haml

This is a loose end from #569: we're allowing HTML in `Project#description` but the "show" view was escaping it. This marks the string as "safe", though it does mean trusting that a privileged user (facility operator) wouldn't do anything malicious.

Allow HTML in Project descriptions to display as HTML

---

config/locales/en.yml
db/schema.rb
vendor/engines/projects/app/controllers/projects/projects_controller.rb
vendor/engines/projects/app/models/projects/ability_extension.rb
vendor/engines/projects/app/views/projects/projects/edit.html.haml
vendor/engines/projects/app/views/projects/projects/new.html.haml
vendor/engines/projects/app/views/projects/projects/show.html.haml
vendor/engines/projects/config/locales/en.yml
vendor/engines/projects/config/routes.rb
vendor/engines/projects/db/migrate/20160503170055_add_active_flag_to_projects.rb
vendor/engines/projects/spec/controllers/projects/projects_controller_spec.rb
vendor/engines/projects/spec/models/projects/ability_extension_spec.rb

This adds a basic interface for editing projects by adding an edit button to the project show view.
It also includes a few `active` flag to the `Project` model. A checkbox appears on the edit form to toggle `active` but the flag has no impact on anything else yet.

[#116373897] Add edit and update actions for Projects

---

spec/lib/nav_tab/link_spec.rb
spec/rails_helper.rb

Doing the `TextHelpers::RSpec.reset_spec_translations` on every single spec significantly increased the testing time on CI, especially for UIC, which went from around 18 minutes to 30-40. I'm not sure why it didn't have the same level of impact on open and NU. This drops the time back down to 17-18 minutes on UIC.

Only reset locales in specs where necessary

---

app/controllers/users_controller.rb
app/mailers/devise_mailer.rb
app/mailers/notifier.rb
app/models/reports/account_transactions_report.rb
app/views/file_uploads/product_survey.html.haml
app/views/notifier/new_user.html.haml
app/views/notifier/new_user.text.haml
app/views/notifier/order_receipt.html.haml
app/views/notifier/order_receipt.text.haml
app/views/notifier/review_orders.html.haml
app/views/notifier/review_orders.text.erb
app/views/notifier/user_update.html.haml
app/views/notifier/user_update.text.erb
app/views/users/new_external.html.haml
app/views/users/search.html.haml
config/initializers/devise.rb
config/locales/en.notifier.yml
config/locales/en.yml
config/locales/views/en.facilities.yml
spec/controllers/facility_orders_controller_spec.rb

The definition of `app_name` should be the only place "NUcore" appears in the locales. Once this is in, we should be able to clean up a lot of the overrides in UIC.

[#115962679] Use `app_name` so the name is more easily overridable 

---

app/assets/javascripts/activate_chosen.js.coffee
app/services/order_details/param_updater.rb
app/views/order_management/order_details/edit.html.haml
db/schema.rb
spec/controllers/order_management/order_details_controller_spec.rb
vendor/engines/projects/app/models/projects/order_detail_extension.rb
vendor/engines/projects/app/models/projects/project.rb
vendor/engines/projects/app/services/projects/order_details/param_updater_extension.rb
vendor/engines/projects/app/views/projects/shared/_select_project.html.haml
vendor/engines/projects/config/locales/en.yml
vendor/engines/projects/db/migrate/20160503184205_add_project_id_to_order_detail.rb
vendor/engines/projects/lib/projects/engine.rb
vendor/engines/projects/spec/controllers/order_management/order_details_controller_spec.rb
vendor/engines/projects/spec/factories/projects.rb
vendor/engines/projects/spec/models/projects/order_detail_extension_spec.rb
vendor/engines/projects/spec/models/projects/project_spec.rb
vendor/engines/projects/spec/services/projects/order_details/param_updater_extension_spec.rb

This injects Project selection into the order detail edit screen (modal, typically).
Highlights:
* The `order_details` table gets another attribute: `project_id`. There are related changes to the order detail updater for the Projects engine to make changes to permitted params.
* There are validations to check that the project:
- belongs to the same facility as the order/order detail
- is active, unless the project was already associated (presumably when it was active)
* There's some cleanup of the edit view partial
* The project selection is injected through a view hook
* There's a change to how it activates `chosen`, in that if the `<select>` is optional, you should be able to "x" out a previous selection.

[#116374821] Assign a project to an OrderDetail

---

vendor/engines/projects/app/views/projects/shared/_select_project.html.haml

This is a loose end from #574: if there are no projects available to select, it shouldn't show a selection widget.

[#116374821] Present project selection if there are selectable projects

---

app/models/journal.rb

This is partially from https://github.com/tablexi/nucore-dartmouth/pull/38. We need `tmp` to exist at the app root, and it does, though it seems it's only because gems like `sprockets` and `letter_opener` will create it if it's not there.
This also reworks the only code I'm aware of that was relying on `Dir.tmpdir`, in journal creation. With this in place, some of the overrides in the DC fork may become redundant.

Ensure tmp exists at app root, and use it

---

app/mailers/base_mailer.rb
app/mailers/notifier.rb
config/initializers/action_mailer_interceptors.rb
config/settings.yml
lib/staging_mail_interceptor.rb
spec/lib/staging_mail_interceptor_spec.rb

As opposed to capturing everything and sending it to a list, this sets up a
whitelist of people who can receive emails. If an email is sent to someone not
on the list, it is captured and redirected to a list of developers.
This should require no configuration changes unless we want to add people to the whitelist that shouldn’t receive the intercepted emails.

[#119031765] New email interceptor that allows a whitelist

---

app/controllers/facilities_controller.rb
app/controllers/facility_facility_accounts_controller.rb
app/controllers/instruments_controller.rb
app/controllers/products_common_controller.rb
app/controllers/reservations_controller.rb
app/controllers/users_controller.rb
app/models/product.rb
app/views/notifier/order_receipt.html.haml
app/views/notifier/order_receipt.text.haml
app/views/training_requests/new.html.haml
config/locales/en.models.yml
config/locales/en.notifier.yml
config/locales/en.yml
config/locales/views/admin/en.facilities.yml
config/locales/views/admin/en.facility_facility_accounts.yml
config/locales/views/admin/en.users.yml
config/locales/views/en.products.yml
config/locales/views/en.reservations.yml
config/locales/views/en.training_requests.yml
spec/mailers/notifier_spec.rb

This takes care of what #566 did not. After this, there should be no more references to "facility" or "facilities" directly in any strings. They should all go through `facility_downcase` or `model_name.human`.

[#115962501] More support of "Facility" overriding

---

app/controllers/facility_journals_controller.rb
app/models/order_detail.rb
app/models/reports/export_raw.rb
app/support/journals/closer.rb
app/views/facility_journals/show.html.haml
config/locales/en.controllers.yml
db/migrate/20160426231556_add_reconciliation_date_to_order_detail.rb
spec/controllers/facility_journals_controller_spec.rb
spec/controllers/order_management/order_details_controller_spec.rb
vendor/engines/split_accounts/app/models/split_accounts/reports/export_raw_transformer.rb

These are based on feedback from our last discussion with NU about the feature.
One big thing we decided was to leave historical non-journaled reconciliation dates blank. They'd rather have no data than incorrect data. Journaled orders' reconciled_at will always be set to the journal_date.
Also, they gave us the go ahead to change the export raw template so I moved the split percentage to a spot where it makes a little more logical grouping.
The migrations haven't gone out on NU & UIC, and there is no important data on DC, so I felt OK changing the migration in place.

[#125075] Manual reconciliation date updates

---

lib/ability.rb
spec/controllers/order_details_controller_spec.rb

In #543, we refactored some of the OrderDetailsController permissions and accidentally removed the order form actions and gave :cancel permission to the account admins instead of the purchaser.

[#126102] Permission fixes

---

spec/models/product_spec.rb

This was causing a spec failure in DC where "facility" is "resource".

Support overridden "facility" in spec

---

config/routes.rb

There’s cleanup that could be done to the routes (why all the reports
routes are like that at the bottom instead of inside the `resources
:facilities`, I don’t know), but I don’t want to tackle that here.

[#119019273] Use "facilities" locale in routes

---

config/locales/en.yml
spec/controllers/facilities_controller_spec.rb
spec/controllers/file_uploads_controller_spec.rb
spec/controllers/instruments_controller_spec.rb
spec/controllers/items_controller_spec.rb
spec/controllers/services_controller_spec.rb
spec/controllers/users_controller_spec.rb
spec/helpers/accounts_helper_spec.rb
spec/presenters/order_detail_presenter_spec.rb
spec/presenters/statement_presenter_spec.rb
spec/price_policies_controller_shared_examples.rb
spec/rails_helper.rb
vendor/engines/c2po/spec/routing/reconciliation_spec.rb

I tried to only use the I18n version in routing specs and elsewhere
switch to the url helper methods. I also kept them using string routes
in presenters because switching to the helpers ends up just asserting
exactly what the methods do.
DC’s latest pull.

Fix i18n route specs 119019273

---

app/services/bulk_email_searcher.rb
spec/services/bulk_email_searcher_spec.rb

If a user is authorized on multiple products, they will be returned as
multiple rows in the results.

[#124331] Bulk Email returns duplicates on authorized user search

---

app/inputs/transaction_chosen_input.rb
lib/transaction_search.rb
spec/controllers/facilities_controller_spec.rb
vendor/engines/projects/app/views/projects/shared/transactions/_search.html.haml

If the page (all transaction, send notifications, etc) only has one
unique project, then that one project was being shown in the box and
the box was disabled. The logic was relying on the fact that all of the
other select fields were non-nullable.

[#116374999] Fix Project Filter on Transactions view

---

app/controllers/users_controller.rb

I added this to make testing easier for #578 so I didn't have to go through the
full user creation process while testing the strings, but forgot to take it out
when I was done.

[#115962501] Do not show save success strings on Users#show

---

app/controllers/reports/reports_controller.rb
spec/controllers/reports/general_reports_controller_spec.rb

RoutingError requires a message. The message should not get displayed
to the user, so it’s just for developers.

[#117175831] Missing argument on reports routing error

---

app/models/order_detail.rb
vendor/engines/projects/app/views/projects/projects/show.html.haml

The shared partial this uses is already set up for pagination, but it was not calling `paginate` on the collection of order details. This change should fix that.
The `order_details` are not ordered by `ordered_at`. Should they be?

[#116374977] Enable pagination of order_details for Project "show" views

---

app/assets/javascripts/app/manage_orders.coffee

The form gets disabled by JS, so this makes sure that any chosen
selects get updated from their `select`’s attributes.

[#119749091] Disable chosen dropdown for reconciled orders

---

app/controllers/orders_controller.rb
spec/controllers/orders_controller_spec.rb
vendor/engines/projects/app/models/projects/order_extension.rb
vendor/engines/projects/app/views/projects/shared/_select_project.html.haml
vendor/engines/projects/spec/models/projects/order_extension_spec.rb

If an order detail did not have a project, but the first detail in the
same order does, that project was appearing in the dropdown.
This also now renders on purchase with quantity changes rather than
redirects. This makes sure the project and the “more options” fields
don’t get lost.

[#119754369] Project dropdown had project if sister detail did

---

app/models/external_service/external_service_receiver.rb

Rails 4 uses method_missing to dynamically define attribute names. So
`response_data` is not defined yet, so when we try to use it inside
`method_missing`, it triggers the stack overflow. If we grab the
attribute directly, we’re good.
http://stackoverflow.com/questions/16088392/defining-method-missing-on-active-record-in-rails-4-throws-systemstackerror-sta
Cuts out about 30 test failures.

Fix problems with external service receivers

---

app/services/account_builder.rb
spec/services/account_builder_spec.rb

This is kind of a weird one. We’re testing some affiliate code in the
base builder, but NufsAccount don’t support affiliates, so they’re
excluded from the `account_params_for_build` and get filtered out by
strong params. CreditCardAccountBuilder & PurchaseOrderAccountBuilder
include affiliate_id and affiliate_other.
Turns out the `using_affiliate? && account_params.key?(:affiliate_id)`
is somewhat redundant, but I like keeping it in there, but this keeps
the data clean.

[rails4] Fix affiliate spec

---

config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
lib/engine_manager.rb

`rails server` will now boot without deprecations, and this takes care of a deprecation on how we test if engines are loaded.

[rails4] Clean up deprecations

---

app/controllers/application_controller.rb
app/controllers/bulk_email_controller.rb
lib/transaction_search.rb

This was a “nice” feature I added when I first created the transaction
search which strips the hidden field parts a GET search to make URL query strings
look just a little nicer.
In Rails 4, the `redirect_to params` raises an "Cannot redirect to a parameter hash!"
error, which seems like a reasonable security feature. It seems the easiest way
to fix the error is to kill the feature altogether. I don’t think anyone will notice.

[rails4] Kill `remove_ugly_params` filter

---

Gemfile
Gemfile.lock
app/models/order.rb
app/models/order_detail.rb
app/views/facility_orders/show.html.haml
app/views/notifier/review_orders.html.haml
app/views/notifier/statement.html.haml
app/views/notifier/statement.text.erb
app/views/notifier/user_update.html.haml
config/locales/en.notifier.yml
lib/staging_mail_interceptor.rb
spec/controllers/facility_orders_controller_spec.rb
spec/lib/staging_mail_interceptor_spec.rb
spec/models/order_detail_spec.rb
spec/models/user_spec.rb
vendor/engines/projects/app/models/projects/project.rb
vendor/engines/projects/app/views/projects/projects/edit.html.haml
vendor/engines/projects/app/views/projects/projects/show.html.haml
vendor/engines/projects/spec/models/projects/project_spec.rb

This merges #621 into the Rails 4 branch *This also includes a few other updates from master*
The syntax is the obvious change, but it's pretty straightforward.
The bigger issue is that prior to AASM 3.0, `AASM::InvalidTransition` would only be raised if the transition did not exist. In 3.0+, guard failures also raise the error. So for example
```ruby
event :validate_order do
transitions to: :validated, from: [:new, :validated], guard: :cart_valid?
end
order.validate_order! # Raises an error in both versions
order.validate_order! # Returns false in 2.X, raises in 3.0+
```
`validate_order!` is the big place where this problematic since it gets called several places with no `rescue`. I chose to keep the change minimal by defining my own `validate_order!` method that calls the …

[Rails4] AASM upgrade to 4.10

---

app/inputs/currency_input.rb
app/inputs/order_detail_quantity_input.rb
app/inputs/readonly_input.rb
app/inputs/transaction_chosen_input.rb

These methods now accept a `wrappers_options` argument.
https://github.com/plataformatec/simple_form/pull/997

[rails4] Clean up deprecation notices from simple_form

---

vendor/engines/projects/app/services/projects/global_search/project_searcher.rb
vendor/engines/projects/spec/controllers/global_search_controller_spec.rb

When determining permissions for the `show` view of a `Project`, it uses the project's `facility` as its base resource. When restricting global searches, it should use the same.
This means that of the 3 current global search types, only one, `OrderSearcher`, would be using the `restrict` method from the base class. It still felt general enough to belong there so I left it.

[#116375253] Restrict Projects by Facility abilities

---

app/views/facility_accounts_reconciliation/_action_row.html.haml

Chrome can parse `Date#to_s` correctly, but Firefox does not. They both handle iso8601.

[#125075] Use correct format for min-date on reconciliation date widget

---

spec/controllers/facility_accounts_controller_spec.rb
spec/controllers/training_requests_controller_spec.rb

These are testing features that can be disabled with a feature flag which removes the routes.
I haven't found any documentation around this, but it seems like Rails 3 controller specs didn't check the routes, it just called methods directly on the controller. Now Rails 4 does check. This should fix some of the tests in UIC.

Enable features in specs where necessary

---

app/controllers/instruments_controller.rb
app/controllers/products_common_controller.rb

In #565, we refactored to share Products#index views. As part of this,
we got rid of the need for the specific `@instruments`, `@services`,
etc in the views. CanCan was still loading these variables, but without
a facility restriction.
There was some vestigial code in the instruments controller that loaded
from when we used to include a lot more information like upcoming
reservations and relay status. See
d4579e6b67419ff51a052a82bb5c93ed0626ead5. I believe this was removed
when we added the timeline/daily view.
This was now loading upcoming reservation status for _every_ instrument
in NUcore, not just the ones for the facility.

[#126377] Fix slow page load on products index

---

app/models/external_service/survey_response.rb
app/models/order_detail.rb
app/views/orders/_cart_row.html.haml
db/migrate/20160601214939_add_quantity_lock_to_external_service_receivers.rb
db/schema.rb
spec/models/external_service/survey_response_spec.rb

If a quantity is returned by the outside application, then disable the quantity box. This will also affect IMSERC, but this appears to be the correct behavior there as well.

[#119570693] Disable quantity editing when survey controls quantity

---

db/schema.rb
vendor/engines/sanger_sequencing/db/migrate/20160519030413_create_sanger_sequencing_submissions.rb

Oracle doesn't support ON UPDATE CASCADE. We don't really need it for MySQL either since our primary keys will never change, so it's easier to just get rid of it.
This has not been released yet, so it shouldn't cause any problems, although devs
should roll back and re-run it to make sure their schema.rb is in sync.

Fix Sanger migration for Oracle

---

app/assets/stylesheets/app/tables.scss
app/assets/stylesheets/application.scss
app/views/orders/show.html.haml
config/locales/en.yml
vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/submissions_controller.rb
vendor/engines/sanger_sequencing/app/views/sanger_sequencing/submissions/edit.html.haml

Extends from #641. Only the last commit is relevant.
* Tightens up the form
* Adds breadcrumbs
* Maintains the My Orders, My Reservations tabs while in the form

Improve Sanger Sequencing form design

---

Gemfile
Gemfile.lock
spec/rails_helper.rb

Depending on the ordering of specs, fixtures might get left in the test database for the next time. This makes sure to clean everything out ahead of time.

Add DatabaseCleaner to make sure fixtures are cleaned before the suite

---

Gemfile
Gemfile.lock
app/controllers/reservations_controller.rb
app/models/reservation.rb
spec/features/purchasing_a_reservation.rb
spec/features/purchasing_a_reservation_on_behalf_of.rb
spec/fixtures/account_users.yml
spec/fixtures/price_group_products.yml
spec/fixtures/price_policies.yml
spec/fixtures/products.yml
spec/fixtures/schedule_rules.yml
spec/fixtures/schedules.yml
spec/rails_helper.rb

The callbacks when ordering on behalf of (specifically with a note) was
causing an infinite loop in Rails 4. We weren’t catching it before
because we were never submitting a note in the tests.

[#126567] Fix infinite loop while ordering reservation on behalf of

---

spec/helpers/date_helper_spec.rb

The `Time.use_zone` needs to be within the `it` block in order to work. The test
was failing in DC where the app is in Eastern time.

Fix timezone spec

---

spec/controllers/facility_facility_accounts_controller_spec.rb
spec/features/purchasing_a_reservation_on_behalf_of_spec.rb
spec/features/purchasing_a_reservation_spec.rb
vendor/engines/sanger_sequencing/spec/features/purchasing_spec.rb

These are cherry-picked from https://github.com/tablexi/nucore-dartmouth/pull/50
* bd6183f and 880b56f set up `AccountPriceGroupMember`s in feature specs.
* 7db8273 replaces an unreliable regular expression with Nokogiri to test for HTML attribute values

Spec updates via the DC fork

---

app/assets/stylesheets/app/cart.scss
app/assets/stylesheets/application.scss
app/controllers/instruments_controller.rb
app/controllers/orders_controller.rb
app/controllers/products_common_controller.rb
app/helpers/orders_helper.rb
app/views/admin/products/_details_fields.haml
app/views/admin/shared/_product_manage.haml
app/views/orders/_cart_row.html.haml
app/views/orders/_form.html.haml
app/views/orders/receipt.html.haml
app/views/reservations/_account_field.html.haml
config/locales/en.yml
config/locales/views/admin/en.products.yml
db/migrate/20160602232926_add_note_available_to_products.rb
db/schema.rb
spec/controllers/instruments_controller_spec.rb
spec/features/placing_an_order_spec.rb
spec/features/purchasing_a_reservation_spec.rb

* Refactor cart form
* Show note on order receipt
* Clean up unnecessary method on InstrumentsController (ProductsCommon could handle it)
* Move note field into same cart row. This enhances the visual connection between
the note and the order detail. It was getting a little confusing when you have
bundles where one item has a note field, and another doesn't.

[#119570781] Add note to cart form for users

---

app/models/product.rb
spec/controllers/users_controller_spec.rb

This removes a stray `scope` missed during the Rails upgrade. It also adds some tests for `UsersController#access_list`, which relies on `Product.group_by_type`.

[#126615] Restore User access list

---

app/assets/javascripts/timeline.js

This sets the `switch` param on relay Ajax requests to "on" if the relay checkbox (switch) is checked, and "off" if it is not.
Before Rails 4 and related jQuery upgrades, this needed to be the opposite; the `:checked` value of the checkbox did not appear to be updated immediately on click, so this used the opposite value.

[#126619] Set relay "switch" param to checked value

---

app/assets/javascripts/app/manage_orders.coffee

See https://github.com/tablexi/nucore-open/pull/155 for where this
broke. We were trying to fix a 500 error when the ajax was triggering
with an empty quantity. However, this then ignored the call for AM/PM
and date changes.
This now just makes sure there is at least something in the field. If
you do something silly like type in a non-numeric into quantity, the
quantity and pricing changes get thrown away by the backend (see the
change in PR #155).

[#126687] AM/PM and Date changes did not trigger pricing update

---

vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/vue_bootstrap.coffee
vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/vue_well_plate.coffee
vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/vue_well_plate_app.coffee
vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/well_plate.js
vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/well_plate_builder.js.coffee
vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/well_plate_colors.coffee
vendor/engines/sanger_sequencing/app/assets/stylesheets/sanger_sequencing/application.scss
vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/batches/new.html.haml
vendor/engines/sanger_sequencing/spec/javascripts/well_plate_builder_spec.js.coffee

This extends from #669 and adds some refactoring including moving the color array into JS. This allowed me to get rid of the magic number that needed to be know between CSS and JS.
It also changes how the rendering of a well plate works so we only "render" whenever we add or remove a submission vs what it was doing before of rendering on every cell when called with `sampleAtCell`. Once we got into multiple plates, I was starting to see some UI slowness. This is much snappier.

[#120869561] Sanger sequencing - support multiple plates

---

spec/rails_helper.rb

This is why our stack traces in engine test failures are so unhelpful.
All we were seeing was the `rails_helper.rb` line, but nothing within
the engine.

Don't exclude vendor from RSpec's stack traces

---

app/controllers/instruments_controller.rb

After the ProductsCommonController refactor of
https://github.com/tablexi/nucore-open/pull/643 the `:schedule` option
of `admin_tab` got lost.

[#126813] Instrument Schedule tab lost header nav

---

config/initializers/csv_renderer.rb
vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/vue_well_plate.coffee
vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/well_plate_builder.js.coffee
vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/well_plate_sample.js.coffee
vendor/engines/sanger_sequencing/app/assets/stylesheets/sanger_sequencing/application.scss
vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/admin/batches_controller.rb
vendor/engines/sanger_sequencing/app/models/sanger_sequencing/ability.rb
vendor/engines/sanger_sequencing/app/models/sanger_sequencing/well_plate.rb
vendor/engines/sanger_sequencing/app/presenters/sanger_sequencing/well_plate_presenter.rb
vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/batches/index.html.haml
vendor/engines/sanger_sequencing/config/locales/en.yml
vendor/engines/sanger_sequencing/config/routes.rb
vendor/engines/sanger_sequencing/spec/features/batches/creating_a_batch_spec.rb
vendor/engines/sanger_sequencing/spec/presenters/sanger_sequencing/well_plate_presenter_spec.rb

This modifies the batch creation so that reserved wells in unused rows don't get persisted: they appear as if they're blank in the well-plate export. But they still show up as "reserved" when creating the well plate.
It also adds a `ActionController::Renderer` for CSV to the root app so we can do `render csv: ObjectRespondingToToCSV.new, filename: "somefilename"`. There are a few places elsewhere in the app I'd like to swap this in in place of CSVHelper, but that seemed outside the scope of this PR.
There are a few fields in the CSV that I'm not really sure if they're supposed to be dynamic or not. I figure we can address those when we meet with Chris next week.

[#120869939] Download Sanger Sequencing template file

---

app/helpers/products_helper.rb
spec/controllers/services_controller_spec.rb

If you submit the product form without a url_name, the form would error
while trying to build the hint.
```No route matches {:action=>"show", :controller=>"services",
:facility_id=>"nugene", :id=>""} missing required keys: [:id]
app/helpers/products_helper.rb:44:in `product_url_hint'
```

[#126870] Do not error on blank product url names

---

app/views/admin/products/index.html.haml

This was broken in https://github.com/tablexi/nucore-open/pull/565 when
we went to share the index view between the different product types.

[#126814] Instrument link should take you to schedule, not details

---

app/controllers/concerns/nav_tab.rb
app/controllers/my_files_controller.rb
app/controllers/order_details_controller.rb
app/helpers/routes_helper.rb
app/models/user.rb
app/presenters/nav_tab/link_collection.rb
app/views/my_files/index.html.haml
config/locales/views/en.my_files.yml
config/locales/views/en.stored_files.yml
config/routes.rb
config/settings.yml
db/migrate/20160706195345_fix_product_column_on_results_files.rb
db/schema.rb
spec/factories/stored_files.rb
spec/features/my_files_spec.rb

The “My Files” tab contains both results files and uploaded order forms. It should only contain files attached to purchased orders (i.e. doesn’t not include uploaded files still in the cart).
The next step will be an extension point so that we can link to sanger sequencing forms.

[#123935331] My Files Tab

---

app/views/notifier/order_receipt.html.haml
app/views/orders/receipt.html.haml
vendor/engines/sanger_sequencing/app/models/sanger_sequencing/submission.rb
vendor/engines/sanger_sequencing/app/presenters/sanger_sequencing/receipt_submission_presenter.rb
vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/submissions/show.html.haml
vendor/engines/sanger_sequencing/app/views/sanger_sequencing/orders/_samples_on_receipt.html.haml
vendor/engines/sanger_sequencing/app/views/sanger_sequencing/submissions/_samples_table.html.haml
vendor/engines/sanger_sequencing/app/views/sanger_sequencing/submissions/show.html.haml
vendor/engines/sanger_sequencing/config/locales/en.yml
vendor/engines/sanger_sequencing/lib/sanger_sequencing/engine.rb
vendor/engines/sanger_sequencing/spec/features/purchasing_spec.rb

Includes the commits from #690 
This adds the sample listing to both the displayed order receipt and the one that is emailed out. I added a couple additional links to the facility and order. At some point, we really should do some styling to the email receipt.

[#119570751] Sanger sample listing on receipt

---

vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/well_plate_builder.js.coffee
vendor/engines/sanger_sequencing/spec/javascripts/well_plate_builder_spec.js.coffee

In the plate count, we weren’t accounting for the two reserved cells,
so if you had 95 or 96 samples added to a plate, the next plate was not
appearing.

Fix 95-96 samples would not show second plate

---

spec/factories/order_statuses.rb
spec/factories/products.rb
spec/support/helper_methods.rb

The factory change allows `FactoryGirl.create(:setup_instrument)` to work from the Rails console without having to load helper methods.

Rework OrderStatus factory to eliminate helper

---

app/controllers/facility_reservations_controller.rb
spec/controllers/facility_reservations_controller_spec.rb

This should correct the issue where correcting a form after a failed `create` would raise an exception.
To reproduce:
* As an administrator, visit `/facilities/:id/instruments/:id/reservations/new`
* Specify a zero-length reservation
* Submit the form
* Get an error screen
* Fill in a valid reservation length
* Submit the form

Make types consistent when creating AdminReservations

---

app/views/search/_create_new_user.html.haml
config/settings.yml

If the school doesn’t use a netid or other directory, then there’s no
need to go through that option when creating a user. This will now just
skip you straight to “Add External User”.
I didn’t think it was worth doing any additional disabling of routes
since it’s still fine if those routes work, this is just much more
efficient.
I’ll have another PR for DC that incorporates this change and changes some locales to make it less confusing for them.

[#121327715] Setting to allow skipping netid lookup

---

app/controllers/file_uploads_controller.rb
app/mailers/results_file_notifier_mailer.rb
app/models/email_event.rb
app/models/stored_file.rb
app/services/results_file_notifier.rb
app/views/results_file_notifier_mailer/file_uploaded.html.haml
config/locales/views/en.results_file_notifier.yml
db/migrate/20160715220430_create_email_events.rb
db/schema.rb
spec/mailers/previews/results_file_notifier_preview.rb
spec/models/email_event_spec.rb
spec/services/results_file_notifier_spec.rb
vendor/engines/sanger_sequencing/app/services/sanger_sequencing/sample_result_file_saver.rb

I decided to debounce email sending based on the order detail so that I could include the order detail link in the email. If we went with a per-facility or global per-user then it wouldn't be a good idea to include the OD link; only the My Files link would be good. 
I also debounced it at 24 hours. That could pretty easily be extracted into a setting if we want.
This is feature-flagged on My Files right now (mainly because I wanted to include the my files links), but that could change as well.

[#125568281] Send notification on results file upload

---

app/controllers/offline_reservations_controller.rb
app/models/order_detail.rb
app/models/reservation.rb
spec/controllers/offline_reservations_controller_spec.rb
spec/models/order_detail_spec.rb

[#126391] Flag ongoing reservations as problem orders when taking an instrument offline

---

app/assets/javascripts/app/reservations.coffee
app/models/product.rb
app/support/products/scheduling_support.rb
app/support/reservations/relay_support.rb
app/views/reservations/_js_variables.html.haml
spec/models/instrument_spec.rb
spec/models/product_spec.rb

This should prevent "Create & Start" as well as starting reservations for an instrument that is offline. It includes cherry-picks from #696 to bring in the `Product#online?` and `#offline?` methods.

[#126389] Prevent reservation start when the instrument is offline

---

app/services/stored_file_zipper.rb

If there are duplicate filenames being downloaded, the mac unarchiver
will break with “Error 1 - Operation not permitted”. If you use the
command line `unzip`, it will expand it, but will be missing a file.
This appends a -N to the end of the filename before the extension. I’m
planning another PR that will prevent duplicate filenames at upload
time.

[#123935371] Handle duplicate filenames in zip download

---

app/controllers/reservations_controller.rb
spec/controllers/reservations_controller_spec.rb

As a facility admin, if you add a reservation to an existing order, the
“The user you are ordering for is not on the authorized list for this
instrument” message was checking the acting user (i.e. the facility
admin’s access) instead of the order’s user.

[#127148] Do not show not authorized message when adding to an order

---

app/controllers/offline_reservations_controller.rb
app/helpers/facility_reservations_helper.rb
app/models/offline_reservation.rb
app/support/reservations/validations.rb
app/views/instruments/schedule.html.haml
app/views/offline_reservations/_form.html.haml
config/locales/en.models.yml
config/locales/en.yml
db/migrate/20160720200222_add_category_to_reservations.rb
db/schema.rb
spec/features/managing_instrument_offline_spec.rb
spec/models/offline_reservation_spec.rb
spec/models/reservation_spec.rb

`OfflineReservation::CATEGORIES` is a hardcoded list but the idea is to eventually turn this into something more flexible (and admin-editable).
The categories for offline reservations appear in the CRUD interface as well as the admin reservation list, but nowhere else yet. They will appear in reports.

[#126393] Support offline reservation categories

---

db/migrate/20100430184238_add_facility_order.rb
db/migrate/20100430222700_change_reservations.rb
db/migrate/20100512222847_set_order_states.rb
db/migrate/20100701183019_create_facility_accounts.rb
db/migrate/20100701232820_change_order_detail_status.rb
db/migrate/20101015210647_edits_for_invoicing_and_journaling_refacting.rb
db/migrate/20110411215240_create_price_group_products.rb
db/migrate/20110425225944_alter_order_details_drop_dispute_resolved_credit.rb
db/migrate/20130108221731_reservations_change_from_instrument_to_product.rb
db/migrate/20140908192950_create_delayed_jobs.rb
db/migrate/20150605165610_create_training_requests.rb
db/migrate/20151113205331_create_payments_received.rb
db/migrate/20160201171348_add_journal_cutoffs.rb
db/schema.rb
vendor/engines/projects/db/migrate/20160328144628_create_projects.rb
vendor/engines/sanger_sequencing/db/migrate/20160519030413_create_sanger_sequencing_submissions.rb

So we can do a full rake db:migrate from scratch.
This adds a few `null: false` to timestamp creations because that was the default in older rails versions. This will keep the schema diff minimal.
The big difference is in index names. I’m not sure there’s a good way to go about fixing that.

Fix migrations for Rails 4.2

---

vendor/engines/sanger_sequencing/app/assets/stylesheets/sanger_sequencing/application.scss
vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/admin/batches_controller.rb
vendor/engines/sanger_sequencing/app/models/sanger_sequencing/submission.rb
vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/batches/_submission_list.html.haml
vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/submissions/index.html.haml
vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/submissions/show.html.haml

This will allow the resource to identify if they need to do any special
handing such as always use full plate submissions as the only
submission in the batch.

[#126916383] Show product name on submission lists

---

config/schedule.rb

Without this, when rails loaded, it did not have an environment set, so
it was trying to load up the `development` database.

Explicitly set RAILS_ENV in schedule.rb

---

config/schedule.rb

This should prevent `curl` from producing progress output for the rolling-cancel `cron` job.

[#127184] Suppress curl progress meter in cron

---

app/assets/stylesheets/nucore.scss
app/views/shared/_footer.html.haml
config/locales/en.yml

DC as a much wider logo. This will handle it much better, including breakpoints.
I'm planning to use a PNG for DC. It feels a little weird to put the filename in the locales, but I settled on there so that it’s right next to the `logo_alt` translation and will be
clean to override.

[#115963269] Refactor footer for override

---

app/models/journal.rb
spec/models/journal_spec.rb

```
Mysql2::Error: Unknown column 'orders.facility_id' in 'where clause':
SELECT  journals.* FROM `journals` WHERE (orders.facility_id IN (1, 2,
3) AND `journals`.`is_successful` IS NULL  ORDER BY journals.created_at
DESC LIMIT 10 OFFSET 0
```

[#127212] Cross-facility journal view inaccessible in rails 4.2

---

app/controllers/price_groups_controller.rb
spec/controllers/price_groups_controller_spec.rb
spec/features/admin/price_group_management_spec.rb
spec/lib/ability_spec.rb

Users were receiving “Facility cannot be blank”. Appears to be an issue
stemming from removing `has_many :price_groups, finder_sql: …` into a
regular method.
https://github.com/tablexi/nucore-open/pull/631/commits/f0eb065598f716acbb06fc14cf94cad39191bb9d
Looks like we handled this for `OrderStatus`es in
https://github.com/tablexi/nucore-open/pull/631/commits/39c2c4f773484aced489d2146ea6822bd0642234
I chose to do one success feature spec at the lowest possible
permissions level and one failure spec at the highest possible level,
and left the rest of the levels to be handled by the Ability spec. I
would probably have only done the success feature spec, but there’s
some weird ability stuff in PriceGroup controller where new/create use
Facility as the ability’s resource, while the member …

[#127220] Could not create price groups for facility

---

app/views/shared/_head.html.haml

This will be used by DC for adding icon link tags. If we end up adding icons to other schools,
then I could see pulling the partial up and using a feature flag.

[#127295589] Add hook point in shared/head

---

db/schema.rb
vendor/engines/sanger_sequencing/db/migrate/20160519030413_create_sanger_sequencing_submissions.rb
vendor/engines/sanger_sequencing/db/migrate/20160802202924_fix_sanger_sequencing_submission_cascades_for_oracle.rb

Oracle doesn’t support ON UPDATE, and since it’s just the
auto-increment primary key, it’ll never change, so we don’t need to
worry about ON UPDATE.

Remove sanger sample ON UPDATE foreign key

---

Gemfile
Gemfile.lock
app/jobs/application_job.rb
app/jobs/file_processing_job.rb
app/models/concerns/async_file_processing.rb
app/views/admin/shared/_sidenav_global.html.haml
config/application.rb
config/locales/en.models.yml
config/locales/en.yml
spec/models/concerns/async_file_processing_spec.rb
spec/rails_helper.rb

This is going to be used by DC for their account uploads (it takes a minute or two to run). It will only allow one file to be in process at a time.
This also makes sure we're using the delayed job adapter for ActiveJob. Turns out that any of the emails we were sending using `deliver_later` were going out synchronously because we didn't turn this on.
I chose to have the job not raise an error on failure because it will continue to retry and we don't really want that in the case of bad input. I'm not currently exposing the error message as it's a backtrace. We'll see if errors become problematic, and if so then we can deal with it then.
I could see order imports being a good candidate to use this as well.

Support for asynchronous file processing

---

app/services/results_file_notifier.rb
config/settings.yml
spec/services/results_file_notifier_spec.rb

Originally it used `my_files`, but NU will keep `my_files` on and turn these
notifications off. If we can find a good way to add a checkbox or somehow make
the notifications optional, then NU might want it.

[#127182] Use different feature flag for notification on results file upload

---

Gemfile
Gemfile.lock

```
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
```

Upgrade sass-rails to 5.0.6 to prevent deprecation warnings

---

app/controllers/facility_orders_controller.rb
app/services/reports/querier.rb
spec/controllers/facility_orders_controller_spec.rb
spec/services/reports/querier_spec.rb

Prevent order details that were “added to” another order by the
facility staff, but were not complete from appearing in export raw.
These would be instrument orders that don’t have a reservation or
service orders where the order form has not been uploaded.
This takes care of it in two ways, either one would work on its own:
* Remove the `ordered_at` from the merge order. Now the querier won’t
find an ordered_at to search. Once the merge order
is ready, the order details are moved onto the main order and then the order is destroyed. So that `ordered_at` that got set when we created the merge order goes away.
* Force the query to only return purchased orders. The merge order is in `new` state.
The only thing I’d like to figure out is how to have it keep a null
order status until the …

[#130559] Exclude non-purchased "add-to" orders from export raw

---

app/models/reports/instrument_unavailable_report.rb
spec/controllers/reports/instrument_unavailable_reports_controller_spec.rb

This should format offline times in hours to two decimal places in all cases.

Format instrument downtime hours to 2 decimal places in reports

---

config/settings.yml
spec/services/results_file_notifier_spec.rb

The results_file_notifications uses my_files_url in the mailer, so if notifications
are enabled, My Files needs to be as well. This fixes a broken spec when my files
was off.
It might be good at some point to address this so the mailer only includes the
my files link if it's enabled, but that's for another time.

Fix specs when My Files is disabled

---

vendor/engines/sanger_sequencing/app/models/sanger_sequencing/sample.rb
vendor/engines/sanger_sequencing/app/services/sanger_sequencing/submission_updater.rb
vendor/engines/sanger_sequencing/spec/features/purchasing_spec.rb

Now, if you have blank customer sample ids at the end of the form, they no longer
get deleted. Instead, they'll get an error for "may not be blank".
This will help make things simpler in NU where the user might not be using the
default IDs (the core sample id is irrelevant to them).
This also adds a default ordering to Sample. MySQL returns ordered by id if no
ORDER BY is specified. Oracle does not do this, so the samples were getting out
of order there.

Sanger Sequencing: Don't delete blanks from end of sample list

---

vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/submissions_controller.rb

If there are relevant validation errors, they will be displayed by simple form
near the appropriate field. In open, the only validation is the customer_sample_id,
but NU will have a few more.

Do not display sanger submission form errors in flash message

---

app/mailers/concerns/offline_reservation_arguments.rb
app/mailers/offline_cancellation_mailer.rb
app/mailers/upcoming_offline_reservation_mailer.rb
app/views/offline_cancellation_mailer/send_notification.html.haml
app/views/offline_cancellation_mailer/send_notification.text.erb
app/views/upcoming_offline_reservation_mailer/send_offline_instrument_warning.html.haml
app/views/upcoming_offline_reservation_mailer/send_offline_instrument_warning.text.erb
config/application.rb
config/locales/views/en.offline_cancellation_mailer.yml
config/locales/views/en.upcoming_offline_reservation_mailer.yml

This updates the offline notifications to handle the case where `Facility#email` is `nil`.
When `email` has a value, the emails should read "Please contact _Facility_ for more information at _address@example.com_" as before. If the `email` field is unset, it should read "Please contact _Facility_ for more information."
This change also consolidates common argument hashes into a helper.

[#126392] Handle empty facility email in offline notifications

---

app/views/facilities/_product_list.html.haml

This adds the same red warning icon (with tooltip)  to the product listing page for offline instruments as seen on the daily view:

[#126394] Add warning icon to offline instruments in product listings

---

app/presenters/reservation_user_action_presenter.rb
app/support/reservations/moving_up.rb
spec/models/reservation_spec.rb
spec/presenters/reservation_user_action_presenter_spec.rb

Commit cba973e should address the specific issue @nutodd brought up: if the instrument is down, the user should not see a "Begin Now" link.
Since `Reservation#can_move?` was only being used to determine if "Begin Now" should appear or not, this changes the method name in 8a54658 to `#startable_now?`, which sounded more appropriate to how we use it (it reads a bit less awkwardly in tests too).

{#126389] Show reservation "begin now" link only if the instrument is online

---

app/controllers/order_imports_controller.rb
app/views/admin/shared/_tabnav_order.html.haml
lib/ability.rb
spec/controllers/order_imports_controller_spec.rb

Also fixes an issue where facility staff/senior staff could access the
import if they had the URL. It was only protected by not showing the
tab.

[#130862] Facilty Admin/Directors did not have access to error reports

---

app/helpers/products_helper.rb
config/environments/development.rb
config/environments/test.rb
config/locales/en.yml

This came about because text_helpers was not translating the "-" in "in-use" but "in use" was not accurate given an instrument might be unavailable because it's offline.
With this change:
* If an instrument is available and online, the tooltip should be "Available"
* If an instrument is offline, the tooltip should be "Instrument is down"
* If an instrument is otherwise unavailable, the tooltip should be "Unavailable"
Though it may not have caught this "in-use" missing translation, this change also configures the ~~`test` and~~ `development` environment~~s~~ to raise exceptions on missing translations.

 [#126394] Update public schedule calendar icon tooltips

---

app/services/order_details/param_updater.rb
spec/controllers/order_management/order_details_controller_spec.rb

The assigned user was not being persisted because the parameter was not
being permitted through.

[#131810] Permit assigned user parameter

---

app/helpers/tab_count_helper.rb
db/schema.rb
vendor/engines/sanger_sequencing/README.md
vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/vue_well_plate_editor_app.coffee
vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/well_plate_builder.js.coffee
vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/admin/batches_controller.rb
vendor/engines/sanger_sequencing/app/models/sanger_sequencing/batch.rb
vendor/engines/sanger_sequencing/app/models/sanger_sequencing/batch_form.rb
vendor/engines/sanger_sequencing/app/models/sanger_sequencing/product_group.rb
vendor/engines/sanger_sequencing/app/models/sanger_sequencing/submission.rb
vendor/engines/sanger_sequencing/app/models/sanger_sequencing/well_plate_configuration.rb
vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/batches/index.html.haml
vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/batches/new.html.haml
vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/shared/_sidenav.html.haml
vendor/engines/sanger_sequencing/app/views/sanger_sequencing/admin/submissions/index.html.haml
vendor/engines/sanger_sequencing/config/locales/en.yml
vendor/engines/sanger_sequencing/config/routes.rb
vendor/engines/sanger_sequencing/db/migrate/20160812230426_add_sanger_product_groups.rb
vendor/engines/sanger_sequencing/spec/features/batches/creating_a_batch_spec.rb

This adds a new table that associates a Product with a "group", which in this case will only be "fragment", or nothing. The batches#new splits out the submissions based on which group the product is in. This will allow us to have multiple products in a group if we need to allow separate pricing. Fragment Analysis does not include control wells.
Once the batch is submitted it now has a group associated as well so it can be split into two separate views. 
The piece that is not done is a different plate file. I wanted to get some eyes and feedback on this before I moved forward to that piece.

[WIP] [#130628] Fragment Analysis

---

db/schema.rb
vendor/engines/sanger_sequencing/app/models/sanger_sequencing/product_group.rb
vendor/engines/sanger_sequencing/db/migrate/20160812230426_add_sanger_product_groups.rb

The original name was too long for oracle.
I couldn’t think of a good way to add a new migration cleanly. This hasn’t been merged downstream anywhere, so it’s just developer environments that may be affected. So before you do a rake db:migrate with this merged, you should do a db:rollback.

[#130628] Shorten table name of Sanger ProductGroup

---

app/models/facility.rb
app/models/user.rb
spec/controllers/facility_users_controller_spec.rb
spec/models/user_spec.rb

* Order detail popup assigned user dropdown
* New/In Process Orders assigned user dropdown
* Admin Facility Staff index - Mentioned in NU #126595, but there are a
couple other issues still left around duplicate behavior.

[#131810] Prevent duplicate users in staff lists

---

app/models/user.rb

`ORA-01791: not a SELECTed expression` because we're not SELECTing the
user_roles table. There's no real reason we're sorting by the role first.
Pulled up from https://github.com/tablexi/nucore-nu/pull/191

Fix Oracle error on loading facility staff (#191)

---

app/controllers/facility_accounts_controller.rb
app/models/account.rb

On the cross-facility tab, we were hitting 1000+ errors on oracle. This
view is still slow based on the #, but this will stop the errors.

[#132121] Handle more than 1000 accounts receivable

---

config/application.rb

The UIC load path was not in the correct order, but only in production. I could not figure out what was happening differently between there and stage, and why it has not been a problem for NU or DC.
I did figure out that `text_helpers` adds the subdirectories `**/*.{rb,yml}`. That happens after this initialization, and appeared to be loading everything again, so we would have `/en.yml` multiple times, which could be after the `override/en.yml`.
This now waits until after that initialization and forces the `override/` directory to happen at higher priority in the load path.
This is already in UIC, and I'm testing it on DC.

Update I18n load_path

---

app/controllers/reservations_controller.rb
app/services/reservation_creator.rb
spec/controllers/reservations_controller_spec.rb
spec/features/purchasing_a_reservation_spec.rb

The big problem is that the account assignment on `order_detail` was autosaving the reservation without enforcing the non-admin validations (`save_as_user`).
The first idea I tried was doing `update_column`s so callbacks didn't get triggered, but it turns out we do need validations.
Next idea was flipping `save` and `save_with_extended_validations` so the extended validations (in the future and within 14 day window) are enforced by default, but not when purchasing as an admin. However, too many of our tests rely on those validations not being enforced as part of setup.
This refactor makes sure that `reservation` is not built until the last moment possible.

[#127094] Normal users could place orders in the past

---

vendor/engines/sanger_sequencing/app/controllers/sanger_sequencing/submissions_controller.rb

The previous commit was cherry-picked out of NU, which was not running the sanger_sequencing engine specs (which it probably shouldn’t many features have been overridden there). This should fix the failure on master.

403 on Sanger Submission controller should 403 instead of error

---

app/controllers/reservations_controller.rb
app/models/order_detail.rb
app/models/reservation.rb
app/services/order_details/param_updater.rb
app/services/reservation_creator.rb
app/support/accessories/child_updater.rb
app/support/end_reservation_only.rb
app/support/order_details/price_checker.rb
app/support/order_uncanceler.rb
app/support/price_policy_mass_assigner.rb
lib/tasks/order_details.rake
spec/app_support/price_policy_mass_assigner_spec.rb
spec/controllers/order_management/order_details_controller_spec.rb
spec/models/order_detail_spec.rb
spec/services/accessories_child_updater_spec.rb
vendor/engines/c2po/spec/models/order_detail_spec.rb
vendor/engines/split_accounts/spec/models/reports/export_raw_spec.rb

If you change the account of an order, we were calculating the price policy based on the current time, not the fulfilled_at date. This removes the parameter from the `assigns_price_policy` method to make sure we don't run into this again.
The one time we do want to use current time is when canceling a reservation with fee, because we don't really have a fulfilled_at, so we should use the current time.
This also cleans up an unused argument in `assign_estimated_price`.
I have two pending tests for another issue: if you change the account of an order in the popup, and also modify the cost, we're recalculating the pricing in the before_save hook and overwriting whatever the user put in. That fix will likely come as a separate PR.

[#132309] Always use fulfilled at for price calculation

---

config/routes.rb

Got set to GET instead of PUT in the Rails upgrade.
We'll want to get this to UIC fairly quickly.

[#132463] Fix route to updating Scheduling Groups on access list

---

spec/controllers/order_management/order_details_controller_spec.rb

When we change accounts, in order to make sure we end up with valid
price policies, the new account needs to be in the same price group as
the old one. In open/nu it’s fine because of user price group
memberships, but in UIC, it’s only account memberships.

New account needs to be in same price group for UIC

---

app/controllers/orders_controller.rb
app/services/order_purchaser.rb
spec/controllers/orders_controller_spec.rb

Here's how to replicate:
* Order as another user
* Open the "More options" so you can see the order date fields
* Change the quantity
* Click "Purchase"
* You'll see "Quantities have changed. Please review updated prices then click "Purchase".", however the date set in "More options" will be stored as the ordered_at date, even though the order has not been purchased.
Also, UIC #121346
This is some pretty gnarly code (I’m pretty sure I wrote it :frowning:), and it didn’t seem worth more time than I had already spent on tracking down the issue.

[#126724] Prevent order_at from getting set on cart quantity change

---

app/controllers/facility_statements_controller.rb
config/settings.yml
spec/controllers/facility_statements_controller_spec.rb

https://pm.tablexi.com/issues/130782
This adds the ability to turn on setting a default start date under the create statements tab in billing.

[#130782] Adds feature tag for setting default start date

---

app/models/journal.rb
app/views/facility_journals/index.html.haml
spec/models/journal_spec.rb

https://pm.tablexi.com/issues/124051
The journal reference has a database length restriction, but this adds a validation so a reference that is too long for the db can't get past the validation.

[#124051] Add validation for journal reference length

---

app/models/order_detail.rb
app/views/facility_orders/show.html.haml
spec/models/order_detail_spec.rb

https://pm.tablexi.com/issues/124334
This restricts the price sum on the orders page based on whether the order status is cancelled.

[#124334] Restrict amount sum to non-cancelled orders

---

app/views/instruments/schedule.html.haml
vendor/engines/bulk_email/app/assets/stylesheets/bulk_email/application.scss
vendor/engines/bulk_email/app/controllers/bulk_email/bulk_email_controller.rb
vendor/engines/bulk_email/app/helpers/bulk_email/application_helper.rb
vendor/engines/bulk_email/app/views/bulk_email/bulk_email/_fields.html.haml
vendor/engines/bulk_email/app/views/bulk_email/bulk_email/_results.html.haml
vendor/engines/bulk_email/app/views/bulk_email/bulk_email/create.html.haml
vendor/engines/bulk_email/app/views/bulk_email/bulk_email/search.html.haml
vendor/engines/bulk_email/app/views/bulk_email/instruments/_send_mail_button.html.haml
vendor/engines/bulk_email/config/locales/en.yml
vendor/engines/bulk_email/lib/bulk_email/engine.rb
vendor/engines/bulk_email/spec/controllers/bulk_email/bulk_email_controller_spec.rb

This adds a "send mail" button to the instrument admin screen to the right of the online/offline toggle button. When clicked, it sends the user into the bulk email flow with the current instrument selected and a range of the next seven days filled-in as start and end dates.
If canceled from the recipient search screen, the user should be sent back to instrument admin.
After a successful send action, the user should be sent back to instrument admin.
If canceled on the mail composition screen, the user is sent back to the recipient search screen as before, and canceling from there should bring the user back to instrument admin.
As before, the user does not get redirected on CSV export though we may want to rethink that.

[#128124193 128124365 128124381] Add instrument down send mail button

---

app/models/bundle.rb

https://pm.tablexi.com/issues/130689
This updates the grouped options for select for the bundle products to properly group them under a single parent.

[#130689] Updates grouped options for select

---

app/controllers/statements_controller.rb
app/models/order_detail.rb
app/views/accounts/transactions.html.haml
app/views/facility_statements/index.html.haml
app/views/shared/_statements_table.html.haml
app/views/shared/_tabnav_account.html.haml
app/views/shared/transactions/_table.html.haml
app/views/shared/transactions/_table_inside.html.haml
app/views/statements/index.html.haml
config/routes.rb
spec/controllers/statements_controller_spec.rb

https://pm.tablexi.com/issues/125701
This gives users a column to download their statements for transactions if available. I made this part of the transactions table, so the users still had the benefits of search to find their statements. The link only shows if they have a statement to view.

[#125701] External user statements view

---

app/models/order_detail.rb
spec/models/order_detail_spec.rb

The signature of the `AASM::InvalidTransition` changed in the new
version, but we weren’t hitting this code (because it should be truly
exceptional) so we didn’t know. Then we tried to update a quantity to
zero, and this blew up.
The save! happens shortly after this, so here we only need to do one
save (hence getting rid of the bang).

[#132794] Get rid of unnecessary error and bang method

---

vendor/engines/bulk_email/app/assets/stylesheets/bulk_email/application.scss
vendor/engines/bulk_email/app/helpers/bulk_email/application_helper.rb
vendor/engines/bulk_email/app/views/bulk_email/bulk_email/_fields.html.haml
vendor/engines/bulk_email/config/locales/en.yml

This includes #782; the feature is in 59046c3.
This adds 3 links that fill in the bulk email recipient search form with some possibly useful date ranges: the last 90 days, the last year, and next month. I expect these to change after client feedback.
These are real links, not JavaScript-driven. I considered JS, but making them standard links updates the recipient list more or less for free.

[#128124251] Add links to select date ranges for bulk email recipient search

---

vendor/engines/bulk_email/app/assets/stylesheets/bulk_email/application.scss
vendor/engines/bulk_email/app/views/bulk_email/bulk_email/_results.html.haml

This should fix a button layout issue I didn't see until testing with nucore-nu's skin.
Here's the "before":
<kbd>![screen shot 2016-10-17 at 4 22 24 pm](https://cloud.githubusercontent.com/assets/46662/19456219/03d5fec0-9486-11e6-962c-8c4f6d7f12d4.png)</kbd>
And the "after":
<kbd>![screen shot 2016-10-17 at 4 22 44 pm](https://cloud.githubusercontent.com/assets/46662/19456225/0ad1739e-9486-11e6-93a0-056ef6e936a1.png)</kbd>
Using `direction: rtl` felt weird but it works, and also removes excess right-padding we got when not displaying the "Compose Mail" button (that is all non-global-admins, for now). I picked it up from http://stackoverflow.com/a/26493444.

Left-align bulk email buttons on the recipient search result screen

---

app/controllers/facility_reservations_controller.rb
app/helpers/facility_reservations_helper.rb
app/models/admin_reservation.rb
app/models/offline_reservation.rb
app/models/reports/instrument_unavailable_export_raw.rb
app/models/reports/instrument_unavailable_report.rb
app/models/reservation.rb
app/support/reservations/validations.rb
app/views/facility_reservations/_reservation_fields.html.haml
app/views/instruments/schedule.html.haml
config/locales/en.yml
spec/controllers/reports/instrument_unavailable_reports_controller_spec.rb
spec/factories/reservations.rb
spec/models/reservation_spec.rb

https://pm.tablexi.com/issues/132076
This allows adding a category on the admin side to a reservation, to indicate blocking off an instrument for a certain period of time.

[#132076] Allows admin to add optional category to reservation

---

vendor/engines/bulk_email/app/services/bulk_email/content_generator.rb

Looking at some test email, I think it looks better and is more readable with a blank line between the greeting and body.

[#128124251] Add space between the greeting and body in bulk emails

---

app/models/order_detail.rb
app/services/order_details/param_updater.rb
spec/controllers/order_management/order_details_controller_spec.rb

We use an ajax call to adjust pricing in the order detail popup, so the
facility staff will see the price changes from an account change, and
they can override that pricing before submitting.

[#132309] Do not auto-assign pricing when using the popup

---

app/helpers/timeline_helper.rb
app/models/order_detail.rb

https://pm.tablexi.com/issues/98768
We want cancelled orders with cost to have a canceled status, not complete, and this fixes that; then they no longer show in the daily view schedule.

[#98768] Hiding cancelled orders with cost

---

vendor/engines/sanger_sequencing/app/presenters/sanger_sequencing/well_plate_presenter.rb
vendor/engines/sanger_sequencing/spec/presenters/sanger_sequencing/well_plate_presenter_spec.rb

The plate_mode argument is coming in as either nil or a blank string
because it’s coming from the `group` field on batches. That was causing
`NoMethodError: undefined method `keys' for #<String:0x00000009d8b6f8>`
on production, and a missing translation in development.

[#132878] Fix default Sanger batch download

---

vendor/engines/bulk_email/app/assets/javascripts/bulk_email/bulk_email.js.coffee
vendor/engines/bulk_email/app/helpers/bulk_email/application_helper.rb

This changes the behavior of the "quick links" for selecting date ranges on the bulk email recipient search screen to just update the date fields without a page reload, to preserve other form values.

[#132896] Update date ranges without a page refresh

---

app/controllers/users_controller.rb
app/models/user.rb

https://pm.tablexi.com/issues/132462
I am guessing that this is occurring because of an ActiveRecord Relation size/count problem, due to the complex query that returns the users being counted. This seems to be an issue within the will_paginate gem (see: https://github.com/mislav/will_paginate/issues), so I don't know how much I want to do beyond this, unless we want to swap the gem out with kaminari. 
This is a hack that should fix the pagination page count issue, by turning the ActiveRecord relation into an array.

[#132462] Fix pagination count issue

---

app/models/order_detail.rb
app/services/transaction_search/date_range_searcher.rb
config/locales/views/admin/en.transaction_search.yml
spec/models/order_detail_spec.rb

https://pm.tablexi.com/issues/132384
This allows you to use `reconciled_at` for an option on the date range search for order details.

[#132384] Adds reconciled filter to date range field

---

app/views/order_management/order_details/edit.html.haml

Useful after #793 which adds a `reconciled_at` filter.
Couple notes:
* Some older reconciled orders do not have `reconciled_at` because we didn't really
know when they were reconciled.
* I'm only showing the date part because most orders are reconciled via journals
which only have a date part, not a time part.

[#132384] Show reconciled date on order popup

---

app/views/instruments/schedule.html.haml

This was a missed `TODO` that should have been done as part of #795.

[#132895] Remove global admin check from the admin reservation listing

---

vendor/engines/bulk_email/config/locales/en.yml
vendor/engines/bulk_email/spec/services/bulk_email/content_generator_spec.rb

This change updates the canned text to be the same for all instrument down categories, but leaves the door open for different messages based on category if needed.

[#126819] Standardize on a general bulk email instrument offline message

---

app/views/facility_accounts_reconciliation/_action_row.html.haml

Pulled up from https://github.com/tablexi/nucore-nu/pull/206

[#132927] Prevent double click on Reconcile Orders

---

app/controllers/users_controller.rb
config/locales/views/admin/en.users.yml
spec/controllers/users_controller_spec.rb

This came about because we found a couple NetIDs that share the same
email, which was causing a translation not found error. The message
will now also include any validation messages.

[#133080] Fix translations on user create failures

---

app/controllers/users_controller.rb
config/initializers/devise.rb
spec/controllers/users_controller_spec.rb

When creating a new external user, any surrounding whitespace should be
ignored when looking up the user as well as when it creates the user.
This had caused a problem for DC where one of their users was unable to
log in, and also because email and username did not match, were unable
to use the forgot password feature.

[#133125] Prevent creation of usernames with extra whitespace

---

vendor/engines/projects/app/models/projects/order_extension.rb
vendor/engines/projects/app/views/projects/shared/_select_project.html.haml
vendor/engines/projects/spec/features/placing_an_order_on_a_project_spec.rb
vendor/engines/projects/spec/features/reserving_an_instrument_on_a_project_spec.rb
vendor/engines/projects/spec/models/projects/order_extension_spec.rb

What was happening is the project_id was being set in the reservation
controller, but then when it redirects to Order#purchase, the
project_id was being reset to NULL.
I discovered this because the newer `.show-for-print` was erring out on
this view.
This also adds feature specs for ordering with a project.

[#133153] Project not persisting on reservation creation

---

app/controllers/users_controller.rb

This was ultimately fixed by PR #780, where ordered_at was being set on
unpurchased orders. There were a few leftover orders still in that
state. I manually set their ordered_at to nil on prod.
This PR cleans up the scopes to use more standardized ones.

[#133007] Unpurchased orders were appearing on user view

---

vendor/engines/bulk_email/app/controllers/bulk_email/bulk_email_controller.rb
vendor/engines/bulk_email/spec/controllers/bulk_email/bulk_email_controller_spec.rb

This should solve the problem of losing bulk email "state" when running into a form error on the mail compose screen. It should also clean up the issue where a flash error message generated in that case was lingering beyond where it made sense to display.
I'm not super-pleased about `#populate_flow_state_params`. I added doc, but does it deserve an extraction?

[#130772] Keep bulk email state on compose form errors

---

vendor/engines/bulk_email/app/controllers/bulk_email/bulk_email_controller.rb
vendor/engines/bulk_email/app/mailers/bulk_email/mailer.rb
vendor/engines/bulk_email/app/models/bulk_email/delivery_form.rb
vendor/engines/bulk_email/app/services/bulk_email/content_generator.rb
vendor/engines/bulk_email/spec/mailers/bulk_email/mailer_spec.rb
vendor/engines/bulk_email/spec/models/bulk_email/delivery_form_spec.rb
vendor/engines/bulk_email/spec/services/bulk_email/content_generator_spec.rb

This changes bulk email logging so that it includes the unalterable "canned" parts of the subject and body along with user-entered text.
As a side-effect it ended up simplifying `BulkEmail::Mailer` quite a bit.

[#133346] Include boilerplate and user-entered content when logging bulk email content

---

app/assets/stylesheets/print.scss
app/helpers/facility_orders_helper.rb
app/views/order_management/order_details/_form.html.haml
app/views/order_management/order_details/_print_details.html.haml
app/views/order_management/order_details/_shared_details.html.haml
app/views/order_management/order_details/edit.html.haml
vendor/engines/projects/app/views/projects/shared/_project.html.haml
vendor/engines/projects/lib/projects/engine.rb

https://pm.tablexi.com/issues/130583
This creates a separate print view for the details normally displayed in the form for printing. This also removes the now unneeded styles from the print file.

[#130583] Creates separate print view

---

app/support/accessories/accessorizer.rb
spec/controllers/accessories_controller_spec.rb

The symptom as described by NU was “there are 5 orders that are marked
as completed but have not moved to Send Notifications. The color of
their pricing is still the orange yellow and not green”.
Here is a way to reproduce:
* Complete a reservation on an instrument that has accessories
* Find the order on "All Transactions"
* Click into the order (not order detail)
* Click the + to "Add Accessories"
* Add an accessory
* The new order detail does not have a fulfilled_at or get its pricing
assigned. It also is in state "new", but it is in the correct
"Complete" order status.

[#133148] Accessories not getting pricing and fulfilled_at set

---

app/controllers/facility_accounts_controller.rb
app/views/shared/_statements_table.html.haml
spec/controllers/facility_accounts_controller_spec.rb
spec/factories/users.rb

Related to #784 and #787, facility staff were getting 403s when trying
to download statements. `statement_path` is a alias to
`facility_account_statement_path`.
When testing, we should make sure all of these views have access to
their statements:
* as a PI looking through “My Payment Sources” (this should be the one
place we use `account_statement_path`.
* as a facility admin, director
* Under “Statement History”
* Under “Payment Sources”…”Statements”
* as a billing admin looking under the cross facility tab under
“Statement History”

[#133375] Fix access to statements for facility admin/director

---

app/views/order_management/order_details/_shared_details.html.haml

https://pm.tablexi.com/issues/130583
This fixes the padding on the modal for order detail editing that went away when the print styles were changed.

[#130583] Add padding back to modal for order detail edit

---

app/views/facility_accounts/show_statement.html.haml
config/locales/en.models.yml
config/locales/en.yml
config/locales/views/en.facility_accounts.yml

https://pm.tablexi.com/issues/132856
This changes the text for Order Status to Current Order Status when attached to an order or order detail, for clarification.

[#132856] Changes order status to current order status

---

app/views/order_details/edit.html.haml

https://pm.tablexi.com/issues/126780
This uses the user that the order was placed for instead of the acting user to scope payment sources for the order detail editing.

[#126780] Change scope for AvailableAccountFinder

---

app/views/instruments/schedule.html.haml

https://pm.tablexi.com/issues/132887
This fixes the link for reservations on shared schedules by using the actual instrument the reservation is attached to for the link instead of the instrument page you are on.

[#132887] Fix links on shared schedules for admin reservations

---

app/models/statement.rb
app/services/global_search/statement_searcher.rb
spec/controllers/global_search_controller_spec.rb
spec/services/global_search/statement_searcher_spec.rb

https://pm.tablexi.com/issues/133457
This adds the ability to only enter the statement id and use the global search to find statements that way. If the search query does not have a hyphen, it looks by only id.

[#133457] Adds ability to search by statement id

---

app/models/order.rb
app/views/facility_orders/_merge_order.html.haml
app/views/orders/_form.html.haml
config/locales/en.yml

* As a facility staff/admin, add a service requiring an order form or a
reservation to an existing order
* You will now have a “The following order details need your
attention.“ listing
* Go to your cart
* The attention-needed order appears as your cart
* Remove the order detail
* Get `orders#remove (RuntimeError) "Can't modify frozen hash”` error
What was happening:
* The Order is destroyed by OrderDetailObserver#after_destroy
* In OrdersController#remove, we trying to set `order.account_id = nil`
on an already destroyed order.
The solution is to make sure the merge order is not considered when
pulling up your cart.
This also fixes some translation missing errors.

[#132637] Cart should not include merge orders

---

app/models/schedule.rb
app/support/products/scheduling_support.rb
app/views/shared/timeline/_instrument.html.haml
app/views/shared/timeline/_schedule.html.haml
spec/models/instrument_spec.rb

On the public timeline, if there were archived or hidden instruments,
the grey background was appearing even if there was only one visible
instrument. On the facility timeline view, archived instruments were
causing the same problem.
This also removes an unused method on Instrument.

[#133079] Hide grey background when archived/hidden instruments

---

spec/services/statement_creator_spec.rb

UIC does not have credit cards enabled. Instead, use the first statementable
payment source type.

Fix StatementCreator specs if c2po engine is not enabled

---

app/mailers/notifier.rb
app/models/account.rb
app/models/account_user.rb
app/support/notification_sender.rb
app/views/notifier/review_orders.html.haml
app/views/notifier/review_orders.text.erb
config/locales/en.notifier.yml
spec/app_support/notification_sender_spec.rb
spec/controllers/facility_notifications_controller_spec.rb
spec/mailers/notifier_spec.rb
spec/mailers/previews/notifier_preview.rb

~~~This includes #827; I'll rebase once that's merged.~~~
Rather than sending one notification per account, this sends one notification per user, noting which accounts the notification is about, and links the user to `/transactions/in_review`.
The notification sender spec got a bit of an overhaul and this adds a new mailer preview for `Notifier.review_orders`.

[#133351] Send one notification per account admin

---

app/views/reservations/new.html.haml

When adding a reservation to an existing order (i.e. by facility
staff), the “Cancel” button was not returning you to the expected
location and was instead causing an error.
`orders#remove (RuntimeError) "Can't modify frozen hash”`

[#132637] Fix behavior of cancel on merge order reservation

---

app/controllers/facility_orders_controller.rb
spec/controllers/facility_orders_controller_spec.rb

https://pm.tablexi.com/issues/125724
This sets the order detail ordered_by accurately for orders that are added to, using the current user instead of just defaulting to the user who placed the original order.

[#125724] Track ordered_by on the order detail level

---

config/locales/en.models.yml
config/locales/en.yml

https://pm.tablexi.com/issues/132856
This changes the locale to return "Current Order Status" for the humanized version of the model name.

[#132856] Fixes Current Order Status copy

---

app/services/available_accounts_finder.rb
app/views/order_details/edit.html.haml
spec/services/available_accounts_finder_spec.rb

https://pm.tablexi.com/issues/126780
This changes the scope so it only returns accounts that both the acting as user and the order detail user have access to.

[#126780] Fixes scope to return overlap of accounts

---

app/models/reservation.rb
spec/models/reservation_spec.rb

https://pm.tablexi.com/issues/121328
This allows you to edit the duration of a started reservation while you are within the grade period (which is automatically added to the reserve_start_at when you Create & Start a reservation right away.

[#121328] Allow editing of started reservation in the grace period

---

app/assets/javascripts/app/manage_instruments.coffee
app/views/instruments/_instrument_fields.html.haml
config/locales/en.yml

This updates the field "hint" text and adds a warning message when the field is zero or blank, explaining what that means.
It looks like this:
I fought with `simple_form` for a bit to try to get the warning to appear just to the right of the field instead but did not arrive there.

[#120321] Update reservation auto-cancel minutes field messaging

---

lib/ability.rb
spec/lib/ability_spec.rb
vendor/engines/split_accounts/app/models/split_accounts/ability_extension.rb
vendor/engines/split_accounts/spec/controllers/facility_accounts_controller_spec.rb

Account Managers previously had `:manage` rights to `Account` (covering all actions) with exceptions for `:suspend` and `:unsuspend`. This removes those exceptions.

[#133417] Grant Account Managers un/suspend Account in cross-facility context

---

spec/app_support/notification_sender_spec.rb
spec/controllers/transactions_controller_spec.rb

This is cherry-picked from https://github.com/tablexi/nucore-nu/pull/216. The results coming back from Oracle are correct but not necessarily in the same order as from MySQL.

Update orders-in-review tests to disregard array ordering

---

spec/controllers/facility_reservations_controller_spec.rb
spec/models/email_event_spec.rb
spec/models/instrument_spec.rb
spec/models/price_policy_spec.rb
spec/services/auto_canceler_spec.rb
spec/services/results_file_notifier_spec.rb

A few more execution-order time issues emerged after merging #841. I searched the code for `/\btravel(_to)?\b/` and believe this takes care of everything that should be using the `travel_to_and_return`/`travel_and_return` helpers instead.

Update travel/travel_to to use TimeHelper methods

---

app/controllers/instruments_controller.rb
app/views/instruments/schedule.html.haml
spec/controllers/instruments_controller_spec.rb

https://pm.tablexi.com/issues/132887
This fixes the instruments schedule to only show the reservations for that instrument in order to simplify the flow of editing reservations.

[#132887] Independent instruments

---

app/mailers/notifier.rb
spec/mailers/notifier_spec.rb

https://pm.tablexi.com/issues/133446
This adds the reply_to option to all facility related emails so they can communicate with the facility in a reply email. 
I *believe* this is all the spots that need it, but I can add it to any other they'd like the reply_to to direct to the facility.

[#133446] Adds reply to for facility email

---

app/support/auto_canceler.rb
config/environment.rb
lib/patches/oracle_enhanced_adapter.rb
spec/support/matchers/sql_matchers.rb

Issues in Oracle queries emerged after switching from TimeCop to Rails' built-in Time Helpers (because `travel`/`travel_to` always round to the nearest second).
These changes came out of https://github.com/tablexi/nucore-nu/pull/217.

Oracle-related query updates and refactoring

---

lib/tasks/reports.rake

https://pm.tablexi.com/issues/132371
This adds a task that returns a basic list for which instruments and price groups have overlapping price policies, and the ids of those price policies (in case we want to manually fix them in some way).

[#132371] Adds task for reporting on overlapping price rules

---

db/migrate/20170112204251_increase_delayed_jobs_handler_capacity.rb
db/schema.rb

This increases the size limit from 2^8 characters to 2^32 for MySQL.
For Oracle, this column is already a `CLOB`, with a size limit of 2**31 characters, so the migration makes no changes.

[#133731] Increase the size of the delayed_jobs.handler column for MySQL

---

spec/controllers/facility_notifications_controller_spec.rb
spec/controllers/orders_controller_spec.rb
spec/controllers/transactions_controller_spec.rb
spec/models/order_detail_spec.rb
spec/rails_helper.rb

We need to set a review period in the `#in_review` tests since we can't count on a review period being set in `Settings`.

Set and restore billing review_period in specs through rspec metadata

---

app/controllers/facility_notifications_controller.rb
app/models/order_detail.rb

The `OrderDetail.all_in_review` scope needs to `JOIN` the orders table to for references to `ordered_at` in transaction searches to work.
This also includes some scope refactoring and cleanup.

[#133966] Join orders to transactions in-review search queries

---

app/mailers/notifier.rb
spec/mailers/notifier_spec.rb
vendor/engines/bulk_email/app/mailers/bulk_email/mailer.rb
vendor/engines/bulk_email/app/models/bulk_email/delivery_form.rb
vendor/engines/bulk_email/spec/mailers/bulk_email/mailer_spec.rb

https://pm.tablexi.com/issues/133446
This adds the reply_to field to the bulk email and removes it from the emails where I mistakenly added it. 
We don't actually have the product id here unless we parse it from the search criteria, so I'm using the facility email. Another option I came across would be adding it to the bulk email form, so it's always customizable (totally doable), would love to hear if anyone has a preference.

[#133446] Reply to bulk email

---

app/controllers/price_policies_controller.rb
app/models/price_policy.rb
app/models/product.rb
spec/models/price_policy_spec.rb
spec/models/product_spec.rb

https://pm.tablexi.com/issues/132371
This fixes the view to only show newest price policies instead of the mistakenly overlapping ones together.

[#132371] Fix view to only show newest price policies

---

app/models/instrument.rb
app/support/products/scheduling_support.rb
app/support/reservations/validations.rb
app/views/instruments/_instrument_fields.html.haml
app/views/instruments/manage.html.haml
config/locales/en.models.yml
config/locales/en.yml
db/migrate/20161213173410_add_cutoff_time_to_products.rb
db/schema.rb
spec/models/instrument_spec.rb
spec/models/reservation_spec.rb
spec/models/reservations_validations_spec.rb

https://pm.tablexi.com/issues/133594
This allows users to set a cutoff time on an instrument that prevents users from making reservations that are less than that number of hours before the reservation (so the staff has time to prepare). You can still cancel the reservation.

[#133594] Implemented reservation cutoff time

---

app/controllers/facility_user_reservations_controller.rb
config/routes.rb
spec/controllers/facility_user_reservations_controller_spec.rb

When canceling an already-canceled reservation, the controller should behave to a client the same as it did when cancelling initially.

[#125660] Make reservation cancellation idempotent

---

app/assets/javascripts/app/merge_order_form.js.coffee
app/assets/stylesheets/app/chosen-override.scss
app/controllers/facility_orders_controller.rb
app/models/instrument.rb
app/models/order_status.rb
app/models/product.rb
app/models/service.rb
app/services/order_appender.rb
app/views/facility_orders/_merge_order_form.html.haml
app/views/facility_orders/show.html.haml
config/locales/en.yml
spec/controllers/facility_orders_controller_spec.rb
spec/factories/products.rb
spec/models/product_spec.rb

This includes general updates to the related controller, views and specs. Enough was happening in private controller methods when adding-to-order that it seemed appropriate to extract it to a service object. I think Code Climate might say it hasn't gone far enough.
A few other notes:
* The addition of a bottom margin on `chosen-container` was specifically to better align the fields on this form, but looking across the app I thought this tweak would make sense elsewhere, like in the report filters.
Without the margin:
With the margin:
* `fulfilled_at` is a date in the form, but a timestamp in the database, set to midnight local (app) time. Would something like noon be more reasonable?
* The order status select offers all available status values, but the state machine won't necessarily …

[#133383] Add optional note, fulfilled_at, and status fields to the facility order screen

---

app/views/facility_orders/_merge_order_form.html.haml

The note expansion PR (https://github.com/tablexi/nucore-open/pull/861) hasn't
gone in yet, and we need to do a release. This should get undone as part of that
PR.

Change note field in merge order to regular text field

---

Gemfile
Gemfile.lock
app/controllers/global_user_roles_controller.rb
app/services/user_finder.rb
app/views/global_user_roles/edit.html.haml
app/views/global_user_roles/index.html.haml
app/views/search/_results_table.html.haml
lib/ability.rb
spec/lib/ability_spec.rb

There's a change in how cancancan handles objects decorated with `SimpleDelegator`, in that it no longer does. This adds `UserPresenter` to `lib/ability.rb` along side the `User` `can`/`cannot` calls for this reason.
More discussion here: https://github.com/CanCanCommunity/cancancan/issues/255

[#133668] Upgrade the cancancan gem to v1.15.0

---

app/views/facility_facility_accounts/index.html.haml
config/locales/views/admin/en.facility_facility_accounts.yml

This should fix a missing translation on `.notice` I found in testing, and also adds whitespace between the account number and "(inactive)" when the recharge chart string is not active.

Facility account view updates

---

config/settings.yml
lib/ability.rb
spec/lib/ability_spec.rb

UIC would like to evaluate this on stage. It shouldn't affect NU (the only BAs currently are staff who do testing). One active DC user is set as a BA. Should it get a feature flag?

[#125093] Activate the cross-facilty Users tab for Billing Administrators

---

doc/FACTORIES.md
doc/coding_standards.md

I found these changes from about 6 months ago while I was cleaning up old branches. I think they still hold.
* Using locales
* View/engine notes about being excluded from rubocop
* Using view hooks
* Remove note about Rails 3.2 TODOs
* Update factories doc for version and hash syntax
* Remove "Refactor Scopes" section now that we're on 4.2
* Add links to decorator preferences
* Improve guidelines on commits and pull requests

Update developer documentation and guidelines

---

app/helpers/products_helper.rb
app/views/admin/shared/_product_manage.haml
app/views/admin/shared/_tabnav_product.html.haml
app/views/instruments/edit.html.haml
app/views/instruments/new.html.haml
app/views/items/edit.html.haml
app/views/items/new.html.haml
app/views/services/edit.html.haml
app/views/services/new.html.haml

As I was working on spiking adding a new product type, I found several
discrepancies between the item/service/instrument new/edit views. This
brings them closer together. There is obviously further DRY to do as
item/new and service/new are identical as well as their edit views. and
their show/edit views are now very similar.
ProductsCommonController sets a `@product` variable, so it was trivial
to switch to that. There were also some discrepancies is what was one
level up from the details_field partial which led some views to have
some additional padding that shouldn’t have been there.
The longer-term goal would be to further clean these up as we add new product
types, but this seemed like a good first step.

Homogenize product new/edit views

---

app/assets/javascripts/app/detail_notes.coffee
app/assets/stylesheets/app/cart.scss
app/assets/stylesheets/app/order_details.scss
app/assets/stylesheets/app/order_management.scss
app/assets/stylesheets/nucore.scss
app/models/order_detail.rb
app/views/facility_orders/_merge_order_form.html.haml
app/views/facility_orders/index.html.haml
app/views/facility_reservations/index.html.haml
app/views/facility_user_reservations/index.html.haml
app/views/order_management/order_details/_form.html.haml
app/views/orders/_cart_row.html.haml
app/views/shared/_order_detail_cell.html.haml
app/views/shared/_order_detail_note.html.haml
app/views/shared/_order_details_table.html.haml
app/views/shared/_reservations_table.html.haml
app/views/shared/transactions/_table_inside.html.haml
config/locales/views/en.order_details.yml
db/migrate/20170123183841_change_note_limit_for_order_details.rb
db/schema.rb
spec/app_support/order_row_importer_spec.rb

https://pm.tablexi.com/issues/134059
This allows more space for order detail notes (no longer restricted to 100 characters, now up to string length of 255). I believe I fixed all views for longer notes, but it's possible I missed some, so if you see anything, just let me know.

[#134059] More space in notes

---

app/controllers/users_controller.rb
app/models/user.rb
app/views/users/_form.html.haml
app/views/users/_form_head.html.haml
app/views/users/edit.html.haml
app/views/users/new_external.html.haml
app/views/users/show.html.haml
config/locales/views/admin/en.users.yml
config/routes.rb
lib/ability.rb
spec/controllers/users_controller_spec.rb
spec/lib/ability_spec.rb

https://pm.tablexi.com/issues/134051
This adds functionality for facility operators updating users' email (same as username), first name, and last name, and non-admin users cannot access it.  They can only edit external users.

[#134051] Admin edit users

---

app/controllers/file_uploads_controller.rb
app/helpers/routes_helper.rb
app/views/admin/shared/_tabnav_product.html.haml
app/views/file_uploads/index.html.haml
app/views/file_uploads/product_survey.html.haml
app/views/order_detail_stored_files/order_file.html.haml
config/locales/en.yml
config/routes.rb
lib/ability.rb
spec/controllers/file_uploads_controller_spec.rb

* Change "upload" to "index"
* Rename "uploader_create" to "upload_sample_results" to better reflect how its used.
There are still more routes to deal with, but this should cover the main Docs tab.

Move FileUpload routes into product resource so they can be reused more easily.

---

doc/HOWTO_ldap.md
doc/HOWTO_ldap.pdf

These are updates I made while configuring LDAP authentication.
The most significant change is probably that it is no longer necessary to install an LDAP server on Mac OS. The LDAP server that ships with the OS works. This change also removes the PDF version.

[#126401] Update LDAP documentation

---

bin/merge_describer
doc/HOWTO_forks.md

This updates the instructions to be more detailed for merging any changes from open into the other branches; next time someone new does one of these merges, this will walk them through the process a bit more step-by-step.

Update instructions for merging from Open

---

app/controllers/price_policies_controller.rb
config/locales/en.controllers.yml
spec/price_policies_controller_shared_examples.rb

https://pm.tablexi.com/issues/132371
This adds a helpful error message if you try to make a price policy for a product with an active applied price policy with the same start date.

[#132371] Returns helpful message on duplicate start date

---

spec/controllers/users_controller_spec.rb
spec/models/product_spec.rb
vendor/engines/bulk_email/spec/services/bulk_email/recipient_searcher_spec.rb

This updates the `UsersController` specs to use the `create_users` flag to determine if `User#edit` and `User#update` are available, and changes the `Product` model specs to not rely on user-based price groups, which are not available in the UIC fork.
This change should resolve the spec failures in https://github.com/tablexi/nucore-uic/pull/113 when merged.

Spec updates related to UIC

---

db/migrate/20170123183841_change_note_limit_for_order_details.rb

Found this when I tried to run on NU with hundreds of thousands of order details.

Speed up note varchar -> text migration

---

app/controllers/reservations_controller.rb
app/models/reservation.rb
app/support/products/scheduling_support.rb
app/support/reservations/moving_up.rb
spec/factories/reservations.rb
spec/models/instrument_spec.rb
spec/models/reservation_spec.rb

- https://pm.tablexi.com/issues/133594 (Dartmouth)
- https://pm.tablexi.com/issues/28901 (NU)
- https://pm.tablexi.com/issues/121867 (UIC)
Extending reservations behaves appropriately in conjunction with mandated advance reservations (cutoff hours).

[#133594] extending reservations for instruments with cutoff hours

---

Gemfile.lock

This includes upgrades of `addressable`, `capybara` and `websocket-driver` as dependencies.

[#134067] Upgrade poltergeist

---

app/models/journal.rb
app/models/order_detail.rb
lib/nucore.rb

Oracle has problems when doing `DISTINCT *` on a table containing CLOBs, which
we now do after changing `order_details.note` to a text field.

CLOB safe distinct

---

lib/ability.rb
spec/lib/ability_spec.rb

We saw behavior on UIC where the user edit link was available even though the `:create_users` feature was turned off. The link would then error, since the route did not exist in that context.
This PR corrects that behavior and adds specs verifying that the correct behavior occurs both when the feature is turned on and turned off.

user edit link appears only if feature is on

---

app/views/admin/shared/_tabnav_product.html.haml
app/views/file_uploads/product_survey.html.haml

https://pm.tablexi.com/issues/134955
The "Docs" and "Order Forms" product paths needed changes after the routing cleanup in #894.

[#134955] Update paths for file uploads

---

config/database.yml.oracle.template
db/migrate/20120510172358_add_bi_table.rb
db/migrate/20160415231343_clean_duplicate_reservations.rb
doc/HOWTO_docker.md
doc/HOWTO_ldap.md
doc/HOWTO_oracle.txt
docker/oracle/create_databases.rb
docker/oracle/setup.sh
docker/oracle/setup.sql
lib/tasks/demo_seed.rake

This is a pared down version of #436 from way back when. That branch sought to do a full environment with Docker. This only has instructions for getting the database set up and the necessary scripts. It assumes you'll be running the app in your native environment.
It also includes some updates for running `rake db:migrate` from scratch. It does not include the resulting Oracle-based `schema.rb`.
Meara and I can use this as a base for getting her NU environment up and running.

Instructions and scripts on running Oracle with Docker

---

app/views/admin/shared/_tabnav_users.html.haml

UIC has manage_payment_sources_with_users: false. Their managers should still be able
to see this tab. When a manager clicks on the payment source, they get kicked over
to the Billing tab, which should be fine.
This was changed in #862.

[#135129] Re-enable Accounts tab within users for UIC

---

app/controllers/application_controller.rb
app/controllers/order_management/order_details_controller.rb
spec/controllers/instruments_controller_spec.rb

https://pm.tablexi.com/issues/133442
As a non-logged in user, the staff member is redirected appropriately when clicking an order link from an assigned staff email.

[#133442] Redirect to order assignment when not logged in

---

spec/controllers/facility_statements_controller_spec.rb

UIC allows their RRC accounts (NufsAccount) to be statemented. This spec was
failing when merged into their fork.

Fix Statment flash spec for when it is not using a CC account

---

app/views/shared/_head.html.haml
config/settings.yml

[#135273](https://pm.tablexi.com/issues/135273)
add:
```
feature:
responsive_on: true
```
to `settings.local.yml`

[#135273] feature flag for responsive site

---

app/controllers/concerns/belongs_to_product_controller.rb
app/controllers/product_access_groups_controller.rb
app/controllers/product_users_controller.rb
app/controllers/schedule_rules_controller.rb
app/models/concerns/products/schedule_rule_support.rb
app/models/instrument.rb
app/views/admin/shared/_tabnav_product.html.haml
app/views/product_access_groups/_fields.html.haml
app/views/product_access_groups/_headers.html.haml
app/views/product_access_groups/edit.html.haml
app/views/product_access_groups/index.html.haml
app/views/product_access_groups/new.html.haml
app/views/product_users/index.html.haml
spec/controllers/product_access_groups_controller_spec.rb
spec/lib/ability_spec.rb
spec/support/shared_examples/product_access_groups_controller_shared_examples.rb
vendor/engines/secure_rooms/config/routes.rb
vendor/engines/secure_rooms/spec/controllers/product_access_groups_controller_spec.rb

This pulls the product_access_group features (aka scheduling groups) out of instruments and into the ScheduleRule support module so the feature can be shared with SecureRooms. This PR also makes necessary changes so the controller can support multiple types of products by making a `BelongsToProductController` module that will load the product by service_id, item_id, etc.

[#140850111] Genericize Product Access Groups and apply to SecureRooms

---

spec/controllers/facility_statements_controller_spec.rb

We were getting failures in DC because they had the send_statement_emails feature
turned off.

Fix spec for statement sending flash message

---

app/assets/javascripts/timeline.js
app/views/shared/timeline/_instrument.html.haml

This was causing JS errors on the timeline view. I only noticed it because the relay switches weren’t appearing.
Related to #910.

Remove dead JS that was relying on draggable/droppable

---

.rubocop.yml
app/controllers/concerns/price_group_members_controller.rb
app/controllers/price_groups_controller.rb
spec/controllers/orders_controller_spec.rb
spec/models/order_detail_observer_spec.rb
vendor/engines/secure_rooms/app/controllers/secure_rooms/card_numbers_controller.rb

- enforce 1.9 hash syntax for symbol keys
- enforce expanded style for empty methods (i.e. no `def method; end`)

update rubocop to reflect in-use style conventions

---

spec/support/matchers/ability_matchers.rb

Introduced in #931, this is intended to test on a block if it's given, otherwise
use the object. We don't actually use the block version of the positive assertion,
but we do use the negative. This was meant to be parallel to the negative version, but looks like I messed
it up.

Fix ability matcher

---

db/schema.rb
vendor/engines/secure_rooms/app/controllers/secure_rooms_api/scans_controller.rb
vendor/engines/secure_rooms/app/models/secure_rooms/card_reader.rb
vendor/engines/secure_rooms/app/presenters/secure_rooms/scan_response_presenter.rb
vendor/engines/secure_rooms/app/views/secure_rooms/card_readers/index.html.haml
vendor/engines/secure_rooms/config/locales/en.yml
vendor/engines/secure_rooms/db/migrate/20170405182534_add_table_token_to_card_readers.rb
vendor/engines/secure_rooms/db/migrate/20170405182534_add_tablet_token_to_card_readers.rb
vendor/engines/secure_rooms/spec/controllers/secure_rooms_api/scans_controller_spec.rb
vendor/engines/secure_rooms/spec/models/secure_rooms/card_reader_spec.rb

I went with `tablet_token` since that feels closer to what it is rather than an identifier. I left the API key the same since the doors service looks for that.

[#140895375] Add tablet token to card readers

---

app/models/schedule_rule.rb
app/support/reservations/validations.rb
spec/models/schedule_rule_spec.rb
vendor/engines/secure_rooms/app/controllers/secure_rooms_api/scans_controller.rb
vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/account_selection_rule.rb
vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/archived_product_rule.rb
vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/base_rule.rb
vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/operator_rule.rb
vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/requires_approval_rule.rb
vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/schedule_rule.rb
vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/verdict.rb
vendor/engines/secure_rooms/app/services/secure_rooms/check_access.rb
vendor/engines/secure_rooms/spec/controllers/secure_rooms_api/scans_controller_spec.rb
vendor/engines/secure_rooms/spec/factories/secure_room.rb
vendor/engines/secure_rooms/spec/services/secure_rooms/access_rules/account_selection_rule_spec.rb
vendor/engines/secure_rooms/spec/services/secure_rooms/access_rules/archived_product_rule_spec.rb
vendor/engines/secure_rooms/spec/services/secure_rooms/access_rules/operator_rule_spec.rb
vendor/engines/secure_rooms/spec/services/secure_rooms/access_rules/requires_approval_rule_spec.rb
vendor/engines/secure_rooms/spec/services/secure_rooms/access_rules/schedule_rule_spec.rb

* Users cannot log in outside of available schedule rules
* If schedule groups are enabled, the user needs to be part of a group for the current rule
* I also cleaned up a little bit on the access rules like making the account list and selected account optional.

[#140850873] Restrict secure rooms by schedule rule

---

lib/ability.rb

- https://pm.tablexi.com/issues/135084
The "Users" link was disappearing from the left nav in the reservations tab on users (`/facilities/:facility_id/users/:user_id/reservations`) due to an ability issue. This PR keeps "Users" in this tab's nav, consistent with the other tabs.

[#135084] fix users nav from reservations tab

---

app/models/user_role.rb
config/settings.yml
spec/models/user_role_spec.rb
vendor/engines/split_accounts/app/models/split_accounts/ability_extension.rb
vendor/engines/split_accounts/spec/controllers/facility_accounts_controller_spec.rb

NU wants only global admins, DC wants account managers to be able to as well.
The change for DC will adding `account_manager` to the new setting that lists the roles that are allowed to create split accounts.

[#135112] Setting to configure which roles can create split accounts

---

spec/controller_spec_helper.rb
spec/controllers/users_controller_spec.rb

Remove older shared context way of doing things, so it's no longer confusing
which style to use.

Use newer metadata-based feature-flags in testing

---

app/assets/stylesheets/application.scss
config/environments/development.rb
vendor/assets/stylesheets/jquery-ui-smoothness.css.erb
vendor/assets/stylesheets/jquery-ui.theme.md

We had problems on deployment because the image assets weren't in the hard-coded
paths we expected (including digest) when we updated to revert to the Smoothness
theme of previous jquery-ui versions. The noticeable was the previous/next month arrows on the date-picker widget.
Inspired by:
https://github.com/jquery-ui-rails/jquery-ui-rails/blob/master/app/assets/stylesheets/jquery-ui/theme.css.erb
The jquery-ui-rails repo has a complicated Rakefile that does similar building
from the "base" theme, but simpler instructions have been provided in
`vendor/assets/stylesheets/jquery-ui.theme.md`.
See #960 for the previous attempt to fix.

[#134079] Make jQuery-ui theme an ERB so it uses rails `image_tag` helper

---

db/migrate/20170308030632_change_schedule_rule_to_belong_to_product.rb

MySQL 5.6+ will rename the foreign key when renaming a column, but Mariadb 5.5
(which Dartmouth uses) triggers constraint validation errors.

Update migration to support mariadb 5.5

---

vendor/engines/secure_rooms/app/controllers/secure_rooms_api/api_controller.rb
vendor/engines/secure_rooms/app/controllers/secure_rooms_api/events_controller.rb
vendor/engines/secure_rooms/app/controllers/secure_rooms_api/scans_controller.rb
vendor/engines/secure_rooms/config/routes.rb
vendor/engines/secure_rooms/spec/controllers/secure_rooms_api/events_controller_spec.rb
vendor/engines/secure_rooms/spec/controllers/secure_rooms_api/scans_controller_spec.rb

This is intentionally basic, only setting up the endpoint and logging,
in order to unblock other work. Future changes in implement the storage
of these events.

[#140895293] Basic SecureRooms events API endpoint

---

app/controllers/orders_controller.rb

`orders#update_or_purchase (NoMethodError) "undefined method `destroy' for nil:NilClass"`
I'm not 100% how to replicate the error, but it appears that through some multiple
tab situation, there was a "Purchase" button available on the cart, even though
the order did not have a reservation on it. After failing and raising the error,
there was no reservation to destroy.
Looking at Lin's cart, there is one instrument in the cart with no reservation set. But the error did have `"commit"=>"Purchase"` in the params, so somehow the Purchase button was clicked.

[#135584] Prevent hard error when trying to purchase an instrument with no reservation

---

.haml-lint_todo.yml
app/views/reservations/_my_table.html.haml
app/views/reservations/list.html.haml
config/locales/views/en.reservations.yml

NU requested "Reserved For" to be changed to read "Reservation
(Edit/Extend)”.
`reservations_table` is not used anywhere else, so I removed it from
`shared`
I have a question out on if they want it for both Upcoming and All tabs, so that may change based on their feedback.

[#134005] Change column header on My Reservations

---

.gitignore
app/assets/javascripts/app/responsive_table.js.coffee
app/assets/stylesheets/app/tables.scss
app/assets/stylesheets/responsive.scss
app/views/global_search/_order_details.html.haml
app/views/global_search/_statements.html.haml
app/views/shared/_head.html.haml
spec/javascripts/fixtures/normal_table.html
spec/javascripts/helpers/jasmine-jquery.js
spec/javascripts/responsive_tables_spec.coffee

https://pm.tablexi.com/issues/135272
Search results changed for mobile screens based on the pattern suggested in https://css-tricks.com/responsive-data-tables/.
I’m not completely sold on repeating the header data in the cells for the responsive version (the css-tricks had the responsive headers in the CSS, which I _really_ didn’t like), but I thought that an array that was used in both places was actually less readable.

[#135272] Responsive Search page

---

app/views/orders/_form.html.haml
config/locales/en.yml

Also, remove the confirmation popup as it was deemed unnecessary and
added friction.

[#135761] Disable cart purchase button on submit

---

app/controllers/facility_reservations_controller.rb
app/support/reservations/date_support.rb
spec/controllers/reservations_controller_spec.rb
spec/models/instrument_spec.rb
spec/models/order_spec.rb
spec/models/reservation_spec.rb
spec/support/helper_methods.rb

These fields are no longer used: we only ever work with minutes. The
larger goal is to remove the Reservations::DateSupport module entirely
with something more sane and more generic.
The UI fields always submit a minutes value for the duration.
It’s not entirely clear why the unit field existed (it came from the
pre “Initial Fork” commit, so git blame is useless here. Possibly,
there was a dropdown allowing you to set the duration as “X hours”.
Since that no longer exists, there is no reason for the added
complexity of supporting multiple units.

Remove Reservation#duration_value/unit fields

---

app/views/product_users/_table.html.haml
app/views/product_users/index.html.haml
config/locales/en.yml
config/locales/views/admin/en.product_users.yml

Prior to #937, we were always setting the route for the `form_for` to
`facility_instrument_update_restrictions_path`, which would route, but
would be invalid. But services and items would never have schedule
groups so the submit would never appear, so we never had any problems.
In #937, we made it generic to support secure rooms, which also support
schedule groups.
A test around this would probably be a good idea, but I’d like to get it out there quickly.

[#135958] Fix error on item and service access list index

---

app/assets/stylesheets/responsive.scss

[#134671](https://pm.tablexi.com/issues/134671)
This PR is being submitted with the awareness that the green header background color gets split in two when the hamburger menu opens. To prevent this would require a *lot* of messy overrides on the way Bootstrap styles the header / menu, in both the small and desktop versions. It may also serve as a subtle indicator as to where the hamburger menu ends when it opens.

[#134671] force responsive nav background color

---

app/assets/javascripts/app/responsive_table.js.coffee
spec/javascripts/fixtures/normal_table.html
spec/javascripts/responsive_tables_spec.coffee

The first round of the JS only set the headers for the first row of the table, this should fix.

Bug fix for responsive tables

---

vendor/engines/secure_rooms/app/models/secure_room_price_policy.rb
vendor/engines/secure_rooms/spec/factories/secure_rooms_price_policies.rb
vendor/engines/secure_rooms/spec/models/secure_room_price_policy_spec.rb

I'm putting this into #997 so it's easier to see the diff. It's actually fairly trivial after that refactor.
I'm assuming that we'll test the actual assignment to an order detail as part of the scan out stories.
I'm also assuming that the specs in `PricePolicies::TimeBasedPriceCalculator` handle the majority of the edge and complicated cases, so I just did basic tests to make sure we're wired up properly.

[#144318485] Secure Room PricePolicy calculations

---

app/assets/stylesheets/responsive.scss
app/views/order_details/show.html.haml
app/views/shared/_order_details_table.html.haml
config/locales/en.yml

https://pm.tablexi.com/issues/135268
This makes the order and order detail page responsive. Notes:
The detail page had Quantity/Product as a two-column header, which I split because the colspan header was confusing the JavaScript creating the headers.

[#135268] Responsive order page and order detail page

---

.gitignore
app/assets/stylesheets/responsive.scss
app/views/my_files/index.html.haml

This one is straightforward -- the only thing to note is that it will push wide right if the filename is long.

[#135267] Responsive Files

---

app/views/accounts/index.html.haml

This didn't have a ticket, but I saw it as I was browsing, so make it responsive, making it a separate PR in case people have comments on the screen shot.

[#134410] responsive payment sources

---

app/assets/javascripts/app/responsive_table.js.coffee
app/assets/stylesheets/responsive.scss
app/views/reservations/_my_table.html.haml
config/locales/views/en.reservations.yml
spec/javascripts/fixtures/normal_table.html
spec/javascripts/responsive_tables_spec.coffee

The obvious problem here is the overflow of the caption "Reservation (Edit/Extend)". There's no particularly easy way to get that to wrap (because of how the responsive div is set up). Is shortening the header to "Reservation" an option?

[#135265] Fix for responsive tables in reservations

---

app/assets/javascripts/app/responsive_table.js.coffee
spec/javascripts/fixtures/normal_table.html
spec/javascripts/responsive_tables_spec.coffee

A blank cell makes the responsive table look bad, so this fixes it by adding a blank space to empty cells in the responsive JavaScript
This kind of shows it:

[#134410] Force Spaces In Responsive Tables

---

app/controllers/users_controller.rb
app/views/users/show.html.haml
spec/controllers/users_controller_spec.rb

The javascript on the front end will make sure the username and email match for external users.

[#133813] Admins should be able to update user's username

---

app/controllers/product_accessories_controller.rb
app/models/product.rb
app/views/product_accessories/index.html.haml
config/locales/en.models.yml
spec/controllers/product_accessories_controller_spec.rb

Bundles should not be able to be used as accessories.
They do not have their own price policies, and when they were getting set up as accessories, they would cause problems with reconciliation because they don’t have price policies.

[#133461] Prevent bundles as accessories 

---

app/assets/stylesheets/app/tables.scss
app/assets/stylesheets/responsive.scss
app/views/orders/_cart_row.html.haml
app/views/orders/_form.html.haml
app/views/orders/_product_description.html.haml
spec/javascripts/fixtures/normal_table.html

A couple of changes from the existing cart. These changes apply to both the responsive and non-responsive versions. 
* [Remove] is not a separate column, I’ve now put it before the name of the product (and made it bold). Putting it after the name is tricky because the name and upload are part of the same partial, but I could move it to all the different partials if we wanted.
* There’s now a thicker bold line between bundles, but not between products that are part of the same bundle.
Here's the responsive bit:
And the non responsive version

[#135266] Responsive cart:

---

app/models/order_detail/accessorized.rb
app/support/accessories/accessorizer.rb
lib/nucore.rb
spec/models/order_details/accessorized_order_detail_spec.rb

In Oracle, nulls are ordered differently than they are in MySQL. This
was causing accessories to appear before their parent in the order show
view.
| Order | Oracle         | MySQL       |
|------ | ------------ |------------|
| ASC   | NULLs last  | NULLs first |
| DESC | NULLs first | NULLs last |
Reference: http://www.sqlines.com/oracle-to-mysql/null_order_by
If we ever do Postgres support we might need to revisit this.
Problem:

[#136246] Fix order detail sorting for accessories in oracle

---

app/helpers/facility_orders_helper.rb
app/models/order_detail.rb
app/models/reservation.rb
app/models/time_data/null_time_data.rb
app/models/time_data/required_time_data.rb
app/views/order_management/order_details/_warnings.html.haml
app/views/shared/_problem_order_details.html.haml
config/locales/en.models.yml
spec/models/reservation_spec.rb
spec/models/time_data/null_time_data_spec.rb
spec/models/time_data/required_time_data_spec.rb
vendor/engines/secure_rooms/app/models/secure_rooms/occupancy.rb
vendor/engines/secure_rooms/spec/models/secure_rooms/occupancy_spec.rb

I did a grep for other calls to `order_detail_notices` and it looks like this is the only other spot
This issue was introduced through in #1007

[#144058895] Remove translation of problem description

---

app/assets/javascripts/app/manage_orders.coffee
app/controllers/journal_cutoff_dates_controller.rb
app/inputs/time_dropdown_input.rb
app/models/journal_cutoff_date.rb
app/models/order_detail.rb
app/services/order_details/param_updater.rb
app/views/journal_cutoff_dates/_form.html.haml
app/views/order_management/order_details/_form.html.haml
app/views/order_management/order_details/_reservation.html.haml
lib/date_time_input/form_data.rb
lib/date_time_input/model.rb
spec/controllers/journal_cutoff_dates_controller_spec.rb
spec/lib/date_time_input/form_data_spec.rb
spec/lib/date_time_input/model_spec.rb
spec/models/journal_cutoff_date_spec.rb
vendor/engines/secure_rooms/app/models/secure_rooms/occupancy.rb
vendor/engines/secure_rooms/app/models/secure_rooms/order_detail_extension.rb
vendor/engines/secure_rooms/app/services/secure_rooms/order_details/param_updater_extension.rb
vendor/engines/secure_rooms/app/views/order_management/order_details/secure_rooms/_occupancy.html.haml
vendor/engines/secure_rooms/config/locales/en.yml
vendor/engines/secure_rooms/lib/secure_rooms/engine.rb
vendor/engines/secure_rooms/spec/features/admin_edit_occupancy_spec.rb

This adds support for modifying an occupancies entry and exit time. I used what was there for JournalCutoffDates as my jumping off point (after a few bad initial attempts) since that was my favorite method we've come up with so far for handling date inputs from forms, so that's why there are changes in that section (I tried to isolate that to the first commit)
Will come in future PRs:
* Implement support for duration
* Better handling against problem occupancies
* Refactor Reservations to use this (this might not happen just yet because it's a significant chunk of work, but I _really_ want to kill off Reservations::DateSupport)

[#144059203] Edit Occupancy Times in Modal

---

vendor/engines/sanger_sequencing/app/assets/javascripts/sanger_sequencing/print_warning.js.coffee
vendor/engines/sanger_sequencing/app/views/sanger_sequencing/submissions/_form.html.haml
vendor/engines/sanger_sequencing/app/views/sanger_sequencing/submissions/edit.html.haml
vendor/engines/sanger_sequencing/config/locales/en.yml
vendor/engines/sanger_sequencing/spec/javascripts/sanger_sequencing/print_warning_spec.js.coffee

Per https://www.tjvantoll.com/2012/06/15/detecting-print-requests-with-javascript/ adds a warning to the Sanger order form page, requesting that users continue their submission if they print.
If the user does print, they get an alert warning them to continue, and the message on the page changes.

Add a warning when the Sanger sequencing is printed

---

vendor/engines/secure_rooms/spec/factories/secure_room.rb

Changed in: https://github.com/tablexi/nucore-open/pull/962/files#diff-0b65ec7aecf9ba902e4573184a39becdR23
Broken ref in: https://github.com/tablexi/nucore-open/pull/1024/files#diff-63c250c022dff5ce3447c43f93437a27R14
Unlucky merge timing.

fix outdated PriceGroup.base ref

---

app/helpers/date_helper.rb
lib/date_time_input/form_data.rb
spec/lib/date_time_input/form_data_spec.rb

When submitting the order detail modal on stage, the times were being interpreted in UTC, even though the application is running in central time.
This switches the input parser to use `parse_usa_date` which is more lenient than what I had before, but it used pretty much everywhere else we have date parsing, so it seemed like a good thing to use.

[#144059203] Fix occupancy modal time zones

---

app/models/concerns/users/roles.rb
app/models/user_role.rb
vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/operator_rule.rb
vendor/engines/secure_rooms/spec/services/secure_rooms/access_rules/operator_rule_spec.rb

unless they also have a facility-specific role.
This last change makes me wonder if we can get rid of some of the `facility_staff_of?`/`facility_senior_staff_of?` methods that are generated by meta-programming. Seemed out of scope for this, though.

[#140077839] Prevent global admins from scanning in to SecureRooms

---

app/models/order_detail.rb
spec/controllers/facility_notifications_controller_spec.rb

Orders with $0 usage rates or instruments configured with a timer but priced on reservation would get a price policy assigned when they were auto-expired. This was causing them to appear in the "Send Notifications" tab, and thus could be reviewed, journaled, and reconciled, even though they were problem orders.
This will now exclude them from the Send Notifications tab so they must first be dealt with in the Problem Reservations tab.

[#136233] Exclude problem orders from Send Notifications

---

app/assets/javascripts/app/reservation_time_field_adjustor.js.coffee

When changing the exit at on occupancies, the hidden field for duration
was getting updated, but it wasn’t updating the displayed field was not
being updated.

[#145286873] Fix: Update duration field when exit_at changes

---

vendor/engines/secure_rooms/app/controllers/secure_rooms/facility_occupancies_controller.rb
vendor/engines/secure_rooms/spec/features/view_facility_occupancies_spec.rb

To be completely honest, I’m not sure why the `current_facility` is
necessary here, but not for the other problem controllers.

[#144059135] Fix route when mass assigning occupancy price policies

---

vendor/engines/secure_rooms/app/services/secure_rooms/check_access.rb
vendor/engines/secure_rooms/spec/factories/card_reader.rb
vendor/engines/secure_rooms/spec/services/secure_rooms/check_access_spec.rb

Re-order rules so that global admins or people not on the access list
are unable to exit a room (just like they are unable to enter a room).

[#140077839] Prevent admins and non-approved users from exiting a room

---

app/support/order_row_importer.rb
spec/app_support/order_row_importer_spec.rb
vendor/engines/secure_rooms/spec/services/order_row_importer_spec.rb

Only allow import of Items and Services by default. This will give a
useful message when trying to import SecureRooms or instruments telling
you the particular product type is not supported for imports.
There are plenty of opportunities to refactor here, but I this was originally considered a "chore", so I opted to just make a minimal change.

[#144059265] More generic handling on importing unsupported product types

---

vendor/engines/secure_rooms/app/models/secure_rooms/occupancy.rb

When associating both an entry_at and exit_at for an entry-only
scanner, the timing of the two `associate_` calls mattered because if
`associate_exit` happens first, then `entry_at > exit_at`, which causes
the price policy to fail. This instead uses the event’s `occured_at`
time to set both, so the times will be equal.
Unfortunately, I couldn’t find a good way to make the tests catch this. Because we’re using Rails’s time helpers, time gets frozen and doesn’t move forward.

[#144058951] Use Event#occurred for occupancy times

---

app/views/shared/transactions/_search.html.haml

The search had an extra `.container` that it didn’t need causing the
transaction search pages to have a horizontal scroll.
Lint cleanup coming in a second commit shortly.

Fix horizontal scroll on transaction search pages

---

app/controllers/admin/services_controller.rb
app/support/auto_logout.rb
config/routes.rb
config/schedule.rb
spec/controllers/admin/services_controller_spec.rb
vendor/engines/secure_rooms/app/support/secure_rooms/auto_orphan_occupancy.rb
vendor/engines/secure_rooms/lib/secure_rooms/engine.rb
vendor/engines/secure_rooms/lib/tasks/restricted_rooms_tasks.rake
vendor/engines/secure_rooms/spec/support/auto_orphan_occupancy_spec.rb

Notes:
* `AutoExpireReservation` uses `Time.zone.now - 12.hours` for the window, but I feel like I remember saying we might just run this job overnight since rooms would typically be closed? If not and we do want the 12 hour window, should that be moved into a real constant and/or setting then?
* I'm not sure how whenever/`schedule.rb` work within the engine, and figured it's easier to chat about it if we're already familiar with that.

[#144059389] Add task marking occupancies orphaned

---

vendor/engines/secure_rooms/app/services/secure_rooms/access_handlers/order_handler.rb
vendor/engines/secure_rooms/config/locales/en.yml
vendor/engines/secure_rooms/spec/services/secure_rooms/access_handlers/occupancy_handler_spec.rb
vendor/engines/secure_rooms/spec/services/secure_rooms/access_handlers/order_handler_spec.rb
vendor/engines/secure_rooms/spec/services/secure_rooms/access_manager_spec.rb

* Exits access handling chain if associated user cannot purchase the room, thus facility operators no longer generate orders.
* If user can purchase but order has no associated account, grabs first account from their list of `accounts_for_product`
* Error messaging now begins by stating the account must be double-checked.

[#144058835] Assign account when entry missing

---

app/assets/javascripts/app/logout_after_end_reservation.coffee
app/assets/javascripts/app/reservation_time_checker.coffee
app/assets/javascripts/app/reservations.coffee
app/views/reservations/_reservation_fields.html.haml
app/views/reservations/new.html.haml

Broken by responsive changes in
https://github.com/tablexi/nucore-open/pull/945 because a class was
removed, probably because it didn’t adhere to the newer best practice
of prefixing with `.js-`.
This also splits some of the js into separate files so each file is
only doing one thing.
We might need to cherry-pick this into NU to get to stage before another release.

[#136397] Fix "Create & Start" on new reservations

---

vendor/engines/secure_rooms/app/controllers/secure_rooms_api/api_controller.rb

Avoids “Can't verify CSRF token authenticity” log messages.

[#144548061] Skip CSRF protection on SecureRooms API

---

vendor/engines/secure_rooms/app/controllers/secure_rooms_api/scans_controller.rb
vendor/engines/secure_rooms/app/models/secure_rooms/card_reader.rb
vendor/engines/secure_rooms/config/locales/en.yml
vendor/engines/secure_rooms/spec/controllers/secure_rooms_api/scans_controller_spec.rb
vendor/engines/secure_rooms/spec/factories/card_reader.rb
vendor/engines/secure_rooms/spec/features/manage_card_reader_spec.rb
vendor/engines/secure_rooms/spec/models/secure_rooms/card_reader_spec.rb

I considered actually renaming the column, but eventually decided against it. I also considered adding an `alias_attribute :control_device_number, :mac_address`. It seemed to make things clearer and more obvious when looking at very specific places (e.g. inside the factory or validations), but got confusing when you stepped back and saw both in the same picture.

[#145490555] Rename Control Device Number to MAC address

---

vendor/engines/secure_rooms/app/models/secure_rooms/card_reader.rb
vendor/engines/secure_rooms/app/services/secure_rooms/access_handlers/order_handler.rb
vendor/engines/secure_rooms/spec/features/scanning_in_and_out_spec.rb
vendor/engines/secure_rooms/spec/services/secure_rooms/access_handlers/occupancy_handler_spec.rb
vendor/engines/secure_rooms/spec/services/secure_rooms/access_handlers/order_handler_spec.rb

* runs `CheckAccess` again, since that will leave `accounts` blank if the user was granted from an earlier rule--then, if `accounts` is populated, the user would have had to select a valid account
* cleans up the `OrderHandler` specs with better fixtures available

[#145957283] Skip order for exempt users

---

Gemfile
Gemfile.lock
spec/models/user_spec.rb
spec/rails_helper.rb

I thought I was going to want a new feature (ignoring case sensitivity in uniqueness), but turns out that doesn't do what I wanted when the case-insensitivity is on the `scoped_to` side. But I figured we might as well have this upgraded.

Upgrade shoulda-matchers to 3.1.X

---

db/migrate/20170501201633_add_canceled_to_order_detail.rb

Admin reservations and Offline reservations do not have an associated order_detail.
Update to https://github.com/tablexi/nucore-open/pull/1008

Fix canceled_at/by migration for Admin and Offline reservations

---

spec/features/creating_a_journal_spec.rb

Depending on the order_detail ID for matching was a little fragile--too high of a chance of accidental matches (with order ID or user ID, etc).  Matching on the description instead should be sufficiently specific.

fix fragile creating_a_journal spec

---

app/support/auto_expire_reservation.rb
config/settings.yml
vendor/engines/secure_rooms/app/support/secure_rooms/auto_orphan_occupancy.rb

Since the setting is now required.. should we add a default directly into the code? Like:
```
Settings.reservations.timeout_period || 12.hours
```

[#146173013] Configure res/occ timeout in settings

---

app/models/journal.rb
app/models/order_detail.rb
app/support/journals/closer.rb
lib/nucore.rb
spec/models/journal_spec.rb

Open source version of https://github.com/tablexi/nucore-nu/pull/259
When there are orders with a SplitAccount on a journal, the association was coming back with duplicate order details because there are multiple journal_rows per order detail (multiple journal rows is intentional). This works fine on MySQL because of the `distinct` scope.
However, the Oracle-specific `clob_safe_distinct` was not working because the inner `distinct` was not being scoped, so it was essentially coming out as `WHERE id IN (SELECT DISTINCT(*) FROM order_details)`. Using a normal `distinct` has problems in oracle because `DISTINCT *` does not work with CLOB fields (notes). `ORA-00932: inconsistent datatypes: expected - got CLOB 00932. 00000 -  "inconsistent datatypes: expected %s got %s"`.
I've made the …

[#136429] Prevent duplicate details in Journal#order_details

---

circle.yml

- Adding circle config to send slack notifications for builds on master/develop branches only (per https://circleci.com/docs/1.0/configuration/#per-branch-notifications)
- Currently the integration is turned on only for open--once this gets merged down into the school-specific forks I'll turn on the integration for those projects as well.

circle sends slack notifications only for master/develop branches

---

db/migrate/20170531183710_fix_schedule_rule_product_index.rb
db/schema.rb

This index was missing on Oracle because it doesn't automatically create indexes
for foreign keys the way MySQL does.
I was a little surprised this worked as is, but mysql didn't need a special condition.

Fix schedule rule foreign key index

---

app/models/order_detail.rb
spec/features/viewing_an_order_spec.rb

This was using the wrong method, originally the logic was `#missing_price_policy?` which includes `complete?` like so:
```
def missing_price_policy?
complete? && price_policy.nil?
end
```

[#146399533] Require complete? to view description

---

db/migrate/20170501201633_add_canceled_to_order_detail.rb

There are about 46 order_details in UIC that were deleted, but the reservations were
not. I suspect this was back when they were running MySQL 5.5, and possibly on MyISAM,
which does not support foreign keys. Likely, when they exported from the old
server and imported to the newer one, the importer temporarily disabled foreign
keys.

Skip adding cancelation fields to reservations with missing order details

---

app/models/order_import.rb
spec/app_support/order_row_importer_spec.rb
spec/models/order_import_spec.rb

There's some funny load order issue in UIC so we were getting undefined constant `CSV` errors.
This pulls https://github.com/tablexi/nucore-uic/pull/129 into open.

Fix CSV requires

---

app/models/order_detail.rb
spec/models/order_detail_spec.rb

The "Missing Actual" badge was appearing for new/inprogress orders.
This fixes `problem_description_key` so it only returns a key if the order is
complete.
PR #1085 was a first attempt to fix the issue, but that only handled the missing
price policy same issue.
The order detail problem spec is a mess, but refactoring it seemed outside the scope of this bug fix.

[#136497] Fix problem reservation badges

---

app/controllers/api/order_details_controller.rb
app/models/api/order_detail.rb
app/models/external_service/url_service.rb
app/models/order_detail.rb
config/routes.rb
spec/models/api/order_detail_spec.rb
spec/models/external_service/url_service_spec.rb

The addition of the `/api/order_details.json?id=123` endpoint and the addition of `order_number` to the order details API are to allow use of the Qualtrics Web Service feature.
The addition of `order_number` to the query string will allow the receiver to use the full order number (e.g. "12345-34521") rather than just the receiver_id ("34521", the order detail id).
I also did some spec refactoring.

[#134550] Changes to support Qualtrics as external survey

---

README.md
lib/tasks/engines.rake

Example: `rake engines:db:migrate_down[projects]`
Conveniently (and honestly a little surprisingly), this will happily run even if the engine is disabled in the Gemfile. 
If the engine is enabled, then following this up with a `db:migrate` should leave the schema in a similar state (column ordering might be different).

Rake task for reverting engine migrations

---

config/settings.yml

We might want to disable this for NU, or we could release it in a stage release to have them test it, but I think it should now be on by default.

Enable responsive feature flag by default

---

app/models/order_detail.rb
spec/models/order_detail_spec.rb

Journal dates are always to midnight of the requested date. The search
was doing a `>`, so it was excluding the very beginning of the day. So
if you had a journal date of `2017-06-05 05:00` and you searched
journal date `6/5/2017`-`6/5/2017`, it was being excluded erroneously.
I did add a spec, but the rest is just organization changes.

[#136550] Journal date search should allow exact match

---

app/assets/javascripts/app/responsive_table.js.coffee
app/assets/stylesheets/responsive.scss
spec/javascripts/fixtures/nested_table.html
spec/javascripts/responsive_tables_spec.coffee

This includes #1100 and #1099.
The main change here is updating the responsive table JS to handle nested tables.
This does some fixing, but I'm wondering if there's a way we can get the height of the row to fit the header if it spans multiple lines. I wasn't having very much luck. I'd rather not use the data attribute with a shorter name, but we could fall back to that if there's no other way.

[#136529] Responsive sanger receipt

---

spec/factories/nufs_accounts.rb

Before, we would occasionally get test failures because `"9100-7777777" < "999-7777777"`
when we were dealing with sorting. This will allow us many more before it rolls over
to add an extra character.
NU overrides this factory to do something similar, but abides by its custom
validation rules.
Example of failure, when the test is checking ordering.
```
expected: "nufs account aaaaabml / 91000-7777777"
got: "nufs account aaaaabmk / 9999-7777777"
```

Prevent spurious test failures when factory sequence adds a character

---

app/assets/javascripts/app/responsive_dropdown.js.coffee
app/views/shared/nav/_manage_facilities.html.haml

https://pm.tablexi.com/issues/136649
See https://stackoverflow.com/questions/17178606/bootstrap-v2-dropdown-navigation-not-working-on-mobile-browsers for a description, but this is a bootstrap bug, and short of manipulating the bootsrap source, this seems to be the fix.

[#136649] Users unable to tap facilities under "Manage Facilities" on phones

---

app/assets/stylesheets/nucore.scss

https://pm.tablexi.com/issues/134974
Aaron requested a small styling change to prevent the invalid payment sources alert from butting up against the sidenav.  We apparently didn't see this in open because of the extra "Projects" search bar which pushed the alert down just enough. The styling change makes no difference to the spacing in open, but fixes the issue on NU.

[#134974] ensure small bottom margin for side nav

---

app/models/reports/export_raw.rb
vendor/engines/projects/app/models/projects/export_raw_transformer.rb

New columns introduced in https://github.com/tablexi/nucore-open/pull/1104
Per client request:
* Move "Charge For" to just right of "Price Group"
* Move "Invoice Number" to just right of "Statemented On"

[#134979] Move new export raw columns to better locations

---

app/assets/stylesheets/responsive.scss

Some of these issues are not obvious in open, I've used examples from DC.
* Make sure dropdown menu elements are not a custom color
* Add gray color for hover

[#136650] Fix colors in responsive hamburger menu

---

app/helpers/products_helper.rb
app/models/bundle.rb
app/views/bundle_products/edit.html.haml
app/views/bundle_products/index.html.haml
app/views/bundle_products/new.html.haml
config/locales/en.models.yml
config/locales/en.yml
config/locales/views/admin/en.bundles.yml

Show "Product missing current price policies" if one of the bundled products is missing current policies. Do not show anything if all the products have active policies. Show "No current price policies" on the bundle's product list.
Addresses NU's #134312

[#136662] Bundles showing "no current price policies"

---

vendor/engines/secure_rooms/app/models/secure_rooms/ability_extension.rb
vendor/engines/secure_rooms/spec/features/view_facility_occupancies_spec.rb
vendor/engines/secure_rooms/spec/models/ability_spec.rb

Facility staff and senior staff are not allowed to access problem orders or problem reservations,
so they should not have access to occupancies.

[#147374881] Staff should not be allowed to access problem occupancies

---

config/initializers/01_nucore.rb

It now gets included by the ldap_authentication engine. If that gem isn't loaded,
this errors out. This change will be necessary for the non-NU forks to load.

Remove devise_ldap_authenticatable require

---

app/presenters/nav_tab/link_collection.rb
app/views/admin/shared/_sidenav_users.html.haml
lib/ability.rb

When under the main "Users" tab, if you navigate to the Bulk Email tab or Payment Sources, the "Users" tab in the sidebar goes away. That's because it is checking for `:index, User` on the ability, but the admin is only granted `:administer`.
See for reference:
* Changed from using `:administer` to `:index` in `_sidenav_users.html.haml` allowing Business Admins to view the tab in cross facility mode. https://github.com/tablexi/nucore-open/commit/2b73d4fb90ff0ef27f192964ac1fb5c0d18ac99f 
* Added the line around `FacilityUserReservationsController` that I am removing here #961

[#136682] Lost tab when on Bulk Email or Payment Sources tab

---

app/models/message_summarizer.rb
app/models/message_summarizer/message_summary.rb
app/models/message_summarizer/order_details_in_dispute_summary.rb
app/views/shared/_message_summary.html.haml
spec/models/message_summarizer_spec.rb

for facility admins. In the upper right "Notices" dropdown, "Disputed Orders" was no longer appearing.
When we got rid of the separate Disputed tabs on "Orders" and "Reservations". When we did that, we got rid of the permission those tabs were using. https://github.com/tablexi/nucore-open/pull/1059
The first commit is the simple change, but it was clear the way we were testing might have been a little too close to the code itself, which was how we missed the regression. So I started to refactor the specs to use actual users with a role instead of a stubbed ability. This led me to also refactor a little bit of the code itself. I also found were one of the specs was actually incorrect (it wasn't a big deal because it involved the training request feature being disabled, but there being a …

[#136705] Disputed orders not displaying in Notices

---

app/assets/javascripts/app/cart.coffee
spec/javascripts/app/cart_spec.coffee
vendor/engines/sanger_sequencing/app/models/sanger_sequencing/submission.rb
vendor/engines/sanger_sequencing/spec/models/sanger_sequencing/submission_spec.rb

In the cart, if the user changes the quantity field to be blank or negative and then clicks the "Complete Order Form" we end up passing a blank string or negative number in the quantity query parameter to the Sanger form. This was then triggering an `ArgumentError: quantity must be positive` in `Submission#create_samples!`.
I also tested with decimal numbers. Those were being passed as decimals, but the form was handling that by dropping the fractional part.
This now handles it at both the cart level and the create_samples level. The cart will disable the "Complete Order Form" button if the quantity is not a valid value. If an invalid value does slip through, then the Sanger form will default to having one sample.

[#136702] Prevent invalid quantities from cart into Sanger form

---

app/views/admin/shared/_tabnav_users.html.haml

We tried to tighten up the permissions in #1094 so AMs only have the permissions
they need, not full `:manage`. Looks like we missed a spot where we were checking.
Cherry-picked from https://github.com/tablexi/nucore-nu/pull/275

[#136391] Restore access to Account Managers to user's payment sources tab

---

app/views/facilities/_facility_fields.html.haml

> The primary facility email address appears in the bottom section, under the "Order notification recipient" entry box. See attachment: Facility Email in Edit Mode. It needs to be removed.

[#134004] Remove order notification hint from facility edit

---

spec/lib/nav_tab/link_spec.rb
spec/rails_helper.rb
vendor/engines/bulk_email/app/services/bulk_email/content_generator.rb
vendor/engines/bulk_email/config/locales/en.yml
vendor/engines/bulk_email/spec/services/bulk_email/content_generator_spec.rb

The default will now be `[NUcore EF]` instead of `[NUcore Example Facility]` as the subject prefix because many facilities have very long names.
I am passing both the name and abbreviation to the locale so a fork can easily
override it and revert back if they want.

[#136008] Use facility abbreviation in bulk email subject

---

app/models/reports/instrument_utilization_report.rb
spec/models/reports/instrument_utilization_report_spec.rb

When a problem reservation is missing its end time this report errors. The error
manifests when a problem reservation's fulfilled_at falls into the "Fulfilled between"
range.
```
nil can't be coerced into Fixnum
app/models/reports/instrument_utilization_report.rb:56:in `+'
```

[#136823] Instrument util report errors on problem reservation

---

db/migrate/20170515214930_drop_canceled_from_reservations.rb
db/schema.rb

Depends on #1008, DO NOT MERGE until that has been deployed/verified on stage.
Will need to be rebased on current master after #1008 is merged in, which should resolve the current test failures.

[#136734] Drop reservation canceled_* columns

---

app/models/user.rb
app/models/user_role.rb

While these methods were on UserRole itself, the results of `User#user_roles`
were not being memoized. It would hit the cache, but on some pages this would still
slow things down noticeably.

Avoid constantly looking up `User#user_roles`

---

app/helpers/facility_orders_helper.rb
app/presenters/order_detail_notice_presenter.rb
app/views/order_details/show.html.haml
app/views/order_management/order_details/_warnings.html.haml
app/views/shared/_problem_order_details.html.haml
app/views/shared/transactions/_table_inside.html.haml
spec/presenters/order_detail_notice_presenter_spec.rb

Adds blue status badges to a couple views under "My Payment Sources" so that account managers and PIs can see the status beyond "complete".
* "In Review"
* "Open Journal"
* "Can Reconcile"
* "In Open Journal"
These badges were already being used on the facility's Order#show view. They are now available on the "Transaction History" and OrderDetail#show views.
Since the transaction history table partial is shared with the billing tab, these badges are now available there as well.
In order to DRY some things up, this changes the problem column of the problem orders tabs into badges.
I currently have some questions out to the client confirming this behavior is all correct and acceptable.

[#125709] Show post-complete badges for account admins

---

.haml-lint.yml

The linter prefers `%p Note: #{order_detail.note}` to `%p= "Note:
#{order_detail.note}”`. We usually go with the latter where the string
interpolation is explicit.
I'm open to debate on this. This can probably wait until Meara is back so she can weigh in on it.

Disable UnnecessaryStringOutput haml linter

---

app/services/order_details/param_updater.rb
app/views/order_management/order_details/_form.html.haml
spec/controllers/order_management/order_details_controller_spec.rb

First ticket number is NU, second is UIC.
An error like “The reservation conflicts with another reservation.” was
erroring with
```
An ActionView::Template::Error occurred in order_details#update:
undefined method `humanize' for nil:NilClass
app/views/order_management/order_details/_warnings.html.haml:14:in
`_app_views_order_management_order_details__warn
```
The `errors` was getting an empty string for a key:
` @messages=
{:""=>
["The reservation conflicts with another reservation.",
"The reservation spans time that the instrument is unavailable for
reservation"]}>`
This would then choke when trying to call `full_messages`

[#136836/#136829] 500 when reservation has `:base` errors

---

db/migrate/20170627182248_drop_roles_if_exists.rb
db/schema.rb

NU and open do not have the roles table--UIC and Dartmouth do. None of the schools actually use this table. This migration will drop the table if it exists, in order to get the schools' schemas in line with each other.

drop roles table if exists

---

app/support/accessories/scaling/auto.rb
app/support/accessories/scaling/manual.rb
app/support/reservations/date_support.rb
spec/controllers/accessories_controller_spec.rb

* Create & Start a reservation on an instrument with accessories
* While it is running, click "Add Accessories"
* Manually scaled accessories are defaulting to "0:00". It should
default to the current duration
* Auto scaled accessories show "0:00", and then when you try to save,
it says "must be greater than or equal to 1"
Adding accessories works fine once the reservation has ended. That's because these are querying the reservation for its `actual_duration_mins`, which now is `nil` if the reservation is running or a problem. This adds a new method that allows you to fall back to using the current time like older behavior. See #1047.

[#136869] Unable to add auto-scaled accessory to running reservation

---

app/services/order_purchaser.rb

The option moved to OrderPurchaseValidator. This was there to forward it on
while the forks were being updated.
Cleaned up in NU in https://github.com/tablexi/nucore-nu/pull/281

Remove deprecated configuration option

---

spec/models/product_spec.rb
spec/models/user_spec.rb

Per https://github.com/tablexi/nucore-dartmouth/pull/104 some tests were
dependent on the `user_based_price_groups` setting, while I was there,
cleaned up some settings changes to use metadata

[#135577] Update RSpec metadata settings.

---

app/assets/javascripts/reservations.js
app/controllers/reservations_controller.rb
app/models/schedule_rule.rb
app/presenters/schedule_rule_calendar_presenter.rb
app/support/reservations/rendering.rb
app/views/reservations/_js_variables.html.haml
app/views/reservations/new.html.haml
spec/controllers/reservations_controller_spec.rb
spec/models/schedule_rule_spec.rb

There is a `show_details` “Show reservation details (name, email, etc)
on schedule” option on instruments that should only show users’ name
and email if the option is on.
However, what was happening is we were sending the string `”false”`
into `Reservations::CalendarPresenter`, which is `present?`, so we were
rending the details if if we didn’t want to.
Even if that was fixed, using a query parameter like this isn’t very
secure. Anyone could conceivably change the query parameter to “true”.
This changes the logic so that if you request details (which happens in
most of the facility-side views), it also checks to make sure that
either the `show_details` option is on or that you have facility-level
permissions.
I also did a little bit of JS cleanup getting rid of the `withDetails` …

[#136900] User details being shown on calendar

---

app/controllers/orders_controller.rb
app/models/order.rb
app/models/order_detail.rb
app/views/orders/_form.html.haml

`comparison of Fixnum with nil failed`
Non-bundled order details have a nil group_id, so we can’t directly
compare a nil and a number.

[#136943] Fix error when item/service and a bundle are in cart

---

app/controllers/reservations_controller.rb
app/services/order_purchase_validator.rb
app/services/order_purchaser.rb
app/services/reservation_creator.rb
app/validators/all_order_details_validator.rb
spec/controllers/reservations_controller_spec.rb

Applies to NU's [#136043] for research safety and UIC's required note field.
If you have multiple line items in your cart that have validations including a reservation, when you try to create the reservation, it is validating every other line item in your cart.
So, add an item that requires a note and an instrument that doesn't to your cart. Click the "Make a Reservation" button. You will not be able to save the reservation, and you will get a "Validation failed:" flash. Part of this is because for reservations, we're displaying the order details's validations.
This changes the note and research safety validators to accept a list of order details (or single order detail) rather than an order. It also changes the research safety validator to place errors on the model itself.
These commits …

[#136306] Fix reservation validations

---

app/helpers/date_helper.rb

`to_time` uses the system's timezone, not the app's.
This was broken by changes made in https://github.com/tablexi/nucore-open/pull/1134
Circle is set to central time as is the application, so that's why this was fine until we merged to DC, which has circle set to central and the app set to eastern. I'm going to open another PR for trying to deal with that.

Fix Date to Time conversion so it uses the app's timezone

---

spec/models/external_service/url_service_spec.rb
spec/services/default_facility_homepage_redirector_spec.rb

DC uses "resources", so this fails when we try to merge it down.

Handle I18n-ed facilities route in spec

---

app/controllers/reservations_controller.rb
app/presenters/reservation_user_action_presenter.rb
app/views/order_details/show.html.haml
app/views/reservations/list.html.haml
app/views/shared/_auto_logout.html.haml
spec/presenters/reservation_user_action_presenter_spec.rb

NUCore should automatically log out users (in customer mode only) after they click "Begin Reservation" from "My Reservations". Identical functionality as what happens when users click "End Reservation", including the 60 second delay and possibility of remaining logged in. T
The existing usage didn’t work from the order page, but it does now. I don’t think this presenter is used any place else, so this shouldn’t trigger anyplace else.

[#98881] Auto-Log Out after Begin Reservation

---

app/support/order_row_importer.rb
spec/app_support/order_row_importer_spec.rb
spec/models/order_import_spec.rb

If the uploaded import file does not have a notes column (the current template
does have this column, but older versions of the template might not), then any
import errors in the error report appear in the "Notes" column as opposed to the
"Errors" column.
There are definitely opportunities for refactoring here, but didn't seem worth the effort for this bug fix.

[#136975] Order import errors appearing in "Notes" field

---

app/models/account.rb
app/models/order_detail.rb
app/presenters/order_detail_notice_presenter.rb
config/locales/en.yml
spec/controllers/order_details_controller_spec.rb
spec/models/order_detail_spec.rb

* Ready for Journal
* Ready for Statement
* Awaiting Payment (statemented, but not reconciled)
* Get rid of `disputed?` method, which is only used in a couple specs
* A couple refactors to use local methods vs hitting the database again
to prevent N+1 queries

[#136924] Ready for Journal/Statement badges

---

Gemfile.lock

- Update spreadsheet gem to avoid deprecation warnings from ruby-ole: https://pm.tablexi.com/issues/137063

[#137063] update spreadsheet/ruby-ole gems

---

Gemfile
Gemfile.lock

Inadvertently dropped the version specifier in https://github.com/tablexi/nucore-open/pull/1150/files#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R128, which caused issues bundling in the UIC fork. Pinning `oj` to the current version.

fix oj version

---

app/assets/stylesheets/responsive.scss

This will clear up an issue for DC where users are printing their receipt
for Sanger Sequencing orders (as they should) and the print view is using
responsive tables.
I'm confirming with the client that they do want the normal table view in the print view, but I figured I'd put this out there anyways.

[#137019] Only go responsive on screen, not print

---

app/assets/stylesheets/app/timeline.scss
app/controllers/reservations_controller.rb
app/helpers/timeline_helper.rb
app/models/concerns/products/scheduling_support.rb
app/models/reservation.rb
app/presenters/reservations/calendar_presenter.rb
app/views/shared/timeline/_facility_tooltip.html.haml
config/locales/en.yml

- https://pm.tablexi.com/issues/133776
- Show the offline blocks on the facility timeline view (I feel like this could be pretty useful). If we do this we should make sure auto-canceled reservations are in front of the offline block
- Show the offline blocks in the calendar on the place reservation view. Show when ordering on behalf of.
- Show the offline blocks in the calendar where you take the instrument online and offline

[#133776] offline reservations display on calendar/timeline

---

app/assets/javascripts/_calendar.js.coffee
app/assets/javascripts/app/calendar.js.coffee
app/assets/javascripts/instruments.js
app/assets/javascripts/reservations.js
app/presenters/reservations/calendar_presenter.rb
app/views/instruments/public_schedule.html.haml
coffeelint.json
spec/app_support/reservations/rendering_spec.rb

> This is specifically useful for shared calendars.
There was a lot of copy/pasted code between `reservations.js` and `instruments.js` for setting up the calendar. This consolidates it into one single class, and then is initialized through those two files.
This will conflict with #1168 in the calendar presenter, but should be straightforward to reconcile.
New reservation:
Public calendar (with details disabled):

[#136142] Add Instrument Name to calendar tooltip

---

app/models/order_detail.rb
spec/models/order_detail_spec.rb

- https://pm.tablexi.com/issues/137184
The fulfilled_at value was being overwritten to nil when updating problem orders for reservation-only instruments.
How to reproduce:
1) Place a reservation in the past for another user on a reservation only instrument that is missing a price policy for that date (this is not a problem for timer instruments)
2) The reservation should appear in "Problem Reservations", and it will have a fulfillment date at this point.
3) Create a price policy that covers the fulfillment date
4) In problem reservations, open up the order detail modal and click save
5) The order will no longer be in problem reservations, but if you open up the modal for that reservation, the fulfillment date is gone.

[#137184] fix fulfilled_at bug

---

app/views/order_management/order_details/_form.html.haml
app/views/order_management/order_details/_reservation.html.haml
spec/features/admin/manage_order_detail_spec.rb
vendor/engines/secure_rooms/app/views/order_management/order_details/secure_rooms/_occupancy.html.haml
vendor/engines/secure_rooms/spec/features/admin_edit_occupancy_spec.rb

- https://pm.tablexi.com/issues/137190
If you try to change a note of an in-progress reservation, you receive the error message "Actual duration may not be blank" but it still lets the note get changed even though you have to use cancel to get out of the screen.
In process Reservation
Click on the Order Number
Change note
Click Save
See error message
Click Cancel
Note is changed

[#137190] note error message

---

app/views/instrument_price_policies/_table.html.haml
app/views/price_policies/_table.html.haml
config/locales/en.models.yml

- https://pm.tablexi.com/issues/137205
Two interrelated issues:
1) There is a missing "close parenthesis" on all Instrument Price Rule pages. It reads: "Price Group (Type"
2) The internal/external Price Group distinguish-er is not present for Service and Items; the UI should be consistent with the instrument price rule pages, listing whether these Price Groups are internal/external

[#137205] text changes/UI cleanup

---

app/models/order_detail.rb
spec/models/order_detail_spec.rb

- https://pm.tablexi.com/issues/137187
Manually reconciled orders were still showing "Ready for Journal" badge, even though they were not available to be journaled.

[#137187] reconciled order details are not ready_for_journal

---

app/presenters/order_detail_notice_presenter.rb
config/settings.yml
spec/presenters/order_detail_notice_presenter_spec.rb

- https://pm.tablexi.com/issues/137189
UIC doesn't use internal billing currently, and would like "ready for journal" badges and notices hidden to avoid confusing facility directors.

[#137189] feature flag ready for journal badges/alerts

---

app/models/journal.rb
config/settings.yml
spec/models/journal_spec.rb

- NU wants to prevent journals being created with order details spanning fiscal years.
- Dartmouth wants to be able to create journals with order details spanning fiscal years.
Added a feature flag to enable/disable this validation per fork.

[#137315] feature flag validation for journals spanning fiscal years

---

Gemfile
Gemfile.lock

Fix deprecation warnings for older version of thin from Ruby 2.4 upgrade.

[#137332] bundle update thin

---

vendor/engines/sanger_sequencing/app/models/sanger_sequencing/submission.rb
vendor/engines/sanger_sequencing/spec/features/batches/creating_a_batch_spec.rb
vendor/engines/sanger_sequencing/spec/features/batches/deleting_a_batch_spec.rb

* Adds `complete` status to scope of batchable order_details; the remaining options `reconciled` and `canceled` are not valid for re-run
* Renames and fixes the existing delete spec

[#136040] Allow reruns of completed submissions

---

app/helpers/facility_reservations_helper.rb

Aaron was encountering errors when trying to edit offline reservations through the admin reservation edit form. Offline reservations should not be editable--this will remove the problematic links.

[#133776] offline reservations are not editable/cancelable

---

app/controllers/product_accessories_controller.rb
app/models/product.rb
app/models/product_accessory.rb
config/locales/en.yml
spec/controllers/accessories_controller_spec.rb
spec/controllers/product_accessories_controller_spec.rb
spec/factories/accessories.rb
spec/factories/price_policies.rb
spec/factories/products.rb
spec/models/order_details/accessorized_order_detail_spec.rb
spec/services/accessorizer_spec.rb

When adding accessories to products, the scaling type chosen must make sense with the accessory that is chosen (i.e. items must have quantity, not a time-based scaling type).

[#137257] charge mode matches accessory

---

vendor/engines/sanger_sequencing/app/models/sanger_sequencing/batch.rb
vendor/engines/sanger_sequencing/app/models/sanger_sequencing/submission.rb
vendor/engines/sanger_sequencing/spec/factories/product_groups.rb
vendor/engines/sanger_sequencing/spec/models/sanger_sequencing/batch_spec.rb

If a user visits the Batch index page without specifying a `group` param, Batches with `group == ""` are not displayed.

[#136038] Update default group scope for Batch

---

app/models/product.rb
db/migrate/20170816180831_lengthen_journal_row_description_column.rb
db/schema.rb

`OrderDetail#long_description` is what gets put into the
`JournalRow#description` field. If you have a really long product name
(that field is limited to 200 characters), then the description is too
long for the journal row field.
The 512 is somewhat arbitrary, but should be more than enough for
fitting long product names, the order detail and a user’s name.

[#137451] Extend journal row description field length

---

app/support/reservations/validations.rb
spec/models/reservations_validations_spec.rb

- https://pm.tablexi.com/issues/137409
- Certain time-related validations should only be run if reserve_start_at and reserve_end_at have valid values to avoid hard-errors.

[#137409] fix reservation validations

---

app/models/instrument_price_policy_calculations.rb
spec/models/instrument_price_policy_calculations_spec.rb

Looks like we had fixed the non-completed scenario in #1201, where it
goes through estimate_cost_and_subsidy, but not the completed order
scenario where it goes through calculate_cost_and_subsidy.
I think we didn’t have the guard clause here because it was assumed
that we would only ever try to calculate pricing on a valid order
(which would always have these fields), but in the `PriceChecker` used
on the order detail popup as an ajax call, it’s possible for the
reservation to become invalid if there is an error parsing the date.

[#137409] Handle invalid dates for reservations on completed

---

app/support/price_displayment.rb
app/support/statement_pdf.rb
app/views/purchase_notifier/order_receipt.html.haml
app/views/purchase_notifier/order_receipt.text.haml

https://pm.tablexi.com/issues/137258
Timed services receipts/statements should display duration appropriately
[EF-4-1-09-08-2017 (2).pdf](https://github.com/tablexi/nucore-open/files/1289202/EF-4-1-09-08-2017.2.pdf)

[#137258] receipt time display

---

app/assets/javascripts/app/merge_orders.coffee
app/controllers/facility_orders_controller.rb
app/models/product.rb
app/models/timed_service.rb
app/services/order_appender.rb
app/support/orders/item_adder.rb
app/views/facility_orders/_merge_order_form.html.haml
coffeelint.json
spec/features/admin/adding_to_an_order_spec.rb
spec/javascripts/app/merge_orders_spec.coffee

When adding a TimedService to an existing order, we will gray out the quantity field (and always adjust it back to 1) and display a new time input field.

[#137282] Add timed service to existing order

---

app/controllers/reservations_controller.rb
spec/controllers/reservations_controller_spec.rb

We did the front end piece in
https://github.com/tablexi/nucore-open/pull/1208 but didn’t verify it
actually persisted.
This also adds the note required validation so the user can’t remove
it. It would be possible to abstract the validation out, but we
probably want this list to be different from the on-purchase
validation. It just didn’t seem worth it right now. If we start adding
other validations (for example, I don’t think we need to run the NU
research safety validations), then it might be at that point.
This largely works because because Reservation delegates `note` and
`note=` to the order detail so in this case they can be treated
interchangeably.

[#137105] Persist note on updating a reservation

---

app/views/users/edit.html.haml
app/views/users/show.html.haml

https://pm.tablexi.com/issues/137762
Hide user-based price group field on user show/edit unless feature is on.

[#137762] hide user based price group field unless feature is on

---

docker/oracle/create_databases.rb

Not sure how I didn't run into this before (or maybe I did and missed pushing a PR for it). Without this extra parameter, you're not allowed to use aliases when loading `YAML.safe_load`.

Read database.yml for docker setup with aliases

---

app/services/account_builder.rb
app/services/nufs_account_builder.rb
app/views/facility_accounts/edit.html.haml
app/views/facility_accounts/show.html.haml

Changes in open for Dartmouth's feature to enable accounts to be designated as internal/external.
Companion to https://github.com/tablexi/nucore-dartmouth/pull/142.

[#137555] toggle account groups changes in open

---

app/assets/stylesheets/responsive.scss
app/views/shared/_header.html.haml

Looks like this was broken by the upgrade in Fontawesome. `icon-bars` is not quite what `fa-bars` is.
**Pre-upgrade:**
**Post-upgrade (current behavior)** 
**This PR**

Fix hamburger menu

---

app/views/bundle_products/index.html.haml

```
An ActionView::Template::Error occurred in bundle_products#index:
undefined method `manage_facility_timedservice_path' for #<#&lt;Class:0x0000000bb08aa0&gt;:0x0000000b51f648>
app/views/bundle_products/index.html.haml:34:in `block in app_views_bundle_products_index_html_haml_145491216999438308_98089920'
```

[#139341] Fix error on BundleProducts#index when including a TimedService

---

app/views/facilities/_product_list.html.haml
config/locales/en.yml

Add note to mitigate confusion over the meaning of the quantity field for timed services.

[#139351] add note for timed service quantity

---

app/controllers/orders_controller.rb
app/controllers/reservations_controller.rb
app/models/concerns/products/scheduling_support.rb
app/models/reservation.rb
app/support/reservations/validations.rb
config/locales/en.controllers.yml
spec/controllers/orders_controller_spec.rb
spec/features/purchasing_a_reservation_on_behalf_of_spec.rb
spec/features/purchasing_a_reservation_spec.rb
spec/models/reservation_spec.rb
spec/models/reservations_validations_spec.rb

What the flash messages look like:
to do:

[#137629] admin hold schedule over

---

spec/features/purchasing_a_reservation_on_behalf_of_spec.rb
spec/features/purchasing_a_reservation_spec.rb

Specs were breaking in forks, as the schools have different fiscal year starts.
https://circleci.com/gh/tablexi/nucore-dartmouth/774?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

fix fiscal year dependent specs

---

config/environments/production.rb
config/environments/stage.rb
config/initializers/rollbar.rb

There's no real need to be notified of this error. This happens if a js/json path meant for ajax is called without a format header. It is already ignored by Rollbar.
This also ignores `ActionController::UnknownHttpMethod` in rollbar. We sometimes see those errors when we're getting vulnerability scanned.
This will get a little funky going into the schools. NU already has the `ActionController::UnknownHttpMethod` ignore and Dartmouth doesn't use ExceptionNotifier. But this should help get things closer in line.

[#139318] Ignore ActionController::UnknownFormat in ExceptionNotifier

---

app/controllers/facility_journals_controller.rb
app/models/journal.rb
app/views/admin/shared/_sidenav_billing.html.haml
lib/nucore.rb
spec/controllers/facility_journals_controller_spec.rb
spec/models/journal_spec.rb

DC accidentally created one and it caused confusion. NU times out on this
view and they don't really use the billing admin role. UIC does their journaling
using an outside system (Banner Feeder).

[#139135] Disable cross-facility journal creation

---

app/helpers/products_helper.rb
app/models/concerns/products/scheduling_support.rb
app/models/reservation.rb
app/support/reservations/validations.rb
config/locales/en.models.yml
spec/features/purchasing_a_reservation_spec.rb
spec/models/instrument_spec.rb
spec/models/reservation_spec.rb

* Rename Instrument#available? to #walkup_available? to better clarify its use-case.
* Refactoring to how reservation validations are performed
* Remove Reservation#save_extended_reservation by using a :user_purchase context
* I18n reservation validation messages

[#139725] Public calendar icon should respect admin reservations

---

config/eye.yml.erb.template

Most of nucore installations use SMTP, so use that instead of aws for
sending notifications. I've already made these updates to the server on NU & UIC. We're getting crash/flapping alerts into opsgenie now.

Update eye template to use SMTP

---

app/forms/admin_reservation_form.rb
app/views/facility_reservations/_admin_reservation_repeat_fields.html.haml
config/locales/en.models.yml
spec/forms/admin_reservation_form_spec.rb

* The "too far in future" error was considered vague. Now say “cannot
be dated more than 12 weeks in the future”
* Retain recurrence interval in dropdown after invalid submission
* Remove blank option in recurrence interval dropdown
* Fix labels for expiration (I18n got lost when we changed from
`Reservation` to `AdminReservationForm`)

[#126403] Address feedback on admin hold recurrence

---

app/assets/javascripts/reconciliation.js.coffee
app/views/facility_accounts_reconciliation/_action_row.html.haml
app/views/facility_accounts_reconciliation/_table.html.haml
vendor/engines/c2po/spec/features/account_reconciliation_spec.rb

Now that we've added filtering, we want the page to start off with nothing checked.

[#136545] Default reconciliation page checkboxes to unchecked

---

app/assets/stylesheets/app/transaction_search.scss
app/views/shared/transactions/_search2.html.haml
vendor/engines/c2po/spec/features/account_reconciliation_spec.rb

https://pm.tablexi.com/issues/136545
Update button name from "Search" to "Filter", move it beneath the statements field, and add padding to disconnect the search form from the table below.
Before: 
After:

[#136545] restyle filter button

---

app/models/schedule_rule.rb
spec/models/instrument_price_policy_calculations_spec.rb
vendor/engines/secure_rooms/spec/models/secure_room_price_policy_spec.rb

Here's an example of what was happening from a local test:
* $60/hour ($1/minute) price policy 
* 24 hour/day schedule rule with a 10% discount.
* Time without relay
* Started 12:34:09, ended 12:41:41 
This should be calculated for 7 minutes, so $7 with a 10% discount = $6.30. Instead it is coming out as $6.26.
The way we calculate a discount is to find the effective discount percent. We find the percent of time a reservation overlaps with each schedule rule, multiply by the discount and sum them up. In this case we have the one rule which should be 100% * 10%, but because we're not trimming the seconds in this part of the calculation we're using 7.53 minutes, it's coming out to 106% overlap with the schedule rule. We then multiply that by the discount (10%), so we come out with as a …

[#139830] Fix schedule rule discount precision

---

app/services/order_details/reconciler.rb
lib/nucore.rb
spec/services/order_details/reconciler_spec.rb

Oracle has its 1000 limit on `WHERE IN` items, so we need to accommodate that.
I tested this on NU, and left the spec commented out because of how slow it is.

[#140057] Handle 1000+ orders for reconciliation

---

app/helpers/reservations_helper.rb
app/models/reservation.rb
app/support/reservations/duration_change_validations.rb
app/views/reservations/_reservation_fields.html.haml
config/locales/en.yml
spec/app_support/reservations/duration_change_validations_spec.rb
spec/features/editing_a_reservation_spec.rb
spec/helpers/reservations_helper_spec.rb
spec/models/reservation_spec.rb

You are now allowed to edit a reservation inside the lock window, but
you cannot change the start time and you cannot shorten the duration,
though you may extend it.

[#139390] Allow extending reservations inside lock window

---

app/controllers/reservations_controller.rb

https://pm.tablexi.com/issues/139964
This can happen with multiple tabs within the "Add to existing order" flow. Steps to reproduce:
As a facility staff/admin, go into an existing order
In the form at the bottom of the page, choose an instrument from the dropdown and click "Add to order"
Right click on the "Make a reservation" and open the form in a new tab. This should open a new reservation form
In the original page, click "Remove" to remove it from the "cart"
In the other tab, submit the form
You should see this same error

[#139964] throw 404 for circuitous multitab error

---

app/controllers/users_controller.rb
spec/features/admin/managing_user_spec.rb

https://pm.tablexi.com/issues/139955
Steps to reproduce:
Log in as an account administrator
Click "Users" tab. URL should be `/facilities/all/users`
Click on a user's name
Click "Edit" button
Click "Update"
This happens because we are expecting a value for `params[:internal]`, which global admins would see as a dropdown for allowing them to manually override if the user should get internal or external pricing. Account managers don't have that dropdown.

[#139955] fix price group params bug

---

Gemfile
Gemfile.lock
app/models/relay_synaccess_rev_a.rb
app/models/relay_synaccess_rev_b.rb
config/settings.yml

That version removes the telnet interface because it was unreliable. We
weren’t using it anywhere so it allowed some minor cleanup where it was
configurable.
We also don't need to be on the github master anymore since I pushed the latest versions to rubygems.

Bump to synaccess 0.3

---

app/controllers/reports/general_reports_controller.rb
app/models/concerns/reports/csv_exporter.rb
app/models/order_detail.rb
app/models/reports/export_raw.rb
app/services/reports/querier.rb
spec/controllers/reports/general_reports_controller_spec.rb
vendor/engines/split_accounts/app/services/split_accounts/order_detail_list_transformer.rb
vendor/engines/split_accounts/app/services/split_accounts/order_detail_splitter.rb
vendor/engines/split_accounts/spec/services/order_detail_splitter_spec.rb

Extends from #1336 and replaces #1337.
Clean diff: https://github.com/tablexi/nucore-open/compare/139681-cross-facility-export-raw...export_raw_optimize_jh?expand=1
I mostly tested this on NU/Oracle since I have a large and realistic dataset locally.
With a 5500 row export (about 2 months of data for IMSERC), it originally took 450-500 seconds. Now it takes ~200 seconds. That same report, the memory in delayed_job would spike to around 250-300mb (this is locally). In this new version, it stays around 150mb.
I'm still experimenting with the batch size. In oracle, at least, we get significantly faster queries, but there are of course more of them.
One of the things I did was to enable the query cache, which is not on by default in delayed_job. This will have minimal effect on open, but for …

Optimize Export Raw performance

---

app/controllers/instruments_controller.rb
spec/controllers/instruments_controller_spec.rb

This will save time when viewing the timeline view if the relay feature
is off (by default in development).
The feature is toggled in `settings.yml` under `relays`.

Do not connect to relays if the feature is disabled

---

config/settings.yml

Feature flag got lost in the merge somehow: https://github.com/tablexi/nucore-open/pull/1336/files#diff-646ad6b10917e4385cbcc8c8524e24a2R131
Should be false for UIC and NU, true for Dartmouth.

Restore cross_facility_reports feature flag

---

spec/features/editing_a_reservation_spec.rb

Reservation was being moved "too far in advance" for the price group that the product had available in UIC.
The product has three price groups, base, external, and one coming from the factory. For some reason the factory-based group has a 1 day reservation window, whereas base/external have a 14 day window. In open, the user is part of base and so has an effective 14 day window, whereas in UIC they are not and so are constrained by the 1 day reservation window.

fix fragile spec

---

app/controllers/facilities_controller.rb
app/forms/transaction_search/search_form.rb
app/inputs/transaction_chosen2_input.rb
app/services/transaction_search/base_searcher.rb
app/services/transaction_search/order_status_searcher.rb
app/services/transaction_search/product_searcher.rb
app/services/transaction_search/searcher.rb
app/views/facilities/transactions.html.haml
app/views/shared/transactions/_search2.html.haml
app/views/shared/transactions/_top2.html.haml
lib/transaction_search.rb
spec/controllers/facilities_controller_spec.rb
spec/features/admin/all_transactions_search.rb
vendor/engines/projects/app/services/projects/project_searcher.rb
vendor/engines/projects/lib/projects/engine.rb
vendor/engines/projects/spec/controllers/facilities_controller_spec.rb

This continues from #1294 and replaces the "All Transactions" search logic, e.g. http://localhost:3000/facilities/example/transactions with the new search. It gets rid of the `_with_search` metaprogramming. Hopefully, this is easier to reason about.
The feature spec I wrote works for both master and this branch. I think more specific unit tests are going to be better for testing the search criteria than the existing controller specs, which is why I did one happy-path feature spec and killed the controller specs for this action.

Replace "All Transactions" search with newer search method

---

vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/account_selection_rule.rb
vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/verdict.rb
vendor/engines/secure_rooms/spec/services/secure_rooms/access_rules/account_selection_rule_spec.rb
vendor/engines/secure_rooms/spec/services/secure_rooms/check_access_spec.rb

So that users always know exactly which account is going to be charged, we
want to always display an account selection, even if there is only one account.
With this change, there is no need to change anything on the nucore-rooms elixir
app or mobile app: as long as we respond with "pending" and the account list (of
only one thing), they behave appropriately.

[#139829] SecureRooms: Always prompt for account selection, even if only one

---

app/assets/stylesheets/calendar/fullcalendar.extensions.scss

[#139183] display calendar time range header

---

app/controllers/product_users_controller.rb
app/models/product_user.rb
spec/controllers/product_users_controller_spec.rb
spec/factories/product_users.rb

Steps to reproduce:
* Add a user to a restricted product
* Open a second tab of the access list
* Click "Remove" to remove the user on one tab
* Click "Remove" for the same user on the second tab
As part of this, I cleaned up the controller spec, so it's probably worth viewing the two commits separately.

[#140005] Prevent error on removing product/user access if already removed

---

Gemfile
config/environments/development.rb

We should take advantage of bullet from time time time, but it should probably not be run by default as it slows down development when you're not paying attention to its output.

Disable bullet by default

---

app/models/order_detail.rb
spec/features/admin/manage_order_detail_spec.rb
spec/models/order_detail_spec.rb

Steps to reproduce:
- Start with a complete order
- Go to the order detail modal
- Choose cancel
- We get the "Pricing Note is required" message
Make sure to handle both a normal cancelation where the actual costs are set to $0 and instrument cancelation with a fee (which technically keeps the order in "complete" state)

[#140234] cancel does not require pricing note

---

app/models/bundle.rb

Drop-down for creating a bundle should read "Timed Services" instead of "TimedServices".

[#139828] use humanized model names for bundle dropdown

---

app/controllers/facilities_controller.rb
app/views/shared/transactions/_search.html.haml
app/views/shared/transactions/_search2.html.haml
config/locales/en.yml
lib/transaction_search.rb

Related to changes from #1295 where we replaced the All Transaction search with the newer version from the reconciliation pages.
* "Export as CSV" was broken
* Did not prepopulate email address in prompt
* New controller action did not respond to `csv`
* Use "Filter" instead of "Search" for consistency with reconciliation page
* Move "Filter" button under the multi-select fields for consistency with reconciliation page
---
**Before:**
**After:**

[#140309] Fix All Transactions Search

---

app/presenters/order_detail_notice_presenter.rb
spec/presenters/order_detail_notice_presenter_spec.rb

https://pm.tablexi.com/issues/137726
Canceled orders were still showing payment badges that were not actually relevant (ie "Ready for Journal").  Canceled orders now do not show any irrelevant payment badges. 
Before:
After:

[#137726] hiding badges for canceled order details

---

spec/factories/orders.rb
spec/features/admin/all_transactions_search_spec.rb

It wasn’t running because it didn’t end in `_spec`. It should have been
failing due to the “Search” -> “Filter” change.

Fix naming of all_transactions_search spec

---

app/views/devise/sessions/new.html.haml

This was added to DC, but didn’t make it up into open.
https://github.com/tablexi/nucore-dartmouth/pull/118

Add login screen announcement view hook

---

app/views/facilities/transactions.html.haml
app/views/shared/transactions/_top2.html.haml

Related to #1295, on the all transaction view we were displaying the form and an empty table if the facility had no order details. This isn't that critical for All Transactions, but will become important when we switch over the other pages.
Before:
---
After:

Better display when no transactions found

---

app/models/order_detail.rb
app/services/transaction_search/date_range_searcher.rb
lib/transaction_search.rb
spec/factories/statements.rb
spec/services/transaction_search/date_range_searcher_spec.rb

In #1295 when we replaced the All Transactions search with the newer search logic, we lost the sorting, which should be reverse chronological by the date field in the dropdown (ordered at, fulfilled at, journal/statement at, reconciled at). This restores that ordering.

Fix date range ordering on All Transactions tab

---

app/services/transaction_search/base_optimizer.rb
app/services/transaction_search/n_plus_one_optimizer.rb
app/services/transaction_search/searcher.rb
lib/transaction_search.rb
vendor/engines/secure_rooms/app/services/secure_rooms/n_plus_one_occupancy_optimizer.rb
vendor/engines/secure_rooms/lib/secure_rooms/engine.rb

Extends from #1387. 
Gets rid of some N+1s in transaction search by adding a new array of optimizers. This also allows us to prevent the n+1 on secure room occupancies.

Fix transaction search N+1s

---

lib/nucore.rb

To be honest, I'm not 100% why this was failing on Dartmouth CI. The only thing I can think of is a slightly different MySQL version.
This change worked on Dartmouth: https://circleci.com/gh/tablexi/nucore-dartmouth/855

Fix ordering of desc nulls first

---

app/controllers/facility_facility_accounts_controller.rb

Northwestern and Dartmouth both have fork-specific `account_number_fields` (overriding AccountNumberSectionable) that need to be included in strong params.

handle strong params for facility facility accounts sections

---

Gemfile.lock
vendor/engines/ldap_authentication/ldap_authentication.gemspec

Upgrade devise_ldap_authenticatable which in turn upgrades net-ldap
https://github.com/cschiewek/devise_ldap_authenticatable/issues/242
```
Known vulnerability found
CVE-2017-17718
Moderate severity
The Net::LDAP (aka net-ldap) gem before 0.16.0 for Ruby has Missing SSL Certificate Validation.
Gemfile.lock update suggested:
net-ldap ~> 0.16.0
```

[#140451] Upgrade LDAP gems

---

app/controllers/order_details_controller.rb
app/services/transaction_search/searcher.rb
config/locales/en.controllers.yml
config/locales/en.yml
spec/features/disputing_an_order_spec.rb

After a BA or account owner goes in to the Transactions in Review page
and they dispute an order, they should be returned to Transactions in
Review rather than the My Orders/My Reservations page.
Also I18n the controller flashes

[#137156] Redirect to In Review after disputing

---

app/forms/transaction_search/search_form.rb

With strong params enabled, `to_h` will return a hash with only
permitted parameters included. We were using `to_h` to support `nil`,
i.e. `nil.to_h => {}`.
```
Hash({}) == {}
Hash(nil) == {}
Hash(normal_hash) == normal_hash
Hash(strong_params) == strong_params
```

Support transaction search with strong params enabled

---

app/views/facilities/transactions.html.haml
app/views/shared/transactions/_top2.html.haml
config/locales/en.yml

Broken by #1390, if there were no transactions matching the default
search on All Transactions (fulfilled since the beginning of last
month), the search form was not rendering.
Now, we will always render the form. This means the form might have no
values in any of the selects, but that should only happen until the
facility gets its first order.

[#140459] Fix display when no transactions on All Transactions

---

app/controllers/facility_notifications_controller.rb
app/views/facility_notifications/index.html.haml
app/views/shared/transactions/_search2.html.haml
spec/controllers/facility_notifications_controller_spec.rb
spec/features/admin/sending_notifications_spec.rb

Part of a larger replacement of `_with_search` with `TransactionSearch::SearchForm`/`TransactionSearch::Searcher`
This is half the story. The other half will be the "Orders in Review" (though the new feature spec does start to cover that piece)

[#140401] Filtering: Replace Send Notifications with new searcher

---

app/controllers/reservations_controller.rb
app/helpers/date_helper.rb
app/views/orders/_edit_date.html.haml
lib/ability.rb
spec/controllers/reservations_controller_spec.rb
spec/features/placing_an_order_on_behalf_of_spec.rb
spec/features/purchasing_a_reservation_on_behalf_of_spec.rb
spec/features/purchasing_a_reservation_spec.rb

To reproduce old issue:
* On a facility with an order form
* Order on behalf of another user
* Add "2" of an instrument to the cart
* "Create Reservation" on the other to the future. Click on the time to get to the edit page and change the start time. This one should have been working fine.
* "Create Reservation" on one of them to the past. 
* Click on the time. This is either not editable (if you're a director/staff), or if you're a global admin changing the start time would not persist.
This also adds authorizations for the reservation controller. Previously, you could copy a link, sign in as another user and still access the pages.

[#121458] Fix admin ability to edit past reservations in cart

---

app/views/facilities/movable_transactions.html.haml
app/views/facility_notifications/index.html.haml

We changed how no transactions displayed in #1411. This broke the outstanding
PRs of #1399 and #1402

Fix display of no transactions on movable transactions and send notifications

---

app/controllers/facility_notifications_controller.rb
app/views/facility_notifications/in_review.html.haml
spec/controllers/facility_notifications_controller_spec.rb
spec/features/admin/review_period_spec.rb

Extends from #1399 to replace the Orders in Review search/filtering.
Clean diff https://github.com/tablexi/nucore-open/compare/send_notifications_replace_searcher...replace_orders_in_review_with_new_search_140401?expand=1

[#140401] Replace orders in review with new search

---

config/eye.yml.erb.template

These settings are not useful. They mean eye is just sitting waiting for the process to come up even after it has returned a successful exit
status.
These will go downstream to the different schools. This is just a template file. I've applied the changes on all the servers.

Remove start/stop grace from eye config

---

app/models/order_detail.rb
app/models/reservation.rb
spec/controllers/accounts_controller_spec.rb

https://pm.tablexi.com/issues/140279
Cleaned up a few queries to use the `.or` operator or otherwise modernize their syntax. There weren't as many spots where it made sense to use the `or` operator as expected, in part because of the very specific parallel structure requirements--gets very messy with joins etc.

[#140279] clean up queries

---

app/controllers/accounts_controller.rb
app/views/accounts/transactions_in_review.html.haml
spec/controllers/accounts_controller_spec.rb

Found while working on filter cleanup for accounts/transactions--these are unused. See https://github.com/tablexi/nucore-open/blob/master/app/controllers/transactions_controller.rb#L14 for the current path.

rm unused controller action/view

---

config/deploy/staging.rb

This changes the capistrano configuration to use tablexi-shared02.txihosting.com as the server. For more details see the discussion on tablexi/chef-repo#1781

Update capistrano server

---

app/controllers/transactions_controller.rb
app/views/transactions/index.html.haml
config/locales/en.yml

- users can view only administered order details
- add account owner searcher
- add no results message rather than displaying empty table

[#139338] Cross Payment Source bounceback changes

---

app/models/order.rb
app/services/order_purchaser.rb
spec/controllers/orders_controller_spec.rb
spec/models/order_spec.rb

https://pm.tablexi.com/issues/140462
Instrument order details should always have order status determined by their dates.

[#140462] order on behalf of reservation statuses determined by dates

---

config/settings.yml
vendor/engines/saml_authentication/README.md
vendor/engines/saml_authentication/lib/saml_authentication/devise_configurator.rb

The University of Connecticut Shibboleth server prefers the HTTP Redirect SAML binding for sign-in. Changing this required overriding the idp_sso_target_url SAML setting passed to ruby-saml.
This is my first pull request for the project, so let me just note the following: I am perfectly fine modifying/improving anything that may not be up to maintainer expectations. I wouldn't call myself a Ruby expert, so if I'm doing something that's not a best practice, please feel free to be blunt and call me out on it. This follows for any future pull requests I make.

Add settings override for default ruby-saml params

---

app/controllers/application_controller.rb
app/controllers/facilities_controller.rb
app/helpers/products_helper.rb
app/models/concerns/users/roles.rb
app/models/facility.rb
app/models/product.rb
app/models/user.rb
app/services/most_recently_used_searcher.rb
app/views/facilities/_product_list.html.haml
app/views/facilities/index.html.haml
config/locales/en.yml
config/locales/views/en.facilities.yml
spec/models/user_spec.rb
spec/services/most_recently_used_searcher_spec.rb

Add a list of the user's 10 most recently purchased products to the user's home page. 
Allow users to access frequently used products faster.
- Rename `sorted` scope on Facilitiy model to `alphabetized`
- Add `MostRecentlyUsedSearcher` service object for Products and Facilities
- Refactor `public_calendar` view helper to handle non-specific facility context

[#137627] add links to 10 most recently purchased products to home page

---

Gemfile
Gemfile.lock

TECH TASK: Revert Rubocop to latest version supported by CodeClimate
Will update back to 0.53.0 when official support is added: https://github.com/codeclimate/codeclimate-rubocop/issues/118

revert rubocop to latest version supported by codeclimate

---

Gemfile.lock

TECH TASK: Addresses CVE-2018-8048
https://github.com/flavorjones/loofah/blob/master/CHANGELOG.md#221--2018-03-19
Addresses a medium-severity security issue identified within the loofah gem (used by rails-html-sanitizer)

Update Loofah to 2.2.1 for security warning

---

app/services/most_recently_used_searcher.rb
spec/controllers/facilities_controller_spec.rb

Fix error on recently used products/facilities when there is no logged in user, follow up to https://github.com/tablexi/nucore-open/pull/1429.
Error was occurring because we were trying to chain additional scopes onto `recently_used_facilities` and `recently_used_products` in `facilities#index`, which was an empty array rather than an empty AR relation when no user is present.

[#137627] recently used products/facilities still works when no logged in user

---

app/views/facility_accounts/accounts_receivable.html.haml

Fix links from Accounts Receivable in the billing tab to properly redirect to All Transactions with the account prepopulated in the filter.

[#140608] Fix links from Accounts Receivable

---

app/helpers/application_helper.rb

Keep existing filter params when sorting on pages like the reservation/orders new/in process tabs.

[#141105] keep existing filter params when sorting

---

app/views/reservations/_account_field.html.haml
app/views/reservations/edit.html.haml
config/locales/en.yml

Add a hint clarifying that notes on reservations are visible to facility staff only.

[#140541] add a hint that reservation note visible to admins only

---

app/models/reports/export_raw.rb
spec/models/reports/export_raw_spec.rb

Add Assigned User column to export raw
Added as the last column because many use the export raw format in their reporting so adding the column earlier could mess up their templates by shifting columns to the right.

[#140980] Add Assigned User to export raw

---

app/controllers/users_controller.rb
app/forms/user_form.rb
app/models/user.rb
app/views/users/edit.html.haml
app/views/users/new_external.html.haml
spec/controllers/users_controller_spec.rb
spec/features/admin/managing_user_spec.rb

Refactor user creation and updating to use a form object, enabling custom validations etc on a per-school basis.
Changes in open to enable requested Dartmouth features, see https://github.com/tablexi/nucore-dartmouth/pull/179 for additional context. Companion to https://github.com/tablexi/nucore-dartmouth/pull/181.

[#140361] refactor user creation/updating to use user form object (open)

---

app/assets/javascripts/app/calendar.js.coffee
app/controllers/facility_reservations_controller.rb
app/forms/admin_reservation_form.rb
app/presenters/reservations/calendar_presenter.rb
app/views/facility_reservations/_admin_reservation_fields.html.haml
app/views/shared/timeline/_facility_tooltip.html.haml
config/locales/en.models.yml
db/migrate/20180330180908_add_user_note_to_reservations.rb
db/schema.rb
spec/app_support/reservations/rendering_spec.rb

Add a note for users on admin reservations and display in hover-over on the instrument calendar view.

[#140541] add user facing note for admin reservations

---

app/controllers/application_controller.rb
spec/features/accessing_invalid_files_spec.rb

Prevent hard errors when attempting to access a page not found with a non-html form, e.g. PDF or XML.
Some data redacted. This can happen on any 404 page, for example `/facili.pdf`.
```
An ActionView::MissingTemplate occurred in facility_accounts#show_statement:
Missing template /404 with {:locale=>[:en], :formats=>[:pdf], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :prawn, :haml]}. Searched in: * 
... [redacted]
app/controllers/application_controller.rb:131:in `render_404'
-------------------------------
Request:
-------------------------------
URL : [redacted]/facilities/xxx/accounts/xxx/statements/xxxx.pdf
```

[#141334] Prevent errors on non-html 404s

---

db/migrate/20160614185348_add_type_to_reservations.rb
db/migrate/20170501201633_add_canceled_to_order_detail.rb

Tech task: Migration from scratch became broken after we introduced Paranoia.
Errors because `deleted_at` column does not exist on earlier migrations of `Reservation`

Fix migration from scratch caused by paranoia

---

spec/features/accessing_invalid_files_spec.rb

Fix routing in spec to use i18n to resolve test failures in forks with alternative translations.

use i18n in routing for spec

---

app/controllers/facilities_controller.rb
app/models/order_detail.rb

Remove order clause from query that causes an oracle compatibility issue.

remove ordering clause that causes oracle compatibility issue

---

config/eye.yml.erb.template

TECH TASK: Prevent `eye restart unicorn` from thinking unicorn has crashed
This change has been made on txi stage and NU servers.
https://github.com/tablexi/nucore-nu/pull/361/files

Add restart_grace for unicorn

---

app/views/users/show.html.haml
config/environments/test.rb
config/locales/en.account_components.yml
config/locales/en.yml

Fix missing translation errors in development. Tech task: raise missing translation errors in test.
By turning on `raise_on_missing_translation` in test, we'll hopefully catch these issues sooner.
Recharge chart string issue was ntroduced in #1493 because I thought this was duplicated, but turns
out this is used by `t("#{account_class.name.underscore}.account_fields.label.account_number
.#{section}”),`
User activate was a typo in #1481
"Remove from journal" has been around for a while. It's never been a problem in production because `raise_on_missing_translation` is set to false on stage and prod, so it just falls back to the titleized version, "Remove From Journal", which is what the translation was anyways.
Resolves #1496

Fix missing translations and enable raising in errors in test/CI

---

app/views/reservations/_reservation_fields.html.haml
config/locales/en.yml
config/locales/views/en.reservations.yml

Add a hint for the reservation duration field on the reservation new/edit views.

[#137478] add hint for reservation duration field

---

vendor/engines/saml_authentication/spec/controllers/saml_authentication/sessions_controller_spec.rb

Ensure matching on email/username to migrate existing email users to SSO via SAML is case-insensitive.

[#140938] add specs to ensure case-insensitive matching

---

app/assets/javascripts/schedule_rules.js
app/views/reservations/edit.html.haml

Fixes: true/false appearing on reservations edit view. and schedule rule column headers were showing up as “object Object”.
[#141580] Schedule rule issues was due to an API change to Full Calendar. https://fullcalendar.io/docs/columnFormat
[#137466] true/false was accidentally left in from debugging on #1478.

[#141580] [#137466] Fixes from full calendar changes

---

app/assets/javascripts/instruments.js
app/assets/stylesheets/calendar/fullcalendar.extensions.scss
app/views/schedule_rules/index.html.haml

Clean up styling issues from Fullcalendar upgrade.
Note the extra space:
Large text:
Clean up date sizing and move to the left:
Clean up extra vertical space on schedule rules page:

Calendar header cleanup

---

spec/features/admin/suspending_a_user_spec.rb

Fix spec for suspending a user, which was failing on forks where create_user is not turned on.

enforce feature setting on for suspending a user spec

---

README.md

This PR does two things:
1. It moves the step to set up `config/secrets.yml` to be before the step for creating databases. Otherwise, `bundle exec rake db:create` results in an error complaining that `secret_key_base` is not set.
1. It simplifies the step to create local databases (development and test both) into a single `rake db:setup`. This tasks [does the creation and loading of seeds in one step](https://github.com/rails/rails/blob/v4.2.10/activerecord/lib/active_record/railties/databases.rake#L167-L168), and `db:create` [defaults to creating both the test and development databases when an environment is not specified](https://github.com/rails/rails/blob/v4.2.10/activerecord/lib/active_record/railties/databases.rake#L15), so we don’t have to run it twice.

Update setup steps in README

---

app/controllers/application_controller.rb
spec/features/accessing_invalid_files_spec.rb

Prevent hard error when accessing a reservation calendar invitation (.ics file) that does not belong to you.
```
ActionView::MissingTemplate: Missing template /403 with {:locale=>[:en], :formats=>[:ics], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :prawn, :haml]}. Searched in:
* "/home/nucore/nucore.northwestern.edu/releases/20180319223809/vendor/engines/jxml/app/views"
* "/home/nucore/nucore.northwestern.edu/releases/20180319223809/vendor/engines/c2po/app/views"
* "/home/nucore/nucore.northwestern.edu/releases/20180319223809/app/views"
* "/home/nucore/nucore.northwestern.edu/releases/20180319223809/vendor/engines/split_accounts/app/views"
* "/home/nucore/nucore.northwestern.edu/releases/20180319223809/vendor/engines/acgt/app/views"
* …
```

[#141448] Prevent hard error on unauthorized access to ICS file

---

app/controllers/reservations_controller.rb
app/models/reservation.rb
config/locales/en.controllers.yml
spec/controllers/reservations_controller_spec.rb

Improve error message when attempting to start a reservation in the grace period while the previous reservation is still running.
Example: 
User 1 creates a reservation from 9-10 and starts their reservation
User 2 creates a reservation from 10-11
At 9:55, when the grace period begins, User 2 sees the "Begin Reservation" link. When clicking the link, they previously saw a confusing error generated by AASM. Now, display a more useful error message.
Unchanged behavior: once the grace period is over at 10:00 (i.e. the previous reservation is
technically over), “Begin Reservation” will start the reservation for User 2 and
move User 1's reservation to the problem queue.
Old message:

[#137552] Better error message when beginning a reservation in grace period

---

app/support/reservations/validations.rb
spec/models/reservation_spec.rb

Prevent users from create & starting a reservation in the 5 minute grace period if they are not part of the required schedule groups.
* Create an instrument
* Control mechanism: Timer without relay
* Requires Approval: Yes
* Usage or overage price rule
* With a "Night" schedule group
* Schedule rules
* A 9-5 globally available schedule rule
* A 5-midnight schedule rule for "Night"
A few test scenarios:
* As a user not in the "Night" group at anytime after 5:00, so say 5:30, adjust the fields for a 5:35 reservation. This will allow you to create the reservation, even though you are not in the required schedule group.
* As a user not in the "Night" group, at 4:55, create an hour-long reservation and "Create & Start". This should not create a reservation.
* As a user, at 4:31pm, create a …

[#141569] Prevent start for schedule groups in grace period

---

app/models/reservation.rb
app/support/reservations/validations.rb
config/locales/en.models.yml
spec/models/reservation_spec.rb

Improve error message when a user is not in the proper schedule group when placing a reservation.
If there are no schedule groups, then we continue to get the old message if the reservation is outside the schedule rules.
A few cases (hopefully all covered by the specs):
* Not restricted - "The reservation spans time that the instrument is unavailable for reservation"
* On behalf of, not restricted - "The reservation spans time that the instrument is unavailable for reservation"
* Restricted, no schedule groups - "The reservation spans time that the instrument is unavailable for reservation"
* On behalf of, restricted, no schedule groups - "The reservation spans time that the instrument is unavailable for reservation"
* Restricted, plus a 5-midnight "Night" group, user not in group - "You …

[#137710] Improve schedule group error message

---

app/controllers/users_controller.rb
lib/ability.rb
spec/lib/ability_spec.rb

Prevent account managers from suspending/unsuspending users.
We were giving account managers full `:manage` access to `User`. This cuts down their access and whitelists only the things they should be able to do. I believe we had originally gone with `:manage` because there were a lot of actions. Hopefully, we've got them all here.

[#141837] Prevent account managers from suspending users

---

app/assets/stylesheets/app/global_alert_banner.scss
app/assets/stylesheets/application.scss
app/views/layouts/application.html.haml

Add hooks/styles for an alert banner (not used by default).
Example from Dartmouth:
Companion to https://github.com/tablexi/nucore-dartmouth/pull/187/commits

[#140939] Add alert banner style and hooks

---

lib/ability.rb
spec/lib/ability_spec.rb

Fixes ability specs when `create_users` setting is turned off (e.g. UIC).
Fixes #1542 when merged into UIC

[#141837] Fix ability spec for account managers when `create_users` is turned off

---

app/controllers/reservations_controller.rb
app/models/user.rb
spec/controllers/reservations_controller_spec.rb

Prevent "argument out of range" errors when browsers are still running old Fullcalendar code.
For some reason, we’re continuing to get `reservations#index
(ArgumentError) "argument out of range”` errors caused by start/stop
parameters being in unix timestamp format. This format changed when we
upgraded Fullcalendar, so it seems like some browsers are continuing to
load the old code. That shouldn’t be happening because the library
should be fingerprinted.
This should stop the errors.
See: https://github.com/tablexi/nucore-open/pull/1478
Example:
https://nucore.northwestern.edu/facilities/imserc/instruments/nmr_a600/reservations.js?all=true&amp;with_details=true&start=1524373200&end=1524978000&_=1524755233886
Referrer: https://nucore.northwestern.edu/facilities/imserc/instruments/nmr_a600/sc …

[#141665] Support both unix timestamps and iso8601 in calendar endpoint

---

config/application.rb

Fix Rails 5 auto/eager loading problem on stage.
Rails 5 disables autoloading by default, so anything in `/lib` was not being found
when it is first used. The big one is
```
NameError: uninitialized constant ApplicationController::Ability
File "/home/nucore/nucore.stage.tablexi.com/releases/20180511175626/app/controllers/application_controller.rb" line 181 in current_ability
```
You can reproduce this problem locally by changing `config.cache_classes` and `config.eager_load` to `true` in `environments/development.rb`.
The other option would be to add these same paths to `eager_load_paths`. I just needed to get this out quickly so we can use open stage.

Fix constant not found problem on stage

---

app/views/facility_journals/_downloads.html.haml

Adds a ViewHook that allows Rails engines to add new file formats to the journal download section.
We're adding a custom journal download format for our financial system.

Add a ViewHook for journal download formats

---

app/assets/javascripts/app/reservation_calendar.js
app/views/reservations/edit.html.haml
app/views/reservations/new.html.haml
config/settings.yml

Enable calendar drag and drop for everyone.
Enables #1478 for everyone by removing the feature flag. NU has been running with this feature for a while, so let's enable it for everyone else.

[#137466] Enable calendar drag-and-drop by default

---

app/views/product_users/index.html.haml

Fix spacing on access list index when there are no users on the list.
Before:
After:

Fix spacing on access list index

---

app/assets/javascripts/price_policy.js.coffee
app/controllers/price_policies_controller.rb
app/helpers/price_policies_helper.rb
app/models/price_policy.rb
app/services/price_policy_builder.rb
app/services/price_policy_updater.rb
app/views/price_policies/_dates.html.haml
app/views/price_policies/_price_policy_fields.html.haml
app/views/time_based_price_policies/_price_policy_fields.html.haml
config/locales/en.controllers.yml
spec/app_support/price_policy_mass_assigner_spec.rb
spec/factories/price_policies.rb
spec/models/item_price_policy_spec.rb
spec/models/order_detail_spec.rb
spec/models/price_policy_spec.rb
spec/models/service_price_policy_spec.rb
spec/price_policies_controller_shared_examples.rb
vendor/engines/secure_rooms/app/views/secure_room_price_policies/_price_policy_fields.html.haml

Better handling of errors for invalid dates in price policy forms.
There was no validation on expire date before, but would hard error if the expire date was invalid/blank (`NoMethodError: undefined method `end_of_day' for nil:NilClass`). Adding that validation did cause some problems with specs that weren't setting it, but I think I got all those cleaned up.
This will now also include some JS validation as used elsewhere which does not actually block the submission. On submit, it will be treated as a null/blank field and on re-render will be blank.

[#137474] Handle invalid dates in price policies

---

config/settings.yml
vendor/engines/saml_authentication/lib/saml_authentication/engine.rb

Tech task: Allow the `saml_authentication` engine to be enabled, but not user-accessible. This will allow the `/users/saml/metadata` endpoint to be accessible so an IdP can import it for configuration, but not yet allow users to log in with it.
This basically hides the login button. In order to set up production for Dartmouth, we're going to need to provide them the metadata so they can import it into their system before the feature will work. So the "off" setting will only be a temporary measure.
There will be a DC PR that sets this configuration option.

Allow SAML engine semi-enabling

---

app/assets/stylesheets/app/header.scss
app/assets/stylesheets/responsive.scss
app/views/shared/_header.html.haml
config/settings.yml

This change allows administrators to add a logo to their header. The new logo image should be called "logo-header.png" and it should be placed in the "app/assets/images/" folder. The changes are not visible immediately, only after the asset pipeline is rebuilt (which just involves restarting Rails).
The diff is a little interesting because the header was redone in Flexbox. The new version is pixel-for-pixel the same, though, and it shouldn't affect user overrides as far as I can tell.
(this is px-for-px the same as "Before")
This is part of a larger set of changes to the design.

Allow admin-defined logo in header

---

Gemfile
Gemfile.lock

TECH TASK: Allow using ed25519 keys to deploy via capistrano
Without these gems, capistrano fails with the following message:
```
$ bundle exec cap staging deploy
(Backtrace restricted to imported tasks)
cap aborted!
NotImplementedError: unsupported key type `ssh-ed25519'
net-ssh requires the following gems for ed25519 support:
* rbnacl (>= 3.2, < 5.0)
* rbnacl-libsodium, if your system doesn't have libsodium installed.
* bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/478 for more information
Gem::LoadError : "rbnacl is not part of the bundle. Add it to your Gemfile."
Tasks: TOP => rvm:hook
(See full trace by running task with --trace)
```
https://blog.g3rt.nl/upgrade-your-ssh-keys.html is a good overview of Ed25519 SSH keys, and why it’s a good idea to migrate …

Add gems to suport ed25519 keys in capistrano

---

config/deploy.rb

TECH TASK: Update Capistrano lock to match updated gem version
https://github.com/tablexi/nucore-open/pull/1582 broke deployments, because Capistrano includes a version lock in addition to the one in `Gemfile.lock`.

Update Capistrano lock to same version as gem

---

app/assets/javascripts/app/calendar.js.coffee
app/presenters/reservations/calendar_presenter.rb
app/views/facility_reservations/edit_admin.html.haml
app/views/facility_reservations/new.html.haml
app/views/facility_reservations/show.html.haml
app/views/instruments/schedule.html.haml
spec/app_support/reservations/rendering_spec.rb

Add an order edit link for each reservation on the product calendar
For the reviewer: I went back and forth between adding an `orderId` attribute in `CalendarPresenter`, and adding an `editOrderPath` attribute (so that the JS code doesn’t have to construct a path). I chose the former approach because the serialization of a Reservation may be used in other contexts beyond this calendar, where that path does not make sense. Additionally, exposing the base path to edit orders mimics the way we expose `events_path` as a global (which I’m not in love with, but that’s a refactoring for another day).

[#136143] Add an order edit link for each reservation on the product calendar

---

vendor/engines/c2po/spec/controllers/facility_accounts_controller_spec.rb

TECH TASK: Match against the first configured account type instead of hard-coding NufsAccount in test
`FacilityAccountsController` checks the list of configured account types, and picks the first one available. When another engine modifies the list in addition to the `c2po` engine, as some school-specific engines do, `NufsAccount` may not be the first configured account type, and these tests fail because they expect incorrect behavior. Hence, this PR modifies the test to assert against the configured account type instead of assuming it will always be `NufsAccount`.

Match against the first configured account type instead of hard-coding NufsAccount in test

---

spec/models/product_for_cart_spec.rb

TECH TASK: Ensure that test checking for accounts does not fail due to a lack of price groups
Some of the school-specific forks contain engines that override `Product#can_purchase?` with rules beyond the default ones. As a result of this, the test which exercises the check that the acting user has appropriate accounts gets tripped up by the false return of `Product#can_purchase?`, which executes sooner. Since we test that path separately, in this context we stub it away to ensure that we get to the check we’re interested in testing.

Ensure that test checking for accounts does not fail due to a lack of price groups

---

spec/models/product_for_cart_spec.rb

TECH TASK: Use single quotes instead of correct apostrophe marks to appease rubocop

Use single quotes instead of correct apostrophe marks to appease rubocop

---

config/locales/en.yml
vendor/engines/saml_authentication/lib/saml_authentication/engine.rb
vendor/engines/saml_authentication/lib/saml_authentication/saml_authenticatable_with_custom_error.rb
vendor/engines/saml_authentication/spec/controllers/saml_authentication/sessions_controller_spec.rb

Allow customizing error message for non-existent users signing in via SAML
The SAML authentication strategy for Devise currently uses the same i18n key for failed logins as other strategies (`devise.failure.invalid`). This PR makes SAML failed logins use `saml_invalid`, so we can customize the messaging in this flow separately from the email & password flow.

[#142184] Allow customizing error message for non-existent users signing in via SAML

---

app/controllers/reservations_controller.rb
app/models/order_detail.rb
spec/controllers/reservations_controller_spec.rb
spec/models/order_detail_spec.rb

Do not show canceled reservations on My Reservations screen
The ticket mentions that problem reservations should not appear on this screen either; however, from what I can [see in the code](https://github.com/tablexi/nucore-open/blob/0be253c1abda99036b59acb249a4b8a644028e00/app/models/order_detail.rb#L896-L904) only completed reservations can be problematic. Since completed reservations do not appear on the My Reservations screen (which shows only upcoming and in-progress reservations), there was nothing to be done there.

[#139111] Do not show canceled reservations on My Reservations screen

---

app/assets/stylesheets/app/product_list.scss
app/assets/stylesheets/application.scss
app/controllers/facilities_controller.rb
app/views/facilities/_product_list.html.haml
app/views/facilities/show.html.haml
config/settings.yml

Instead of a single list of objects belonging to a facility, multiple columns representing each type of object are used.

Split facility sub-items to their own columns

---

app/controllers/product_accessories_controller.rb
spec/controllers/product_accessories_controller_spec.rb

Exclude archived, aka inactive, products from the available accessory dropdown within instrument management.
Within this dropdown:

[#139184] Exclude inactive/archived products from available accessories

---

app/views/notifier/new_user.html.haml
app/views/notifier/new_user.text.erb

Add additional interpolation values into new user email for use in NU's updated message.
Companion to NU's https://github.com/tablexi/nucore-nu/pull/386 
I considered doing further refactoring/cleanup (there's a lot of duplication between the text and html version), but I didn't want to affect DC, who also overrides this email.

[#139276] Add extra interpolation params to new user email

---

app/support/reservations/relay_support.rb

TECH TASK: Remove method Reservations::RelaySupport#can_kill_power?
The method was [deprecated over 5 years ago](https://github.com/tablexi/nucore-open/commit/5e24403a6dcbd640ee560542970ae3928beea92f#diff-b39c6bac92522dc31e5c571520c942faR30), and it is not used anywhere.

Remove method Reservations::RelaySupport#can_kill_power?

---

app/models/order_detail.rb
spec/models/order_detail_spec.rb

Only show reservations with state new or inprocess reservations in My Reservations
After #1591, reservations that are canceled with a cost continued to appear in My Reservations, since these have a state of `completed` along with a `canceled_at` timestamp. Since we only want new or in-progress reservations, it is more direct and simpler to filter asking for those, instead of filter to reject canceled (or any other states that we don’t want).

[#139111] Only show reservations with state new or inprocess in My Reservations

---

vendor/engines/saml_authentication/app/controllers/saml_authentication/sessions_controller.rb

Fix error on logout link when signed in via SSO.
```
ActionView::Template::Error: undefined method `destroy_saml_authenticatable_with_custom_error_user_session_path
```
Broken after #1589 changed the strategy name to "saml_authenticatable_with_custom_error",
which causes a mismatch with the route. The old version is probably overly general. Within this controller, the winning strategy should always we `saml_authenticatable`.

[#140359] Fix SAML logout link error

---

app/controllers/order_management/order_details_controller.rb

Filter sub-statuses of Canceled to current facility in the order detail modal.
When an order is canceled, the order status dropdown was including all sub-statuses of Canceled, even across facilities. This filters to only the current facility.

[#73295] Filter sub-statuses of Canceled to current facility

---

app/forms/user_form.rb

Fix delegation on UserForm caused by simple_form 3.5.1. This will fix downstream forks that use custom UserForms.
See #1410 for what we did to fix this on other forms. The form was being rendered
with the `User` as the form object, not the `UserForm` so any custom errors or
I18n were lost.
There will be a PR for Dartmouth coming soon.

Fix delegation on UserForm caused by simple_form 3.5.1

---

spec/models/order_import_spec.rb

TECH TASK: Make OrderImport spec more flexible to allow different account number formats.
This is coming out of work I'm doing on the validator for Dartmouth. Their account numbers are in a different format, so this is triggering validation errors. This will now use the format described by the `nufs_account` factory, which can be overridden per school.
I know this is not publicly accessible, but here is the current branch I've been working on: https://github.com/tablexi/nucore-dartmouth/compare/dartmouth_account_validator_142015?expand=1

[#142015] Make order import spec use the nufs_account format

---

vendor/engines/saml_authentication/lib/saml_authentication/saml_authenticatable_with_custom_error.rb
vendor/engines/saml_authentication/spec/controllers/saml_authentication/sessions_controller_spec.rb

Allow clickable links in failure message for SAML sign-in
If `fail!` is used with a symbol, Devise performs its own `I18n.t` lookup, which is not marked as `html_safe`. If the argument is a string, it only calls `to_s` on it, so we take advantage of that code path to pass in our own html-safe string.

[#142184] Allow clickable links in failure message for SAML sign-in

---

lib/tasks/price_policies.rake

Add a rake task for copying the all service price policies from the previous fiscal year into the current fiscal year.
UIC has a facility with 200+ services. They requested that all of the
price policies be extended to 06/30/2019 (the end of the next fiscal
year). Since price policies are not allowed to span fiscal years in
NUcore, this makes new copies with the requested dates.

[#142643] Rake task for new price polices in the current fiscal year

---

spec/models/product_for_cart_spec.rb

TECH TASK: When the feature is disabled, the route is not available.
```
NoMethodError:
undefined method `new_facility_product_training_request_path' for #<Module:0x007fbeaaca4f98>
Did you mean?  new_facility_instrument_product_access_group_path
```

Fix spec broken when training request feature is disabled

---

.circleci/config.yml

Tech task: (Hopefully) fix coverage report sending to CodeClimate. Also, fix stage deployment branch name. Also reorders some steps and fixes an indentation error.
Related to #1626. Looking at the codeclimate_circle_ci_coverage gem, it looks like it doesn't play well if you have a working directory since it looks in `home/circleci/project/#{ARTIFACT_PREFIX}/.resultset.json"`. See https://github.com/rdunlop/codeclimate_circle_ci_coverage/blob/master/lib/codeclimate_circle_ci_coverage/circle_ci_2.rb
See https://github.com/rdunlop/codeclimate_circle_ci_coverage/issues/8
If this doesn't work, then we can just comment it out for now.

Fix Circle 2.0 coverage reporting

---

vendor/engines/secure_rooms/db/migrate/20170405182534_add_tablet_token_to_card_readers.rb

Tech task: Fix SecureRooms migration.
The superclass of SecureRooms::CardReader in the migration needs to match the
superclass of the app class. We had originally run this migration on NU's stage
before the change to ApplicationRecord. Now that we're trying to deploy to production,
the migration is failing.

Fix SecureRooms migration

---

app/mailers/order_detail_dispute_mailer.rb
app/services/order_details/assignment_notifier.rb
app/services/order_details/dispute_resolved_notifier.rb
app/services/order_details/param_updater.rb
app/views/order_detail_dispute_mailer/dispute_resolved.html.haml
app/views/order_detail_dispute_mailer/dispute_resolved.text.erb
config/locales/views/en.order_detail_dispute_mailer.yml
spec/controllers/order_management/order_details_controller_spec.rb
spec/factories/order_details.rb
spec/mailers/previews/order_detail_dispute_mailer_preview.rb
spec/rails_helper.rb
spec/services/order_details/dispute_resolved_notifier_spec.rb

[#133717] When a dispute is resolved, send an email to the user who disputed the charges as well as the owner and business administrators of the order's account.
[#142698] Do not trigger email notifications to assigned users when the save is not successful (open/UIC only)
I discovered the assigned user issue as I was working on the dispute notification and the refactoring idea I had applied to it as well, so I lumped them together. The order assignment notification feature is currently disabled on NU & Dartmouth but is enabled in open and UIC.
See see https://github.com/tablexi/nucore-open/pull/86 for the original order notification feature.
* Open the order detail in the popup
* Change the assigned user
* Do something to make the form invalid (clearing out the price field for example)
* …

[#133717] [#142698] Notify users on dispute resolution

---

.circleci/config.yml

Tech Task: Only run `teaspoon` (javascript tests) on a single CI job.
We were getting a bunch of failures where PhantomJS was crashing. While I couldn't find any logs detailing _why_ it crashed, I suspect that it's because it was trying to start up the teaspoon server on each job on the same port. Ports are shared across all the jobs since they're all run on the same host, so they can conflict with each other.
Before this, I was seeing errors about 50% of the time. I ran this a few times w/o `rspec` and I haven't seen it yet. https://circleci.com/gh/tablexi/nucore-open/tree/phantom_js3

Only run teaspoon on one CI job

---

.circleci/config.yml

Tech task: Remove timezone setting from circle configuration.
On a whim, I decided to test this out. So far, looking good. I want to kick it off one more time in the  it's today here, but tomorrow in UTC.

Remove timezone setting from circle

---

app/mailers/order_detail_dispute_mailer.rb
app/services/order_details/assignment_notifier.rb
app/services/order_details/dispute_resolved_notifier.rb
app/services/order_details/param_updater.rb
app/views/order_detail_dispute_mailer/dispute_resolved.html.haml
app/views/order_detail_dispute_mailer/dispute_resolved.text.erb
config/locales/views/en.order_detail_dispute_mailer.yml
spec/controllers/order_management/order_details_controller_spec.rb
spec/factories/order_details.rb
spec/mailers/previews/order_detail_dispute_mailer_preview.rb
spec/services/order_details/dispute_resolved_notifier_spec.rb

Tech task: Backport #1624 Notify users on dispute resolution to Rails 4.2
Has an additional change beyond the original PR as the code was relying on some Rails 5 functionality (`[attribute]_previously_changed?` existing).

[#133717] Backport #1624 to Rails 4.2

---

app/controllers/facility_facility_accounts_controller.rb
app/forms/facility_account_form.rb
app/models/account.rb
app/models/facility_account.rb
app/models/order_detail.rb
app/views/facility_facility_accounts/_facility_account_fields.html.haml
app/views/facility_facility_accounts/edit.html.haml
app/views/facility_facility_accounts/index.html.haml
app/views/shared/_account_fields.html.haml
config/locales/views/admin/en.facility_facility_accounts.yml
lib/validator/validator_factory.rb
spec/controllers/facility_facility_accounts_controller_spec.rb
spec/factories/facility_accounts.rb
spec/models/instrument_for_cart_spec.rb

Disable editing of recharge chart strings. Tech task: Improve extensibility of recharge chart string validations.
Extracted from https://github.com/tablexi/nucore-dartmouth/pull/206
Refactors out a form object so we can hook in callbacks around validation. For example, making a call to an API to populate a validation table in Dartmouth's case.
This also disables editing of existing FacilityAccounts. NU confirmed that this is good. There could have been the possibility of creating a valid chart string and then later the chart string becomes invalid. You wouldn't be able to mark it as invalid because it would have failed validation.

Disable editing of recharge chart strings

---

db/schema.rb

Tech task: Refresh schema in Rails 5.0
I was looking at another ticket that was going to need a migration and saw the schema change was really noisy because of some changes in the format between rails 4.2 and 5.
From a fresh database:
```
bin/rake db:create db:schema:load db:schema:dump
```

Refresh schema.rb for Rails 5.0

---

config/database.yml.oracle.template
doc/HOWTO_oracle.md
docker/oracle/setup.sql

I thought I had this documentation committed already, but turns out not.

Add instructions for loading a database dump into Oracle/Docker

---

spec/factories/accessories.rb
spec/factories/account_users.rb
spec/factories/accounts.rb
spec/factories/external_services.rb
spec/factories/facilities.rb
spec/factories/facility_accounts.rb
spec/factories/journals.rb
spec/factories/nufs_accounts.rb
spec/factories/order_details.rb
spec/factories/orders.rb
spec/factories/payments.rb
spec/factories/price_groups.rb
spec/factories/price_policies.rb
spec/factories/products.rb
spec/factories/relays.rb
spec/factories/reservations.rb
spec/factories/schedule_rules.rb
spec/factories/stored_files.rb
spec/factories/user_preferences.rb
spec/factories/users.rb

Updates the factory definitions, as factory_bot is deprecating the static attributes (only block-style attributes are supported in the future).
Ref: https://robots.thoughtbot.com/deprecating-static-attributes-in-factory_bot-4-11

Update factory definitions

---

app/controllers/account_price_group_members_controller.rb
app/views/account_price_group_members/search_results.html.haml
spec/controllers/account_price_group_members_controller_spec.rb
vendor/engines/c2po/spec/controllers/account_price_group_members_controller_spec.rb

Enhance account price group member search results to include full account number. Also, limit the results to only include global payment sources or ones specific to that facility.
Before, we were just displaying the account number. Instead, let's display the
full account number with description like we do everywhere else.

[#143112] Enhance account price group member search results

---

config/locales/en.models.yml
spec/features/admin/manage_order_detail_spec.rb

Tech task: Allow "Reservation Cost" text to be overridden.
Taken from https://github.com/tablexi/nucore-dartmouth/pull/217

[#136049] Allow reservation cost to be overridden

---

spec/controllers/account_price_group_members_controller_spec.rb

Tech task: Fix spec when account number is not considered valid.
In Dartmouth and possibly other schools, the "TESTING123" is not a valid format, but
for the sake of this spec, we don't care: we just need it to be considered a global
account type.
Fixes the merge of https://github.com/tablexi/nucore-open/pull/1659 into DC

[#143112] Fix spec when account number is not valid

---

Gemfile

the `haml_lint` documentation recommends `require: false` so that the linter code is not loaded in rails.

haml_lint should not be loaded as part of the application

---

app/controllers/users_controller.rb
app/models/serializable_facility.rb
app/views/admin/shared/_tabnav_users.html.haml
lib/ability.rb
spec/lib/ability_spec.rb
vendor/engines/bulk_email/app/controllers/bulk_email/bulk_email_controller.rb
vendor/engines/bulk_email/app/decorators/bulk_email/job_decorator.rb
vendor/engines/bulk_email/app/helpers/bulk_email/application_helper.rb
vendor/engines/bulk_email/app/models/bulk_email/delivery_form.rb
vendor/engines/bulk_email/app/services/bulk_email/recipient_searcher.rb
vendor/engines/bulk_email/app/views/bulk_email/bulk_email/_fields.html.haml
vendor/engines/bulk_email/app/views/bulk_email/bulk_email/create.html.haml
vendor/engines/bulk_email/app/views/bulk_email/jobs/show.html.haml
vendor/engines/bulk_email/spec/controllers/bulk_email/bulk_email_controller_spec.rb
vendor/engines/bulk_email/spec/features/bulk_emailer_searching_spec.rb
vendor/engines/bulk_email/spec/services/bulk_email/recipient_searcher_spec.rb

Enable cross-facility bulk email for global admins. This also enables several of the Users tab features such as Payment Sources, and Secure Room card numbers. Access List remains disabled in cross-facility mode. 
I decided to spend the extra time to get these other features to work as well since their tab gets opened up when I enable Bulk Email for global admins. Before, they had the global User tab disabled unless they were also a billing admin. Access List seemed outside the scope of this work to ensure it works properly with scheduling groups and it would probably get too unwieldy with every single product on the page.

[#142448] Cross facility bulk email

---

bin/merge_describer

Tech task: Add ability to use `merge_describer` to compare against a branch besides develop. Useful when doing a production release and you want to compare your current branch to `master`.

Tech task: add ability to use merge_describer against a branch that isn't develop

---

app/models/account.rb
app/models/order_detail.rb
config/locales/models/en.account.yml

Tech task: Make "account is not open" text localized so it can be overridden.
Dartmouth would like a different message than "The Chart String is not open for the required account".
Extracted from https://github.com/tablexi/nucore-dartmouth/pull/226 which was merged in to expedite a release.

[#143237] Make "account is not open" text localized and overridable

---

app/support/reconcilable_account.rb

TECH TASK: Remove unused method ReconcilableAccount::ClassMethods#need_reconciling

Remove unused method ReconcilableAccount::ClassMethods#need_reconciling

---

app/controllers/product_notifications_controller.rb
app/mailers/cancellation_mailer.rb
app/models/instrument.rb
app/views/product_notifications/edit.html.haml
app/views/product_notifications/show.html.haml
config/locales/en.models.yml
config/locales/views/admin/en.product_notifications.yml
db/migrate/20180822191538_add_cancellation_notification_to_product.rb
db/schema.rb
spec/controllers/order_details_controller_spec.rb
spec/mailers/previews/cancelation_mailer_preview.rb

TECH TASK: Rename cancellation_notification_recipients to cancellation_email_recipients
On Oracle, and identifier can’t be longer than 30 characters, and the column name `cancellation_notification_recipients` is 36 characters. Hence, running the migration which adds this column results in the error:
```
OCIError: ORA-00972: identifier is too long: ALTER TABLE "PRODUCTS" ADD "CANCELLATION_NOTIFICATION_RECIPIENTS" CLOB
```
so the feature from #1666 will not work on Oracle as-is.

TECH TASK: Rename cancellation_notification_recipients to cancellation_email_recipients

---

db/migrate/20170308030632_change_schedule_rule_to_belong_to_product.rb

TECH TASK: Fix remove_foreign_key call for non-standard column
Running `rake db:migrate` on an empty database currently fails on this call to `remove_foreign_key`, because Rails can’t find the appropriate column. When the foreign key [is added](https://github.com/tablexi/nucore-open/blob/de02a553304d013dc089ea654ba74003cdcf807a/db/migrate/20100101000000_initial_schema.rb#L127-L128), it is added against the `products` table but it is on the `instrument_id` column, so the `remove_foreign_key` needs additional information to be able to find the appropriate foreign key.

TECH TASK: Fix remove_foreign_key call for non-standard column

---

lib/nucore.rb
spec/models/order_detail_spec.rb

Tech task: Update `where_ids_in` scope for ActiveRecord `or` support.
Pulled up from https://github.com/tablexi/nucore-nu/pull/408
I ended up using the dumb string version because I couldn't get an Arel version
working on Rails 5/`where-or`. This now works on both 4.2 and 5.0.

Update where_ids_in query for Rails 5

---

db/migrate/20180907190857_fix_oracle_timestamps.rb
db/schema.rb

Tech task: Update Oracle database DATE column types to TIMESTAMP.
Pulled up from https://github.com/tablexi/nucore-nu/pull/405
In rails 4.2, ruby `DateTime` maps to an oracle `DATE` column (which supports seconds, but not subseconds). Now it's assocated to ruby `Date`. So In rails 5, it's only grabbing the date portion of those columns. And the schema dumper writes them as  `t.date` rather than `t.datetime` https://github.com/rsim/oracle-enhanced/pull/875
Looks like they're going to be using TIMESTAMP for the rails datetime. https://github.com/rsim/oracle-enhanced/pull/739
This ends up being a no-op when applied to MySQL.
For additional reference, we go from 1.6.9 -> 1.7.11 of the oracle adapter https://github.com/rsim/oracle-enhanced/blob/master/History.md
I kind of like changing the …

Fix oracle types in Rails 5

---

vendor/engines/secure_rooms/app/views/secure_rooms/shared/_dashboard_column.html.haml
vendor/engines/secure_rooms/app/views/secure_rooms/shared/_secure_rooms_dashboard.html.haml
vendor/engines/secure_rooms/config/locales/en.yml

Adds another "Current Occupancies" column to the secure rooms dashboard so that a high occupancy (more than 10) does not overflow the screen.
I chatted with Aaron and showed him a couple options. This maintains the current behavior of always showing the "Current Occupancies" header and table header of the first column for empty rooms. We hide the second column header if there is nothing there.
The facilities occupancies shows all of the rooms for a facility, but shared the same code with the public dashboard so this change applies to both places.

[#143399] Add another column to current rooms dashboard

---

app/controllers/concerns/nav_tab.rb
app/controllers/facilities_controller.rb
app/models/serializable_facility.rb
app/presenters/nav_tab/link_collection.rb
app/views/shared/nav/_nav_links.html.haml
config/locales/en.yml
config/settings.yml

Implementation of our Use/Manage design separation. Currently, "Use" will bring the user back to the facility list home page unless they are managing a facility. If they are an admin and managing a facility, then they will be taken to the facility-specific homepage with the product list.
Manage mode will take the user to the manageable facility list, however it could also be a dropdown such as in our original design.

Implement Use/Manage Separation

---

app/controllers/concerns/nav_tab.rb
app/views/layouts/application.html.haml

Tech task: Add `manage-mode` body class when in manage mode.
This will allow us to target the CSS of the page based on if we are in use or manage mode.

Add `manage-mode` body class when in manage mode

---

app/controllers/offline_reservations_controller.rb
app/mailers/problem_order_mailer.rb
app/models/order_detail.rb
app/models/reservation.rb
app/models/serializable_facility.rb
app/services/move_to_problem_queue.rb
app/support/auto_expire_reservation.rb
app/support/auto_logout.rb
app/views/problem_order_mailer/notify_user.html.haml
app/views/problem_order_mailer/notify_user.text.erb
config/locales/views/en.problem_order_mailer.yml
spec/app_support/auto_expire_reservation_spec.rb
spec/app_support/auto_logout_spec.rb
spec/controllers/offline_reservations_controller_spec.rb
spec/mailers/previews/problem_order_mailer_preview.rb
spec/models/order_detail_spec.rb
spec/models/reservation_spec.rb
vendor/engines/secure_rooms/app/models/secure_rooms/occupancy.rb
vendor/engines/secure_rooms/app/support/secure_rooms/auto_orphan_occupancy.rb
vendor/engines/secure_rooms/spec/support/auto_orphan_occupancy_spec.rb

Notify the user via email if their reservation/occupancy enters into the problem queue. 
We do not trigger the email for missing price policies as that is something the facility needs to address.
For reservations, this only applies to timer and relay based instruments.
* Reservation never started, 12 hours after it was scheduled to end
* Reservation started, but never ended, 12 hours after it was scheduled to end
* Reservation started, but never ended and another reservation is started. Applies across a shared scheduled.
* Logged out via the Auto Logout setting (relays only)
* Reservation started and not yet ended and instrument is marked offline. Applies across a shared schedule.
For occupancies, this only applies to normal users. Facility staff does not get orders associated with their …

[#137154] Email user when an order goes into problem queue

---

app/assets/javascripts/ckeditor/editor.js
app/controllers/facilities_controller.rb
app/inputs/readonly_input.rb
app/models/facility.rb
app/views/facilities/_facility_fields.html.haml
app/views/facilities/manage.html.haml
app/views/facilities/show.html.haml
app/views/layouts/application.html.haml
config/initializers/sanitized_allowed.rb
config/locales/en.models.yml
config/locales/views/admin/en.facilities.yml
config/settings.yml
db/migrate/20180917224024_add_facility_notice.rb
db/schema.rb

Adds a per-facility optional banner notification that can be configured by the facility. The banner appears on the facility's home page (the instrument listing).
In Dartmouth when combined with the SSO warning notice (hopefully will be going away in the next little bit).
Combined with the order on behalf of banner. This doesn't look great, but that banner could definitely use some love in the future. We could also hide the notification banner if the order on behalf banner.
I gave this a feature flag because I could see NU not being interested.

[#133770] Facility Notification Banner

---

app/services/admin_reservation_expirer.rb
vendor/engines/bulk_email/app/views/bulk_email/bulk_email/_results.html.haml

Fixes for Rails 5 issues discovered in testing
1. Due to the datetime column changes, a `TO_TIMESTAMP` type cast is necessary to make the query in Oracle comparisons
2. Rails 5 automatically disables form submit buttons when they are clicked. On the bulk email form, this is undesirable for the Export button, since clicking the button doesn’t leave the page (the file is just downloaded).

Fixes for Rails 5 issues discovered in testing by NU

---

app/controllers/reconcilliations_controller.rb
app/views/order_management/order_details/_form.html.haml
config/locales/en.yml
config/routes.rb
spec/controllers/reconcilliations_controller_spec.rb

Allow global admins to unreconcile orders

[#142011] Allow global admins to unreconcile orders

---

app/controllers/affiliates_controller.rb
app/helpers/affiliates_helper.rb
app/models/affiliate.rb
app/views/affiliates/index.html.haml
app/views/facility_accounts/new.html.haml
spec/factories/affiliates.rb

Fixes alphabetization in the Affiliates global settings and the affiliate dropdown for credit card/purchase orders. Add a view hook for accounts#new.
Pulled up from https://github.com/tablexi/nucore-dartmouth/pull/231

[#143678] Affiliate changes

---

app/controllers/orders_controller.rb
app/models/order_detail.rb
app/services/move_to_problem_queue.rb
spec/app_support/auto_expire_reservation_spec.rb
spec/controllers/offline_reservations_controller_spec.rb
spec/factories/orders.rb
spec/models/reservation_spec.rb
vendor/engines/secure_rooms/app/services/secure_rooms/access_handlers/order_handler.rb
vendor/engines/secure_rooms/spec/services/secure_rooms/access_handlers/occupancy_handler_spec.rb
vendor/engines/secure_rooms/spec/services/secure_rooms/access_handlers/order_handler_spec.rb
vendor/engines/secure_rooms/spec/support/auto_orphan_occupancy_spec.rb

Fixes issues with emailing users when an order goes into the problem queue (#1685):
* Duplicate emails were being sent out
* Hard error when there was a problem order that had been canceled
* Email was not being sent when scanning out of a room without an entry scan
* Email was not being sent when double-scanning in

[#137154] Fix problem order email issues

---

app/assets/javascripts/price_policy.js.coffee
app/helpers/bootstrap_helper.rb
app/models/instrument_price_policy.rb
app/models/instrument_price_policy_calculations.rb
app/models/order_detail.rb
app/presenters/reservation_user_action_presenter.rb
app/services/cancellation_fee_calculator.rb
app/services/price_policy_updater.rb
app/views/facility_user_reservations/index.html.haml
app/views/price_policies/_price_policy_fields.html.haml
app/views/reservations/_my_table.html.haml
app/views/time_based_price_policies/_adjustment_row.html.haml
app/views/time_based_price_policies/_amount_row.html.haml
app/views/time_based_price_policies/_price_policy_fields.html.haml
app/views/time_based_price_policies/_table.html.haml
config/locales/en.models.yml
config/locales/en.yml
config/settings.yml
db/migrate/20180919211201_add_full_cost_cancellation_to_price_policies.rb
db/schema.rb
spec/factories/price_groups.rb
spec/features/admin/instrument_price_policies_controller_spec.rb
spec/features/admin/item_price_policies_controller_spec.rb
spec/features/admin/timed_service_price_policies_controller_spec.rb
spec/models/instrument_price_policy_calculations_spec.rb
spec/models/order_detail_spec.rb
spec/presenters/reservation_user_action_presenter_spec.rb
spec/services/cancellation_fee_calculator_spec.rb
vendor/engines/secure_rooms/app/views/secure_room_price_policies/_price_policy_fields.html.haml

Adds the ability to charge the full reservation cost (based on reservation times) on cancellation. This take precedence over the "Reservation/Cancellation Cost"
This could have compliance issues for NU, so that's why it's being feature flagged. Also, Dartmouth overrides the `cancellation_cost` locale from "Reservation Cost" to "Cancellation Cost" so we'll want to adjust the local for this new field to match for them.

[#136151] Ability to charge full reservation cost for cancellation

---

app/assets/javascripts/timeline.js
app/assets/stylesheets/app/timeline.scss
app/views/shared/timeline/_instrument.html.haml

Keep date navigation on timeline pages always visible
This makes the date navigation always visible on the public timeline, and manage timeline pages for a facility. I tried to make the datepicker scroll along with the date navigation, but after a few attempts, including a fix [like this one](https://stackoverflow.com/a/22038827), I was unable to get this working. Since closing and reopening the date picker positions it correctly, I don’t think this is worth pursuing further.
A note about the instrument ids: because the date navigation is always visible, the JS code takes its height into account when determining which instrument is the first visible one. Therefore, the URL fragment when clicking next and previous gets set to the element which is partially covered by the date navigation, …

[#142635] Keep date navigation on timeline pages always visible

---

config/ldap.yml.template
vendor/engines/ldap_authentication/README.md
vendor/engines/ldap_authentication/lib/ldap_authentication.rb

Update documentation for developing against LDAP
I did this while starting to work on the tool for auto-suspending users if they are removed from the LDAP directory.
Removes older instructions for setting up an LDAP server on your Mac OS system. We now recommend using Docker.
This also adds the ability to use YAML aliases in the configuration.
When we get to the story about removing if they're not in LDAP, do we think it might be worth seeding an LDAP server on Circle to test against? I feel that would be nice, but would make running a local test suite harder.

Update LDAP documentation

---

app/presenters/account_user_presenter.rb
app/views/account_users/new.html.haml
app/views/accounts/_member_table.html.haml
app/views/facility_account_users/new.html.haml
config/locales/en.yml

Resolves https://github.com/SquaredLabs/nucore-uconn/issues/37
Added localization to member roles under facility accounts.
Because the roles are hard coded and in the database, there is no way to elegantly allow them to be localized. 
See: `account_user.rb`
```ruby
ACCOUNT_PURCHASER = "Purchaser"
ACCOUNT_OWNER = "Owner"
ACCOUNT_ADMINISTRATOR = "Business Administrator"
```
Business administrator has a space, so it cannot be used to query i18n. My best workaround is to convert it in the view:
```haml
%td= t(".role.#{au.user_role.downcase.parameterize.underscore}")
```

Localize member roles for facility accounts

---

app/support/reservations/duration_change_validations.rb
spec/app_support/reservations/duration_change_validations_spec.rb

Prevents an error on the reservation edit form when start/end at is blank because of invalid data.
Here's the error: "NoMethodError: undefined method `<' for nil:NilClass" on the `if duration_is < duration_was` line. 
The error that we originally got notified of was super weird: it was missing the `reserve_start_mins` and `reserve_end_mins` parameters. I could recreate that if I deleted the dropdown from within my browser's dev tools. But I was able to replicate it as well by putting in an invalid date like "10/0/2018" into the date fields.

[#143771] Prevent error on invalid dates on Reservation#update

---

app/controllers/training_requests_controller.rb
app/views/products_common/_description.html.haml
app/views/products_common/show.html.haml
app/views/reservations/_documentation.html.haml
app/views/reservations/new.html.haml
app/views/training_requests/new.html.haml
config/locales/en.yml
config/locales/views/en.products.yml

Add product description and documentation to training request page. Before, users weren't able to see any details about the product before requesting training. Now they can.
Before:
After:
The same instrument's reservation page:

[#139203] Add product description to training request page

---

app/assets/javascripts/application.js
vendor/assets/javascripts/polyfills.js
vendor/assets/javascripts/polyfills/array.includes.js

Fix issue in IE where "Compose Mail" button was triggering CSV download rather than taking you to the compose form
The bulk email JS code uses `Array.includes` which is not available in IE 11 and below (it is available in Edge). This adds a polyfill for that functionality.
The email form is not particularly pretty in IE (the email list and greeting line inputs are not a good height), but I believe that is outside the scope of this PR.

[#144271] Fix bulk email in IE

---

app/assets/stylesheets/app/product_list.scss
app/views/facilities/show.html.haml

Resolves https://github.com/SquaredLabs/nucore-uconn/issues/31
Placed the columns on the order form, and gave the button its own row.

Fix columns in order form

---

spec/models/order_detail_spec.rb

Tech task: Fix test failure when `charge_full_price_on_cancellation` feature is turned off.
See test failure on https://github.com/tablexi/nucore-open/compare/disable_full_cancellation_cost?expand=1

[#136151] Fix test failure when charge_full_price_on_cancellation is turned off

---

app/helpers/view_hook_helper.rb
app/presenters/view_hook.rb
app/views/devise/sessions/new.html.haml
config/locales/views/en.devise.yml
vendor/engines/saml_authentication/app/views/saml_authentication/sessions/_new.html.haml

Tech task: Add a view hook to enable downstream forks to override the login form.
Extracted from https://github.com/tablexi/nucore-dartmouth/pull/233 so we can collapse the login form via javascript to direct people to login via SSO instead.

[#144151] Add ability to override login form

---

app/models/instrument_price_policy.rb
app/services/price_policy_updater.rb
app/views/time_based_price_policies/_adjustment_row.html.haml
app/views/time_based_price_policies/_amount_row.html.haml
app/views/time_based_price_policies/_table.html.haml
config/locales/en.models.yml
db/migrate/20180919211201_add_full_cost_cancellation_to_price_policies.rb
db/schema.rb
spec/features/admin/instrument_price_policies_controller_spec.rb
spec/models/instrument_price_policy_calculations_spec.rb
spec/models/order_detail_spec.rb
spec/services/cancellation_fee_calculator_spec.rb

TECH TASK: Rename column to full_price_cancellation so it fits into Oracle <= 30 limit
When deploying to NU, whose DB server runs Oracle 12.1, the migration fails:
```
== 20180919211201 AddFullCostCancellationToPricePolicies: migrating ===========
-- add_column(:price_policies, :charge_full_price_on_cancellation, :boolean, {:default=>false, :null=>false})
rake stderr: rake aborted!
StandardError: An error has occurred, all later migrations canceled:
OCIError: ORA-00972: identifier is too long: ALTER TABLE "PRICE_POLICIES" ADD "CHARGE_FULL_PRICE_ON_CANCELLATION" NUMBER(1) DEFAULT 0 NOT NULL
stmt.c:243:in oci8lib_240.so
```
Therefore, I am renaming the DB column only, from `charge_full_price_on_cancellation` to `full_price_cancellation`, so it is less than 30 characters and can be applied. …

[#136151] Rename column to full_price_cancellation so it fits into Oracle <= 30 limit

---

app/controllers/concerns/nav_tab.rb
app/presenters/nav_tab/link_collection.rb
app/views/layouts/plain.html.haml
app/views/layouts/two_column.html.haml
app/views/layouts/two_column_head.html.haml

* Update the logic to check which mode the page is in.
* Add manage mode class to other pages.
It seems like the issue was not necessarily that the use/manage class was not correct in the helper. The fix ended up being that some views don't use `application.html.haml`, there are also two-column layouts that it needed to be added to.

Fix manage mode to work on other pages
